### ISSUE TITLE
How to send message with recipients UUID instead of phone number?

### ISSUE THREAD

**Issue by jokebattle3** [AsamK/signal-cli#1003]
With signal-cli 0.10.11 i'm not able to send a message via UUID.

When sending via DBUS with UUID "XYZ-5618-4dd7-83f7-XYZ" (where as XYZ is placeholder for pricacy reason), signal-cli throws the error "Failed to send message: Unregistered user "+XYZ56184dd783f7XYZ".

How can I pass the UUID to the signal-cli via DBUS?

_Originally posted by @jokebattle3 in https://github.com/AsamK/signal-cli/issues/1002#issuecomment-1237023062_

**Comment by jokebattle3** [comment]
I send the message via PHP and DBUS Proxy.

My code in PHP looks like this: 

```
$recipients = [MY_RECIPIENT_UUID];

$dbusRecipients = new \DBusArray(\DBus::STRING, $recipients);

$dbus->sendMessage($text, $medias, $dbusRecipients);

```

In signal-cli.log it shows me the following error message:

```
2022-09-07T12:52:44.736+0200 [DBusConnection [listener=false]] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodCall(0,5) { Path=>/org/asamk/Signal/_MY_SIGNAL_PHONE_NUMBER, Interface=>org.asamk.Signal, Member=>sendMessage, Destination=>org.asamk.Signal, Sender=>:1.22733982, Signature=>sasas } { Willkommen!, [], [29754675-REMOVED_FOR_PRIVACY_REASON] }
2022-09-07T12:52:44.736+0200 [DBusConnection [listener=false]] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method call: MethodCall(0,5) { Path=>/org/asamk/Signal/_4915153329969, Interface=>org.asamk.Signal, Member=>sendMessage, Destination=>org.asamk.Signal, Sender=>:1.22733982, Signature=>sasas } { MESSAGE_TEXT, [], [29754675-REMOVED_FOR_PRIVACY_REASON] }
2022-09-07T12:52:44.737+0200 [DBus-MethodCall-Receiver-2] DEBUG o.f.d.c.impl.DBusConnection - Running method public abstract long org.asamk.Signal.sendMessage(java.lang.String,java.util.List,java.util.List) throws org.asamk.Signal$Error$AttachmentInvalid,org.asamk.Signal$Error$Failure,org.asamk.Signal$Error$InvalidNumber,org.asamk.Signal$Error$UntrustedIdentity for remote call
2022-09-07T12:52:44.737+0200 [DBus-MethodCall-Receiver-2] WARN  LibSignal - [PhoneNumberFormatter]: Got local CC: DE
2022-09-07T12:52:44.737+0200 [DBus-MethodCall-Receiver-2] WARN  LibSignal - [PhoneNumberFormatter]: Error type: TOO_LONG. The string supplied is too long to be a phone number.
        at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:3339)
        at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3127)
        at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3117)
        at org.whispersystems.signalservice.api.util.PhoneNumberFormatter.formatNumber(PhoneNumberFormatter.java:110)
        at org.asamk.signal.manager.api.RecipientIdentifier$Single.fromString(RecipientIdentifier.java:34)
        at org.asamk.signal.dbus.DbusSignalImpl.getSingleRecipientIdentifier(DbusSignalImpl.java:891)
        at org.asamk.signal.dbus.DbusSignalImpl.getSingleRecipientIdentifiers(DbusSignalImpl.java:882)
        at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:221)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.freedesktop.dbus.connections.AbstractConnection$2.run(AbstractConnection.java:804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-09-07T12:52:44.737+0200 [DBus-MethodCall-Receiver-2] DEBUG o.a.s.m.api.RecipientIdentifier - Normalized number 29754675-REMOVED_FOR_PRIVACY_REASON to +29754675-REMOVED_FOR_PRIVACY_REASON.
2022-09-07T12:52:45.293+0200 [DBus-MethodCall-Receiver-2] DEBUG o.f.d.c.impl.DBusConnection - null
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.freedesktop.dbus.connections.AbstractConnection$2.run(AbstractConnection.java:804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.asamk.Signal$Error$Failure: Failure:
Failed to send message:
Unregistered user "+29754675-REMOVED_FOR_PRIVACY_REASON"
1662547964737
        at org.asamk.signal.dbus.DbusSignalImpl.checkSendMessageResult(DbusSignalImpl.java:824)
        at org.asamk.signal.dbus.DbusSignalImpl.checkSendMessageResults(DbusSignalImpl.java:831)
        at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:225)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 5 common frames omitted
2022-09-07T12:52:45.293+0200 [DBus-MethodCall-Receiver-2] DEBUG o.f.d.c.impl.DBusConnection -
org.asamk.Signal$Error$Failure: Failure:
Failed to send message:
Unregistered user "+29754675-REMOVED_FOR_PRIVACY_REASON"
1662547964737
        at org.asamk.signal.dbus.DbusSignalImpl.checkSendMessageResult(DbusSignalImpl.java:824)
        at org.asamk.signal.dbus.DbusSignalImpl.checkSendMessageResults(DbusSignalImpl.java:831)
        at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:225)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.freedesktop.dbus.connections.AbstractConnection$2.run(AbstractConnection.java:804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-09-07T12:52:45.293+0200 [DBus-MethodCall-Receiver-2] DEBUG org.freedesktop.dbus.errors.Error - Creating message with serial 34538
2022-09-07T12:52:45.293+0200 [DBus-MethodCall-Receiver-2] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: yyyy data: [108, 3, 0, 1]
2022-09-07T12:52:45.293+0200 [DBus-MethodCall-Receiver-2] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: ua(yv) data: [34538, [[4, [s, org.asamk.Signal.Error.Failure]], [5, [u, 5]], [6, [s, :1.22733982]], [8, [g, s]]]]
2022-09-07T12:52:45.293+0200 [DBus-MethodCall-Receiver-2] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: s data: [Failure:
Failed to send message:
Unregistered user "+29754675-REMOVED_FOR_PRIVACY_REASON"
1662547964737]
2022-09-07T12:52:45.293+0200 [DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= Error(0,34538) { Error Name=>org.asamk.Signal.Error.Failure, Reply Serial=>5, Destination=>:1.22733982, Signature=>s } { Failure:
Failed to send message:
Unregistered user "+29754675-REMOVED_FOR_PRIVACY_REASON"
1662547964737 }

```

**Comment by AsamK** [comment]
It looks like signal-cli doesn't recognize your UUID as a UUID and thus treats it as a phone number.
The relevant code is here: https://github.com/AsamK/signal-cli/blob/27dbc671e09c3efbaaf4d0f16d3ccdfb640ae603/lib/src/main/java/org/asamk/signal/manager/api/RecipientIdentifier.java#L30

The code uses this regular expression to check if it's a UUID or not: `[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`
 Can you check that your UUID has the correct format?

**Comment by jokebattle3** [comment]
@AsamK you are totally right: I can confirm it is working to send a message using the recipient UUID. 

Due to an internal storage in my chain the UUID was accidently cropped to 32 chars. Testing against the regex gave me the answer! Thanks a lot!

Additional to this: After sending the message via UUID I receive both received and read events for the message via the ReceiptReceivedV2 event and the phone number as the recipients identifier, and not UUID then.

Question: Is it possible to do a lookup from the phone number to the UUID and vice versa? It would need some kind of mechanism to get the releationship between them to resolve the incoming events correctly.

**Comment by AsamK** [comment]
Lookup from phone number to UUID is possible with the getUserStatus or listContacts command, but i don't think via dbus yet.

**Comment by jokebattle3** [comment]
@AsamK Thank for your information.
