### ISSUE TITLE
0.10.11 - Failed to access RecordComponents of type `org.asamk.signal.manager.storage.groups.GroupStore$Storage`

### ISSUE THREAD

**Issue by morph027** [AsamK/signal-cli#1007]
0.10.11 in native mode throws the following exception:

```
java.lang.IllegalArgumentException: Failed to access RecordComponents of type `org.asamk.signal.manager.storage.groups.GroupStore$Storage`
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4324)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:637)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:171)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:89)
        at org.asamk.signal.manager.SignalAccountFiles.lambda$initMultiAccountManager$1(SignalAccountFiles.java:64)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183)
        at java.util.stream.Nodes$CollectorTask$OfRef.doLeaf(Nodes.java:2193)
        at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
        at java.util.stream.Nodes.collect(Nodes.java:328)
        at java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:111)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:570)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at org.asamk.signal.manager.SignalAccountFiles.initMultiAccountManager(SignalAccountFiles.java:69)
        at org.asamk.signal.App.handleMultiLocalCommand(App.java:306)
        at org.asamk.signal.App.init(App.java:188)
        at org.asamk.signal.Main.main(Main.java:58)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed to access RecordComponents of type `org.asamk.signal.manager.storage.groups.GroupStore$Storage`
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:642)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4805)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4386)
        ... 26 more

```

**Comment by jspraul** [comment]
My stack trace includes `[Source: (FileInputStream); line: 1, column: 1]`; I'm investigating whether there may be some issue accessing the file.

Same new v0.10.11 in native mode, but not sure it's the exact same issue (this is `signal-cli receive`):
```
WARN  RecipientStore - Failed to load recipient store
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed to access RecordComponents of type `org.asamk.signal.manager.storage.recipients.RecipientStore$Storage`
 at [Source: (FileInputStream); line: 1, column: 1]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:642)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4805)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.load(RecipientStore.java:60)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$18(SignalAccount.java:1102)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1506)
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1101)
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientResolver(SignalAccount.java:1089)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:644)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:171)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:89)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:76)
        at org.asamk.signal.App.loadManager(App.java:345)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.init(App.java:219)
        at org.asamk.signal.Main.main(Main.java:58)
Error loading state file for user [...]: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed to access RecordComponents of type `org.asamk.signal.manager.storage.recipients.RecipientStore$Storage`
 at [Source: (FileInputStream); line: 1, column: 1] (RuntimeException)
```

**Comment by morph027** [comment]
Ah, looks like it was my fault while building w/ reflect config from master.
