### ISSUE TITLE
Runtime SQL Exception: When running dbus daemon 0.10.11 (6feff1e4) and dbus client based on older version of signal-cli 

### ISSUE THREAD

**Issue by mweser** [AsamK/signal-cli#1012]
Unsure what other context might be important here, but getting this runtime exception. 

```WARN  Utils - Failed to read from database result
java.sql.SQLException: no such column: 'urgent'
        at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:50)
        at org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(JDBC3ResultSet.java:194)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.getBoolean(HikariProxyResultSet.java)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.getMessageSendLogEntryFromResultSet(MessageSendLogStore.java:381)
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:105)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.findMessages(MessageSendLogStore.java:104)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleDecryptionErrorMessage(IncomingMessageHandler.java:303)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleMessage(IncomingMessageHandler.java:245)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:197)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:163)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:196)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesContinuously(ReceiveHelper.java:80)
        at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$12(ManagerImpl.java:871)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "receive-4" java.lang.RuntimeException: java.sql.SQLException: no such column: 'urgent'
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:109)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.findMessages(MessageSendLogStore.java:104)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleDecryptionErrorMessage(IncomingMessageHandler.java:303)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleMessage(IncomingMessageHandler.java:245)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:197)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:163)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:196)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesContinuously(ReceiveHelper.java:80)
        at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$12(ManagerImpl.java:871)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: no such column: 'urgent'
        at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:50)
        at org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(JDBC3ResultSet.java:194)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.getBoolean(HikariProxyResultSet.java)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.getMessageSendLogEntryFromResultSet(MessageSendLogStore.java:381)
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:105)
        ... 18 more
WARN  ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name wit the updateProfile command. This may become mandatory in the future.
```

**Comment by mweser** [comment]
I would assume commit 38c9fe9c is most relevant to this. Somehow the local database isn't getting the update to add the 'urgent' field.

**Comment by mweser** [comment]
For my own personal version of signal-cli, I simply hardcoded "urgent" to 'false' (MessageSendLogStore.java:381):

`    private MessageSendLogEntry getMessageSendLogEntryFromResultSet(ResultSet resultSet) throws SQLException {
        final var groupId = Optional.ofNullable(resultSet.getBytes("group_id")).map(GroupId::unknownVersion);
        final SignalServiceProtos.Content content;
        try {
            content = SignalServiceProtos.Content.parseFrom(resultSet.getBinaryStream("content"));
        } catch (IOException e) {
            logger.warn("Failed to parse content from message send log", e);
            return null;
        }
        final var contentHint = ContentHint.fromType(resultSet.getInt("content_hint"));
        **_final var urgent = false;_**
        return new MessageSendLogEntry(groupId, content, contentHint, urgent);
    }
`
