### ISSUE TITLE
FileSystemException after update to v0.11.0 (Windows)

### ISSUE THREAD

**Issue by wo80** [AsamK/signal-cli#1018]
After updating from version `0.10.11` to current version `0.11.0` I get the error shown below. Trying to switch back to version `0.10.11` also gives an error (as expected, when changing database). Unfortunately, I don't have a recent database backup, so I hope this can be fixed. I still have access to Signal using the desktop app, so unless that breaks, this isn't a major issue for me.

OS: Windows 10 x64
Java: 18.0.2

The error message translated to English is: `The process cannot access the file because it is used by another process.`

```
signal-cli.bat -u +xxxx receive
WARN  LegacyRecipientStore2 - Failed to load recipient store
java.nio.file.FileSystemException: C:\Users\xyz\.local\share\signal-cli\data\604851.d\recipients-store: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at org.asamk.signal.manager.storage.recipients.LegacyRecipientStore2.migrate(LegacyRecipientStore2.java:87)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:629)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:180)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)
        at org.asamk.signal.App.loadManager(App.java:348)
        at org.asamk.signal.App.handleLocalCommand(App.java:281)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)
Error loading state file for user +xxxx: java.nio.file.FileSystemException: C:\Users\xyz\.local\share\signal-cli\data\604851.d\recipients-store: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird (RuntimeException)
```

**Comment by AsamK** [comment]
Damn, I hate windows locking files in use ...
At this point you can just delete the recipients-store file manually, the migration to the database was already done and committed.
I'll push a fix for this, it will probably also affect the other store migrations.

**Comment by AsamK** [comment]
Can you try again with this development build? : https://github.com/AsamK/signal-cli/actions/runs/3173839197/jobs/5169902862

**Comment by wo80** [comment]
@AsamK I tested `signal-cli-archive-18` just replacing the `lib.jar` and everything went fine (without deleting the recipients-store file manually).

Thank you very much!
