### ISSUE TITLE
[0.11.0] Sending Message to Group Fails

### ISSUE THREAD

**Issue by rfrederick** [AsamK/signal-cli#1019]
After upgrading to 0.11.0, sending a message to a group fails with the following exception thrown:

`$ echo 'Test Message.' | /usr/local/bin/signal-cli -a +12345551212 --trust-new-identities always send -g base64GroupID --message-from-stdin`
`java.lang.RuntimeException: Failed read from session store
        at org.asamk.signal.manager.storage.sessions.SessionStore.getAllAddressesWithActiveSessions(SessionStore.java:231)
        at org.asamk.signal.manager.storage.protocol.SignalProtocolStore.getAllAddressesWithActiveSessions(SignalProtocolStore.java:139)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.buildGroupTargetInfo(SignalServiceMessageSender.java:2157)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupMessage(SignalServiceMessageSender.java:2042)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupDataMessage(SignalServiceMessageSender.java:499)
        at org.asamk.signal.manager.helper.SendHelper.lambda$sendGroupMessage$10(SendHelper.java:348)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternalWithSenderKey(SendHelper.java:563)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternal(SendHelper.java:429)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessage(SendHelper.java:369)
        at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:310)
        at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:103)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:458)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:552)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:179)
        at org.asamk.signal.App.handleLocalCommand(App.java:282)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (unrecognized token: "<tokenHere>")
        at org.sqlite.core.DB.newSQLException(DB.java:1135)
        at org.sqlite.core.DB.newSQLException(DB.java:1146)
        at org.sqlite.core.DB.throwex(DB.java:1106)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:122)
        at org.sqlite.core.DB.prepare(DB.java:264)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:31)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:206)
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
        at org.asamk.signal.manager.storage.sessions.SessionStore.getAllAddressesWithActiveSessions(SessionStore.java:221)
        ... 16 more`

Sending to individual accounts works without issue.

**Comment by AsamK** [comment]
Thanks for reporting!

**Comment by morph027** [comment]
Thanks for the quick fix, can confirm it's working!

**Comment by rfrederick** [comment]
I can also confirm that the fix works.
