### ISSUE TITLE
DeprecatedVersionException (status code 499)

### ISSUE THREAD

**Issue by Seirdy** [AsamK/signal-cli#1022]
Sending and receiving messages with signal-cli seems to trigger a "DeprecatedVersionException" as of 2022-10-05, 21:59 UTC. This exception seems to be intended to disable deprecated clients. I used the latest official binary release (0.11.1) and the old 0.10.0 release.

Verbose log (0.11.1):

```
2022-10-05TXX:XX:XX.XXX-XXXX [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.20.0
2022-10-05TXX:XX:XX.XXX-XXXX [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-10-05TXX:XX:XX.XXX-XXXX [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@23d1e5d0
2022-10-05TXX:XX:XX.XXX-XXXX [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-10-05TXX:XX:XX.XXX-XXXX [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-10-05TXX:XX:XX.XXX-XXXX [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Error while checking account +XXXXXXXXXXX: StatusCode: 499
org.whispersystems.signalservice.api.push.exceptions.DeprecatedVersionException: StatusCode: 499
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1887)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1831)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1813)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1802)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1738)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1714)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.setAccountAttributes(PushServiceSocket.java:428)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.setAccountAttributes(SignalServiceAccountManager.java:422)
        at org.asamk.signal.manager.helper.AccountHelper.updateAccountAttributes(AccountHelper.java:143)
        at org.asamk.signal.manager.helper.AccountHelper.checkAccountState(AccountHelper.java:63)
        at org.asamk.signal.manager.ManagerImpl.checkAccountState(ManagerImpl.java:193)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:116)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)
        at org.asamk.signal.App.loadManager(App.java:348)
        at org.asamk.signal.App.handleLocalCommand(App.java:281)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)
```

JVM information:

```
openjdk 19 2022-09-20
OpenJDK Runtime Environment (Red_Hat-19.0.0.0.36-3.rolling.fc36) (build 19+36)
OpenJDK 64-Bit Server VM (Red_Hat-19.0.0.0.36-3.rolling.fc36) (build 19+36, mixed mode, sharing)
```

System information:

- OS: Fedora 36
- Environment: `SIGNAL_CLI_OPTS=-Xint`

**Comment by Seirdy** [comment]
Seems I'm not the only one. Looks like [the Signal server did something by 21:01 UTC today](https://github.com/bbernhard/signal-cli-rest-api/issues/243#issuecomment-1268971240) which ended up classifying current signal-cli versions as deprecated clients.

**Comment by etlweather** [comment]
Not sure where that is in this but on the Android build, the CANONICALVERSION must be updated to 1136

**Comment by wizkid057** [comment]
This seems to be affecting the latest release and master branch. None of my signal-cli setups are currently functional as a result.

**Comment by etlweather** [comment]
I was able to hack this a bit and get it somewhat working. I can receive fine after changing the user agent. I can also send but the sending while it does send the message, returns an error

```


WARN  ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name wit the updateProfile command. This may become mandatory in the future.
WARN  RecipientHelper - CDSI request failed, trying fallback to CDS
java.io.IOException: java.net.SocketTimeoutException: Connect timed out
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsersWithCdsi(SignalServiceAccountManager.java:579)
        at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsersV2(RecipientHelper.java:158)
        at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsers(RecipientHelper.java:112)
        at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUser(RecipientHelper.java:128)
        at org.asamk.signal.manager.helper.RecipientHelper.lambda$resolveRecipient$0(RecipientHelper.java:91)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:167)
        at org.asamk.signal.manager.helper.RecipientHelper.resolveRecipient(RecipientHelper.java:89)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:447)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:552)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:179)
        at org.asamk.signal.App.handleLocalCommand(App.java:282)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.asamk.signal.manager.config.ServiceConfig.lambda$getServiceEnvironmentConfig$0(ServiceConfig.java:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833
```

**Comment by etlweather** [comment]
@AsamK any idea?

**Comment by wizkid057** [comment]
> I was able to hack this a bit and get it somewhat working. I can receive fine after changing the user agent. I can also send but the sending while it does send the message, returns an error

Applied this hack, and everything works fine for me. Thanks!

For linux a quick and dirty way to do it to the binary package (need zip and unzip installed):
```
cd signal-cli-0.11.1/lib/
mkdir tmp
cd tmp
unzip ../signal-cli-0.11.1.jar 
sed -i 's/Signal-Android\/5.22.3/Signal-Android\/5.51.7/g' org/asamk/signal/BaseConfig.class 
zip -r ../signal-cli-0.11.1.jar org/ META-INF/
```

**Comment by rfrederick** [comment]
I've had the same issue since around the same timestamp. Currently the only piece of routine functionality that's working for me is sending to groups.

**Comment by etlweather** [comment]
@AsamK Thanks for merging! I assume you will make an official build next? Once we have that, I have that, I can see that `signal-cli-rest-api` is updated too (as that's what I am using).

**Comment by AsamK** [comment]
Indeed, will make another release later today.

**Comment by stevie553** [comment]
@AsamK, do you think it'd be useful to add checks to stop retrying to connect to the servers in case of fatal errors like this one?

One reason is that so the client doesn't get rate limited or even the IP gets blocked from connecting to the servers. And the error will not be fixed by constantly reconnecting anyway.

Also, are there any other fatal errors like status code 499 that the client should just stop reconnecting since it won't be fixed automatically anyway?

This may not be a problem if you're just using "receive" but it could cause problems if you're running in dbus and the client just keeps reconnecting.

Note: if something like this gets implemented, I don't think it'd be good for the client to just terminate, since that could trigger service manager to just restart it (if configured that way of course) which will throw the client in the same loop of reconnecting. So maybe just an error to the log for further inspection by the user would be suitable?

**Comment by AsamK** [comment]
@stevie553 There's already an exponential backoff implemented in case the receive websocket connection fails to connect, with a maximum of 51 seconds.
```
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 100 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 200 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 400 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 800 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 1600 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 3200 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 6400 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 12800 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 25600 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 51200 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 51200 ms
```

**Comment by AsamK** [comment]
v0.11.2 has been released with the fix

**Comment by morph027** [comment]
You're using the amd64 version on arm64...Where did you find the installer? Also might be better to create a new [discussion](https://github.com/AsamK/signal-cli/discussions) as it's not reall related with this issue.

**Comment by plord12** [comment]
> Uhmm how to update to a newer version?

I'm just doing the same ... see https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal

**Comment by Miniontoby** [comment]
I dont! I downloaded the armv7-unknown-linux-gnueabihf version...

Also since I am on mobile and dont have my gh account here I can only use
email to reply and so I am not able to make a new Discussion thingy... we
can rename this issue and remove old comments... or you have to make one
and mention me, i think...

Op do 6 okt. 2022 20:39 schreef morph027 ***@***.***>:

**Comment by Miniontoby** [comment]
I used
https://github.com/AsamK/signal-cli/issues/855#issuecomment-1004287788 as
installer but it gives me

```
WARN  ServiceConfig - Failed to call libsignal-client: 'void
org.signal.libsignal.internal.Native.Logger_Initialize(int,
java.lang.Class)'
Missing required native library dependency: libsignal-client
```

What to do?

Op vr 7 okt. 2022 18:22 schreef Tobias Gaarenstroom <
***@***.***>:

**Comment by Miniontoby** [comment]
Update:

Changed the installer to use one of those gitlab builds...

```
OpenJDK Server VM warning: You have loaded library
/opt/signal-cli-0.11.2/lib/libsignal_jni.so which might have disabled stack
guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c
<libfile>', or link it with '-z noexecstack'.
WARN  ServiceConfig - Failed to call libsignal-client:
/opt/signal-cli-0.11.2/lib/libsignal_jni.so:
/opt/signal-cli-0.11.2/lib/libsignal_jni.so: invalid ELF header
Missing required native library dependency: libsignal-client
```

I downloaded arm64 version btw

Op do 6 okt. 2022 20:59 schreef Peter Lord ***@***.***>:

**Comment by morph027** [comment]
Are you using a Pi 4 w/ arm64? And Raspbian? Then you could just try to download and install this artifact?

```bash
curl -Lo /tmp/signal-cli-jre_0.11.3-1_arm64.deb https://gitlab.com/packaging/signal-cli/-/jobs/3144100577/artifacts/raw/signal-cli-jre_0.11.3-1_arm64.deb
apt-get install /tmp/signal-cli-jre_0.11.3-1_arm64.deb
```

**Comment by Miniontoby** [comment]
Uhmm 'uname -a' says armv7l. But it is Rpi4 with rasbian

I used https://github.com/exquo/signal-libs-build/ but that one doesnt have
.so's anymore...


Op za 8 okt. 2022 19:25 schreef morph027 ***@***.***>:

**Comment by morph027** [comment]
Jeah, latest libsignal builds are quite tricky for armv7 (https://github.com/signalapp/libsignal/issues/481)

**Comment by Miniontoby** [comment]
Maybe we need to fork
https://github.com/exquo/signal-libs-build/tree/fbd417d7204738c81a3d514e9d5c456c15bc02b5
(mostly the exact commit) since this one did produce 0.8.x version with all
files...

Op za 8 okt. 2022 19:38 schreef morph027 ***@***.***>:

**Comment by jarrah31** [comment]
Is the following StatusCode: 499 error different or the same to what this thread is discussing?
```
WARN  AccountHelper - Messages have been last received 185 days ago. The Signal protocol expects that incoming messages are regularly received.
Error while checking account +xxxxxxxxx: StatusCode: 499
```

**Comment by Miniontoby** [comment]
I got it to work!

Using the 0.18.1 release from https://github.com/exquo/signal-libs-build/
and it now works!


Op za 8 okt. 2022 19:38 schreef morph027 ***@***.***>:

**Comment by morph027** [comment]
Also w/ latest version? [CHANGELOG](https://github.com/AsamK/signal-cli/blob/master/CHANGELOG.md#0110---2022-10-02) says that starting 0.11.0 libsignal-client version 0.20.0 is required....

**Comment by Miniontoby** [comment]
> Also w/ latest version? [CHANGELOG](https://github.com/AsamK/signal-cli/blob/master/CHANGELOG.md#0110---2022-10-02) says that starting 0.11.0 libsignal-client version 0.20.0 is required....

Uhmm if you look at the releases page of the prev mentioned URL then you could have filled it in yourself. The answer is no. This is because after 0.18.1 the release assets are just 2 instead of 9, where 1 of 9 was the armv7 release.

I am just going to hope that some change which causes this type of error never accures and then I will be fine! Cause I don't want and I don't do upgrading at all for these type of stuff.

(And why GH, why do you not send the reply using email and why did I get a message of a new comment but I don't see it here, BRUH)

**Comment by Miniontoby** [comment]
Update:

Changed the installer to use one of those gitlab builds...

```
OpenJDK Server VM warning: You have loaded library
/opt/signal-cli-0.11.2/lib/libsignal_jni.so which might have disabled stack
guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c
<libfile>', or link it with '-z noexecstack'.
WARN  ServiceConfig - Failed to call libsignal-client:
/opt/signal-cli-0.11.2/lib/libsignal_jni.so:
/opt/signal-cli-0.11.2/lib/libsignal_jni.so: invalid ELF header
Missing required native library dependency: libsignal-client
```
I downloaded arm64 version


Op za 8 okt. 2022 15:15 schreef Tobias Gaarenstroom <
***@***.***>:

**Comment by Miniontoby** [comment]
This is the same error, yes! Install version 0.11.2 to fix it and restart
your dbus (if you use it)

Op za 8 okt. 2022 21:24 schreef jarrah31 ***@***.***>:
