### ISSUE TITLE
Failed to send read receipt in group

### ISSUE THREAD

**Issue by chetbox** [AsamK/signal-cli#1029]
I've just updated to version 11.2.0 because of #1022 but now I'm getting the following error when sending read receipts to a group:

```
Could not send read receipt to number in group [REDACTED]: Error: Failed to send message
[54](https://github.com/chetbox/brighton-explorers-signal/actions/runs/3199278747/jobs/5224848452#step:11:54)
    at JSONRPCClient.<anonymous> (/home/runner/work/brighton-explorers-signal/brighton-explorers-signal/node_modules/json-rpc-2.0/dist/client.js:115:66)
[55](https://github.com/chetbox/brighton-explorers-signal/actions/runs/3199278747/jobs/5224848452#step:11:55)
    at step (/home/runner/work/brighton-explorers-signal/brighton-explorers-signal/node_modules/json-rpc-2.0/dist/client.js:33:23)
[56](https://github.com/chetbox/brighton-explorers-signal/actions/runs/3199278747/jobs/5224848452#step:11:56)
    at Object.next (/home/runner/work/brighton-explorers-signal/brighton-explorers-signal/node_modules/json-rpc-2.0/dist/client.js:14:53)
[57](https://github.com/chetbox/brighton-explorers-signal/actions/runs/3199278747/jobs/5224848452#step:11:57)
    at fulfilled (/home/runner/work/brighton-explorers-signal/brighton-explorers-signal/node_modules/json-rpc-2.0/dist/client.js:5:58)
[58](https://github.com/chetbox/brighton-explorers-signal/actions/runs/3199278747/jobs/5224848452#step:11:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by AsamK** [comment]
Can you provide the log files from the signal-cli daemon?

**Comment by morph027** [comment]
Hm, works for me.

```
signal-cli -c /var/lib/signal-cli/ -a "+<account>" sendReceipt -t <timestamp> --type read "+<recipient>"
1665082177374
```

`<timestamp>` is a timestamp from a group message where `<+recipient>` is member of.
