### ISSUE TITLE
java.lang.InternalError: Currency data is possibly corrupted

### ISSUE THREAD

**Issue by rotmajster** [AsamK/signal-cli#103]
I installed signal-cli on my raspberryPi. It worked, but today, I tried it after 1 month and I'm getting this message using commang: signal-cli -u +42********* send -m nasraaaat +42******

java.lang.InternalError: Currency data is possibly corrupted
	at java.util.Currency$1.run(Currency.java:223)
	at java.util.Currency$1.run(Currency.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.Currency.<clinit>(Currency.java:212)
	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:638)
	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
	at sun.util.locale.provider.NumberFormatProviderImpl.getInstance(NumberFormatProviderImpl.java:178)
	at sun.util.locale.provider.NumberFormatProviderImpl.getIntegerInstance(NumberFormatProviderImpl.java:131)
	at java.text.NumberFormat.getInstance(NumberFormat.java:884)
	at java.text.NumberFormat.getInstance(NumberFormat.java:861)
	at java.text.NumberFormat.getIntegerInstance(NumberFormat.java:508)
	at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:639)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:605)
	at com.fasterxml.jackson.databind.util.StdDateFormat.<clinit>(StdDateFormat.java:89)
	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:212)
	at org.asamk.signal.Manager.<init>(Manager.java:109)
	at org.asamk.signal.Main.handleCommands(Main.java:125)
	at org.asamk.signal.Main.main(Main.java:80)

But it is possible, that my RaspberryPi SDcard is damaged or something...

**Comment by AsamK** [comment]
This looks like a corrupted java installation. signal-cli tries to format a date and java throws an exception because it can't read the locale data.

**Comment by rotmajster** [comment]
Asam, that is correct. Java itself does not work. Sorry.
