### ISSUE TITLE
java.sql.SQLException: no such column: 'urgent'

### ISSUE THREAD

**Issue by riazm** [AsamK/signal-cli#1031]
Since updating to 0.11.2 (great work getting it out so fast btw) I am getting the following error
```

r@<redacted>:~/projects/scli$ signal-cli -u +44<redacted>--output=plain-text daemon
INFO  DaemonCommand - Starting daemon in single-account mode for +<redacted>
INFO  TransportBuilder - Using transport dbus-java-transport-native-unixsocket to connect to unix:path=/run/user/1000/test-dbus
WARN  Utils - Failed to read from database result
java.sql.SQLException: no such column: 'urgent'
        at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:50)
        at org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(JDBC3ResultSet.java:194)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.getBoolean(HikariProxyResultSet.java)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.getMessageSendLogEntryFromResultSet(MessageSendLogStore.java:381)
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:105)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.findMessages(MessageSendLogStore.java:104)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleDecryptionErrorMessage(IncomingMessageHandler.java:303)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleMessage(IncomingMessageHandler.java:245)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:197)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleRetryEnvelope(IncomingMessageHandler.java:106)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessage(ReceiveHelper.java:251)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessages(ReceiveHelper.java:234)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:131)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesContinuously(ReceiveHelper.java:80)
        at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$12(ManagerImpl.java:871)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "receive-0" java.lang.RuntimeException: java.sql.SQLException: no such column: 'urgent'
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:109)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.findMessages(MessageSendLogStore.java:104)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleDecryptionErrorMessage(IncomingMessageHandler.java:303)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleMessage(IncomingMessageHandler.java:245)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:197)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleRetryEnvelope(IncomingMessageHandler.java:106)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessage(ReceiveHelper.java:251)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessages(ReceiveHelper.java:234)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:131)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesContinuously(ReceiveHelper.java:80)
        at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$12(ManagerImpl.java:871)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: no such column: 'urgent'
        at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:50)
        at org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(JDBC3ResultSet.java:194)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.getBoolean(HikariProxyResultSet.java)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.getMessageSendLogEntryFromResultSet(MessageSendLogStore.java:381)
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:105)
        ... 20 more
INFO  DaemonCommand - DBus daemon running on SESSION bus: org.asamk.Signal

```

After this I don't get any further messages.

It's kind of strange because it appeared to be working for a moment ad I was receiving messages.

**Comment by AsamK** [comment]
Thanks for reporting, there was a bug when handling decryption error messages.
Should be fixed now.
https://github.com/AsamK/signal-cli/actions/runs/3203952939/jobs/5234655286
