### ISSUE TITLE
Error downloading messages

### ISSUE THREAD

**Issue by aaapl** [AsamK/signal-cli#1045]
When I download messages I get the following results:

# signal-cli receive --send-read-receipts --ignore-attachments
Envelope from: ?NAME? +48111222333 (device: 1)
Timestamp: 1665329829515 (2022-10-09T15:37:09.515Z)
Server timestamps: received: 1665329829506 (2022-10-09T15:37:09.506Z) delivered: 1665329888502 (2022-10-09T15:38:08.502Z)
Received a sync message
Received sync read messages list
- From: +48123456789 Message timestamp: 1665329791216 (2022-10-09T15:36:31.216Z)

Envelope from: ?NAME? +48111222333 (device: 1)
Timestamp: 1665329841481 (2022-10-09T15:37:21.481Z)
Server timestamps: received: 1665329841749 (2022-10-09T15:37:21.749Z) delivered: 1665329888502 (2022-10-09T15:38:08.502Z)
Received a sync message
Received sync sent message
  To: +48123456789
  Timestamp: 1665329841481 (2022-10-09T15:37:21.481Z)
  Expiration started at: 1665329841773 (2022-10-09T15:37:21.773Z)
  Message timestamp: 1665329841481 (2022-10-09T15:37:21.481Z)
  Is Expiration update: true
  Expires in: 86400 seconds
  With profile key

java.lang.IllegalArgumentException: Invalid UUID string: +48123456789
        at java.base/java.util.UUID.fromString1(UUID.java:280)
        at java.base/java.util.UUID.fromString(UUID.java:258)
        at org.whispersystems.signalservice.api.push.ServiceId.parseOrThrow(ServiceId.java:37)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:140)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:196)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:955)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:938)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:67)
        at org.asamk.signal.App.handleLocalCommand(App.java:282)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)

Version: 0.11.03

**Comment by AsamK** [comment]
Will be fixed in the next version (ca5951861acb790345648b426fe91b41cbcc5da7)
You can try the development build from here: https://github.com/AsamK/signal-cli/actions/runs/3207313303

**Comment by Draghtnod** [comment]
Had the same issue. Current master solves it.

**Comment by AsamK** [comment]
The underlying issue will be fixed in the next libsignal-client version.
https://github.com/signalapp/libsignal/pull/492
