### ISSUE TITLE
Exception thrown occasionally on recieve 

### ISSUE THREAD

**Issue by johnflan** [AsamK/signal-cli#1057]
Running version `signal-cli-0.11.3` and i see the following error in my logs from time to time (on the order of once per day)

```
ERROR IncomingMessageThread - FatalException in connection thread
org.freedesktop.dbus.exceptions.FatalDBusException: java.io.EOFException: (1) Underlying transport returned -1
	at org.freedesktop.dbus.connections.AbstractConnection.readIncoming(AbstractConnection.java:1130)
	at org.freedesktop.dbus.connections.IncomingMessageThread.run(IncomingMessageThread.java:42)
Caused by: java.io.EOFException: (1) Underlying transport returned -1
	at org.freedesktop.dbus.spi.message.InputStreamMessageReader.readMessage(InputStreamMessageReader.java:47)
	at org.freedesktop.dbus.connections.transports.AbstractTransport.readMessage(AbstractTransport.java:85)
     at org.freedesktop.dbus.connections.AbstractConnection.readIncoming(AbstractConnection.java:1119)
         ... 1 common frames omitted
```

**Comment by AsamK** [comment]
Looks like signal-cli lost the connection to the dbus daemon.
Maybe the dbus daemon was restarted?

**Comment by johnflan** [comment]
You are totally right, I didn't connect the two actions -- sorry for the false report
