### ISSUE TITLE
DISPLAY variable not set

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1070]
When I try to start the daemon from crontab I get this result:
```
INFO  DaemonCommand - Starting daemon in single-account mode for +XXXXXXX
org.freedesktop.dbus.exceptions.AddressResolvingException: Cannot Resolve Session Bus Address: DISPLAY variable not set
        at org.freedesktop.dbus.utils.AddressBuilder.getSessionConnection(AddressBuilder.java:64)
        at org.freedesktop.dbus.connections.impl.DBusConnectionBuilder.forSessionBus(DBusConnectionBuilder.java:42)
        at org.freedesktop.dbus.connections.impl.DBusConnectionBuilder.forType(DBusConnectionBuilder.java:89)
        at org.freedesktop.dbus.connections.impl.DBusConnectionBuilder.forType(DBusConnectionBuilder.java:76)
        at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:358)
        at org.asamk.signal.commands.DaemonCommand.runDbusSingleAccount(DaemonCommand.java:300)
        at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:142)
        at org.asamk.signal.App.handleLocalCommand(App.java:282)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)
```

How can I fix this?

**Comment by Tsjippy** [comment]
fixed it myself:
`@reboot sleep 60 && export DISPLAY=:0.0;DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus signal-cli --config  SOMEFOLDER -u +MYNUMBER daemon`
