### ISSUE TITLE
Must have either a ServiceId or E164 number

### ISSUE THREAD

**Issue by Cempakers87** [AsamK/signal-cli#1074]
Hello, please help what should I do if facing issue like following?
Occured when execute `receive` command.
Thanks in advance.

`java.lang.AssertionError: Must have either a ServiceId or E164 number!
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:28)
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:33)
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:49)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientLocked(RecipientStore.java:743)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:177)
        at org.asamk.signal.manager.storage.recipients.RecipientResolver$RecipientResolverWrapper.resolveRecipient(RecipientResolver.java:47)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessage(ReceiveHelper.java:264)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessages(ReceiveHelper.java:235)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:132)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:109)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:957)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:940)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:71)
        at org.asamk.signal.App.handleLocalCommand(App.java:282)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)`

**Comment by AsamK** [comment]
Thanks for reporting.
Should be fixed now, you could try this development build: https://github.com/AsamK/signal-cli/actions/runs/3346887012
