### ISSUE TITLE
Sending message to group fails / receiving times out

### ISSUE THREAD

**Issue by piratenpanda** [AsamK/signal-cli#1083]
Using latest git code I get the following error. Unfortunately I can't go back to previous versions due to config changes.

```
$SIGNAL_CLI --verbose -u $USER send -m "Test" -g $GROUP
2022-11-03T14:27:37.691+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2022-11-03T14:27:38.011+0100 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.21.1
2022-11-03T14:27:38.012+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-11-03T14:27:38.310+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-11-03T14:27:38.437+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@6b98a075
2022-11-03T14:27:38.439+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-11-03T14:27:40.046+0100 [main] DEBUG o.a.signal.manager.helper.SendHelper - Can use sender key for 5/5 recipients.
2022-11-03T14:27:40.069+0100 [main] DEBUG LibSignal - [SignalServiceMessageSender]: [1667482059716] Sending a group data message to 5 recipients using DistributionId 2468a807-5e39-49aa-a19f-3abfffe37b31
2022-11-03T14:27:40.114+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-11-03T14:27:40.117+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2022-11-03T14:27:40.117+0100 [msl-cleanup] DEBUG o.a.s.m.s.s.MessageSendLogStore - Stopping msl cleanup thread
org.signal.libsignal.protocol.InvalidSessionException: invalid session: failed to decode session record protobuf
        at org.signal.libsignal.internal.Native.SessionRecord_Deserialize(Native Method)
        at org.signal.libsignal.protocol.state.SessionRecord.<init>(SessionRecord.java:47)
        at org.asamk.signal.manager.storage.sessions.SessionStore.getSessionRecordFromResultSet(SessionStore.java:341)
        at org.asamk.signal.manager.storage.sessions.SessionStore.lambda$getAllAddressesWithActiveSessions$2(SessionStore.java:226)
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:106)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.asamk.signal.manager.storage.sessions.SessionStore.getAllAddressesWithActiveSessions(SessionStore.java:230)
        at org.asamk.signal.manager.storage.protocol.SignalProtocolStore.getAllAddressesWithActiveSessions(SignalProtocolStore.java:139)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.buildGroupTargetInfo(SignalServiceMessageSender.java:2159)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupMessage(SignalServiceMessageSender.java:2038)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupDataMessage(SignalServiceMessageSender.java:496)
        at org.asamk.signal.manager.helper.SendHelper.lambda$sendGroupMessage$10(SendHelper.java:348)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternalWithSenderKey(SendHelper.java:564)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternal(SendHelper.java:430)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessage(SendHelper.java:370)
        at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:310)
        at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:103)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:467)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:561)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:200)
        at org.asamk.signal.App.handleLocalCommand(App.java:289)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
```

when trying to receive a message I get a timeout:

```
 $SIGNAL_CLI -u $USER receive
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 100 ms
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 100 ms
```

**Comment by AsamK** [comment]
Looks like the session record got corrupted, I've pushed a commit to recover from that case.
Not sure if the receive timeout is related, if it still occurs with the latest master, you can open a new issue for that and include `--verbose` log output for it.
