### ISSUE TITLE
Sendimg message to groups still fails in latest master

### ISSUE THREAD

**Issue by piratenpanda** [AsamK/signal-cli#1085]
I get the following output:

```
$SIGNAL_CLI --verbose -u $USER send -m "Test" -g $GROUP
2022-11-04T09:11:04.434+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2022-11-04T09:11:04.737+0100 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.21.1
2022-11-04T09:11:04.739+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-11-04T09:11:05.024+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-11-04T09:11:05.151+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@6b98a075
2022-11-04T09:11:05.154+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-11-04T09:11:06.805+0100 [main] DEBUG o.a.signal.manager.helper.SendHelper - Can use sender key for 5/5 recipients.
2022-11-04T09:11:06.827+0100 [main] DEBUG LibSignal - [SignalServiceMessageSender]: [1667549466460] Sending a group data message to 5 recipients using DistributionId 2468a807-5e39-49aa-a19f-3abfffe37b31
2022-11-04T09:11:06.872+0100 [main] WARN  o.asamk.signal.manager.storage.Utils - Failed to read from database result
org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
        at org.sqlite.core.DB.newSQLException(DB.java:1135)
        at org.sqlite.core.DB.newSQLException(DB.java:1146)
        at org.sqlite.core.DB.throwex(DB.java:1106)
        at org.sqlite.jdbc3.JDBC3ResultSet.next(JDBC3ResultSet.java:82)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:103)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.asamk.signal.manager.storage.sessions.SessionStore.getAllAddressesWithActiveSessions(SessionStore.java:229)
        at org.asamk.signal.manager.storage.protocol.SignalProtocolStore.getAllAddressesWithActiveSessions(SignalProtocolStore.java:139)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.buildGroupTargetInfo(SignalServiceMessageSender.java:2159)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupMessage(SignalServiceMessageSender.java:2038)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupDataMessage(SignalServiceMessageSender.java:496)
        at org.asamk.signal.manager.helper.SendHelper.lambda$sendGroupMessage$10(SendHelper.java:348)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternalWithSenderKey(SendHelper.java:564)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternal(SendHelper.java:430)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessage(SendHelper.java:370)
        at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:310)
        at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:103)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:467)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:561)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:200)
        at org.asamk.signal.App.handleLocalCommand(App.java:289)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
2022-11-04T09:11:06.904+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-11-04T09:11:06.908+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2022-11-04T09:11:06.908+0100 [msl-cleanup] DEBUG o.a.s.m.s.s.MessageSendLogStore - Stopping msl cleanup thread
java.lang.RuntimeException: org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:110)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.asamk.signal.manager.storage.sessions.SessionStore.getAllAddressesWithActiveSessions(SessionStore.java:229)
        at org.asamk.signal.manager.storage.protocol.SignalProtocolStore.getAllAddressesWithActiveSessions(SignalProtocolStore.java:139)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.buildGroupTargetInfo(SignalServiceMessageSender.java:2159)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupMessage(SignalServiceMessageSender.java:2038)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupDataMessage(SignalServiceMessageSender.java:496)
        at org.asamk.signal.manager.helper.SendHelper.lambda$sendGroupMessage$10(SendHelper.java:348)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternalWithSenderKey(SendHelper.java:564)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternal(SendHelper.java:430)
        at org.asamk.signal.manager.helper.SendHelper.sendGroupMessage(SendHelper.java:370)
        at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:310)
        at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:103)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:467)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:561)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:200)
        at org.asamk.signal.App.handleLocalCommand(App.java:289)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
Caused by: org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
        at org.sqlite.core.DB.newSQLException(DB.java:1135)
        at org.sqlite.core.DB.newSQLException(DB.java:1146)
        at org.sqlite.core.DB.throwex(DB.java:1106)
        at org.sqlite.jdbc3.JDBC3ResultSet.next(JDBC3ResultSet.java:82)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
        at org.asamk.signal.manager.storage.Utils$1.tryAdvance(Utils.java:103)
        ... 23 more
```
I wonder how the SQL database got corrupted. This signal-cli gets involked by a cron job and sends messages when things change on the server.

**Comment by AsamK** [comment]
Looks similar to this issue https://github.com/AsamK/signal-cli/issues/885
Is your database file on any special filesystem?

**Comment by piratenpanda** [comment]
It's Ubuntu on Windows. Yeah sorry about that, but it's the best I could do at work. So I actually don't know if it's NTFS or ext4

**Comment by AsamK** [comment]
Sorry, I can't help with that, it's some issue with sqlite and WSL...
I'd suggest to check that you're using WSL2 and that the signal-cli data is on the Linux partition with ext4, not the mounted windows dirs. I assume the would have the best chance of working

**Comment by piratenpanda** [comment]
I converted the wsl1 install to wsl2 and it signal-cli runs on ext4. Any hints how to to undo the malformed database? What commands would I need to run?

**Comment by piratenpanda** [comment]
I there a way to recreate account.db without deleting the account and registering again?

**Comment by lampnout** [comment]
I'll share my experience in case it helps anyone in the future. I had a similar stack trace about database disk image being malformed. I removed the `account.db` and re-ran signal-cli. It worked with no issues.
