### ISSUE TITLE
Cannot invoke "org.asamk.signal.manager.Settings.trustNewIdentity()" because "this.settings" is null

### ISSUE THREAD

**Issue by 1a7r0ch3** [AsamK/signal-cli#1093]
I get this error when issuing any command.
```
$ signal-cli --verbose updateAccount 
2022-11-08T23:20:08.259+0100 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.19.3
2022-11-08T23:20:08.263+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-11-08T23:20:08.492+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-11-08T23:20:08.585+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@70fab835
2022-11-08T23:20:08.586+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
Error loading state file for user +XXX: Cannot invoke "org.asamk.signal.manager.Settings.trustNewIdentity()" because "this.settings" is null (NullPointerException)
java.lang.NullPointerException: Cannot invoke "org.asamk.signal.manager.Settings.trustNewIdentity()" because "this.settings" is null
	at org.asamk.signal.manager.storage.SignalAccount.lambda$getIdentityKeyStore$18(SignalAccount.java:1159)
	at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)
	at org.asamk.signal.manager.storage.SignalAccount.getIdentityKeyStore(SignalAccount.java:1158)
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:673)
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181)
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92)
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)
	at org.asamk.signal.App.loadManager(App.java:355)
	at org.asamk.signal.App.handleLocalCommand(App.java:288)
	at org.asamk.signal.App.init(App.java:229)
	at org.asamk.signal.Main.main(Main.java:60)
```

**Comment by 1a7r0ch3** [comment]
So quick to fix, thanks!
