### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid UUID string: SOMEPHONENUMBER

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1094]
I think something is wrong with my master signal-cli account.
When I run `signal-cli receive` I get this response:
```
java.lang.IllegalArgumentException: Invalid UUID string: +SOMEPHONENUMBER
        at java.base/java.util.UUID.fromString1(UUID.java:280)
        at java.base/java.util.UUID.fromString(UUID.java:258)
        at org.whispersystems.signalservice.api.push.ServiceId.parseOrThrow(ServiceId.java:37)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:140)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:196)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:955)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:938)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:67)
        at org.asamk.signal.App.handleLocalCommand(App.java:282)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)
```

Everytime I run the command the phone number is different but the result the same.
I lost the sim card so I cannot reregister

**Comment by Tsjippy** [comment]
nevcer mind, I should have updated to version 0.11.5 first. Fixed by that
