### ISSUE TITLE
Cannot add device

### ISSUE THREAD

**Issue by kroerig** [AsamK/signal-cli#1131]
I'm trying to link an instance of https://github.com/bbernhard/signal-cli-rest-api to my signal-cli.

`signal-cli -v addDevice --uri 'sgnl://linkdevice?uuid=jYufsorhVUxxyjr2PBTEyw&pub_key=Bel5qEBqnbRuR3XXZGtNV9rOc3quqcV%2FGd6Umiykl9o3'
2022-12-20T22:41:13.381+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2022-12-20T22:41:14.016+0100 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.21.1
2022-12-20T22:41:14.023+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-12-20T22:41:14.803+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-12-20T22:41:15.088+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@13f17eb4
2022-12-20T22:41:15.091+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-12-20T22:41:17.389+0100 [main] ERROR o.a.signal.commands.AddDeviceCommand - Add device link failed
org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1761)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1742)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1680)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1674)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendProvisioningMessage(PushServiceSocket.java:462)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.addDevice(SignalServiceAccountManager.java:882)
        at org.asamk.signal.manager.helper.AccountHelper.addDevice(AccountHelper.java:184)
        at org.asamk.signal.manager.ManagerImpl.addDeviceLink(ManagerImpl.java:340)
        at org.asamk.signal.commands.AddDeviceCommand.handleCommand(AddDeviceCommand.java:48)
        at org.asamk.signal.App.handleLocalCommand(App.java:289)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
2022-12-20T22:41:17.537+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-12-20T22:41:17.545+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Add device link failed
org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1761)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1742)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1680)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1674)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendProvisioningMessage(PushServiceSocket.java:462)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.addDevice(SignalServiceAccountManager.java:882)
        at org.asamk.signal.manager.helper.AccountHelper.addDevice(AccountHelper.java:184)
        at org.asamk.signal.manager.ManagerImpl.addDeviceLink(ManagerImpl.java:340)
        at org.asamk.signal.commands.AddDeviceCommand.handleCommand(AddDeviceCommand.java:48)
        at org.asamk.signal.App.handleLocalCommand(App.java:289)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
`
What's going wrong:

Signal-CLI: 0.11.6

(The URI has been made invalid for this post)

**Comment by Underground78** [comment]
Same issue here.

**Comment by kroerig** [comment]
I tried several times.

**Comment by SlugFiller** [comment]
Are you doing the process fast enough? A device provision link is only valid for 60 seconds. After that, trying to use the link will give a 404 error, as above. At which point the only option is to generate a new link/QR and try again.
