### ISSUE TITLE
Cannot add member in group

### ISSUE THREAD

**Issue by nkray2704** [AsamK/signal-cli#1146]
Hi Team, Below exception occurred when add member in group

com.altametrics.signal.commands.exceptions.UserErrorException: The user +919873788703 is not registered.
	at com.altametrics.signal.commands.UpdateGroupCommand.processCommand(UpdateGroupCommand.java:291)
	at com.altametrics.signal.test.CreateGroupIDTest.handleLocalCommand(CreateGroupIDTest.java:88)
	at com.altametrics.signal.test.CreateGroupIDTest.processRequest(CreateGroupIDTest.java:73)
	at com.altametrics.signal.test.CreateGroupIDTest.init(CreateGroupIDTest.java:64)
	at com.altametrics.signal.test.CreateGroupIDTest.main(CreateGroupIDTest.java:37)

**Comment by AsamK** [comment]
That's not a signal-cli stacktrace and it probably means the user is not registered on signal servers.

**Comment by nkray2704** [comment]
this "+919873788703" signal number is the member signal number. As per document member signal mobile number not need to register. Below is the actual log

org.asamk.signal.manager.api.UnregisteredRecipientException: Unregistered user: +918858142021
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:208)
	at org.asamk.signal.manager.helper.RecipientHelper.resolveRecipient(RecipientHelper.java:89)
	at org.asamk.signal.manager.helper.RecipientHelper.resolveRecipients(RecipientHelper.java:78)
	at org.asamk.signal.manager.ManagerImpl.updateGroup(ManagerImpl.java:416)
	at  #org.asamk.signal.commands.UpdateGroupCommand.processCommand(UpdateGroupCommand.java:254)
