### ISSUE TITLE
Signal Desktop Sync Issues + "Receive" Issues + Link Issue

### ISSUE THREAD

**Issue by muad-dumb** [AsamK/signal-cli#1171]
When attempting to Receive, Signal CLI will print some messages received, then spit out 1000 lines of 

WARN  SyncHelper - Sync groups contained invalid group, ignoring: ID missing on group record!

then print some more messages, and then more lines of the above WARN message.

At the bottom of the Receive output, the CLI prints:

java.lang.IllegalArgumentException: Invalid UUID string: +"contact phone number"
	at java.base/java.util.UUID.fromString1(UUID.java:280)
	at java.base/java.util.UUID.fromString(UUID.java:258)
	at org.whispersystems.signalservice.api.push.ServiceId.parseOrThrow(ServiceId.java:37)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:140)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:196)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
	at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:955)
	at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:938)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:67)
	at org.asamk.signal.App.handleLocalCommand(App.java:282)
	at org.asamk.signal.App.init(App.java:222)
	at org.asamk.signal.Main.main(Main.java:60)

When checking that Contact's conversation settings through the phone app, the Contact appears to be registered (no error messages) and the Safety Number is intact.

These issues are concurrent with the Signal Desktop not updating any messages even after Receive. 

Recently there was a Linking issue which seems to have been resolved (linking through the CLI QR Code would be successful, but the Desktop would still insist that it was Unlinked; the fix was to click on the Please Link banner and scan the provided QR code (i put in a different name for this second Linked instance, may or may not be causing issues? the Signal Phone App shows two linked devices, which isn't unusual for my Signal CLI / Signal Desktop setup). The banner has since disappeared, but Signal Desktop remains unsynced.

This is within the (possibly unrelated) context of a larger DNS issue through connecting this laptop through the Signal android phone's wifi, but that is being sidestepped by attempting these links and Receives through public wifi, which is working.

**Comment by muad-dumb** [comment]
> The `ID missing on group record` error is probably caused by a bug in the Signal Phone App, the groups in the sync message must always have an id.
> 
> Also looks like you're using an older signal-cli version, the `Invalid UUID string` error is fixed in the latest version.

Copy, thank you! 

My signal-cli doesn't update/upgrade when I run updates to my packages in the CLI, is there a way to make it update/upgrade along with everything else?

**Comment by AsamK** [comment]
For updating you'll need a distro specific package repository, if one is available.
There are some community provided ones listed here: https://github.com/AsamK/signal-cli/wiki/Binary-distributions
