### ISSUE TITLE
register was successful but verify failed with error message

### ISSUE THREAD

**Issue by Euplectello** [AsamK/signal-cli#1176]
Hello all, after successfully receiving the voice message for registering a landline i tried to verify with the given code and received the folloiwing error message. Can anyone please help ?

Thank you, Olaf

./signal-cli -u +4940xxxxxx verify yyyyyy

java.lang.NullPointerException: Cannot invoke "org.signal.libsignal.protocol.IdentityKeyPair.getPublicKey()" because the return value of "org.asamk.signal.manager.storage.SignalAccount.getPniIdentityKeyPair()" is null
	at org.asamk.signal.manager.storage.SignalAccount.finishRegistration(SignalAccount.java:1597)
	at org.asamk.signal.manager.RegistrationManagerImpl.verifyAccount(RegistrationManagerImpl.java:140)
	at org.asamk.signal.commands.VerifyCommand.verify(VerifyCommand.java:67)
	at org.asamk.signal.commands.VerifyCommand.handleCommand(VerifyCommand.java:43)
	at org.asamk.signal.App.handleRegistrationCommand(App.java:261)
	at org.asamk.signal.App.init(App.java:221)
	at org.asamk.signal.Main.main(Main.java:60)

**Comment by AsamK** [comment]
Seems to be a bug with older account files, please try the development build, to check if that fixes the issue: https://github.com/AsamK/signal-cli/actions/runs/4096415647
