### ISSUE TITLE
Send Fails - with Exception in thread "OkHttp Dispatcher"

### ISSUE THREAD

**Issue by ldavis2020** [AsamK/signal-cli#1195]
Hi all,

I'm running signal-cli on proxmox (based OS not a container or VM) and am running into problems sending messages.

I was able to register and verify my account and can receive messages fine, but get the following error when I try to send messages:

```
signal-cli --config /home/account/signal-cli-config --verbose -a +123456789 send -m "Test message!" +1987654321
2023-02-26T09:41:13.247+1100 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.21.1
2023-02-26T09:41:13.250+1100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-02-26T09:41:13.324+1100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@5f3990e
2023-02-26T09:41:13.324+1100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-02-26T09:41:14.736+1100 [main] WARN  LibSignal - [PhoneNumberFormatter]: Got local CC: US
2023-02-26T09:41:16.033+1100 [OkHttp https://cdsi.signal.org/...] DEBUG LibSignal - [CdsiSocket]: [onOpen]
2023-02-26T09:41:16.034+1100 [OkHttp https://cdsi.signal.org/...] DEBUG LibSignal - [CdsiSocket]: [onMessage] stage: WAITING_FOR_CONNECTION
Exception in thread "OkHttp Dispatcher" java.lang.NoClassDefFoundError: org/signal/libsignal/cds2/DcapException
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:343)
        at org.signal.libsignal.internal.Native.Cds2ClientState_New(Native.java)
        at org.signal.libsignal.cds2.Cds2Client.<init>(Cds2Client.java:37)
        at org.whispersystems.signalservice.api.services.CdsiSocket$1.onMessage(CdsiSocket.java:122)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:338)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:247)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```
Some additional info that might be useful:
```
$ signal-cli --version
signal-cli 0.11.7

$ java --version
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1deb11u1, mixed mode, sharing)
```
Any thoughts on why I might be seeing this issue would be most appreciated!

Thanks!

**Comment by AsamK** [comment]
You need libsignal-client version 0.22.0 for signal-cli 0.11.7

**Comment by ldavis2020** [comment]
Thanks, all sorted!

Love `signal-cli` btw!
