### ISSUE TITLE
Failed to load native library (sqlite)

### ISSUE THREAD

**Issue by Android-X13** [AsamK/signal-cli#1213]
All of a sudden I am getting this error when trying to send a message. I was using version `signal-cli 0.11.4` without problems, after this error I installed the latest one and still getting the same response.

Similar to #1182, #1129

```
INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.22.2
2023-03-25T17:21:25.117+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
OpenJDK Server VM warning: You have loaded library /tmp/sqlite-3.40.1.0-0f34d1f4-31cc-46e7-b5bc-a4225cd11b6b-libsqlitejdbc.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Failed to load native library:sqlite-3.40.1.0-0f34d1f4-31cc-46e7-b5bc-a4225cd11b6b-libsqlitejdbc.so. osinfo: Linux/aarch64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.40.1.0-0f34d1f4-31cc-46e7-b5bc-a4225cd11b6b-libsqlitejdbc.so: /tmp/sqlite-3.40.1.0-0f34d1f4-31cc-46e7-b5bc-a4225cd11b6b-libsqlitejdbc.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AARCH64 .so on a ARM platform)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)
        at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:67)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1653)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1653)
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)
        at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:28)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:639)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)
        at org.asamk.signal.App.loadManager(App.java:355)
        at org.asamk.signal.App.handleLocalCommand(App.java:288)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
2023-03-25T17:21:26.557+0200 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1653)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1653)
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)
        at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:28)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:639)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)
        at org.asamk.signal.App.loadManager(App.java:355)
        at org.asamk.signal.App.handleLocalCommand(App.java:288)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/org/sqlite/native/Linux/aarch64:/usr/java/packages/lib:/lib:/usr/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:67)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
        ... 30 common frames omitted
```

On a Raspberry Pi 4:

`Linux raspberrypi 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux`

**Comment by DrAndZe** [comment]
I have the same issue, it is probably related to latest kernel update from:
uname -a
Linux raspi4 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux
to 
Linux raspi4 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux
Running the 32bit version of RaspberrypiOS the aarch64 library cannot be loaded.
I have no idea how to solve it yet.

**Comment by DrAndZe** [comment]
I added 
arm_64bit=0
to the 
/boot/config.txt 
and rebooted. Voilá:
Linux raspi4 6.1.19-v7l+ #1637 SMP Tue Mar 14 11:07:55 GMT 2023 armv7l GNU/Linux
And signal_cli is working again.

**Comment by Android-X13** [comment]
> arm_64bit=0

It worked, thanks!

I'll close this issue then.
