### ISSUE TITLE
`listIdentities` now seems to require a target phone number (`-n`)

### ISSUE THREAD

**Issue by camwebb** [AsamK/signal-cli#1215]
(openjdk 17.0.6, libsignal-client 0.22.0, signal-cli 0.11.7)

```bash
signal-cli -u +xxxxxxxxxxx listIdentities
```
used to work, but now gives an error:
``` 
java.lang.AssertionError: Must have either a UUID or E164 number!
```
However,
```bash
signal-cli -u +xxxxxxxxxxx listIdentities -n +xxxxxxxxxxx
```
works fine. Not a problem, but the help and man pages need to be updated to indicate that a target number is now required. 

(Thanks for the great app!)

**Comment by AsamK** [comment]
The `listIdentities` command should still work without target phone number.
Can you please run the command with the `--verbose` flag and post the error stack trace here?

**Comment by camwebb** [comment]
```
signal-cli --verbose -u +xxxxxxxxxxx listIdentities

2023-04-04T13:56:05.102-0800 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.20.0
2023-04-04T13:56:05.107-0800 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-04-04T13:56:05.347-0800 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-04-04T13:56:05.436-0800 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@59aa20b3
2023-04-04T13:56:05.438-0800 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-04-04T13:56:07.128-0800 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-04-04T13:56:07.130-0800 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.

java.lang.AssertionError: Must have either a UUID or E164 number!
	at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:22)
	at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:35)
	at org.asamk.signal.manager.storage.recipients.RecipientResolver.resolveRecipient(RecipientResolver.java:22)
	at org.asamk.signal.manager.ManagerImpl.toIdentity(ManagerImpl.java:1048)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.asamk.signal.manager.ManagerImpl.getIdentities(ManagerImpl.java:1039)
	at org.asamk.signal.commands.ListIdentitiesCommand.handleCommand(ListIdentitiesCommand.java:55)
	at org.asamk.signal.App.handleLocalCommand(App.java:282)
	at org.asamk.signal.App.init(App.java:222)
	at org.asamk.signal.Main.main(Main.java:60)
```

**Comment by camwebb** [comment]
Great! thanks @AsamK
