### ISSUE TITLE
Unable to link device - "Link request error: StatusCode: 409"

### ISSUE THREAD

**Issue by itsabdelrahman** [AsamK/signal-cli#1226]
Hey Sebastian, incredible project - appreciate your work on this!

---

Just wanted to let you know that I wasn't able to link `signal-cli` as a device to my existing Signal account.

First, I executed the `signal-cli link` command and piped its output to `qrencode`, as per the instructions in the [wiki](https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)):

```
$ signal-cli link -n "signal-cli" | tee >(xargs -L 1 qrencode -t utf8)
sgnl://linkdevice?uuid=[REDACTED]&pub_key=[REDACTED]
█████████████████████████████████████
█████████████████████████████████████
████ ▄▄▄▄▄ █ ▄ ▄▀ ▄█▀█▀█▄█ ▄▄▄▄▄ ████
████ █   █ ██▄ ▄█▄ ▄▀▄▀▄██ █   █ ████
████ █▄▄▄█ █ █▀▄█▀▀██▀██▀█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ █ █ █ █▄█ █▄█▄▄▄▄▄▄▄████
████▄▄ ▀█ ▄▀  ▄▄▀▀█ ▀▄▀▀ ▄  ▄▀▀▄ ████
█████ █▄▀▄▄▀▄█▄ ██   █▄▄▀▀▄ ▄▄▄█ ████
████ █▄▀▀ ▄██ ▄▄ ██ ▄▄█ ▀▀  ██▀█▀████
█████▄█▄ █▄█ ▄ ▄█▄▀▄▀▄▀▄▀█ █▀▄█▀ ████
████▄██▀▄ ▄█▄ ▄▄ ▀▀█▀▄█ ▀█  █ ▀█ ████
████▄▄▄   ▄ ██▄▄ ▄ ▄ ▄█ ▀ █ ▀██▀ ████
████▄▄████▄█ █▄▄ ▀ ▄ ▄█▀ ▄▄▄  ▀  ████
████ ▄▄▄▄▄ █▀▀█▄▀▄▀▄▀▄ █ █▄█ ▀█▀▄████
████ █   █ ██▀█▄  ▀▄ ▄█ ▄ ▄▄  ▀▀ ████
████ █▄▄▄█ █ ██ ▄█ ▄ █ █ ▄█▀▄ ▄▄▄████
████▄▄▄▄▄▄▄█▄▄█▄█▄█▄█▄██▄██▄█▄██▄████
█████████████████████████████████████
█████████████████████████████████████
```

Once I scanned the QR code using the Signal Android app (aka the master device), the app showed me a "Device approved!" toast 😄 Immediately afterwards, I got the following error from `signal-cli`:

```
INFO  ProvisioningManagerImpl - Received link information from [REDACTED], linking in progress ...
Link request error: StatusCode: 409
```

---

Here's what I get when I run the same command with the `--verbose` flag:

<details>
<pre>
$ signal-cli -v link -n "signal-cli" | tee >(xargs -L 1 qrencode -t utf8)
2023-04-16T18:07:25.633+0200 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-04-16T18:07:25.979+0200 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.22.0
2023-04-16T18:07:25.981+0200 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-04-16T18:07:26.172+0200 [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:1632497828] connect()
2023-04-16T18:07:26.770+0200 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:1632497828] onOpen() connected
sgnl://linkdevice?uuid=[REDACTED]&pub_key=[REDACTED]
█████████████████████████████████████
█████████████████████████████████████
████ ▄▄▄▄▄ █ ▄ ▄▀ ▄█▀█▀█▄█ ▄▄▄▄▄ ████
████ █   █ ██▄ ▄█▄ ▄▀▄▀▄██ █   █ ████
████ █▄▄▄█ █ █▀▄█▀▀██▀██▀█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ █ █ █ █▄█ █▄█▄▄▄▄▄▄▄████
████▄▄ ▀█ ▄▀  ▄▄▀▀█ ▀▄▀▀ ▄  ▄▀▀▄ ████
█████ █▄▀▄▄▀▄█▄ ██   █▄▄▀▀▄ ▄▄▄█ ████
████ █▄▀▀ ▄██ ▄▄ ██ ▄▄█ ▀▀  ██▀█▀████
█████▄█▄ █▄█ ▄ ▄█▄▀▄▀▄▀▄▀█ █▀▄█▀ ████
████▄██▀▄ ▄█▄ ▄▄ ▀▀█▀▄█ ▀█  █ ▀█ ████
████▄▄▄   ▄ ██▄▄ ▄ ▄ ▄█ ▀ █ ▀██▀ ████
████▄▄████▄█ █▄▄ ▀ ▄ ▄█▀ ▄▄▄  ▀  ████
████ ▄▄▄▄▄ █▀▀█▄▀▄▀▄▀▄ █ █▄█ ▀█▀▄████
████ █   █ ██▀█▄  ▀▄ ▄█ ▄ ▄▄  ▀▀ ████
████ █▄▄▄█ █ ██ ▄█ ▄ █ █ ▄█▀▄ ▄▄▄████
████▄▄▄▄▄▄▄█▄▄█▄█▄█▄█▄██▄██▄█▄██▄████
█████████████████████████████████████
█████████████████████████████████████
2023-04-16T18:07:39.654+0200 [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:1632497828] disconnect()
2023-04-16T18:07:39.666+0200 [main] INFO  o.a.s.m.ProvisioningManagerImpl - Received link information from [REDACTED], linking in progress ...
2023-04-16T18:07:39.747+0200 [main] DEBUG o.a.s.m.ProvisioningManagerImpl - Finishing new device registration
2023-04-16T18:07:39.810+0200 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:1632497828] onClosing()
2023-04-16T18:07:39.810+0200 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:1632497828] onClose()
Link request error: StatusCode: 409
org.whispersystems.signalservice.internal.push.exceptions.MismatchedDevicesException: StatusCode: 409
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1779)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1756)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1694)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1688)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.finishNewDeviceRegistration(PushServiceSocket.java:455)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.finishNewDeviceRegistration(SignalServiceAccountManager.java:724)
	at org.asamk.signal.manager.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:129)
	at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
	at org.asamk.signal.App.handleProvisioningCommand(App.java:238)
	at org.asamk.signal.App.init(App.java:192)
	at org.asamk.signal.Main.main(Main.java:60)
</pre>
</details>

---

- Linked device
  - Machine: Mac Mini (M1, 2020) 
  - OS: macOS Ventura `13.3.1`
  - `signal-cli` version: `0.11.8`
- Master device
  -  Signal Android _([the website distrubution build](https://signal.org/android/apk/))_ version: `6.17.3`
 
---

Thank you!

**Comment by AsamK** [comment]
409 is returned by the signal server, when the new device (in this case signal-cli) doesn't have a capability that the primary device has. Would have to check which one that is.
```java
      final DeviceCapabilities capabilities = accountAttributes.getCapabilities();
      if (capabilities != null && isCapabilityDowngrade(account.get(), capabilities)) { 
       throw new WebApplicationException(Response.status(409).build());
      } 
```
https://github.com/signalapp/Signal-Server/blob/main/service/src/main/java/org/whispersystems/textsecuregcm/controllers/DeviceController.java#L190
