### ISSUE TITLE
urgent: ERROR IncomingMessageThread - FatalException in connection thread 

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1246]
I am on version 0.11.10 on Ubuntu.
When I try to start a deamon with `signal-cli daemon` I get this response:

```
INFO  DaemonCommand - Starting daemon in multi-account mode
INFO  TransportBuilder - Using transport dbus-java-transport-native-unixsocket for address unix:path=/run/user/1001/bus
ERROR IncomingMessageThread - FatalException in connection thread
org.freedesktop.dbus.exceptions.FatalDBusException: java.io.EOFException: (1) Underlying transport returned -1
        at org.freedesktop.dbus.connections.AbstractConnection.readIncoming(AbstractConnection.java:1180)
        at org.freedesktop.dbus.connections.IncomingMessageThread.run(IncomingMessageThread.java:42)
Caused by: java.io.EOFException: (1) Underlying transport returned -1
        at org.freedesktop.dbus.spi.message.InputStreamMessageReader.readMessage(InputStreamMessageReader.java:47)
        at org.freedesktop.dbus.connections.transports.AbstractTransport.readMessage(AbstractTransport.java:89)
        at org.freedesktop.dbus.connections.AbstractConnection.readIncoming(AbstractConnection.java:1169)
        ... 1 common frames omitted
Dbus command failed: Disconnected
```

I get the same error when in single account mode

**Comment by AsamK** [comment]
Looks like an issue with the DBus server ...
Maybe a more verbose log output with `-vvv` provides more information.
