### ISSUE TITLE
Exception in thread "OkHttp Dispatcher"

### ISSUE THREAD

**Issue by t351206** [AsamK/signal-cli#1249]
Hi,

I am getting the following error message when  sending a message:

Exception in thread "OkHttp Dispatcher" java.lang.UnsatisfiedLinkError: 'byte[] org.signal.libsignal.internal.Native.Cds2ClientState_InitialRequest(long)'
        at org.signal.libsignal.internal.Native.Cds2ClientState_InitialRequest(Native Method)
        at org.signal.libsignal.cds2.Cds2Client.initialRequest(Cds2Client.java:52)
        at org.whispersystems.signalservice.api.services.CdsiSocket$1.onMessage(CdsiSocket.java:125)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:338)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:247)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

My system:
raspberrypi (Raspbian GNU/Linux 11 (bullseye))
openjdk 17.0.6 2023-01-17
signal-cli 0.11.9.1
native library version: libsignal_v0.24.0 ( https://github.com/exquo/signal-libs-build/releases/download/libsignal_v0.24.0/libsignal_jni.so-v0.24.0-armv7-unknown-linux-gnueabihf.tar.gz)

Hope you can help ...

**Comment by t351206** [comment]
after installing the latest version 0.11.10 I get the following error message:

java.lang.RuntimeException: JNI error Null pointer in get_array_elements array argument
        at org.signal.libsignal.internal.Native.PreKeyBundle_New(Native Method)
        at org.signal.libsignal.protocol.state.PreKeyBundle.<init>(PreKeyBundle.java:36)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:694)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getPreKeys(SignalServiceMessageSender.java:2538)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2509)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2489)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:2095)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendContent(SignalServiceMessageSender.java:483)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendDataMessage(SignalServiceMessageSender.java:436)
        at org.asamk.signal.manager.helper.SendHelper.lambda$sendMessage$18(SendHelper.java:631)
        at org.asamk.signal.manager.helper.SendHelper.handleSendMessage(SendHelper.java:656)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:629)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:95)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:486)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:470)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:591)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:207)
        at org.asamk.signal.App.handleLocalCommand(App.java:289)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
