### ISSUE TITLE
Can't link signal-desktop to signal-cli

### ISSUE THREAD

**Issue by strake** [AsamK/signal-cli#1281]
I'm fairly sure signal-cli is primary, since i used it to link other signal-desktops. But now (since a few weeks ago) it has been failing with the following messages:

```shell
$ signal-cli -u+XXXXXXXXXXX addDevice --uri 'sgnl://linkdevice?uuid=sgnl://linkdevice?uuid=XXXX&pub_key=XXXX'
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
ERROR AddDeviceCommand - Add device link failed
org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1799)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1780)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1718)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1712)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendProvisioningMessage(PushServiceSocket.java:488)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.addDevice(SignalServiceAccountManager.java:767)
        at org.asamk.signal.manager.helper.AccountHelper.addDevice(AccountHelper.java:275)
        at org.asamk.signal.manager.internal.ManagerImpl.addDeviceLink(ManagerImpl.java:363)
        at org.asamk.signal.commands.AddDeviceCommand.handleCommand(AddDeviceCommand.java:50)
        at org.asamk.signal.App.handleLocalCommand(App.java:289)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
Add device link failed
$ 
```

I tried multiple times. I am using signal-cli v0.11.11.

Maybe a dup of #1131, but that issue is closed, and i'm not sure whether it is, as the versions and error locations are not the same.

**Comment by AsamK** [comment]
You're uri looks wrong, there's signl:// twice in it.

**Comment by strake** [comment]
Derp, you're right, sorry for the noise!
