### ISSUE TITLE
java.lang.IllegalArgumentException: Argument is not an array

### ISSUE THREAD

**Issue by morph027** [AsamK/signal-cli#1287]
using graalvm 22.3.3 throws the following error in JSON-RPC calls:

```
ERROR SignalJsonRpcDispatcherHandler - Command execution failed
java.lang.IllegalArgumentException: Argument is not an array
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.getPrimitiveArrayRegion(JNIGeneratedMethodSupport.java:125)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetByteArrayRegion(JNIFunctions.java:0)
        at org.signal.libsignal.internal.Native.ProfileKey_GetProfileKeyVersion(Native.java)
        at org.signal.libsignal.zkgroup.profiles.ProfileKey.getProfileKeyVersion(ProfileKey.java:32)
        at org.whispersystems.signalservice.api.services.ProfileService.getProfile(ProfileService.java:84)
        at org.asamk.signal.manager.helper.ProfileHelper.retrieveProfile(ProfileHelper.java:378)
        at org.asamk.signal.manager.helper.ProfileHelper.retrieveProfile(ProfileHelper.java:313)
        at org.asamk.signal.manager.helper.ProfileHelper.getRecipientProfile(ProfileHelper.java:249)
        at org.asamk.signal.manager.helper.ProfileHelper.getRecipientProfile(ProfileHelper.java:94)
        at org.asamk.signal.manager.internal.ManagerImpl.lambda$getUserStatus$6(ManagerImpl.java:238)
        at java.base@17.0.8/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
        at java.base@17.0.8/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base@17.0.8/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@17.0.8/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@17.0.8/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.asamk.signal.manager.internal.ManagerImpl.getUserStatus(ManagerImpl.java:231)
        at org.asamk.signal.commands.GetUserStatusCommand.handleCommand(GetUserStatusCommand.java:42)
        at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:25)
        at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:15)
        at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler$CommandRunnerImpl.handleCommand(SignalJsonRpcCommandHandler.java:150)
        at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.parseParamsAndRunCommand(SignalJsonRpcCommandHandler.java:261)
        at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.runCommand(SignalJsonRpcCommandHandler.java:209)
        at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.handleRequest(SignalJsonRpcCommandHandler.java:63)
        at org.asamk.signal.http.HttpServerHandler.lambda$handleRpcEndpoint$1(HttpServerHandler.java:109)
        at org.asamk.signal.jsonrpc.JsonRpcReader.handleRequest(JsonRpcReader.java:104)
        at org.asamk.signal.jsonrpc.JsonRpcReader.handleMessage(JsonRpcReader.java:80)
        at org.asamk.signal.jsonrpc.JsonRpcReader.readMessages(JsonRpcReader.java:52)
        at org.asamk.signal.http.HttpServerHandler.handleRpcEndpoint(HttpServerHandler.java:109)
        at jdk.httpserver@17.0.8/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver@17.0.8/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver@17.0.8/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver@17.0.8/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:851)
        at jdk.httpserver@17.0.8/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver@17.0.8/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:818)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

Building w/ graalvm 22.3.2 works fine. Not sure what has changed upstream (https://www.graalvm.org/release-notes/22_3/)

**Comment by morph027** [comment]
Update: Build w/ 22.3.2 still throws this error after a while. Something changed on the signal servers maybe? There were a lot of libsignal releases since the last release.

Will run the java version for now and see how it goes and report back.

**Comment by morph027** [comment]
@PastCoder looks like you're using my apt repo. Meanwhile you could install `signal-cli-jre`

**Comment by PastCoder** [comment]
> @PastCoder looks like you're using my apt repo. Meanwhile you could install `signal-cli-jre`

Thanks for the quick reply. At least my problem is solved with that. 
Just not sure why I did not use the correct repo and how to fix that.

**Comment by datenleck** [comment]
Hope this will be solved some day because  signal-cli-native  is much quicker...
Thanks!

**Comment by morph027** [comment]
I'm going to spin up a test build from master using libsignal 0.30 and see how it goes.

**Comment by morph027** [comment]
I've uploaded the [build artifact](http://download.morph027.de/signal-cli-native.tar.gz) (just overwrite `/usr/bin/signal-cli-native`) and will keep it running on my system for now to see if the error appears again. Last time i've checked it worked in the beginning and stopped after a while.

**Comment by gediminasel** [comment]
Same issue here but with `signal-cli-jre` I get

```
java.lang.IllegalArgumentException: invalid argument: invalid Service-Id-FixedWidthBinary
	at org.signal.libsignal.internal.Native.ProfileKey_GetProfileKeyVersion(Native Method)
	at org.signal.libsignal.zkgroup.profiles.ProfileKey.getProfileKeyVersion(ProfileKey.java:32)
	at org.whispersystems.signalservice.api.services.ProfileService.getProfile(ProfileService.java:84)
	at org.asamk.signal.manager.helper.ProfileHelper.retrieveProfile(ProfileHelper.java:378)
	at org.asamk.signal.manager.helper.ProfileHelper.retrieveProfile(ProfileHelper.java:313)
	at org.asamk.signal.manager.helper.ProfileHelper.getRecipientProfile(ProfileHelper.java:249)
	at org.asamk.signal.manager.helper.ProfileHelper.getRecipientProfile(ProfileHelper.java:94)
	at org.asamk.signal.manager.helper.ProfileHelper.getSelfProfile(ProfileHelper.java:227)
	at org.asamk.signal.manager.internal.ManagerImpl.sendMessage(ManagerImpl.java:582)
	at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:227)
	at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:25)
	at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:15)
	at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler$CommandRunnerImpl.handleCommand(SignalJsonRpcCommandHandler.java:150)
	at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.parseParamsAndRunCommand(SignalJsonRpcCommandHandler.java:261)
	at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.runCommand(SignalJsonRpcCommandHandler.java:209)
	at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.handleRequest(SignalJsonRpcCommandHandler.java:87)
	at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.lambda$handleConnection$3(SignalJsonRpcDispatcherHandler.java:130)
	at org.asamk.signal.jsonrpc.JsonRpcReader.handleRequest(JsonRpcReader.java:104)
	at org.asamk.signal.jsonrpc.JsonRpcReader.handleMessage(JsonRpcReader.java:80)
	at org.asamk.signal.jsonrpc.JsonRpcReader.readMessages(JsonRpcReader.java:69)
	at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:130)
	at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:76)
	at org.asamk.signal.commands.JsonRpcDispatcherCommand.handleCommand(JsonRpcDispatcherCommand.java:64)
	at org.asamk.signal.App.handleLocalCommand(App.java:289)
	at org.asamk.signal.App.init(App.java:229)
	at org.asamk.signal.Main.main(Main.java:60)
```

**Comment by gediminasel** [comment]
Compiling signal-cli-jre from master solves the issue

**Comment by morph027** [comment]
Build is still working and sending messages 🎉

**Comment by AsamK** [comment]
Thanks for confirming, I've create a new release.
