### ISSUE TITLE
Unable to send contacts or sync chats with signal Desktop App due to IO Error

### ISSUE THREAD

**Issue by 0815-4711** [AsamK/signal-cli#1289]
I "updated" signal-cli to version 0.11.11 and added signal Desktop on antother device.
Unfortunately i am not able to sync contacts or send contacts. This is the error message:

WARN  SendHelper - Failed to send message due to IO exception: java.net.ProtocolException: unexpected end of stream

OS: Win10
signal-cli: 0.11.11 (self compiled)
jdk: openJDK 20.0.2
signal-cli -u MYPHONENUMBER7 --verbose sendContacts delivers the following:

2023-08-06T17:23:04.947+0200 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-08-06T17:23:04.970+0200 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.11.11
2023-08-06T17:23:05.105+0200 [main] INFO  LibSignal - [libsignal]: rust\bridge\jni\src\logging.rs:156: Initializing libsignal version:0.26.0
2023-08-06T17:23:05.106+0200 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-08-06T17:23:05.768+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-08-06T17:23:06.205+0200 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@13e3c1c7
2023-08-06T17:23:06.209+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-08-06T17:23:09.241+0200 [main] WARN  LibSignal - [SignalServiceMessageSender]: [uploadAttachmentV2] Pipe unavailable, falling back... (WebSocketUnavailableException: WebSocket not currently available.)
2023-08-06T17:23:09.969+0200 [main] WARN  o.a.signal.manager.helper.SendHelper - Failed to send message due to IO exception: java.net.ProtocolException: unexpected end of stream
2023-08-06T17:23:09.970+0200 [main] DEBUG o.a.signal.manager.helper.SendHelper - Exception
org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.ProtocolException: unexpected end of stream
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn0(PushServiceSocket.java:1566)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:1388)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.uploadAttachmentV2(SignalServiceMessageSender.java:780)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.uploadAttachment(SignalServiceMessageSender.java:757)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.createAttachmentPointer(SignalServiceMessageSender.java:2408)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.createMultiDeviceContactsContent(SignalServiceMessageSender.java:1391)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendSyncMessage(SignalServiceMessageSender.java:673)
        at org.asamk.signal.manager.helper.SendHelper.sendSyncMessage(SendHelper.java:189)
        at org.asamk.signal.manager.helper.SyncHelper.sendContacts(SyncHelper.java:180)
        at org.asamk.signal.manager.internal.ManagerImpl.sendContacts(ManagerImpl.java:1068)
        at org.asamk.signal.commands.SendContactsCommand.handleCommand(SendContactsCommand.java:30)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
        at org.asamk.signal.App.handleLocalCommand(App.java:276)
        at org.asamk.signal.App.handleCommand(App.java:192)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:60)
Caused by: java.net.ProtocolException: unexpected end of stream
        at okhttp3.internal.connection.Exchange$RequestBodySink.close(Exchange.kt:244)
        at okio.RealBufferedSink.close(RealBufferedSink.kt:286)
        at okio.RealBufferedSink$outputStream$1.close(RealBufferedSink.kt:127)
        at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:189)
        at org.signal.libsignal.protocol.incrementalmac.IncrementalMacOutputStream.close(IncrementalMacOutputStream.java:67)

at org.whispersystems.signalservice.api.crypto.DigestingOutputStream.close(DigestingOutputStream.java:48)
        at org.whispersystems.signalservice.internal.push.http.DigestingRequestBody.writeTo(DigestingRequestBody.kt:67)
        at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
        at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.asamk.signal.manager.config.ServiceConfig.lambda$getServiceEnvironmentConfig$0(ServiceConfig.java:56)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn0(PushServiceSocket.java:1560)
        ... 15 common frames omitted
2023-08-06T17:23:09.977+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-08-06T17:23:09.987+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.

**Comment by 0815-4711** [comment]
Update: I did a rebuild with jdk 17.0.8, with the same result

**Comment by AsamK** [comment]
Please try again with the latest master version. There's been a fix for this in libsignal-service-java.

**Comment by 0815-4711** [comment]
I did a rebuild with the latest commit on Master. I don't get any failure message, but "sendContacts" and syncing with the desktop app seems to have no effect ( I first press the "import groups and contacts" button in desktop app and use the "receive" comand in cli)
