### ISSUE TITLE
Problem with sending message

### ISSUE THREAD

**Issue by promokodio** [AsamK/signal-cli#1291]
Hi!
I have an issue with sending messages to phone numbers:

INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
WARN  RecipientHelper - CDSI request failed, trying fallback to CDS
java.io.IOException: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsersWithCdsi(SignalServiceAccountManager.java:579)
	at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsersV2(RecipientHelper.java:164)
	at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsers(RecipientHelper.java:113)
	at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUser(RecipientHelper.java:129)
	at org.asamk.signal.manager.helper.RecipientHelper.lambda$resolveRecipient$0(RecipientHelper.java:91)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:206)
	at org.asamk.signal.manager.helper.RecipientHelper.resolveRecipient(RecipientHelper.java:89)
	at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:456)
	at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:561)
	at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:200)
	at org.asamk.signal.App.handleLocalCommand(App.java:289)
	at org.asamk.signal.App.init(App.java:229)
	at org.asamk.signal.Main.main(Main.java:60)
Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Failed to send (some) messages:
+XXXXXXXXXXXX: Unregistered user "+XXXXXXXXXXXX"
1691445763482
Failed to send message

Tell me pleasу how i can solve it?
Thank you!

**Comment by alexlab2017** [comment]
It seems that te user (phone number) you are trying to send the message to is not registered, it means this number does not have Signal Messenger.

To debug you can double check the number or try a known registered user.

**Comment by promokodio** [comment]
@alexlab2017 Hi Alex!
This is my numbers, both have a account in signal.

**Comment by AsamK** [comment]
Are you using the latest signal-cli version?

**Comment by promokodio** [comment]
Dear @AsamK 
yes, latest

**Comment by AsamK** [comment]
Can you retry with the latest development build, that might fix the issue:
https://github.com/AsamK/signal-cli/actions/runs/5813225462
