### ISSUE TITLE
Uploading attachments doesn't work when ran in IntelliJ IDEA

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#130]
If I run signal-cli in IDEA (2018.1 Ultimate, W10 Pro N 64bit) and receive a group and a contact request, both fail:

```
"C:\Program Files\Java\jdk-10.0.1\bin\java.exe" -javaagent:C:\Users\Benni\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\181.4892.42\lib\idea_rt.jar=14012:C:\Users\Benni\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\181.4892.42\bin -Dfile.encoding=UTF-8 -classpath C:\Users\Benni\repositories\signal-cli\out\production\classes;C:\Users\Benni\.m2\repository\com\github\turasa\signal-service-java\2.7.5_unofficial_1\signal-service-java-2.7.5_unofficial_1.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.59\2507204241ab450456bdb8e8c0a8f986e418bd99\bcprov-jdk15on-1.59.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\net.sourceforge.argparse4j\argparse4j\0.8.1\2c8241f84acf6c924bd75be0dbd68e8d74fbcd70\argparse4j-0.8.1.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\org.freedesktop.dbus\dbus-java\2.7.0\2ed929643b0b6011c69c3b4435da48302c2c0002\dbus-java-2.7.0.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\org.whispersystems\signal-protocol-java\2.6.2\2834b2bb1a6defeb340a458bf0a71ea68d5e5735\signal-protocol-java-2.6.2.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protobuf-java\2.5.0\a10732c76bfacdbd633a7eb0f7968b1059a65dfa\protobuf-java-2.5.0.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\com.googlecode.libphonenumber\libphonenumber\8.8.10\81430f0e37972d100df401d3141316ed94dc55de\libphonenumber-8.8.10.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.5.0\489b7552dd3322b63f694122d16ce62c21c303b5\jackson-databind-2.5.0.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\3.9.0\1b6c10b5120995a7542c1a31b7828fb8593c8ba\okhttp-3.9.0.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpclient\4.4\6d220441ca681dddc55a189eae81a437309128b8\httpclient-4.4.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\com.madgag.spongycastle\prov\1.51.0.0\6755081df770180856ca48694b40cd34c2208128\prov-1.51.0.0.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\org.abstractj.libmatthew\unix\0.5.1\498fcee99631a1abcd982254c45b246300e55180\unix-0.5.1.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.5.0\a2a55a3375bc1cef830ca426d68d2ea22961190e\jackson-annotations-2.5.0.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.5.0\b2ece1bd57ac7b4c315b7505b65ac79cb1da4270\jackson-core-2.5.0.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\org.whispersystems\curve25519-java\0.4.1\e4b3d01c38475b13ab524a7adfedde7941641863\curve25519-java-0.4.1.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\com.squareup.okio\okio\1.13.0\a9283170b7305c8d92d25aff02a6ab7e45d06cbe\okio-1.13.0.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore\4.4\e9b3863fd9c8a273ceed4a7fae10f40bb10a2328\httpcore-4.4.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.2\4bfc12adfe4842bf07b657f0369c4cb522955686\commons-logging-1.2.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\commons-codec\commons-codec\1.9\9ce04e34240f674bc72680f8b843b1457383161a\commons-codec-1.9.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\com.madgag.spongycastle\core\1.51.0.0\f642963312ea0e615ad65f28adc5a5b3a2a0862\core-1.51.0.0.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\org.abstractj.libmatthew\debug\1.1.1\807650a05d08369d7dad5156368f5779fb0bc592\debug-1.1.1.jar;C:\Users\Benni\.gradle\caches\modules-2\files-2.1\org.abstractj.libmatthew\hexdump\0.2.1\4e836cc86525a2ecd6db3e2c448c44ab52d240e9\hexdump-0.2.1.jar org.asamk.signal.Main -u +49XXXXXX462 receive
java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:263)
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:270)
	at java.base/sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:413)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:162)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:532)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:360)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createAttachmentPointer(SignalServiceMessageSender.java:643)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createMultiDeviceContactsContent(SignalServiceMessageSender.java:417)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:241)
	at org.asamk.signal.Manager.sendSyncMessage(Manager.java:893)
	at org.asamk.signal.Manager.sendContacts(Manager.java:1555)
	at org.asamk.signal.Manager.handleMessage(Manager.java:1217)
	at org.asamk.signal.Manager.receiveMessages(Manager.java:1177)
	at org.asamk.signal.Main.handleCommands(Main.java:480)
	at org.asamk.signal.Main.main(Main.java:83)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1831)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:335)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:95)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:520)
	... 10 more
Caused by: java.lang.NullPointerException: No password supplied for PKCS#12 KeyStore.
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:367)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:315)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:59)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:51)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:945)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:917)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1090)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.security.Provider.newInstanceUtil(Provider.java:153)
	at java.base/java.security.Provider.access$1100(Provider.java:107)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1824)
	... 22 more
Envelope from: “Y” +49XXXXXX462 (device: 13)
Timestamp: 1526590141090 (2018-05-17T20:49:01.090Z)
Received a sync message
Received sync request
 - contacts request

java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:263)
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:270)
	at java.base/sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:413)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:162)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:532)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:360)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createAttachmentPointer(SignalServiceMessageSender.java:643)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createMultiDeviceGroupsContent(SignalServiceMessageSender.java:427)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:244)
	at org.asamk.signal.Manager.sendSyncMessage(Manager.java:893)
	at org.asamk.signal.Manager.sendGroups(Manager.java:1507)
	at org.asamk.signal.Manager.handleMessage(Manager.java:1224)
	at org.asamk.signal.Manager.receiveMessages(Manager.java:1177)
	at org.asamk.signal.Main.handleCommands(Main.java:480)
	at org.asamk.signal.Main.main(Main.java:83)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1831)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:335)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:95)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:520)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:360)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createAttachmentPointer(SignalServiceMessageSender.java:643)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createMultiDeviceContactsContent(SignalServiceMessageSender.java:417)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:241)
	at org.asamk.signal.Manager.sendSyncMessage(Manager.java:893)
	at org.asamk.signal.Manager.sendContacts(Manager.java:1555)
	at org.asamk.signal.Manager.handleMessage(Manager.java:1217)
	... 3 more
Caused by: java.lang.NullPointerException: No password supplied for PKCS#12 KeyStore.
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:367)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:315)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:59)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:51)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:945)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:917)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1090)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.security.Provider.newInstanceUtil(Provider.java:153)
	at java.base/java.security.Provider.access$1100(Provider.java:107)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1824)
	... 22 more
Envelope from: “Y” +49XXXXXX462 (device: 13)
Timestamp: 1526590141977 (2018-05-17T20:49:01.977Z)
Received a sync message
Received sync request
 - groups request


Process finished with exit code 0
```

Since this repo contains remnants of IDEA files I assume you use it too - does it work for you?

**Comment by lkwg82** [comment]
Hi, I just had the same issue and solved it.

I had pointing JAVA_HOME to a different jdk as I was using in intellij.

**Comment by peteh** [comment]
Looks like the unlimited encryption api is not available in the jdk you are using in Intellij. ikw82 is probably right. Update your local jdk to a newer version that includes unlimited crypto api and remove the old one.
