### ISSUE TITLE
Trust a new number fails with "User is not registered"

### ISSUE THREAD

**Issue by prinzema** [AsamK/signal-cli#1304]
The problem
When I try to trust/add a new target the following error appears. Same when I want to message a new number. The number can send me a text and it will be received.

Sending messages to my existing contacts works fine.

Is there traffic to cdsi that is different from standard ports? It waits a while and waits for timeout before error appears.

Using bbernhard/signal-cli-rest-api 0.67 which uses your signal-cli 0.11.11

signal-api@7f2c3d648048:/$ signal-cli --config /home/.local/share/signal-cli -vv -u +##user### trust -a +##target###
2023-08-16T10:58:22.252Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-08-16T10:58:22.264Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.11.11
2023-08-16T10:58:22.333Z [main] INFO LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.25.0
2023-08-16T10:58:22.334Z [main] TRACE org.asamk.signal.manager.Manager - Expected exception when checking libsignal-client: Deserialization failure in zkgroup
2023-08-16T10:58:22.564Z [main] TRACE org.asamk.signal.App - Loading account file for +##user###
2023-08-16T10:58:22.631Z [main] TRACE o.a.s.manager.storage.SignalAccount - Opening account file
2023-08-16T10:58:22.632Z [main] TRACE o.a.s.manager.storage.SignalAccount - Loading account file
2023-08-16T10:58:22.641Z [main] TRACE o.a.s.manager.storage.SignalAccount - Migrating legacy parts of account file
2023-08-16T10:58:22.660Z [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
2023-08-16T10:58:22.668Z [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
2023-08-16T10:58:22.668Z [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
2023-08-16T10:58:22.669Z [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................none
2023-08-16T10:58:22.671Z [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql..............."PRAGMA foreign_keys=ON"
2023-08-16T10:58:22.672Z [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............none
2023-08-16T10:58:22.672Z [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
2023-08-16T10:58:22.672Z [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................none
2023-08-16T10:58:22.672Z [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............none
2023-08-16T10:58:22.672Z [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................none
2023-08-16T10:58:22.673Z [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{open_mode=70, transaction_mode=IMMEDIATE, password=, date_precision=MILLISECONDS, busy_timeout=60000, date_string_format=yyyy-MM-dd HH:mm:ss.SSS, jdbc.explicit_readonly=false, date_class=INTEGER, shared_cache=false}
2023-08-16T10:58:22.673Z [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................none
2023-08-16T10:58:22.673Z [main] DEBUG com.zaxxer.hikari.HikariConfig - exceptionOverrideClassName......none
2023-08-16T10:58:22.673Z [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
2023-08-16T10:58:22.674Z [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............none
2023-08-16T10:58:22.674Z [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
2023-08-16T10:58:22.674Z [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailTimeout.......1
2023-08-16T10:58:22.674Z [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
2023-08-16T10:58:22.674Z [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:sqlite:/home/.local/share/signal-cli/data/+##user###.d/account.db
2023-08-16T10:58:22.674Z [main] DEBUG com.zaxxer.hikari.HikariConfig - keepaliveTime...................0
2023-08-16T10:58:22.674Z [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
2023-08-16T10:58:22.674Z [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
2023-08-16T10:58:22.675Z [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................10
2023-08-16T10:58:22.675Z [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................none
2023-08-16T10:58:22.675Z [main] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........none
2023-08-16T10:58:22.675Z [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................1
2023-08-16T10:58:22.675Z [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................
2023-08-16T10:58:22.675Z [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................"HikariPool-1"
2023-08-16T10:58:22.676Z [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
2023-08-16T10:58:22.676Z [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
2023-08-16T10:58:22.676Z [main] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutor...............none
2023-08-16T10:58:22.676Z [main] DEBUG com.zaxxer.hikari.HikariConfig - schema..........................none
2023-08-16T10:58:22.676Z [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................internal
2023-08-16T10:58:22.676Z [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............default
2023-08-16T10:58:22.676Z [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................none
2023-08-16T10:58:22.676Z [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
2023-08-16T10:58:22.680Z [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-08-16T10:58:22.689Z [main] DEBUG c.z.hikari.util.DriverDataSource - Loaded driver with class name org.sqlite.JDBC for jdbcUrl=jdbc:sqlite:/home/.local/share/signal-cli/data/+##user###.d/account.db
2023-08-16T10:58:22.787Z [main] INFO com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@20f12539
2023-08-16T10:58:22.789Z [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-08-16T10:58:22.798Z [main] TRACE o.a.s.m.storage.AccountDatabase - Current database version: 13 Program database version: 13
2023-08-16T10:58:22.808Z [main] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.sqlite.jdbc4.JDBC4Connection@20f12539
2023-08-16T10:58:22.817Z [main] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.sqlite.jdbc4.JDBC4Connection@20f12539
2023-08-16T10:58:22.819Z [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@245c64ea
2023-08-16T10:58:22.889Z [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
2023-08-16T10:58:22.891Z [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After cleanup stats (total=2, active=0, idle=2, waiting=0)
2023-08-16T10:58:22.891Z [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool has sufficient level or currently being filled (queueDepth=0).
2023-08-16T10:58:23.022Z [main] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.sqlite.jdbc4.JDBC4Connection@20f12539
2023-08-16T10:58:23.756Z [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: NL
2023-08-16T10:58:52.891Z [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
2023-08-16T10:58:52.892Z [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After cleanup stats (total=2, active=0, idle=2, waiting=0)
2023-08-16T10:58:52.892Z [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool has sufficient level or currently being filled (queueDepth=0).
2023-08-16T10:58:53.939Z [OkHttp https://cdsi.signal.org/...] WARN LibSignal - [CdsiSocket]: [onFailure] response? false
java.net.SocketTimeoutException: Connect timed out
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
at java.base/java.net.Socket.connect(Socket.java:633)
at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at org.asamk.signal.manager.config.ServiceConfig.lambda$getServiceEnvironmentConfig$0(ServiceConfig.java:54)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-16T10:58:53.973Z [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-08-16T10:58:53.973Z [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before shutdown stats (total=2, active=0, idle=2, waiting=0)
2023-08-16T10:58:53.975Z [HikariPool-1 connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Closing connection org.sqlite.jdbc4.JDBC4Connection@20f12539: (connection evicted)
2023-08-16T10:58:53.975Z [HikariPool-1 connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Closing connection org.sqlite.jdbc4.JDBC4Connection@245c64ea: (connection evicted)
2023-08-16T10:58:53.976Z [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After shutdown stats (total=0, active=0, idle=0, waiting=0)
2023-08-16T10:58:53.976Z [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
The user +##target### is not registered.

**Comment by numericOverflow** [comment]
Same issue here. Any ideas as to why?

Note: I am using a real number in my code, it was redacted with "+19876543210" below to protect the innocent. 

> 2023-08-24 17:02:52,673 - ERROR - Command: '/usr/local/bin/signal-cli -u +19876543210 send   -m "This is a test message to new user" +19876543210 '
> 2023-08-24 17:02:52,674 - ERROR - Command output: 'b'User +19876543210 is not registered.''

**Comment by AsamK** [comment]
Does this still happen in the latest signal-cli version?
