### ISSUE TITLE
Can't add third device: addDevice fails from the second device

### ISSUE THREAD

**Issue by purpleidea** [AsamK/signal-cli#1307]
First of all, this project is working brilliantly well, please keep up the great work, thank you!

I noticed an interesting bug. To repro:

1) Register a device (signal-cli register ...) -- works fine
2) Add a new device (signal-cli link / addDevice) -- works fine
3) Make a third device, run `link` on it, and then run `addDevice` from the SECOND machine/device you added. This fails with the following error:

```
ERROR AddDeviceCommand - Add device link failed
org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [401] Authorization failed!
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1797)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1780)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1718)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1712)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getNewDeviceVerificationCode(PushServiceSocket.java:474)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getNewDeviceVerificationCode(SignalServiceAccountManager.java:659)
        at org.asamk.signal.manager.helper.AccountHelper.addDevice(AccountHelper.java:271)
        at org.asamk.signal.manager.internal.ManagerImpl.addDeviceLink(ManagerImpl.java:363)
        at org.asamk.signal.commands.AddDeviceCommand.handleCommand(AddDeviceCommand.java:50)
        at org.asamk.signal.App.handleLocalCommand(App.java:289)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
Add device link failed
```

I tried this multiple times, but got the same result. However if I run the addDevice on the very first signal machine that I did the initial register from, then it works just fine.

The only thing I noticed that was perhaps unusual was that the device name of the first is `null`.

Example (timestamps removed)

```
signal-cli listDevices
- Device 1:
  Name: null
  Created: XXX
  Last seen: XXX
- Device 2:
  Name: machine2
  Created: XXX
  Last seen: XXX
- Device 3 (this device):
  Name: machine3
  Created: XXX
  Last seen: XXX
```

Everything seen is happening on either Fedora 37 (second and third machines) or Centos Stream 9 (first machine). They're all using java via:

```
dnf install java-latest-openjdk.x86_64
```

And project version is: `0.11.11`.

Thanks again!

**Comment by AsamK** [comment]
Adding devices only works on the primary device, this is a restriction on the Signal-Server.
The device name of the first device is always `null` by default, you can set a name there with the `updateAccount` command.

**Comment by purpleidea** [comment]
Would a doc patch be helpful in this situation at least for now?

One reason why I think this feature is important (unless you know of a workaround):

Suppose you have N machines running signal-cli on the same account to send monitoring alerts from your homelab, and the initial server dies! You'd have to re-provision signal on each one to replace the new first node.

Cheers!
