### ISSUE TITLE
signal-cli 0.12.0 fails to update kyber_pre_key store

### ISSUE THREAD

**Issue by selfbc** [AsamK/signal-cli#1310]
Going from signal-cli 0.11.0 to 0.12.0, the following error occurs:
WARN  PreKeyHelper - Failed to store new pre keys, resetting preKey id offset
java.lang.RuntimeException: Failed update kyber_pre_key store
	at org.asamk.signal.manager.storage.prekeys.KyberPreKeyStore.storeKyberPreKey(KyberPreKeyStore.java:120)
	at org.asamk.signal.manager.storage.prekeys.KyberPreKeyStore.storeKyberPreKey(KyberPreKeyStore.java:101)
	at org.asamk.signal.manager.storage.SignalAccount.addKyberPreKeys(SignalAccount.java:1122)
	at org.asamk.signal.manager.helper.PreKeyHelper.generateKyberPreKeys(PreKeyHelper.java:154)
	at org.asamk.signal.manager.helper.PreKeyHelper.refreshKyberPreKeys(PreKeyHelper.java:136)
	at org.asamk.signal.manager.helper.PreKeyHelper.refreshKyberPreKeys(PreKeyHelper.java:125)
	at org.asamk.signal.manager.helper.PreKeyHelper.refreshPreKeysIfNecessary(PreKeyHelper.java:60)
	at org.asamk.signal.manager.helper.PreKeyHelper.refreshPreKeysIfNecessary(PreKeyHelper.java:37)
	at org.asamk.signal.manager.helper.AccountHelper.checkAccountState(AccountHelper.java:80)
	at org.asamk.signal.manager.internal.ManagerImpl.checkAccountState(ManagerImpl.java:210)
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:122)
	at org.asamk.signal.manager.SignalAccountFiles.lambda$initMultiAccountManager$1(SignalAccountFiles.java:70)
	at java.base@17.0.8/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.8/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.8/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183)
	at java.base@17.0.8/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149)
	at java.base@17.0.8/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base@17.0.8/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base@17.0.8/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base@17.0.8/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base@17.0.8/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base@17.0.8/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base@17.0.8/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: kyber_pre_key.account_id_type, kyber_pre_key.key_id)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.execute(DB.java:985)
	at org.sqlite.core.DB.executeUpdate(DB.java:1054)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:119)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:118)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:100)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.asamk.signal.manager.storage.prekeys.KyberPreKeyStore.storeKyberPreKey(KyberPreKeyStore.java:117)
	... 26 common frames omitted
WARN  PreKeyHelper - Failed to store new pre keys, resetting preKey id offset
java.lang.RuntimeException: Failed update kyber_pre_key store
	at org.asamk.signal.manager.storage.prekeys.KyberPreKeyStore.storeKyberPreKey(KyberPreKeyStore.java:120)
	at org.asamk.signal.manager.storage.prekeys.KyberPreKeyStore.storeKyberPreKey(KyberPreKeyStore.java:101)
	at org.asamk.signal.manager.storage.SignalAccount.addKyberPreKeys(SignalAccount.java:1122)
	at org.asamk.signal.manager.helper.PreKeyHelper.generateKyberPreKeys(PreKeyHelper.java:154)
	at org.asamk.signal.manager.helper.PreKeyHelper.refreshKyberPreKeys(PreKeyHelper.java:136)
	at org.asamk.signal.manager.helper.PreKeyHelper.refreshKyberPreKeys(PreKeyHelper.java:125)
	at org.asamk.signal.manager.helper.PreKeyHelper.refreshPreKeysIfNecessary(PreKeyHelper.java:60)
	at org.asamk.signal.manager.helper.PreKeyHelper.refreshPreKeysIfNecessary(PreKeyHelper.java:37)
	at org.asamk.signal.manager.helper.AccountHelper.checkAccountState(AccountHelper.java:80)
	at org.asamk.signal.manager.internal.ManagerImpl.checkAccountState(ManagerImpl.java:210)
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:122)
	at org.asamk.signal.manager.SignalAccountFiles.lambda$initMultiAccountManager$1(SignalAccountFiles.java:70)
	at java.base@17.0.8/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.8/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.8/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183)
	at java.base@17.0.8/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149)
	at java.base@17.0.8/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base@17.0.8/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base@17.0.8/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base@17.0.8/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1223)
	at java.base@17.0.8/java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1915)
	at java.base@17.0.8/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:433)
	at java.base@17.0.8/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:687)
	at java.base@17.0.8/java.util.stream.Nodes.collect(Nodes.java:328)
	at java.base@17.0.8/java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:111)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:570)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base@17.0.8/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base@17.0.8/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base@17.0.8/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.asamk.signal.manager.SignalAccountFiles.initMultiAccountManager(SignalAccountFiles.java:78)
	at org.asamk.signal.App.handleMultiLocalCommand(App.java:287)
	at org.asamk.signal.App.handleCommand(App.java:164)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:60)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: kyber_pre_key.account_id_type, kyber_pre_key.key_id)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.execute(DB.java:985)
	at org.sqlite.core.DB.executeUpdate(DB.java:1054)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:119)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:118)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:100)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.asamk.signal.manager.storage.prekeys.KyberPreKeyStore.storeKyberPreKey(KyberPreKeyStore.java:117)
	... 36 common frames omitted

**Comment by AsamK** [comment]
Does this happen on every startup? Can you provide the log lines before this happens (with verbose logging `-v`)?

**Comment by selfbc** [comment]
It was happening on every startup.  I was able to get around it by deleting the databases and letting signal-cli rebuild them.  I'll see if I can use some data from backups to reproduce, but it was causing a service outage on our hobbyist chat so I had to improvise rather than wait for a fix.

**Comment by AsamK** [comment]
This might have been caused by a previous bug that created lots of unnecessary kyber pre keys. That bug has already been fixed and I've now also implemented a cleanup of old pre keys that should help prevent this issue in the future.
