### ISSUE TITLE
onMessageReceived not getting any messages

### ISSUE THREAD

**Issue by mh-g** [AsamK/signal-cli#1315]
On a new signal-cli installation (0.12.0 on Raspberry OS), I cannot receive messages via system-dbus. I use the standard code from https://github.com/AsamK/signal-cli/wiki/DBus-service#receive-messages-from-signal-cli-daemon Essentially, the program does not call msgRcv and does not produce any kind of output.

journalctl gives:
```
Aug 29 20:19:57 mediaberry8g signal-cli[3625]: Envelope from: “XXX” +49XXX (device: 1) to +49XXX
Aug 29 20:19:57 mediaberry8g signal-cli[3625]: Timestamp: 1693333197232 (2023-08-29T18:19:57.232Z)
Aug 29 20:19:57 mediaberry8g signal-cli[3625]: Server timestamps: received: 1693333197248 (2023-08-29T18:19:57.248Z) delivered: 1693333197250 (2023-08-29T18:>
Aug 29 20:19:57 mediaberry8g signal-cli[3625]: Sent by unidentified/sealed sender
Aug 29 20:19:57 mediaberry8g signal-cli[3625]: Received a typing message
Aug 29 20:19:57 mediaberry8g signal-cli[3625]:   Action: STARTED
Aug 29 20:19:57 mediaberry8g signal-cli[3625]:   Timestamp: 1693333197232 (2023-08-29T18:19:57.232Z)
Aug 29 20:19:58 mediaberry8g signal-cli[3625]: Envelope from: “XXX” +49XXX (device: 1) to +49XXX
Aug 29 20:19:58 mediaberry8g signal-cli[3625]: Timestamp: 1693333198052 (2023-08-29T18:19:58.052Z)
Aug 29 20:19:58 mediaberry8g signal-cli[3625]: Server timestamps: received: 1693333198029 (2023-08-29T18:19:58.029Z) delivered: 1693333198031 (2023-08-29T18:>
Aug 29 20:19:58 mediaberry8g signal-cli[3625]: Sent by unidentified/sealed sender
Aug 29 20:19:58 mediaberry8g signal-cli[3625]: Message timestamp: 1693333198052 (2023-08-29T18:19:58.052Z)
Aug 29 20:19:58 mediaberry8g signal-cli[3625]: Body: crucified
Aug 29 20:19:58 mediaberry8g signal-cli[3625]: With profile key
Aug 29 20:20:00 mediaberry8g signal-cli[3625]: Envelope from: “XXX” +49XXX (device: 1) to +49XXX
Aug 29 20:20:00 mediaberry8g signal-cli[3625]: Timestamp: 1693333200234 (2023-08-29T18:20:00.234Z)
Aug 29 20:20:00 mediaberry8g signal-cli[3625]: Server timestamps: received: 1693333200217 (2023-08-29T18:20:00.217Z) delivered: 1693333200219 (2023-08-29T18:>
Aug 29 20:20:00 mediaberry8g signal-cli[3625]: Sent by unidentified/sealed sender
Aug 29 20:20:00 mediaberry8g signal-cli[3625]: Received a typing message
Aug 29 20:20:00 mediaberry8g signal-cli[3625]:   Action: STOPPED
Aug 29 20:20:00 mediaberry8g signal-cli[3625]:   Timestamp: 1693333200234 (2023-08-29T18:20:00.234Z)
```

I have not trusted the senders phone number, is this the cause. (How to do this via dbus?)

**Comment by mh-g** [comment]
Did some further digging within journalctl:

```
Aug 31 17:00:36 mediaberry8g signal-cli[3535]: Exception in thread "dbus-init" java.lang.RuntimeException: Failed read recipient store
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:184)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at org.asamk.signal.manager.storage.recipients.RecipientResolver$RecipientResolverWrapper.resolveRecipient(RecipientResolver.java:47)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at org.asamk.signal.manager.internal.ManagerImpl.toIdentity(ManagerImpl.java:1140)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at org.asamk.signal.manager.internal.ManagerImpl.getIdentities(ManagerImpl.java:1131)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at org.asamk.signal.dbus.DbusSignalImpl.updateIdentities(DbusSignalImpl.java:1039)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at org.asamk.signal.dbus.DbusSignalImpl.exportObjects(DbusSignalImpl.java:106)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at org.asamk.signal.dbus.DbusSignalImpl.initObjects(DbusSignalImpl.java:94)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at java.base/java.lang.Thread.run(Thread.java:833)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]: Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: recipient.pni)
Aug 31 17:00:36 mediaberry8g signal-cli[3535]:         at org.sqlite.core.DB.newSQLException(DB.java:1179)
```

I originally had several (similar) phone numbers I tried to register, so there were several entries in accounts.json, most of them not verified. I removed them manually, as well as the corresponding files and folders. This did not change anything. I did not look into account.db of the remaining number yet.

**Comment by mh-g** [comment]
Something seems to be wrong with the database. From another machine, I copied the 123456.d/ folder, the 123456 file and the corresponding parts of the accounts.json. I also stripped the "-u ACCOUNT" parameter from the system.d config file. With the new account, receiving works.

I will keep the database file for a week or so if someone wants to debug it further. I will not spend any time on it.

**Comment by mh-g** [comment]
I must reopen this issue. After re-installation I have the same problem again: Receiving does not work via system dbus. If I start the service with "-u XXX" I get the exception in database handling; if I start without "-u" and instead add "_XXX" in the python script, I see no errors, but also no messages. My interpretation is that effectively the same error occurs, but the exception remains invisible to me.

**Comment by AsamK** [comment]
The exception should be fixed in version 0.12.1

**Comment by mh-g** [comment]
Indeed, with 0.12.1 and sqlite 3.42 I can now receive (without "-u XXX"). However, when sending, I now get
`Error org.freedesktop.dbus.exceptions.DBusExecutionException: Error Executing Method org.asamk.Signal.sendMessage: 'boolean org.signal.libsignal.internal.Native.SessionRecord_HasSenderChain(long)'
`
I am using https://github.com/exquo/signal-libs-build/releases/download/libsignal_v0.32.0/libsignal_jni.so-v0.32.0-aarch64-unknown-linux-gnu.tar.gz patched as described on the main page of the project.

**Comment by AsamK** [comment]
signal-cli 0.12.1 requires libsignal 0.30.0
https://github.com/AsamK/signal-cli/blob/master/CHANGELOG.md#0121---2023-08-26

**Comment by mh-g** [comment]
Thanks! Now it works. For whatever reason, it seems as if only the prebuilt version from projektzentrisch did work.
