### ISSUE TITLE
Failed to load native library:sqlite-3.42.0.1-8da682e6-e484-4fb4-b8d8-a840defa5916-libsqlitejdbc.so.

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1324]
I have tried to compile signal-cli for my rpi4 but it gives me this error:
`Failed to load native library:sqlite-3.42.0.1-8da682e6-e484-4fb4-b8d8-a840defa5916-libsqlitejdbc.so.` Full log is at the bottom.

I tried both the armv7 and the aarch64 from https://github.com/exquo/signal-libs-build/releases  Both gave the same issue.

Full log:

```
signal-cli -o json getUserStatus PHONENUMBER
OpenJDK Client VM warning: You have loaded library /tmp/sqlite-3.42.0.1-ae5a6e8d-6ef4-4ee4-bae4-5508fd31cfc8-libsqlitejdbc.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Failed to load native library:sqlite-3.42.0.1-ae5a6e8d-6ef4-4ee4-bae4-5508fd31cfc8-libsqlitejdbc.so. osinfo: Linux/aarch64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.42.0.1-ae5a6e8d-6ef4-4ee4-bae4-5508fd31cfc8-libsqlitejdbc.so: /tmp/sqlite-3.42.0.1-ae5a6e8d-6ef4-4ee4-bae4-5508fd31cfc8-libsqlitejdbc.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AARCH64 .so on a ARM platform)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:284)
        at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:241)
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:349)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:72)
        at org.sqlite.core.NativeDB.load(NativeDB.java:67)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:280)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:34)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$16(SignalAccount.java:1260)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1734)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1258)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$8(SignalAccount.java:1233)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1734)
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1230)
        at org.asamk.signal.manager.storage.SignalAccount.getProfileStore(SignalAccount.java:1237)
        at org.asamk.signal.manager.storage.SignalAccount.migrateLegacyConfigs(SignalAccount.java:411)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:175)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:98)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:85)
        at org.asamk.signal.App.loadManager(App.java:313)
        at org.asamk.signal.App.handleLocalCommand(App.java:275)
        at org.asamk.signal.App.handleCommand(App.java:192)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:60)
Failed to load native library through System.loadLibrary
java.lang.UnsatisfiedLinkError: no sqlitejdbc in java.library.path: /usr/java/packages/lib:/usr/lib/arm-linux-gnueabihf/jni:/lib/arm-linux-gnueabihf:/usr/lib/arm-linux-gnueabihf:/usr/lib/jni:/lib:/usr/lib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibraryJdk(SQLiteJDBCLoader.java:303)
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:373)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:72)
        at org.sqlite.core.NativeDB.load(NativeDB.java:67)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:280)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:34)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$16(SignalAccount.java:1260)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1734)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1258)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$8(SignalAccount.java:1233)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1734)
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1230)
        at org.asamk.signal.manager.storage.SignalAccount.getProfileStore(SignalAccount.java:1237)
        at org.asamk.signal.manager.storage.SignalAccount.migrateLegacyConfigs(SignalAccount.java:411)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:175)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:98)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:85)
        at org.asamk.signal.App.loadManager(App.java:313)
        at org.asamk.signal.App.handleLocalCommand(App.java:275)
        at org.asamk.signal.App.handleCommand(App.java:192)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:60)
ERROR HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:283)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:34)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$16(SignalAccount.java:1260)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1734)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1258)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$8(SignalAccount.java:1233)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1734)
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1230)
        at org.asamk.signal.manager.storage.SignalAccount.getProfileStore(SignalAccount.java:1237)
        at org.asamk.signal.manager.storage.SignalAccount.migrateLegacyConfigs(SignalAccount.java:411)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:175)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:98)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:85)
        at org.asamk.signal.App.loadManager(App.java:313)
        at org.asamk.signal.App.handleLocalCommand(App.java:275)
        at org.asamk.signal.App.handleCommand(App.java:192)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:60)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/org/sqlite/native/Linux/aarch64:/usr/java/packages/lib:/usr/lib/arm-linux-gnueabihf/jni:/lib/arm-linux-gnueabihf:/usr/lib/arm-linux-gnueabihf:/usr/lib/jni:/lib:/usr/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:380)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:72)
        at org.sqlite.core.NativeDB.load(NativeDB.java:67)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:280)
        ... 31 common frames omitted
Error loading state file for user PHONENUMBER: Failed to initialize pool: Error opening connection (PoolInitializationException)
```

**Comment by Tsjippy** [comment]
Never mind I should have checked the issue list first. Solved by #1213
