### ISSUE TITLE
Rate Limit Challenge Issue [2023-9-21]

### ISSUE THREAD

**Issue by muad-dumb** [AsamK/signal-cli#1328]
Rate Limit Challenge has appeared again, effects under 10 of about 170 messages performed via signal-batch.

Following instructions printed in the CLI but I can't seem to get the Captcha created using the URL, and I also cannot fix it using the CLI instructions printed from Signal after the failure. 

The URL for the captcha (via CLI) pulls up the Signal Desktop app, but no Captcha is then generated and no options or dialog appears.

I believe i'm correctly inputting the commands and the Captcha Token (hitting F12 and copy-pasting the generated token). 

Verbose printout below [portions of Challenge Token and Captcha have been replaced with "x" for abundance of caution]:

./signal-cli -v submitRateLimitChallenge --challenge 8xxxxxx8-0xx2-4xx9-9xx2-4xxxxxxxxxx7 --captcha signal-hcaptcha.5fad97ac-7xx6-4xx4-bxxa-b950b20148ff.challenge.P1_eyJ0eXAiOiJKV1xxxxxxxxxxOiJIUzI1NiJ9.hKdwYXNza2V5xQSMWVaIaPeu4f0P7mXf35h4Nj4PNrqAKWHCUGUvTHHQlrAHaQgYRG6t1qDeb0ALcvIXUtnxk-qAUqxMIxbNOareWwOLOHjgjLu90xkR8OGfNUGeke7f1uk7UoEzQ-gA6ESE9oPxZ0FiHKgvx1-0jhf6ZRC1437D_izOrh6V7v6sGlVxxxxxxxxxxNZRvEBtyPJWAkeWWuiBBNecn43ynWMYK6tyXtL5eE5K1Q8SyodZ6f9YiPmmOI9Z0m0EEIOGKabyXVteZX1kb0OPfdO3TxJhcMBdCRAZwVQzFhwVAP2mlj4GgoxCWMFdYx-crEmhEXFm-F3xwIKyLHk0QnIflGdKzO56n77ZI-wfMuMi4FV_C95svuUuC2YfluqmcEAIrBEzJfx7F4YUkYqjMEi5Z70kPjn3gqPvfmqK5PNdD9uZTe7Ywgs3m3fJb5Szdj9g_ydbp99J27nsyWmFApmVwFi-IyL355v8IdaurBO7QD-zPpceFYqzKiO5v5ySk-TosoS0dvKjUoKG7Pn00DdBRaAbzBsJPWE4CmcMAKLg0s-fhklNiR-Rkns6SkYz_TJ1gsVG5Lo_1Vidkvy6of1ZGvMCVxNGsGbBjo9LHpKHaz1gRspkgs9NQ4yJCTLYt90TpOByU0lgYf6IywEn6qG9yB-fUClILrjfXNCQT9lb2FJaeLToLUv2vzrA49wmybpZSQOE1kV0oGtOYhVMPRCtbnuXT6B5kVfSZxEcXC31KF5YaYyO8koCur1ByEovxth2vud_RT3MF7ebZF9t1pvWXigFyV37EJnjMDiXnFaPxXA7wKcNE-KfJeOeZJ8Mw0bo85YP4NR5Oau1KHzCMoBRGkBgX2uAEkmSBytiietDQRVlkneGz9wJ6wAbIYasaKQPNPoC42yaAEWpUwyEP-d0kEmSHkOH-lWIHDaY6HPlatpJN0D16_X5aFkRYTykC_FNWEvKxi-pZjxgbO1CDxSTI3gFU8RnG8LIbiBgcC3vfBquX6LbV60pBPK9SJQdcFBMnhJvwJihCmq0NpyxdFs6VNIJLX-52oJkTBYiMB3nC4wOrgGD4acZFavf-DoBI3VnpjJEOHwgbJeo0x4OA_koSUZDVo6Uev-wocNklDwULzgxhX7oGq4YWLdr-S3GOGO6GxgNehNa9FB0Cf5wqXO6CmWqIgneE54zDX-ajMAa4Oc4iupsYCIrxnIdzdJUrbUc9_E51rRs5S2WCI_QkSBcfCaNAtFKqqJqxCsa8CGS4w7guBT2xzgypPy5sU99qanY1qc3ggSxCiQWcQ5CbpKXz_3PRxmd70osZpEyCxFhRVmZ3H3fB91QIFrURUp1r3V8dPNPC1F3q_C7WtM8IQHSrCAnxP55UMdy0eESDixXWNlC8qfy6tx7ZTZ8WbIiYC3KqSZvfblHYHvSd7W76nwJMHTt0m_ToLX04_ElZRoIA18_Fa2Pf4-rYG20quPXEsMOn_Z9I0RnwszqKgteWPGsiWDYfR-Z-JQugGiB9YJHiIHhcBjvt7eKCLVjjVFUTQdCSLBxycRXZe8qA-BfaISTo2V4cM5lDNp1qHNoYXJkX2lkzjGtTIGicGQA.zdk4thTU6wuP9p7v6ujdppz0CnS1pNj-EeHAPXKVcM4
2023-09-22T16:35:10.313-0400 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.11.11
2023-09-22T16:35:10.578-0400 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.25.0
2023-09-22T16:35:10.580-0400 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-09-22T16:35:11.010-0400 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-09-22T16:35:11.111-0400 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@522a32b1
2023-09-22T16:35:11.112-0400 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-09-22T16:35:13.603-0400 [main] WARN  LibSignal - [PushServiceSocket]: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4916)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4818)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at org.whispersystems.signalservice.internal.util.JsonUtil.fromJson(JsonUtil.java:63)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.readBodyJson(PushServiceSocket.java:2276)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.readResponseJson(PushServiceSocket.java:2292)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1823)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1780)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1718)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1712)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.submitRateLimitRecaptchaChallenge(PushServiceSocket.java:1061)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.submitRateLimitRecaptchaChallenge(SignalServiceAccountManager.java:883)
	at org.asamk.signal.manager.internal.ManagerImpl.submitRateLimitRecaptchaChallenge(ManagerImpl.java:331)
	at org.asamk.signal.commands.SubmitRateLimitChallengeCommand.handleCommand(SubmitRateLimitChallengeCommand.java:38)
	at org.asamk.signal.App.handleLocalCommand(App.java:289)
	at org.asamk.signal.App.init(App.java:229)
	at org.asamk.signal.Main.main(Main.java:60)

2023-09-22T16:35:13.667-0400 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-09-22T16:35:13.670-0400 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Submit challenge error: Unable to parse entity
org.whispersystems.signalservice.api.push.exceptions.MalformedResponseException: Unable to parse entity
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.readBodyJson(PushServiceSocket.java:2279)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.readResponseJson(PushServiceSocket.java:2292)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1823)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1780)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1718)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1712)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.submitRateLimitRecaptchaChallenge(PushServiceSocket.java:1061)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.submitRateLimitRecaptchaChallenge(SignalServiceAccountManager.java:883)
	at org.asamk.signal.manager.internal.ManagerImpl.submitRateLimitRecaptchaChallenge(ManagerImpl.java:331)
	at org.asamk.signal.commands.SubmitRateLimitChallengeCommand.handleCommand(SubmitRateLimitChallengeCommand.java:38)
	at org.asamk.signal.App.handleLocalCommand(App.java:289)
	at org.asamk.signal.App.init(App.java:229)
	at org.asamk.signal.Main.main(Main.java:60)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4916)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4818)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at org.whispersystems.signalservice.internal.util.JsonUtil.fromJson(JsonUtil.java:63)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.readBodyJson(PushServiceSocket.java:2276)
	... 12 more

..... bin$

[could not print the 12 final rows because the CLI completed it's function and returned to bin]

**Comment by muad-dumb** [comment]
Correction: Captcha does generate, "click for human" etc, and I'm able to complete the picture challenge. But once that challenge is completed, I'm returned to the Desktop app. Messages that were failed are not sent after the challenge is completed, and no other options are created after the Signal Desktop app is opened.

Apologies for any confusion in the initial post, I misspoke.

**Comment by muad-dumb** [comment]
Addition:

When opening the Signal Desktop app to send the failed messages manually, the Desktop App asks for some form of verification (I forget what kind, exactly), and when clicking Submit/Okay/Enter (haven't been able to get it to generate a new one for the exact language) it creates another different type of Captcha. 

After that Captcha is completed, the message that failed to send manually sends, but no other messages that failed (the failed batch messages) send. 

After completing this second Captcha, no other verification is requested from the Desktop App for sending messages.

**Comment by muad-dumb** [comment]
Addition:

Failures appear to be for the same recipients, or at least some of the same recipients, out of the batch file. All those recipients are verified, and there is no output from the CLI that indicates that they are untrusted or otherwise have issues.

**Comment by cuu508** [comment]
> ./signal-cli -v submitRateLimitChallenge --challenge 8xxxxxx8-0xx2-4xx9-9xx2-4xxxxxxxxxx7 --captcha signal-hcaptcha.5fad97ac-7xx6-4xx4-bxxa-

The argument to `--captcha` should start with `signalcaptcha://`. The prefix appears to be missing here, perhaps that's the problem?

> Messages that were failed are not sent after the challenge is completed

Submitting a CAPTCHA solution to Signal does not affect the send attempts that already failed. It increases the chances that future sends will succeed.

**Comment by Geremia** [comment]
@cuu508  

>Submitting a CAPTCHA solution to Signal does not affect the send attempts that already failed. It increases the chances that future sends will succeed.

Is this why I'm getting [this issue](https://github.com/signalapp/Signal-Desktop/issues/6803)?

**Comment by cuu508** [comment]
@Geremia no, I don't think these are related. My comment is about *signal-cli*, and about its handling of messages that fail to send on the first try. Your issue is with a different app, *Signal Desktop*, and with its CAPTCHA solution submission functionality.

**Comment by nomansial** [comment]
I need commadn to sumit captcha sending limit

**Comment by cuu508** [comment]
@nomansial it's documented here: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#submitratelimitchallenge

**Comment by nomansial** [comment]
@cuu508  Thank you for your response. Actually Im getting below error on running command, Could you please guide me what is the issue

C:\Users\Lenovo>signal-cli -a +852650xxxxx submitRateLimitChallenge --challenge 5fad97ac-7d06-4e44-b18a-b950b20148ff --captcha 2n4KBa7z2CvkFbpgIvUHCSgS 

_**Submit challenge error: [400] Bad response: 400 : {"code":400,"message":"too few parts"}**_

**Comment by cuu508** [comment]
@nomansial the captcha argument should start with `signalcaptcha://` and be significantly longer (2000 characters or so)

**Comment by nomansial** [comment]
@cuu508 how to send a message including special characters for example line break?

When i send a paragraph with line break it only sends first line and removes remaining paragraph.

**Comment by m-ueberall** [comment]
@nomansial : Questions like this should generally be asked in https://github.com/AsamK/signal-cli/discussions/ (in this case, you may want to keep an eye on discussion #1688).

**Comment by nomansial** [comment]
@AsamK  @m-ueberall I solved captcha and after sending one message it is showing rate limit error again. What could be the reason?

**Comment by benebrice** [comment]
I'm experiencing the same issue here. 
Actually it's happening almost for every new phone number. 🤔

**Comment by nomansial** [comment]
@AsamK please help...

**Comment by cuu508** [comment]
I don't think this is something that can be fixed on signal-cli side, the rate limiting is being done on signal.org servers, and the exact rate limiting criteria is not publicly known (which makes sense). 

@benebrice how often are you sending to new phone numbers? I would not expect rate limiting to kick in if you start sending to a new number once in a while. But if you are going through a lot of new numbers, it could be argued it is working as intended :-)

**Comment by benebrice** [comment]
Currently @cuu508 I'm just running local tests but I'm always through a VPN. I tried without but I have the same issue. 

Once the number is known (I solved the rate challenge), it's ok. I can send several message to this number without problem. 

Since I'm planning to have this tool to confirm phone number of a large scale app, I cannot afford this challenge that often. 😕
