### ISSUE TITLE
signal-cli 0.12.3 exception NoSessionException while receiving massages

### ISSUE THREAD

**Issue by dKibi** [AsamK/signal-cli#1351]
Hello, I have a problem with signal-cli 0.12.3, when I am trying to receive messages with `/signal-cli -a +receiver_phone_num receive` some of them give an Exception, example:
```
Timestamp: 1697638790343 (2023-10-18T14:19:50.343Z)
Server timestamps: received: 1697638834156 (2023-10-18T14:20:34.156Z) delivered: 1697638889672 (2023-10-18T14:21:29.672Z)
Sent by unidentified/sealed sender
Exception: org.signal.libsignal.protocol.NoSessionException: missing sender key state for distribution ID 93361069-e01e-48a9-ab2e-ac62592cc38a (ProtocolNoSessionException)
```

Receiving most messages works good, except few, but in my case it is important, so my question is:
1. What causes an error ? 
2. Are there any ways to avoid it at my side ? 
3. Whose side is the problem on? (Signal/Me/Code, etc.)

## Related with:
- #239

**Comment by AsamK** [comment]
This can happen when messages weren't received regularly and the message with the sender key (for group message encryption) was discarded by the server previously.
signal-cli should re-request the message from the sender in this case.
A verbose log (with `-v`) would show if this is working correctly.

**Comment by dKibi** [comment]
Thank you, that is, I understand correctly - even if `NoSessionException` occurs, signal-cli will try to receive message again and theoretically the message will not be missed due to an error?

While testing, another error appeared (while getting message from group from new sender):
```
Fetching messages from Signal, please wait..
An error occurred while receiving the message: ERROR ReceiveHelper - Unknown error when handling messages
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.updateRecipientAddress(RecipientStore.java:835)
	at org.asamk.signal.manager.storage.recipients.RecipientStore$HelperStore.updateRecipientAddress(RecipientStore.java:1145)
	at org.asamk.signal.manager.storage.recipients.MergeRecipientHelper.resolveRecipientTrustedLocked(MergeRecipientHelper.java:45)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:693)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:283)
	at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveRecipientTrusted(RecipientTrustedResolver.java:35)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:253)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:203)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:214)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1108)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1094)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:81)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:276)
	at org.asamk.signal.App.handleCommand(App.java:192)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:61)
ERROR ReceiveHelper - Unknown error when handling messages
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.updateRecipientAddress(RecipientStore.java:835)
	at org.asamk.signal.manager.storage.recipients.RecipientStore$HelperStore.updateRecipientAddress(RecipientStore.java:1145)
	at org.asamk.signal.manager.storage.recipients.MergeRecipientHelper.resolveRecipientTrustedLocked(MergeRecipientHelper.java:45)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:693)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:283)
	at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveRecipientTrusted(RecipientTrustedResolver.java:35)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:253)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:203)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:214)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1108)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1094)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:81)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:276)
	at org.asamk.signal.App.handleCommand(App.java:192)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:61)
ERROR ReceiveHelper - Unknown error when handling messages
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.updateRecipientAddress(RecipientStore.java:835)
	at org.asamk.signal.manager.storage.recipients.RecipientStore$HelperStore.updateRecipientAddress(RecipientStore.java:1145)
	at org.asamk.signal.manager.storage.recipients.MergeRecipientHelper.resolveRecipientTrustedLocked(MergeRecipientHelper.java:45)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:693)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:283)
	at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveRecipientTrusted(RecipientTrustedResolver.java:35)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:253)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:203)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:214)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1108)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1094)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:81)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:276)
	at org.asamk.signal.App.handleCommand(App.java:192)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:61)
ERROR ReceiveHelper - Unknown error when handling messages
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.updateRecipientAddress(RecipientStore.java:835)
	at org.asamk.signal.manager.storage.recipients.RecipientStore$HelperStore.updateRecipientAddress(RecipientStore.java:1145)
	at org.asamk.signal.manager.storage.recipients.MergeRecipientHelper.resolveRecipientTrustedLocked(MergeRecipientHelper.java:45)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:693)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:283)
	at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveRecipientTrusted(RecipientTrustedResolver.java:35)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:253)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:203)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:214)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1108)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1094)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:81)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:276)
	at org.asamk.signal.App.handleCommand(App.java:192)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:61)
```

And in general, what is better for more stable receipt of messages - linking an existing account or creating a new one?

The existing account is completely empty and will be used only for receiving messages, that is, the question will be whether two clients (console and phone) will interfere or not?

**Comment by AsamK** [comment]
For NoSessionException signal-cli requests the message again from the server, so if the message isn't too old and the sender still has it in its send cache, it will be received again.

The ConcurrentModificationException is a regression in the latest version, I'll create a new version with a fix soon.

Linked accounts can receive messages reliably. So when choosing between linking and separate accounts, the more relevant question if both should receive exactly the same messages, in which case linked accounts work well.
As long as each devices receives messages are regularly, before the server discards older messages from its queue.
