### ISSUE TITLE
signal-cli 0.12.3 GraalVM - send - Handle Rate Limit Challenge

### ISSUE THREAD

**Issue by 13rac1** [AsamK/signal-cli#1352]
Hello! Thanks for this project. I'm seeing the following error sending to _some_ other accounts with the native version:
```
2023-10-19T12:08:24.110-XX00 [main] WARN  o.a.signal.manager.helper.SendHelper - Failed to send message due to IO exception: Unable to parse entity
2023-10-19T12:08:24.110-XX00 [main] DEBUG o.a.signal.manager.helper.SendHelper - Exception
org.whispersystems.signalservice.api.push.exceptions.MalformedResponseException: Unable to parse entity
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.readBodyJson(PushServiceSocket.java:2519)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.readResponseJson(PushServiceSocket.java:2532)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:2063)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2021)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1960)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:628)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:2228)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendContent(SignalServiceMessageSender.java:484)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendDataMessage(SignalServiceMessageSender.java:437)
	at org.asamk.signal.manager.helper.SendHelper.lambda$sendMessage$19(SendHelper.java:655)
	at org.asamk.signal.manager.helper.SendHelper.handleSendMessage(SendHelper.java:680)
	at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:653)
	at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:96)
	at org.asamk.signal.manager.internal.ManagerImpl.sendMessage(ManagerImpl.java:537)
	at org.asamk.signal.manager.internal.ManagerImpl.sendMessage(ManagerImpl.java:521)
	at org.asamk.signal.manager.internal.ManagerImpl.sendMessage(ManagerImpl.java:642)
	at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:235)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:276)
	at org.asamk.signal.App.handleCommand(App.java:192)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:61)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.whispersystems.signalservice.internal.push.ProofRequiredResponse`: cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized
 at [Source: (String)"{"token":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX","options":["recaptcha","pushChallenge"]}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1915)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1355)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1421)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at org.whispersystems.signalservice.internal.util.JsonUtil.fromJson(JsonUtil.java:67)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.readBodyJson(PushServiceSocket.java:2516)
	... 21 common frames omitted
Failed to send (some) messages:
+1XXXXXXXXXXXX: Network failure for "+XXXXXXXXXXXX"
XXXXXXXXXXXXXXX
2023-10-19T12:08:24.113-XX00 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-10-19T12:08:24.114-XX00 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2023-10-19T12:08:24.114-XX00 [msl-cleanup] DEBUG o.a.s.m.s.s.MessageSendLogStore - Stopping msl cleanup thread
Failed to send message
```

**Comment by 13rac1** [comment]
Ah ha, running the Java version gives a proper error:
```
Failed to send (some) messages:
+XXXXXXXXXXXX: CAPTCHA proof required for sending to "+XXXXXXXXXXXX", available options "RECAPTCHA, PUSH_CHALLENGE" with challenge token "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", or wait "86400" seconds.
To get the captcha token, go to https://signalcaptchas.org/challenge/generate.html
Check the developer tools (F12) console for a failed redirect to signalcaptcha://
Everything after signalcaptcha:// is the captcha token.
Use the following command to submit the captcha token:
signal-cli submitRateLimitChallenge --challenge CHALLENGE_TOKEN --captcha CAPTCHA_TOKEN
XXXXXXXXXXXXX
2023-10-19T12:47:08.589-XX00 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-10-19T12:47:08.592-XX00 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2023-10-19T12:47:08.593-0XX00 [msl-cleanup] DEBUG o.a.s.m.s.s.MessageSendLogStore - Stopping msl cleanup thread
Failed to send message due to rate limiting
org.asamk.signal.manager.api.RateLimitException: Rate limit
	at org.asamk.signal.util.SendMessageResultUtils.outputResult(SendMessageResultUtils.java:57)
	at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:236)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:276)
	at org.asamk.signal.App.handleCommand(App.java:192)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:61)
```

**Comment by AsamK** [comment]
Thanks for the log, should be fixed by adding the class to the graalvm reflect config.
