### ISSUE TITLE
Cannot join a V2 group as self does not have a versioned profile

### ISSUE THREAD

**Issue by wan-may** [AsamK/signal-cli#1362]
I had registered a phone number via SMS and the command line:
```
PS D:\bin\signal-cli-0.12.4\bin> ./signal-cli listAccounts
Number: +1234567890
```

I made a profile, making sure to add an avatar and name at the same time. No errors.
```
PS D:\bin\signal-cli-0.12.4\bin> ./signal-cli -u +1234567890 updateProfile --name "myname" --avatar "..\..\..\img\avatar.png"
```

Then I join the group:
```
PS D:\bin\signal-cli-0.12.4\bin> ./signal-cli joinGroup --uri "https://signal.group/#CjQKIIkOG1mGW-uRmf1mk99SEI_8KUspmFhCoQotzCs4c0FhEhCzRFKU3YbkcWLTKML9ND0N"
Failed to send message: Cannot join a V2 group as self does not have a versioned profile (IOException)
```

The other issues I could find were light on troubleshooting details.
What else do I have to do to make a "versioned" profile?

**Comment by AsamK** [comment]
Try running the updateProfile command before.

**Comment by AsamK** [comment]
Yes, that should do it.
Can you run the joinGroup command again with the `-v` parameter, to get a more detailed log?

**Comment by hatl** [comment]
I'm running into the same issue.
Unfortunately, the updateProfile command doesn't help:

```
signal-cli -v -u +1234567890 updateProfile --name "Home Assistant" --about "for notifications only" --avatar /home/.local/share/signal-cli/hass.png 
2023-11-03T11:32:51.678Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-11-03T11:32:51.683Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.4
2023-11-03T11:32:51.738Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.32.1
2023-11-03T11:32:51.739Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-11-03T11:32:51.905Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-03T11:32:51.974Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@44040454
2023-11-03T11:32:51.975Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-03T11:32:53.495Z [main] DEBUG o.a.s.manager.helper.ProfileHelper - Uploading new profile
2023-11-03T11:32:54.538Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-03T11:32:54.539Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.



signal-cli -v -u +1234567890 joinGroup --uri https://signal.group/#__GROUP_ID__
2023-11-03T11:33:11.450Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-11-03T11:33:11.455Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.4
2023-11-03T11:33:11.511Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.32.1
2023-11-03T11:33:11.512Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-11-03T11:33:11.679Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-03T11:33:11.748Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@4c550889
2023-11-03T11:33:11.749Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-03T11:33:14.441Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-03T11:33:14.443Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Failed to send message: Cannot join a V2 group as self does not have a versioned profile (IOException)
java.io.IOException: Cannot join a V2 group as self does not have a versioned profile
        at org.asamk.signal.manager.helper.GroupV2Helper.joinGroup(GroupV2Helper.java:431)
        at org.asamk.signal.manager.helper.GroupHelper.joinGroup(GroupHelper.java:307)
        at org.asamk.signal.manager.internal.ManagerImpl.joinGroup(ManagerImpl.java:515)
        at org.asamk.signal.commands.JoinGroupCommand.handleCommand(JoinGroupCommand.java:55)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.handleCommand(App.java:179)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:61)
```

any ideas?
