### ISSUE TITLE
Statuscode 404

### ISSUE THREAD

**Issue by A380Coding** [AsamK/signal-cli#1368]
Running:
signal-cli -v --config /home/.local/share/signal-cli -a +123456789 verify 123456
I get this error:
org.whispersystems.signalservice.api.push.exceptions.NoSuchSessionException: StatusCode: 404 

Any idea what is causing this?

**Comment by A380Coding** [comment]
yes, using https://github.com/bbernhard/signal-cli-rest-api and I received the verification code. Maybe I repeat that via the console to see if it any other issue appears upfront

**Comment by A380Coding** [comment]
Trying to register I get:
signal-cli output (stderr): INFO  RegistrationManagerImpl - Reactivated existing account, verify is not necessary.

But I'm unable to send or receive anything. strange.

**Comment by AsamK** [comment]
That means the account is active, can you paste a verbose log from sending/receiving?

**Comment by A380Coding** [comment]
I tried sending and get this exception now:
[main] WARN  o.a.s.manager.helper.PreKeyHelper - Failed 
to store new pre keys, resetting preKey id offset                                
java.lang.RuntimeException: Failed update pre_key store

**Comment by A380Coding** [comment]
I received a message now, even though I got these exceptions.

**Comment by AsamK** [comment]
There should be a stack trace along with the error message that could show more details in what's going wrong there.

**Comment by A380Coding** [comment]
I can check on that. Currently it is running fine. I don't now why, but it is working now. Maybe it needs some time after verification to be accepted?
Trying to change the name and picture now.

**Comment by marsavar** [comment]
Getting the same 404 error when attemtping to run the `setPin` command. Here are verbose logs:

```
$ ./signal-cli -a **REDACTED** --verbose --config /home/ubuntu/.local/share/signal-cli/data setPin **REDACTED**"
2023-11-08T12:41:34.045Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-11-08T12:41:34.067Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.2
2023-11-08T12:41:34.317Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.32.1
2023-11-08T12:41:34.915Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-08T12:41:35.076Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@51cd7ffc
2023-11-08T12:41:35.079Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-08T12:41:35.479Z [main] INFO  o.a.s.manager.helper.AccountHelper - The Signal protocol expects that incoming messages are regularly received.
2023-11-08T12:41:37.373Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-08T12:41:37.382Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Set pin error: [404] Not found
org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:2021)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2002)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1941)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1935)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getAuthCredentials(PushServiceSocket.java:1275)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getKeyBackupServiceAuthorization(PushServiceSocket.java:1289)
	at org.whispersystems.signalservice.api.KeyBackupService.newPinChangeSession(KeyBackupService.java:63)
	at org.asamk.signal.manager.helper.PinHelper.setRegistrationLockPin(PinHelper.java:42)
	at org.asamk.signal.manager.helper.AccountHelper.setRegistrationPin(AccountHelper.java:307)
	at org.asamk.signal.manager.internal.ManagerImpl.setRegistrationLockPin(ManagerImpl.java:378)
	at org.asamk.signal.commands.SetPinCommand.handleCommand(SetPinCommand.java:36)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:276)
	at org.asamk.signal.App.handleCommand(App.java:192)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:60)
```
The config path is the same I used for registration.
Any help is greatly appreciated

**Comment by AsamK** [comment]
@marsavar that's an unrelated issue. You need to update to signal-cli 0.12.4, as the old pin endpoints on the server have been removed.
