### ISSUE TITLE
Must have either a ServiceId or E164 number (signal-cli-native)

### ISSUE THREAD

**Issue by incognico** [AsamK/signal-cli#1369]
Just got this twice, signal-cli-native 0.12.4. Seems similar to #1074 

```
java.lang.AssertionError: Must have either a ServiceId or E164 number!
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:39)
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:44)
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:71)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientLocked(RecipientStore.java:759)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:187)
        at org.asamk.signal.manager.storage.recipients.RecipientResolver$RecipientResolverWrapper.resolveRecipient(RecipientResolver.java:47)
        at org.asamk.signal.manager.api.MessageEnvelope$Data$Quote.from(MessageEnvelope.java:236)
        at org.asamk.signal.manager.api.MessageEnvelope$Data.lambda$from$2(MessageEnvelope.java:143)
        at java.base@17.0.8/java.util.Optional.map(Optional.java:260)                                                                                                                                  at org.asamk.signal.manager.api.MessageEnvelope$Data.from(MessageEnvelope.java:143)
        at org.asamk.signal.manager.api.MessageEnvelope$Edit.from(MessageEnvelope.java:532)
        at org.asamk.signal.manager.api.MessageEnvelope.lambda$from$1(MessageEnvelope.java:930)                                                                                                        at java.base@17.0.8/java.util.Optional.map(Optional.java:260)
        at org.asamk.signal.manager.api.MessageEnvelope.from(MessageEnvelope.java:930)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:287)                                                                               at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:203)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:214)                                                                                               at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
        at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1108)
        at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1094)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:81)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.handleCommand(App.java:179)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:61)
```

**Comment by AsamK** [comment]
Thanks for the stack trace. Looks like you got a message with a quote without an author, that shouldn't happen ...
I guess the best thing signal-cli could do here is to ignore the quote.

**Comment by incognico** [comment]
One sender replied (quote) to a message (which had an image attachment) but deleted it and then sent it again. If I had to guess it probably had something to do with the deleted message or the editing of the second message.
