### ISSUE TITLE
ExternalServiceFailureException

### ISSUE THREAD

**Issue by KiaraGrouwstra** [AsamK/signal-cli#1373]
as per the readme instructions, i try to register using `signal-cli -a "+3185627442" register --captcha signalcaptcha://...` (replacing the URI with the one obtained from https://signalcaptchas.org/registration/generate.html).
upon doing this i am met with error: `Failed to register: StatusCode: 502 (ExternalServiceFailureException)`.
am i doing anything wrong? is this a known issue by any chance?

**Comment by ZVanoZ** [comment]
Ia have the same error.
````bash
./signal-cli -v -u +380671234567 egister --captcha signalcaptcha://signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.challenge.P1************

2024-01-05T21:19:45.433+0200 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.7
2024-01-05T21:19:45.581+0200 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.36.1
2024-01-05T21:19:45.582+0200 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-01-05T21:19:45.723+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-01-05T21:19:45.792+0200 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@56303b57
2024-01-05T21:19:45.793+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-01-05T21:19:46.922+0200 [main] DEBUG o.a.s.m.util.NumberVerificationUtils - No registration session, creating new one.
2024-01-05T21:19:47.673+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-01-05T21:19:47.675+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.

````

**Comment by bereshbr** [comment]
same error
any suggestions?

**Comment by gantlord** [comment]
for whatever reason the error has changed that I'm getting, now getting 499, DepcrecatedVersionException:

ubuntu@ip-172-31-19-252:~$ signal-cli -u [CENSORED] register --captcha signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQP1aOJqCGQ-ltAV4fE4qOtgl1eO7MTJ-49OaWom4SajKWBMkM6vH2YPzXuTXs9GrxPxy10Yg82fndkcwkSIO4-bZ7dMudkrNx1bIKJ44Hz9pf3ar1djzJ7I5l3ONAk4lGk18ajyWC9tT1pL-BpW288fiiZDO-nFf_ONsn5uRamajxBFn4qHnLO8iEbHua5jKyPYPTadDYzDry1KpjmMmo3p7e7j4smoZnlsum7ExGN0zSAimA8R8Vq0ASbNOLY1bHV6e8EW5JoIibEiqOsd6A31xoldK1Ke5L6aAnLMvMHHMT-sG5a33Xw8lUSzeRT1hUlcDr4NHYfBlu8N2_tN7qn68d7GMW2r36jwJIjsgVc-ZyKUWqxLDHAk4IG1ruMpSseHrzdf7nM2HgEyuBDRvp7uyHBiMjcSK-6jMyiGIL_IaDXU1l-tFOv-U9wRhzqJyywFjTMZvysb8dt2Be-dprRskJKhN8UeOl3vLKGIfiSRVcRQufpTc26ZIFkZEY-W6bZxlEYCiRbLpEoqBFrPa-ecIUHspCKz8UulE7GtoOLNEXtcoGksGs77e1u9F37J01USc9Isgao-Hfe1HyWxN1yIQ0IO_d90cahe7BxCynE7Ry5J5dxnmJ1RoqLUg9Ah3-gTcLhNE0IZPWE0jz818kSAVfqb_K32zdwe4-rIdK2ezFImv9hyoEbS5eKJ7-szt6QH8FpeYsjtbTCdxQVOzcvViSqOOlHnTppiX7BnTXMJdOB2Irfv3N6QcP4qjKSokgT8ZVo_oq1BVFS1IZCcLFSCCoAwBjMJIWCEK-hYCu6UPY0Vg_9Iq2DkES8gqGk7JJU6Q8Fp3pKUcQbWYMjRv6j8vJP0wOxcDfg6WctEN77naLztW9s0kwqLGYvh_i1NWEN1hz2WeSQgk71FcBXbZqVPupzyWbb3p-_e0ycPQ4OsVxpBx3p1OOl9V0sgsf0_YqcatCXTGW3cic2wQ0dqw2DNySZFB91YL7ATGThqA0RTCGx1f1RrHpvsd2H9VZCN62SZxlM9k-zWWFZrNDSRT3udppJAb7mIK3v69DWCcSokjmHuibWPXF8yQ8amZT69-eCe90Ig76awKaXghpbe1dTBqBoN3KGS2VjQJii4RpfZvhsGR0qvuVSI2xUlAWbF-3vjTs1tyOWqOU5uRT0jnYd0n3-IYfbvlF191Ud6xeJNtbFjDqN3O_WpmPPNR5IP4lXCwkc2e0DcXI8I7XjQEWQqp5O1gc9tQres7dZmsWaz3Oqg_6fPEF95SMDFVUXq0gmkm3Vmvg_hYHZ1Rl6kjQzU23rxKx8uHG26djZUFbQGW-52VLTeGlGfKYu2BdgU3wfMaHmtvfSjZXhwzmXBQYOoc2hhcmRfaWTOAzGDb6JwZAA.5Gj-b_qAhXMVsUN74GTEpY9GhDCZgAjFqwoxz_D2UT0 -v
2024-02-05T20:21:30.398Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.7
2024-02-05T20:21:30.746Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.36.1
2024-02-05T20:21:30.748Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-02-05T20:21:31.251Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-02-05T20:21:31.484Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@7fe7c640
2024-02-05T20:21:31.486Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-02-05T20:21:32.209Z [main] DEBUG o.a.s.m.util.NumberVerificationUtils - No registration session, creating new one.
2024-02-05T20:21:34.029Z [main] DEBUG o.a.s.m.i.RegistrationManagerImpl - Signal-Server returned deprecated version exception
org.whispersystems.signalservice.api.push.exceptions.DeprecatedVersionException: StatusCode: 499
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:2092)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2037)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.createVerificationSession(PushServiceSocket.java:353)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.createRegistrationSession(SignalServiceAccountManager.java:238)
        at org.asamk.signal.manager.util.NumberVerificationUtils.requestValidSession(NumberVerificationUtils.java:151)
        at org.asamk.signal.manager.util.NumberVerificationUtils.getValidSession(NumberVerificationUtils.java:161)
        at org.asamk.signal.manager.util.NumberVerificationUtils.handleVerificationSession(NumberVerificationUtils.java:40)
        at org.asamk.signal.manager.internal.RegistrationManagerImpl.register(RegistrationManagerImpl.java:114)
        at org.asamk.signal.commands.RegisterCommand.register(RegisterCommand.java:70)
        at org.asamk.signal.commands.RegisterCommand.handleCommand(RegisterCommand.java:46)
        at org.asamk.signal.commands.CommandHandler.handleRegistrationCommand(CommandHandler.java:31)
        at org.asamk.signal.App.handleRegistrationCommand(App.java:265)
        at org.asamk.signal.App.handleCommand(App.java:174)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:61)
2024-02-05T20:21:34.036Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-02-05T20:21:34.043Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Failed to register: StatusCode: 499 (DeprecatedVersionException)
org.whispersystems.signalservice.api.push.exceptions.DeprecatedVersionException: StatusCode: 499
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:2092)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2037)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.createVerificationSession(PushServiceSocket.java:353)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.createRegistrationSession(SignalServiceAccountManager.java:238)
        at org.asamk.signal.manager.util.NumberVerificationUtils.requestValidSession(NumberVerificationUtils.java:151)
        at org.asamk.signal.manager.util.NumberVerificationUtils.getValidSession(NumberVerificationUtils.java:161)
        at org.asamk.signal.manager.util.NumberVerificationUtils.handleVerificationSession(NumberVerificationUtils.java:40)
        at org.asamk.signal.manager.internal.RegistrationManagerImpl.register(RegistrationManagerImpl.java:114)
        at org.asamk.signal.commands.RegisterCommand.register(RegisterCommand.java:70)
        at org.asamk.signal.commands.RegisterCommand.handleCommand(RegisterCommand.java:46)
        at org.asamk.signal.commands.CommandHandler.handleRegistrationCommand(CommandHandler.java:31)
        at org.asamk.signal.App.handleRegistrationCommand(App.java:265)
        at org.asamk.signal.App.handleCommand(App.java:174)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:61)

**Comment by bcs1gh** [comment]
Also getting this error

**Comment by m-ueberall** [comment]
> for whatever reason the error has changed that I'm getting, now getting 499, DepcrecatedVersionException:

> Also getting this error

@gantlord, @bcs1gh: You need to upgrade to [release v0.12.8](https://github.com/AsamK/signal-cli/releases/tag/v0.12.8); older releases use an outdated user agent identification ([see here](https://github.com/AsamK/signal-cli/compare/v0.12.7...v0.12.8#diff-ed8ca6cd4fb78b6663ed8e8f77a901f0c8fa2e9f9d03001ae7d57ca8bf18887e)).

**Comment by gantlord** [comment]
Hi @m-ueberall, thanks for the tip - I installed the new version - I was back to getting the 429 error afterwards. 

The problem I had was in fact that I was trying to solve captchas from a different machine than the one running signal-cli, so it didn't see the captchas as valid and I couldn't unblock the 429's that started coming. 

After going down a few rabbit holes trying to get a browser to work on the server, I eventually just conceded and ran the registration on my laptop - this worked in the end, so it's enough for me to get started, albeit when I come to deploy something production I've still a problem to solve.

**Comment by bereshbr** [comment]
I tried the same thing on my laptop. unfortunately still error 429 with release v0.12.8

**Comment by gantlord** [comment]
> I tried the same thing on my laptop. unfortunately still error 429 with release v0.12.8

What happens if you do a captcha? Nothing changes?

Maybe try the challenge captcha url:

https://signalcaptchas.org/challenge/generate.html

**Comment by bereshbr** [comment]
same error 429 with "registration" or "challenge"

**Comment by m8ichael** [comment]
I get the same error 429 (v0.12.8)

**Comment by orazioedoardo** [comment]
@MarcMichalsky I would try with the smartphone app to make sure it's an issue specific to signal-cli.

**Comment by MarcMichalsky** [comment]
> @MarcMichalsky I would try with the smartphone app to make sure it's an issue specific to signal-cli.

OK, I tried it with the app and it worked.

**Comment by Monox83** [comment]
Same problem for me, it works without --voice.

**Comment by orazioedoardo** [comment]
Perhaps Signal server is considering call verification without trying sms first a toll fraud attempt? https://www.twilio.com/docs/verify/preventing-toll-fraud
