### ISSUE TITLE
Rate Limit Challenge Problem

### ISSUE THREAD

**Issue by anotherbridge** [AsamK/signal-cli#1380]
Similarly, as mentioned in #1328 I also face a problem when solving the captcha challenge. When trying to solve it via 

```bash
signal-cli --config /home/.local/share/signal-cli -v submitRateLimitChallenge --challenge "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" --captcha '<captcha>'
```

I am not able to solve the challenge. With a freshly generated captcha I am always getting a response code of 400 telling me that I performed an invalid captcha action. The full verbose output is: 

```
2023-11-13T10:49:36.060Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-11-13T10:49:36.099Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.4
2023-11-13T10:49:36.355Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.32.1
2023-11-13T10:49:37.002Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-13T10:49:37.258Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@4c2cc639
2023-11-13T10:49:37.264Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-13T10:49:37.462Z [main] INFO  o.a.s.manager.helper.AccountHelper - The Signal protocol expects that incoming messages are regularly received.
2023-11-13T10:49:46.423Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-13T10:49:46.437Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Submit challenge error: [400] Bad response: 400 : {"code":400,"message":"invalid captcha action"}
org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: [400] Bad response: 400 : {"code":400,"message":"invalid captcha action"}
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:2049)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1993)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1932)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1926)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.submitRateLimitRecaptchaChallenge(PushServiceSocket.java:1148)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.submitRateLimitRecaptchaChallenge(SignalServiceAccountManager.java:914)
	at org.asamk.signal.manager.internal.ManagerImpl.submitRateLimitRecaptchaChallenge(ManagerImpl.java:381)
	at org.asamk.signal.commands.SubmitRateLimitChallengeCommand.handleCommand(SubmitRateLimitChallengeCommand.java:38)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:278)
	at org.asamk.signal.App.handleCommand(App.java:179)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:61)
```

I tried solving the challenge with the `signalcaptcha://` and also without it, but had no luck so far...

Any idea on how to resolve this?

**Comment by jampot9** [comment]
Also facing the same invalid action issue.

**Comment by i-infra** [comment]
@jampot9 what URL are you using to generate solutions to ratelimit challenges? IIRC it should be: https://signalcaptchas.org/challenge/generate
