### ISSUE TITLE
receive and java.lang.NullPointerException: Must not be null!

### ISSUE THREAD

**Issue by xyz-nobody** [AsamK/signal-cli#1387]
I have a problem, I noticed that during a network failure while synchronizing, I get this message. And I can no longer retrieve new messages.

out of 10 master accounts I have on signal-cli, I have this problem on 2. The other 8 work perfectly.

Any idea what I can do?
I can't register the number, I don't have it anymore.

signal-cli --verbose -u +XXXX receive
Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
2023-11-21T16:33:02.218Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.11.11
2023-11-21T16:33:02.354Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.25.0
2023-11-21T16:33:02.354Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-11-21T16:33:02.729Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-21T16:33:02.854Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@5b1f29fa
2023-11-21T16:33:02.855Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-21T16:33:07.183Z [main] INFO  LibSignal - [WebSocketConnection]: [normal:860941277] connect()
2023-11-21T16:33:07.196Z [main] INFO  LibSignal - [WebSocketConnection]: [unidentified:247575268] connect()
2023-11-21T16:33:07.206Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2023-11-21T16:33:07.220Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
2023-11-21T16:33:08.568Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [normal:860941277] onOpen() connected
2023-11-21T16:33:08.569Z [RxComputationThreadPool-2] DEBUG o.a.s.m.i.SignalWebSocketHealthMonitor - WebSocket is now connected
2023-11-21T16:33:08.691Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Retrieved 1 envelopes!
2023-11-21T16:33:08.702Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2023-11-21T16:33:08.702Z [main] INFO  LibSignal - [WebSocketConnection]: [normal:860941277] disconnect()
2023-11-21T16:33:08.704Z [main] INFO  LibSignal - [WebSocketConnection]: [unidentified:247575268] disconnect()
2023-11-21T16:33:08.705Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-21T16:33:08.715Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
java.lang.NullPointerException: Must not be null!
	at org.whispersystems.signalservice.api.util.Preconditions.checkNotNull(Preconditions.java:36)
	at org.whispersystems.signalservice.api.util.Preconditions.checkNotNull(Preconditions.java:31)
	at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:39)
	at org.whispersystems.signalservice.api.messages.SignalServiceEnvelope.getSourceAddress(SignalServiceEnvelope.java:184)
	at org.asamk.signal.manager.helper.ReceiveHelper.lambda$receiveMessagesInternal$0(ReceiveHelper.java:151)
	at org.whispersystems.signalservice.api.SignalWebSocket.readMessageBatch(SignalWebSocket.java:279)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:144)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1033)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1019)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:81)
	at org.asamk.signal.App.handleLocalCommand(App.java:289)
	at org.asamk.signal.App.init(App.java:229)
	at org.asamk.signal.Main.main(Main.java:60)

**Comment by AsamK** [comment]
Please try updating to the latest signal-cli version.

**Comment by xyz-nobody** [comment]
With version v0.12.5 I got the same message a few times but the difference is that it downloaded messages and displayed :

java.lang.NullPointerException: Must not be null!

I re-run it several times, it downloaded everything and now everything is back to normal.
