### ISSUE TITLE
Link request error: StatusCode: 409 (exceptions.MissingCapabilitiesException)

### ISSUE THREAD

**Issue by aizelauna** [AsamK/signal-cli#1392]
Hi,

I am trying to link an instance of signal-cli with my primary account managed by my android phone.
But when I try the link, it fails with the error 409.

Here is a verbose log :

```
$ signal-cli -v link  -n "nokia xr20" | tee >(xargs -L 1 qrencode -t utf8)
2023-11-30T22:06:17.382+0100 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.5
2023-11-30T22:06:17.516+0100 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.32.1
2023-11-30T22:06:17.517+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-11-30T22:06:17.827+0100 [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:412788346] connect()
2023-11-30T22:06:18.799+0100 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:412788346] onOpen() connected
sgnl://linkdevice?uuid=CsS6-x1E8Hxp7fSJN5gHNA&pub_key=BVeUSnPu0t71HmGPj9GA9pwtaIFKSKVGskrFkLykNXpC
█████████████████████████████████████████████
█████████████████████████████████████████████
████ ▄▄▄▄▄ █   █▄▄▀▄ ▀▄ █ █▄█▀ █▄█ ▄▄▄▄▄ ████
████ █   █ █ ▀▄ █▀ ▀▀  ▀▄▄██ ▀▀▄▄█ █   █ ████
████ █▄▄▄█ █▀██▀▀█ █▄█▀▀▀█▀█▀▀▀▄▀█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄▀▄█ █ █▄▀▄█▄▀▄█▄█▄▀▄█▄▄▄▄▄▄▄████
████▄▄▀▀ ▄▄█▀█▀▄▀▀██  ▀▀▄  ▀▄▀██▀▀█▄▀  ▄▄████
█████▀██▀ ▄▄▄▄█ ▄▄█▄▀▀██▄ ▄  ██ ▀██  ▀▀ ▀████
████ ▄▄ ▀ ▄█▄█▄█▄ ▀▄▀ ▄▄▀ ▀▀█▀▄▀▄ ▄▀▀▀ ▀█████
████▀▀ █ ▀▄▄█  █▀▄▄▄▀ ▀▀  █ █▄   ██ ██▀ █████
█████ ██▀█▄█▄▄ ▄▀█▀█ █▀▄▀█▄▀█▀▀  ▄▄▄▀▀ ▄█████
████▀▄▄  █▄▀ ▀▄ ▄▄▀▄▀▀ █▀▀ ▄▀▄▄ █▄▄▄▄▄ ▀▀████
█████ ▀▀█ ▄█▄▀██▄▄▀▄▀█▀▄██ ▀  █ █▄▄▄▀█ ▄█████
█████ █▄▀█▄██▀▀█▀█▄▄▄ ▀██▀▀ ▄▄▀▄▄▀█▄▀█ █▀████
████ █ ▀ █▄▀██▄▄ ███▀ ▄▄▀▄▄█▄▄▀▀▄▀▄▄▀▀ ▄▄████
██████▄▄▀█▄██  ▄▄█▀ ▀ ▀█  █▄▀▄█▄▀█▄▀▄▄▀█▀████
████▄▄█▄█▄▄▄  ▄█▄█▀▄▀▄█▄██ ▄▄▄▀▀ ▄▄▄ █ ▀▄████
████ ▄▄▄▄▄ █▀▀  █▄▀ ▀ ███ █ █▄▄▄ █▄█ █▀▀▀████
████ █   █ █▄▄█▀█▄▀▀▀▄█ ██ ▄▄▀▄▀   ▄▄▀▄█▄████
████ █▄▄▄█ █▀ ▄ █▄▄ ▄▀ ▀▀▀▄▄ █ ▄▄ █ █▄ ▀█████
████▄▄▄▄▄▄▄█▄█▄▄█▄██▄▄██▄▄▄█▄██▄█▄██▄█▄▄▄████
█████████████████████████████████████████████
█████████████████████████████████████████████
2023-11-30T22:06:27.060+0100 [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:412788346] disconnect()
2023-11-30T22:06:27.071+0100 [main] INFO  o.a.s.m.i.ProvisioningManagerImpl - Received link information from +33667450287, linking in progress ...
2023-11-30T22:06:27.192+0100 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:412788346] onClosing()
2023-11-30T22:06:27.193+0100 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:412788346] onClose()
2023-11-30T22:06:27.197+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-30T22:06:27.281+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@22680f52
2023-11-30T22:06:27.282+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-30T22:06:27.315+0100 [main] INFO  o.a.s.manager.helper.AccountHelper - The Signal protocol expects that incoming messages are regularly received.
2023-11-30T22:06:28.399+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-30T22:06:28.402+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2023-11-30T22:06:28.415+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
2023-11-30T22:06:28.416+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Added connection org.sqlite.jdbc4.JDBC4Connection@1352434e
2023-11-30T22:06:28.416+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
2023-11-30T22:06:28.461+0100 [main] DEBUG o.a.s.m.i.ProvisioningManagerImpl - Finishing new device registration
2023-11-30T22:06:29.127+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown initiated...
2023-11-30T22:06:29.129+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown completed.
Link request error: StatusCode: 409
org.whispersystems.signalservice.internal.push.exceptions.MissingCapabilitiesException: StatusCode: 409
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.lambda$static$0(PushServiceSocket.java:509)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2011)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1949)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.finishNewDeviceRegistration(PushServiceSocket.java:503)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.finishNewDeviceRegistration(SignalServiceAccountManager.java:743)
	at org.asamk.signal.manager.internal.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:148)
	at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
	at org.asamk.signal.commands.CommandHandler.handleProvisioningCommand(CommandHandler.java:25)
	at org.asamk.signal.App.handleProvisioningCommand(App.java:255)
	at org.asamk.signal.App.handleCommand(App.java:158)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:61)
```

It looks like the signal server does not validate the signal-cli capabilities. Is this related to a recent change in the signal server side?

Regards,

**Comment by aizelauna** [comment]
I just realized that a similar issue had been already opened.
And it looks like it should be fixed with next version.
Thanks so much!

https://github.com/AsamK/signal-cli/issues/1386
