### ISSUE TITLE
version 0.11.5.1 does not work anymore?

### ISSUE THREAD

**Issue by piotr5** [AsamK/signal-cli#1406]
about 10 days ago it still worked, now I get:

```
WARN  PreKeyHelper - Failed to store new pre keys, resetting preKey id offset
org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeCodeException: [422] Bad response: 422
         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1782)
         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1725)
         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1663)
         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1657)
         at org.whispersystems.signalservice.internal.push.PushServiceSocket.registerPreKeys(PushServiceSocket.java:623)
...
```
has signal changed protocols? do I need a newer version? (in gentoo this is the newest)

**Comment by xusiai** [comment]
Broken on NixOS as well. When attempting to link a new device this occurs: 

```
ERROR: Encountered a problem while linking:
INFO  ProvisioningManagerImpl - Received link information from [redacted], linking in progress ...
Link request error: [405] Bad response: 405 
```

**Comment by AsamK** [comment]
There have been server side changes to linking, you need version 0.12.7 for linking.
