### ISSUE TITLE
java.lang.AssertionError: org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup

### ISSUE THREAD

**Issue by Miniontoby** [AsamK/signal-cli#1419]
I cannot seem to link my device...
```
pi@kodipi:~/signalbot $ signal-cli link
java.lang.AssertionError: org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup
        at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:33)
        at org.asamk.signal.manager.internal.ProvisioningManagerImpl.<init>(ProvisioningManagerImpl.java:78)
        at org.asamk.signal.manager.SignalAccountFiles.initProvisioningManager(SignalAccountFiles.java:143)
        at org.asamk.signal.manager.SignalAccountFiles.initProvisioningManager(SignalAccountFiles.java:139)
        at org.asamk.signal.App.handleProvisioningCommand(App.java:254)
        at org.asamk.signal.App.handleCommand(App.java:158)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:61)
Caused by: org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup
        at org.signal.libsignal.internal.Native.ServerPublicParams_CheckValidContents(Native Method)
        at org.signal.libsignal.zkgroup.ServerPublicParams.<init>(ServerPublicParams.java:14)
        at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:31)
        ... 7 more
```

please help!

**Comment by AsamK** [comment]
Please try with libsignal-client 0.36.1
See https://github.com/AsamK/signal-cli/blob/master/CHANGELOG.md#0127---2023-12-15

**Comment by Miniontoby** [comment]
Thanks, that fixed it.

It would be nice if the changelog stuff (mostly the libsignal-client version) could be added to the release body on the releases page. Cause personally I do not look in the CHANGELOG file...

**Comment by Henner** [comment]
same problem with:
signal_cli_ver=0.12.7
signal_lib_ver=0.39.3

**Comment by jgnoonan** [comment]
Can this issue be reopened?  I am trying to run the latest signal-server.  The pom.xml refers to libsignal version 0.39.0.  I tried upgrading to 0.41.0 but no matter what version I use, I still get:

org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup
	at org.signal.libsignal.internal.Native.GenericServerSecretParams_CheckValidContents(Native Method)
	at org.signal.libsignal.zkgroup.GenericServerSecretParams.<init>(GenericServerSecretParams.java:35)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:693)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:261)
	at io.dropwizard.core.cli.EnvironmentCommand.run(EnvironmentCommand.java:66)
	at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.core.cli.Cli.run(Cli.java:78)
	at io.dropwizard.core.Application.run(Application.java:94)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:1050)

I am running this on an EC2 x86_64 instance using Ubuntu 22.04.  I am really banging my head into a wall on this.  Any guidance is appreciated!
