### ISSUE TITLE
java.lang.AssertionError: Must have either a UUID or E164 number

### ISSUE THREAD

**Issue by k-bx** [AsamK/signal-cli#1455]
An hour ago, I started getting this error:

```
java.lang.AssertionError: Must have either a UUID or E164 number!
        at org.asamk.signal.manager.api.RecipientAddress.<init>(RecipientAddress.java:22)
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.toApiRecipientAddress(RecipientAddress.java:174)
        at org.asamk.signal.manager.api.MessageEnvelope.from(MessageEnvelope.java:947)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:282)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleRetryEnvelope(IncomingMessageHandler.java:122)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessage(ReceiveHelper.java:280)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessages(ReceiveHelper.java:263)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:134)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:109)
        at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1148)
        at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1120)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:86)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.handleCommand(App.java:179)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:56)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

signal-cli from master

**Comment by AsamK** [comment]
Thanks for reporting, will be fixed in the next version.
