### ISSUE TITLE
Exception when calling updateConfiguration

### ISSUE THREAD

**Issue by mitar** [AsamK/signal-cli#1471]
I get the following exception:

```
WARN  JobExecutor - Job SyncStorageJob failed
java.lang.NullPointerException: Cannot invoke "org.asamk.signal.manager.storage.groups.GroupInfoV1.setBlocked(boolean)" because "group" is null
	at org.asamk.signal.manager.syncStorage.GroupV1RecordProcessor.updateLocal(GroupV1RecordProcessor.java:116)
	at org.asamk.signal.manager.syncStorage.GroupV1RecordProcessor.insertLocal(GroupV1RecordProcessor.java:107)
	at org.asamk.signal.manager.syncStorage.GroupV1RecordProcessor.insertLocal(GroupV1RecordProcessor.java:20)
	at org.asamk.signal.manager.syncStorage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:53)
	at org.asamk.signal.manager.syncStorage.GroupV1RecordProcessor.process(GroupV1RecordProcessor.java:20)
	at org.asamk.signal.manager.helper.StorageHelper.processKnownRecords(StorageHelper.java:536)
	at org.asamk.signal.manager.helper.StorageHelper.readDataFromStorage(StorageHelper.java:175)
	at org.asamk.signal.manager.helper.StorageHelper.syncDataWithStorage(StorageHelper.java:92)
	at org.asamk.signal.manager.jobs.SyncStorageJob.run(SyncStorageJob.java:17)
	at org.asamk.signal.manager.internal.JobExecutor.lambda$runNextJob$0(JobExecutor.java:59)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

With v0.13.0.

**Comment by mitar** [comment]
Thanks!
