### ISSUE TITLE
removeDevice: "Error while removing device: [403] Authorization failed!"

### ISSUE THREAD

**Issue by Geremia** [AsamK/signal-cli#1474]
```
$ signal-cli -v removeDevice -d 1
2024-02-23T15:13:34.935-0700 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.1-SNAPSHOT
2024-02-23T15:13:35.151-0700 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.39.2
2024-02-23T15:13:35.152-0700 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-02-23T15:13:35.520-0700 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-02-23T15:13:35.667-0700 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@616fe72b
2024-02-23T15:13:35.669-0700 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-02-23T15:13:37.472-0700 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-02-23T15:13:37.475-0700 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Error while removing device: [403] Authorization failed!
org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [403] Authorization failed!
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:2158)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2135)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2072)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2066)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.removeDevice(PushServiceSocket.java:630)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.removeDevice(SignalServiceAccountManager.java:817)
        at org.asamk.signal.manager.helper.AccountHelper.removeLinkedDevices(AccountHelper.java:484)
        at org.asamk.signal.manager.internal.ManagerImpl.removeLinkedDevices(ManagerImpl.java:440)
        at org.asamk.signal.commands.RemoveDeviceCommand.handleCommand(RemoveDeviceCommand.java:35)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.handleCommand(App.java:179)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:56)
```
Is removing the signal-cli device not permitted? Is this why I'm getting this error?

**Comment by AsamK** [comment]
Removing linked devices only works from the primary device.
