### ISSUE TITLE
Cannot register with signal-cli 0.13.1

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#1491]
I got reports from my users that they failed to register with "Error in registerWithCaptcha:Invalid captcha given."
I can reproduce this both using Dbus and directly from CLI.
Tried captchas from both sources given in the Wiki, immediately used "copy link" on the "Open Signal" URL which got me something like signalcaptcha://signal-hcaptcha-short.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.pYpZRKG_y9w2jtsiMglF9ODo
and used it with signal-cli (method SMS)
The number I'm trying to register is a German landline - so I was planning to use "voice" in a second step, but never get that far.
After several attemps I'm getting "Failed to register: StatusCode: 429 (RegistrationRetryException)" which is an indication that the server really got my registration attemps.

**Comment by icacrr** [comment]
I've the same two issues.
I'm using signal-cli 0.13.1 and the SMS method.

1. Sometime the captcha, even if well completed, return an invalid token.
In the firefox console log, I can see that, when the token is invalid, I have only the warning "Prevented navigation to “signalcaptcha://signal-hcaptcha.XXXXX" (yellow) and not the log "Navigated to signalcaptcha://signal-hcaptcha.XXXXX" (blue).

2. When I got a valid captcha token, the register command respond "Failed to register: StatusCode: 429 (RegistrationRetryException)".
Here is the command result with verbose log:

```
$ signal-cli -v -u +XXXXXXX register --captcha signal-hcaptcha.XXX
2024-03-21T16:01:04.092Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2024-03-21T16:01:04.093Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.1
2024-03-21T16:01:06.037Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.39.2
2024-03-21T16:01:06.037Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-03-21T16:01:06.072Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-03-21T16:01:06.145Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@770e93b6
2024-03-21T16:01:06.145Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-03-21T16:01:07.092Z [main] DEBUG org.asamk.signal.manager.util.Utils - Invalid locale 'en', using fallback: en_US
2024-03-21T16:01:07.398Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-03-21T16:01:07.399Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Failed to register: StatusCode: 429 (RegistrationRetryException)
org.whispersystems.signalservice.api.push.exceptions.RegistrationRetryException: StatusCode: 429
	at org.whispersystems.signalservice.internal.push.PushServiceSocket$RegistrationCodeRequestResponseHandler.handle(PushServiceSocket.java:2958)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2130)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestVerificationCode(PushServiceSocket.java:403)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:283)
	at org.asamk.signal.manager.util.NumberVerificationUtils.requestVerificationCode(NumberVerificationUtils.java:98)
	at org.asamk.signal.manager.internal.RegistrationManagerImpl.register(RegistrationManagerImpl.java:136)
	at org.asamk.signal.commands.RegisterCommand.register(RegisterCommand.java:75)
	at org.asamk.signal.commands.RegisterCommand.handleCommand(RegisterCommand.java:51)
	at org.asamk.signal.commands.CommandHandler.handleRegistrationCommand(CommandHandler.java:31)
	at org.asamk.signal.App.handleRegistrationCommand(App.java:265)
	at org.asamk.signal.App.handleCommand(App.java:174)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:56)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

```

**Comment by kjcole** [comment]
This persists in 0.13.3.

**Comment by orazioedoardo** [comment]
CAPTCHA registration works for me on 0.13.3. Have you tried enclosing the captcha URI in single quotes? Perhaps there are some shell characters in the token.

**Comment by roymasad** [comment]
same issue with version 0.13.4

**Comment by Geremia** [comment]
@orazioedoardo Enclosed in quotes or not, I get this issue, too.

**Comment by icacrr** [comment]
This persists in version 0.13.4 (I tried with a debian and a ubuntu).

**Comment by icacrr** [comment]
Logs of CAPTCHA registration, with signal-cli version 13.4.
CAPTCHA generated with https://signalcaptchas.org/registration/generate (with same IP than signa-cli)

```
$ signal-cli -u +1XXXXXXXXXX -vv register --captcha signalcaptcha://signal-hcaptcha.[...]
2024-07-10T16:12:39.090Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2024-07-10T16:12:39.090Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.4
2024-07-10T16:12:50.759Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:161: Initializing libsignal version:0.47.0
2024-07-10T16:12:50.759Z [main] TRACE org.asamk.signal.manager.Manager - Expected exception when checking libsignal-client: Failed to deserialize zkgroup::api::groups::uuid_ciphertext::UuidCiphertext
2024-07-10T16:12:50.759Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-07-10T16:12:50.767Z [main] TRACE o.a.s.manager.storage.SignalAccount - Opening account file
2024-07-10T16:12:50.767Z [main] TRACE o.a.s.manager.storage.SignalAccount - Loading account file 269669
2024-07-10T16:12:50.769Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-07-10T16:12:50.837Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@6f98ba07
2024-07-10T16:12:50.837Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-07-10T16:12:50.837Z [main] TRACE o.a.s.m.storage.AccountDatabase - Current database version: 26 Program database version: 26
2024-07-10T16:12:52.881Z [main] DEBUG o.a.s.m.i.RegistrationManagerImpl - Failed to reactivate account
2024-07-10T16:12:53.864Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-07-10T16:12:53.866Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Invalid captcha given.
```

**Comment by amao12580** [comment]
same issues with the latest version 0.13.14,please help me




root@us1:/home/user# signal-cli -vv -u +121864XXXXX register --captcha signalcaptcha://signal-hcaptcha-short.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.XXXXXXXXXXXXXXXXXXXXX
2025-04-24T03:19:26.691Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2025-04-24T03:19:26.704Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.14
2025-04-24T03:19:27.500Z [main] TRACE org.asamk.signal.manager.Manager - Expected exception when checking libsignal-client: Failed to deserialize zkgroup::api::groups::uuid_ciphertext::UuidCiphertext
2025-04-24T03:19:27.500Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2025-04-24T03:19:27.864Z [main] TRACE o.a.s.manager.storage.SignalAccount - Opening account file
2025-04-24T03:19:27.867Z [main] TRACE o.a.s.manager.storage.SignalAccount - Loading account file 869766
2025-04-24T03:19:27.961Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2025-04-24T03:19:28.107Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@5316e95f
2025-04-24T03:19:28.109Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2025-04-24T03:19:28.118Z [main] TRACE o.a.s.m.storage.AccountDatabase - Current database version: 27 Program database version: 27
2025-04-24T03:19:28.369Z [main] TRACE o.a.s.m.s.keyValue.KeyValueStore - Got entry for key verification-session-number from db
2025-04-24T03:19:28.384Z [main] TRACE o.a.s.m.s.keyValue.KeyValueStore - Got entry for key verification-session-id from db
2025-04-24T03:19:29.387Z [main] TRACE o.a.s.m.s.keyValue.KeyValueStore - Got entry for key verification-session-number from db
2025-04-24T03:19:29.387Z [main] TRACE o.a.s.m.s.keyValue.KeyValueStore - Got entry for key verification-session-id from db
2025-04-24T03:19:29.776Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2025-04-24T03:19:29.778Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Failed to register: [403] Authorization failed! (AuthorizationFailedException)
org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [403] Authorization failed!
    at org.whispersystems.signalservice.api.NetworkResultUtil.toBasicLegacy(NetworkResultUtil.kt:51)
    at org.asamk.signal.manager.util.Utils.handleResponseException(Utils.java:158)
    at org.asamk.signal.manager.util.NumberVerificationUtils.submitCaptcha(NumberVerificationUtils.java:180)
    at org.asamk.signal.manager.util.NumberVerificationUtils.handleVerificationSession(NumberVerificationUtils.java:79)
    at org.asamk.signal.manager.internal.RegistrationManagerImpl.register(RegistrationManagerImpl.java:132)
    at org.asamk.signal.commands.RegisterCommand.register(RegisterCommand.java:80)
    at org.asamk.signal.commands.RegisterCommand.handleCommand(RegisterCommand.java:51)
    at org.asamk.signal.commands.CommandHandler.handleRegistrationCommand(CommandHandler.java:33)
    at org.asamk.signal.App.handleRegistrationCommand(App.java:268)
    at org.asamk.signal.App.handleCommand(App.java:177)
    at org.asamk.signal.App.init(App.java:147)
