### ISSUE TITLE
Cannot setPin or verify --pin 

### ISSUE THREAD

**Issue by icacrr** [AsamK/signal-cli#1492]
I think there might be a problem with the PIN management.
I'm using signal-cli 0.13.1.

I have two situations, the first one where I try to register an already existing Signal account (with SMS code) and I don't think that I mistake on the PIN (but I could).

```
$ signal-cli -u +4412345678 verify 123456 --pin XXXXXX

Verification failed! Invalid pin, tries remaining: X

```
The second one, where I try to register a new account. I can register the account, but I cannot set the PIN.

```
$ signal-cli -u +4412345678 setPin XXXXXX
Set pin error: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'

```
The same one with verbose:

```
$ signal-cli -v -u +4412345678 setPin XXXXXX
2024-03-16T17:41:27.020Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2024-03-16T17:41:27.021Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.1
2024-03-16T17:41:28.991Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.39.2
2024-03-16T17:41:28.991Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-03-16T17:41:29.026Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-03-16T17:41:29.096Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@56b5bdec
2024-03-16T17:41:29.096Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-03-16T17:41:30.856Z [main] DEBUG o.a.s.manager.internal.JobExecutor - Running RefreshRecipientsJob job
2024-03-16T17:41:30.858Z [pool-5-thread-1] DEBUG o.a.s.manager.helper.RecipientHelper - No new numbers to query.
2024-03-16T17:41:30.858Z [pool-5-thread-1] DEBUG o.a.s.m.s.recipients.RecipientStore - Marking 0 numbers as unregistered
2024-03-16T17:41:35.501Z [OkHttp https://svr2.signal.org/...] INFO  LibSignal - [libsignal]: rust/attest/src/enclave.rs:128: Successfully completed attested connection
2024-03-16T17:41:35.994Z [OkHttp https://svr2.signal.org/...] INFO  LibSignal - [Svr2Socket]: [onClosing] code: 1000, reason: 
2024-03-16T17:41:38.027Z [OkHttp https://svr2.signal.org/...] INFO  LibSignal - [libsignal]: rust/attest/src/enclave.rs:128: Successfully completed attested connection
2024-03-16T17:41:38.480Z [OkHttp https://svr2.signal.org/...] INFO  LibSignal - [Svr2Socket]: [onClosing] code: 1000, reason: 
2024-03-16T17:41:40.154Z [OkHttp https://svr2.signal.org/...] WARN  LibSignal - [Svr2Socket]: [onFailure] response? true
java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)

2024-03-16T17:41:40.155Z [main] WARN  LibSignal - [SecureValueRecoveryV2]: [Set] Failed with a network exception!
java.io.IOException: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at org.whispersystems.signalservice.api.svr.Svr2Socket$SvrWebSocketListener.onFailure(Svr2Socket.kt:164)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:174)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	... 7 more

2024-03-16T17:41:40.158Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-03-16T17:41:40.159Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Set pin error: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
java.io.IOException: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at org.whispersystems.signalservice.api.svr.Svr2Socket$SvrWebSocketListener.onFailure(Svr2Socket.kt:164)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:174)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	... 7 more

```

**Comment by AsamK** [comment]
Can you try with the latest development build? There was an update of libsignal-service that might fix this issue: https://github.com/AsamK/signal-cli/actions/runs/8214382663

**Comment by icacrr** [comment]
I'm not sure I'm doing it properly.
Here is what I got when I download [signal-cli-native.zip](https://github.com/AsamK/signal-cli/actions/runs/8214382663/artifacts/1311660815)

```
$ ./signal-cli --version
signal-cli 0.13.2-SNAPSHOT

```
But if I'm not wrong, I've got an exception (the same one) with both commands: register and verify.


```
$ ./signal-cli -u +4412345678 register --captcha signal-hcaptcha.XXX
java.lang.NoClassDefFoundError: java/lang/NoClassDefFoundError
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:359)
	at org.signal.libsignal.internal.Native.preloadClasses(Native Method)
	at org.signal.libsignal.internal.Native.<clinit>(Native.java:69)
	at org.asamk.signal.manager.Manager.isSignalClientAvailable(Manager.java:73)
	at org.asamk.signal.App.init(App.java:138)
	at org.asamk.signal.Main.main(Main.java:56)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

$ ./signal-cli -u +4412345678 verify XXXXXX
java.lang.NoClassDefFoundError: java/lang/NoClassDefFoundError
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:359)
	at org.signal.libsignal.internal.Native.preloadClasses(Native Method)
	at org.signal.libsignal.internal.Native.<clinit>(Native.java:69)
	at org.asamk.signal.manager.Manager.isSignalClientAvailable(Manager.java:73)
	at org.asamk.signal.App.init(App.java:138)
	at org.asamk.signal.Main.main(Main.java:56)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)



```

**Comment by AsamK** [comment]
Please retry with 0.13.2

**Comment by icacrr** [comment]
I can't go this far in the process because of [this issue](https://github.com/AsamK/signal-cli/issues/1491).
Sorry
