### ISSUE TITLE
[Issue] Exception after adding new users to chat

### ISSUE THREAD

**Issue by redradist** [AsamK/signal-cli#1516]
Hi all,

After adding to chat few users, start getting the following exception

```console
signal-cli --output=json receive --ignore-attachments --ignore-stories

java.lang.AssertionError: RecipientAddress without identifier
	at org.asamk.signal.manager.api.RecipientIdentifier$Single.fromAddress(RecipientIdentifier.java:55)
	at org.asamk.signal.json.JsonMessageEnvelope.from(JsonMessageEnvelope.java:53)
	at org.asamk.signal.json.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.java:32)
	at org.asamk.signal.manager.internal.ManagerImpl.lambda$receiveMessages$14(ManagerImpl.java:1252)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:272)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleRetryEnvelope(IncomingMessageHandler.java:124)
	at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessage(ReceiveHelper.java:275)
	at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessages(ReceiveHelper.java:257)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:129)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:104)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1250)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1222)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:86)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:278)
	at org.asamk.signal.App.handleCommand(App.java:179)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:56)
```

Is there a way to fix an issue ? How to get new addess for these added abonents ?

**Comment by k-bx** [comment]
Same, we have this error as well.

**Comment by k-bx** [comment]
Resolved by patching signal-cli like this:

```
kon@jvln:/fast/kon/workspace/signal-cli$ git diff
diff --git a/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java b/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java
index bafa97e7..98e599ac 100644
--- a/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java
+++ b/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java
@@ -45,12 +45,16 @@ public record JsonMessageEnvelope(
         final String source;
         final String sourceNumber;
         final String sourceUuid;
-        final String sourceName;
+        String sourceName;
         if (sourceAddress != null) {
             source = sourceAddress.getLegacyIdentifier();
             sourceNumber = sourceAddress.number().orElse(null);
             sourceUuid = sourceAddress.uuid().map(UUID::toString).orElse(null);
-            sourceName = m.getContactOrProfileName(RecipientIdentifier.Single.fromAddress(sourceAddress));
+           try {
+               sourceName = m.getContactOrProfileName(RecipientIdentifier.Single.fromAddress(sourceAddress));
+           } catch (java.lang.AssertionError e) {
+               sourceName = null;
+           }
         } else {
             source = null;
             sourceNumber = null;
```

**Comment by redradist** [comment]
> Resolved by patching signal-cli like this:
> 
> ```
> $ git diff
> diff --git a/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java b/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java
> index bafa97e7..98e599ac 100644
> --- a/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java
> +++ b/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java
> @@ -45,12 +45,16 @@ public record JsonMessageEnvelope(
>          final String source;
>          final String sourceNumber;
>          final String sourceUuid;
> -        final String sourceName;
> +        String sourceName;
>          if (sourceAddress != null) {
>              source = sourceAddress.getLegacyIdentifier();
>              sourceNumber = sourceAddress.number().orElse(null);
>              sourceUuid = sourceAddress.uuid().map(UUID::toString).orElse(null);
> -            sourceName = m.getContactOrProfileName(RecipientIdentifier.Single.fromAddress(sourceAddress));
> +           try {
> +               sourceName = m.getContactOrProfileName(RecipientIdentifier.Single.fromAddress(sourceAddress));
> +           } catch (java.lang.AssertionError e) {
> +               sourceName = null;
> +           }
>          } else {
>              source = null;
>              sourceNumber = null;
> ```

Have you create a PR for it ?
