### ISSUE TITLE
`remoteDelete` throws error

### ISSUE THREAD

**Issue by doobry-systemli** [AsamK/signal-cli#1518]
When trying to delete a message from a group via JSON RPC call, signal-cli throws an error:

`curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"remoteDelete","id":"as","params":{"account":"+*****","group-id":"*****","timestamp":"*****"}}' http://localhost:8080/api/v1/rpc | jq .` returns:
```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32603,
    "message": null,
    "data": null
  },
  "id": "as"
}
```

And `signal-cli` logs the following error trace:

```
ERROR SignalJsonRpcDispatcherHandler - Command execution failed
java.lang.NullPointerException: null
	at org.asamk.signal.commands.RemoteDeleteCommand.handleCommand(RemoteDeleteCommand.java:56)
	at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:25)
	at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:15)
	at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler$CommandRunnerImpl.handleCommand(SignalJsonRpcCommandHandler.java:153)
	at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.parseParamsAndRunCommand(SignalJsonRpcCommandHandler.java:272)
	at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.runCommand(SignalJsonRpcCommandHandler.java:212)
	at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.handleRequest(SignalJsonRpcCommandHandler.java:66)
	at org.asamk.signal.http.HttpServerHandler.lambda$handleRpcEndpoint$1(HttpServerHandler.java:129)
	at org.asamk.signal.jsonrpc.JsonRpcReader.handleRequest(JsonRpcReader.java:134)
	at org.asamk.signal.jsonrpc.JsonRpcReader.handleMessage(JsonRpcReader.java:85)
	at org.asamk.signal.jsonrpc.JsonRpcReader.readMessages(JsonRpcReader.java:54)
	at org.asamk.signal.http.HttpServerHandler.handleRpcEndpoint(HttpServerHandler.java:129)
	at jdk.httpserver@21.0.3/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver@21.0.3/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver@21.0.3/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
	at jdk.httpserver@21.0.3/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
	at jdk.httpserver@21.0.3/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver@21.0.3/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
	at java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
```

**Comment by AsamK** [comment]
group-id parameter needs to be in camelCase: groupId.

**Comment by AsamK** [comment]
The timestamp parameter is called `target-timestamp`

**Comment by doobry-systemli** [comment]
> The timestamp parameter is called target-timestamp

Ha, that was the culprit. Thanks so much for the pointer, I should have read the docs more carefully :see_no_evil:
