### ISSUE TITLE
"signal-cli register --reregister" has no effect.

### ISSUE THREAD

**Issue by Geremia** [AsamK/signal-cli#1545]
I installed Signal on an Android device, then I got "User +xxxxxxxxxx is not registered" with `signal-cli`. Then I tried:

    signal-cli register --reregister --captcha 'signalcaptcha://signal-hcaptcha.…'

but it had no effect. It still says:
```
$ signal-cli listDevices
User +xxxxxxxxxx is not registered.
```

**Comment by Geremia** [comment]
Now I'm getting:

```
Failed to register: StatusCode: 429 (RegistrationRetryException)
org.whispersystems.signalservice.api.push.exceptions.RegistrationRetryException: StatusCode: 429
        at org.whispersystems.signalservice.internal.push.PushServiceSocket$RegistrationCodeRequestResponseHandler.handle(PushServiceSocket.java:2997)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2169)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestVerificationCode(PushServiceSocket.java:408)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:284)
        at org.asamk.signal.manager.util.NumberVerificationUtils.requestVerificationCode(NumberVerificationUtils.java:98)
        at org.asamk.signal.manager.internal.RegistrationManagerImpl.register(RegistrationManagerImpl.java:136)
        at org.asamk.signal.commands.RegisterCommand.register(RegisterCommand.java:75)
        at org.asamk.signal.commands.RegisterCommand.handleCommand(RegisterCommand.java:51)
        at org.asamk.signal.commands.CommandHandler.handleRegistrationCommand(CommandHandler.java:31)
        at org.asamk.signal.App.handleRegistrationCommand(App.java:265)
        at org.asamk.signal.App.handleCommand(App.java:174)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:56)
```

**Comment by AsamK** [comment]
After registration you need to call the `verify` command with the verification code.
Calling the register command too many times results in a rate limiting.

**Comment by Geremia** [comment]
@AsamK  Even before the RegistrationRetryException rate-limiting exception, I was getting invalid captcha responses. This is with master (0.13.5-SNAPSHOT).
