### ISSUE TITLE
Invalid ACI in SyncMessage.readList

### ISSUE THREAD

**Issue by brad2014** [AsamK/signal-cli#1596]
I'm seeing this warning in signal-cli 0.13.6 when receiving messages.  From the error message, I cannot tell what content is invalid, what the consequences of being invalid are, and if it caused subsequent messages to be dropped.

```
WARN  IncomingMessageHandler - Invalid content! [SyncMessage] Invalid ACI in SyncMessage.readList!
java.lang.Throwable: null
	at org.whispersystems.signalservice.api.messages.EnvelopeContentValidator$Result$Invalid.<init>(EnvelopeContentValidator.kt:430)
	at org.whispersystems.signalservice.api.messages.EnvelopeContentValidator.validateSyncMessage(EnvelopeContentValidator.kt:193)
	at org.whispersystems.signalservice.api.messages.EnvelopeContentValidator.validate(EnvelopeContentValidator.kt:57)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.validate(IncomingMessageHandler.java:197)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:146)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:213)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:104)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1284)
	at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1256)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:86)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:278)
	at org.asamk.signal.App.handleCommand(App.java:179)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:56)
	at [java.base@21.0.4/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit](mailto:java.base@21.0.4/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit)(LambdaForm$DMH)
```

**Comment by AsamK** [comment]
Thanks for posting the error stack trace.
The warning is harmless. It means one of your linked devices is sending you a sync message about which messages have been read on that device. For some reason it contains an invalid recipient id (ACI). The sync message is ignored, but otherwise receiving continues normally.
