### ISSUE TITLE
Rate limit exceeded: 413 while sending direct message.

### ISSUE THREAD

**Issue by abezruchenkov** [AsamK/signal-cli#1603]
Hello everyone! I've encountered a strange issue with a 413 rate limit error, and I'm stuck. Please help! 

I was tasked with creating a Signal bot to send announcements to my colleagues. I created the bot and successfully sent the initial message via script to about 100 new contacts. Everything worked fine — no limits or captchas.

However, yesterday I tried to send a test message to myself (I was also on the list) and received a "Rate limit exceeded: 413" error from the first message. Since then, I haven't been able to send any messages. Occasionally, on some numbers, I see a captcha challenge, but after resolving it, I get the same "Rate limit exceeded: 413" error again. All contacts are marked as TRUSTED_UNVERIFIED. Below is my detailed sending log:

`signal-api@ca633098e843:/$ signal-cli -u +1234567890 -v send -m 'test message' +1234567891
2024-10-04T19:00:57.408Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2024-10-04T19:00:57.416Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.5
2024-10-04T19:00:57.490Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-10-04T19:00:57.734Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-10-04T19:00:57.815Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@1522d8a0
2024-10-04T19:00:57.817Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-10-04T19:00:59.239Z [main] WARN  LibSignal - [PhoneNumberFormatter]: Got local CC: UA
2024-10-04T19:00:59.682Z [main] INFO  LibSignal - [SignalServiceMessageSender]: [sendMessage][1728068459245] Pipe unavailable, falling back... (WebSocketUnavailableException: WebSocket not currently available.)
2024-10-04T19:00:59.821Z [main] WARN  o.a.signal.manager.helper.SendHelper - Sending failed due to rate limiting from the signal server: [413] Rate limit exceeded: 413
Failed to send (some) messages:
+380637178066: Network failure for "+1234567891"
1728068459245
2024-10-04T19:00:59.834Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-10-04T19:00:59.836Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2024-10-04T19:00:59.837Z [msl-cleanup] DEBUG o.a.s.m.s.s.MessageSendLogStore - Stopping msl cleanup thread
Failed to send message due to rate limiting
org.asamk.signal.manager.api.RateLimitException: Rate limit
	at org.asamk.signal.util.SendMessageResultUtils.outputResult(SendMessageResultUtils.java:61)
	at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:246)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:278)
	at org.asamk.signal.App.handleCommand(App.java:179)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:56)`

**Comment by jonabert** [comment]
I have similar problems, did you find a solution/workaround?

**Comment by abezruchenkov** [comment]
> I have similar problems, did you find a solution/workaround?

Nope( The only workaround we've found - to use another phone number..

**Comment by jonabert** [comment]
ok, but they reset automatically after some time, so why would you get another number?

**Comment by madrid-fran** [comment]
Hi,

I'm having the same issue with the CAPTCHA when sending the same message to multiple devices.

I'd like to continue using SIGNAL and not have to resort to other sending platforms.

What’s the exact maximum number of messages allowed before a CAPTCHA is enforced?

If the limit is exceeded, what’s the default cooldown period before sends resume without CAPTCHA?
