### ISSUE TITLE
Compliance between signal-cli and signal desktop (official)

### ISSUE THREAD

**Issue by FengJi2021** [AsamK/signal-cli#1620]
quick question. i use the config parameter like truststore, zkgroupparameter, copying from signal-desktop config.json, it gives me error. Does signal-cli stay in compilance with signal desktop configuration?

i noticed the truststore and some public parameters are different in both implementations.

`java.lang.AssertionError: Unexpected checked exception class org.signal.libsignal.zkgroup.InvalidInputException
        at org.signal.libsignal.internal.FilterExceptions.reportUnexpectedException(FilterExceptions.java:71)
        at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:115)
        at org.signal.libsignal.zkgroup.ServerPublicParams.<init>(ServerPublicParams.java:17)
        at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:31)
        at org.asamk.signal.manager.internal.ProvisioningManagerImpl.<init>(ProvisioningManagerImpl.java:80)
        at org.asamk.signal.manager.SignalAccountFiles.initProvisioningManager(SignalAccountFiles.java:143)
        at org.asamk.signal.manager.SignalAccountFiles.initProvisioningManager(SignalAccountFiles.java:139)
        at org.asamk.signal.App.handleProvisioningCommand(App.java:254)
        at org.asamk.signal.App.handleCommand(App.java:158)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:56)`

**Comment by AsamK** [comment]
signal-cli uses the same config as Signal-Android.
