### ISSUE TITLE
Verify error: StatusCode: 404

### ISSUE THREAD

**Issue by pavex** [AsamK/signal-cli#1623]
Hi,
The command keeps giving me a 404. Is it possible to find out why? Many thanks.
```
signal-cli.bat -u +000000000000 verify 123456
Verify error: StatusCode: 404
```

**Comment by AsamK** [comment]
Which signal-cli version are you using?

**Comment by AsamK** [comment]
That version should work, you can get more details with the `-vv` parameter.

**Comment by m-ueberall** [comment]
.@mv1769: See the last comment above:
> That version should work, you can get more details with the `-vv` parameter.

Those details might be essential to answer your question (don't forget to redact your phone number, etc.) …

**Comment by m-ueberall** [comment]
@mv1769 : Try `./signal-cli -vv -u PHONENUMBER verify CODE`

**Comment by mv1769** [comment]
@m-ueberall 

I get this after : 

2025-01-27T20:43:34.754+0100 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.12
2025-01-27T20:43:35.122+0100 [main] TRACE org.asamk.signal.manager.Manager - Expected exception when checking libsignal-client: Failed to deserialize zkgroup::api::groups::uuid_ciphertext::UuidCiphertext
2025-01-27T20:43:35.122+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2025-01-27T20:43:35.355+0100 [main] TRACE o.a.s.manager.storage.SignalAccount - Opening account file
2025-01-27T20:43:35.357+0100 [main] TRACE o.a.s.manager.storage.SignalAccount - Loading account file 403200
2025-01-27T20:43:35.434+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2025-01-27T20:43:35.566+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@a8c1f44
2025-01-27T20:43:35.567+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2025-01-27T20:43:35.574+0100 [main] TRACE o.a.s.m.storage.AccountDatabase - Current database version: 27 Program database version: 27
2025-01-27T20:43:36.879+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2025-01-27T20:43:36.883+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Verify error: StatusCode: 404
org.whispersystems.signalservice.api.push.exceptions.NoSuchSessionException: StatusCode: 404
	at org.whispersystems.signalservice.internal.push.PushServiceSocket$RegistrationCodeSubmissionResponseHandler.handle(PushServiceSocket.java:3352)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2371)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.submitVerificationCode(PushServiceSocket.java:455)
	at org.whispersystems.signalservice.api.registration.RegistrationApi.verifyAccount$lambda$4(RegistrationApi.kt:84)
	at org.whispersystems.signalservice.api.NetworkResult$Companion.fromFetch(NetworkResult.kt:44)
	at org.whispersystems.signalservice.api.registration.RegistrationApi.verifyAccount(RegistrationApi.kt:83)
	at org.asamk.signal.manager.internal.RegistrationManagerImpl.verifyAccountWithCode(RegistrationManagerImpl.java:264)
	at org.asamk.signal.manager.internal.RegistrationManagerImpl.lambda$verifyAccount$2(RegistrationManagerImpl.java:167)
	at org.asamk.signal.manager.util.NumberVerificationUtils.verifyNumber(NumberVerificationUtils.java:120)
	at org.asamk.signal.manager.internal.RegistrationManagerImpl.verifyAccount(RegistrationManagerImpl.java:163)
	at org.asamk.signal.commands.VerifyCommand.verify(VerifyCommand.java:71)
	at org.asamk.signal.commands.VerifyCommand.handleCommand(VerifyCommand.java:43)
	at org.asamk.signal.commands.CommandHandler.handleRegistrationCommand(CommandHandler.java:33)
	at org.asamk.signal.App.handleRegistrationCommand(App.java:268)
	at org.asamk.signal.App.handleCommand(App.java:177)
	at org.asamk.signal.App.init(App.java:147)
	at org.asamk.signal.Main.main(Main.java:56)

**Comment by mv1769** [comment]
The problem was solved when I redid the process with the captcha link (the sms had been sent too late?)! I'm moving on to the next steps, thank you very much :)
