### ISSUE TITLE
MobileCoin addresses are Base58, not Base64.

### ISSUE THREAD

**Issue by christian-oudard** [AsamK/signal-cli#1637]
I'm working with Fire Digital (https://fire.cx/, https://github.com/xederifofficial), and we're building a cryptocurrency exchange. My current project is a Signal bot to process deposits and withdrawals for MobileCoin. `signal-cli` crashes when I put in my MobileCoin wallet, due to a confusion between Base58 and Base64.

Currently, this is being handled by re-encoding Base58 addresses as Base64, but it would be convenient to have this done automatically by signal-cli.

```
$ signal-cli --mobile-coin-address=4RN98ba92FqD3u3bS63XyNMHBmCm8TVDRprF1FaHfUD9kUGtfPmE3SXAKBkEr1uB7gbFBURXRrFUjvGZyMCkHPPCcGEx9pvQodsfHBQaV7YFtfUCspSvynDfo4EGYLb2hgK7xeJGKvy49BZmfCadqLd4pULaEmtxY64XEHwW2bauEYrXhWZ4SMAELRc78ptpqBiN2VAsPd99FPXsCyV2Y6RaLd3KRRmbawaSTrxWwA9Pt9dSS

java.lang.IllegalArgumentException: Last unit does not have enough valid bits
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:872)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:570)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:593)
        at org.asamk.signal.commands.UpdateProfileCommand.handleCommand(UpdateProfileCommand.java:48)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.handleCommand(App.java:179)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:56)

$ signal-cli --version
signal-cli 0.13.9
```

**Comment by m-ueberall** [comment]
AFAIK, `--mobile-coin-address` is not a valid argument, so maybe this should be reported against a downstream project/fork?
Apart from that, why not simply convert the argument "4RN98ba92…" using `B64=$(echo '4RN98ba92…' | base58 -d | base64 -w0); signal-cli --mobile-coin-addres=${B64}`?

**Comment by AsamK** [comment]
signal-cli is using base64 for all binary data. I'm not a fan of adding an additional encoding scheme, as base58 conversion should be straight forward for signal-cli users.
