### ISSUE TITLE
signal-cli-native seems broken in 0.13.10+morph027+1

### ISSUE THREAD

**Issue by incognico** [AsamK/signal-cli#1642]
```
WARN  JobExecutor - Job RefreshRecipientsJob failed
java.lang.UnsatisfiedLinkError: org.signal.libsignal.internal.Native.LookupRequest_setReturnAcisWithoutUaks(JZ)V [symbol: Java_org_signal_libsignal_internal_Native_LookupRequest_1setReturnAcisWithoutUaks or Java_org_signal_libsignal_internal_Native_LookupRequest_1setReturnAcisWithoutUaks__JZ]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
        at org.signal.libsignal.internal.Native.LookupRequest_setReturnAcisWithoutUaks(Native Method)
        at org.signal.libsignal.net.CdsiLookupRequest$NativeRequest.<init>(CdsiLookupRequest.java:85)
        at org.signal.libsignal.net.CdsiLookupRequest.makeNative(CdsiLookupRequest.java:48)
        at org.signal.libsignal.net.CdsiLookup.start(CdsiLookup.java:19)
        at org.signal.libsignal.net.Network.cdsiLookup(Network.java:109)
        at org.whispersystems.signalservice.api.services.CdsiV2Service.lambda$new$1(CdsiV2Service.java:59)
        at org.whispersystems.signalservice.api.services.CdsiV2Service.getRegisteredUsers(CdsiV2Service.java:76)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsersWithCdsi(SignalServiceAccountManager.java:249)
        at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsersV2(RecipientHelper.java:238)
        at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsers(RecipientHelper.java:187)
        at org.asamk.signal.manager.helper.RecipientHelper.refreshUsers(RecipientHelper.java:156)
        at org.asamk.signal.manager.jobs.RefreshRecipientsJob.run(RefreshRecipientsJob.java:15)
        at org.asamk.signal.manager.internal.JobExecutor.lambda$runNextJob$0(JobExecutor.java:59)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```

Downgraded to .9 and it works again.

**Comment by morph027** [comment]
Hm, just got the same error. Weird that it was working 3 weeks for me until today :see_no_evil:

Will debug the cause later.

**Comment by morph027** [comment]
Hm, i get a little different error now on my test build when using a jsonrpc call.

```
Dec 21 19:59:18 signal-gateway signal-cli[28253]: ERROR SignalJsonRpcDispatcherHandler - Command execution failed
Dec 21 19:59:18 signal-gateway signal-cli[28253]: java.lang.UnsatisfiedLinkError: org.signal.libsignal.internal.Native.LookupRequest_setReturnAcisWithoutUaks(JZ)V [symbol: Java_org_signal_libsignal_internal_Native_LookupRequest_1setReturnAcisWithoutUaks or Java_org_signal_libsignal_internal_Native_LookupRequest_1setReturnAcisWithoutUaks__JZ]
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.signal.libsignal.internal.Native.LookupRequest_setReturnAcisWithoutUaks(Native Method)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.signal.libsignal.net.CdsiLookupRequest$NativeRequest.<init>(CdsiLookupRequest.java:85)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.signal.libsignal.net.CdsiLookupRequest.makeNative(CdsiLookupRequest.java:48)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.signal.libsignal.net.CdsiLookup.start(CdsiLookup.java:19)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.signal.libsignal.net.Network.cdsiLookup(Network.java:109)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.whispersystems.signalservice.api.services.CdsiV2Service.lambda$new$1(CdsiV2Service.java:59)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.whispersystems.signalservice.api.services.CdsiV2Service.getRegisteredUsers(CdsiV2Service.java:76)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsersWithCdsi(SignalServiceAccountManager.java:249)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsersV2(RecipientHelper.java:238)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsers(RecipientHelper.java:187)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsers(RecipientHelper.java:179)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.manager.internal.ManagerImpl.getUserStatus(ManagerImpl.java:269)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.commands.GetUserStatusCommand.handleCommand(GetUserStatusCommand.java:54)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:23)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:15)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler$CommandRunnerImpl.handleCommand(SignalJsonRpcCommandHandler.java:155)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.parseParamsAndRunCommand(SignalJsonRpcCommandHandler.java:278)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.runCommand(SignalJsonRpcCommandHandler.java:216)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.handleRequest(SignalJsonRpcCommandHandler.java:68)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.http.HttpServerHandler.lambda$handleRpcEndpoint$1(HttpServerHandler.java:129)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.jsonrpc.JsonRpcReader.handleRequest(JsonRpcReader.java:134)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.jsonrpc.JsonRpcReader.handleMessage(JsonRpcReader.java:85)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.jsonrpc.JsonRpcReader.readMessages(JsonRpcReader.java:54)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.asamk.signal.http.HttpServerHandler.handleRpcEndpoint(HttpServerHandler.java:129)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at jdk.httpserver@21.0.2/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at jdk.httpserver@21.0.2/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at jdk.httpserver@21.0.2/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at jdk.httpserver@21.0.2/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at jdk.httpserver@21.0.2/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at jdk.httpserver@21.0.2/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
Dec 21 19:59:18 signal-gateway signal-cli[28253]:         at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Dec 21 19:59:18 signal-gateway python3[28418]: Error preparing recipients: SignalCliJSONRPCError('signal-cli JSON RPC request failed: SignalCliJSONRPCError("signal-cli JSON RPC request failed: SignalCliJSONRPCError(\'org.signal.libsignal.internal.Native.LookupRequest_setReturnAcisWithoutUaks(JZ)V [symbol: Java_org_signal_libsignal_internal_Native_LookupRequest_1setReturnAcisWithoutUaks or Java_org_signal_libsignal_internal_Native_LookupRequest_1setReturnAcisWithoutUaks__JZ] (UnsatisfiedLinkError)\')")')
```

**Comment by morph027** [comment]
Some more debugging. Only happens to me when sending to a single contact. Sending to groups still works.

**Comment by AsamK** [comment]
An `UnsatisfiedLinkError` is sign, that you're not using the correct version of the libsignal-client native library.
The `setReturnAcisWithoutUaks` has been removed in libsignal-client 0.63.0 (https://github.com/signalapp/libsignal/commit/0dd5a0242f74271225f5a848db625619b0ef7e4d)
signal-cli 0.13.10 requires libsignal-client 0.62.0

**Comment by morph027** [comment]
My build script fetches the required version from the release tarball ([link](https://gitlab.com/packaging/signal-cli/-/blob/master/.gitlab-ci/build.sh?ref_type=heads#L32-47)).

```bash
+ curl -sfLo /tmp/signal-cli-0.13.10.tar.gz https://github.com/AsamK/signal-cli/releases/download/v0.13.10/signal-cli-0.13.10.tar.gz
+ tar -C /tmp -xzf /tmp/signal-cli-0.13.10.tar.gz
++ find /tmp/signal-cli-0.13.10/lib -type f -name 'libsignal-client-*.jar'
+ libsignalclient=/tmp/signal-cli-0.13.10/lib/libsignal-client-0.62.0.jar
+ '[' -z /tmp/signal-cli-0.13.10/lib/libsignal-client-0.62.0.jar ']'
+ libsignalclient_version=/tmp/signal-cli-0.13.10/lib/libsignal-client-0.62.0
+ libsignalclient_version=0.62.0
+ libsignalclient_download_url='https://gitlab.com/packaging/libsignal-client/-/jobs/artifacts/v0.62.0/raw/libsignal-client/amd64/libsignal_jni.so?job=libsignal-client-amd64'
```

So looks ike the version is correct. Will probably try another build of libsignal-client.

But thanks for the hint!

**Comment by morph027** [comment]
Ok, using 0.62 exquo/signal-libs-build works, there must be something wrong in my builds. Will craft a new christmas release later :grin:

**Comment by morph027** [comment]
New release has been published to the repo...

**Comment by morph027** [comment]
Hm, looks like i'm running into the same after a while. Will trigger another test build.
