### ISSUE TITLE
Invalid device link :  bad key length <24> for key with type <Djb>

### ISSUE THREAD

**Issue by mdubit** [AsamK/signal-cli#1652]
Hi,

I am trying to add **signal-desktop** as a new device with signal-cli. After having serched for similar problems on the list, I tested, in vain, to escape or unescape unquote the uri provided by the qrcode. 

Unfortunately, I always have a similar message:

```
@L-PERSON-800:~/signal$ ./signal-cli --verbose -u +32xxxxxxx85 addDevice --uri 'sgnl://linkdevice?uuid=Sq87jQT7Es1S_XYwDTIpiw%3D%3D&pub_key=BZ3dG4S39zD80%2FcqIN%2FohqYV64xes830'

2024-12-13T14:34:40.381+0100 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.10
2024-12-13T14:34:40.487+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-12-13T14:34:40.494+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-12-13T14:34:40.544+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@712d7542
2024-12-13T14:34:40.544+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-12-13T14:34:41.232+0100 [main] INFO  o.a.signal.commands.AddDeviceCommand - Invalid device link
2024-12-13T14:34:41.232+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-12-13T14:34:41.232+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Invalid device link
org.asamk.signal.manager.api.InvalidDeviceLinkException: Invalid device link
        at org.asamk.signal.manager.api.DeviceLinkUrl.parseDeviceLinkUri(DeviceLinkUrl.java:42)
        at org.asamk.signal.commands.AddDeviceCommand.handleCommand(AddDeviceCommand.java:53)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:37)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.handleCommand(App.java:179)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:56)
        at java.base@21.0.5/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: org.signal.libsignal.protocol.InvalidKeyException: bad key length <24> for key with type <Djb>
        at org.signal.libsignal.internal.Native.ECPublicKey_Deserialize(Native Method)
        at org.signal.libsignal.protocol.ecc.ECPublicKey.lambda$new$0(ECPublicKey.java:22)
        at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:165)
        at org.signal.libsignal.protocol.ecc.ECPublicKey.<init>(ECPublicKey.java:21)
        at org.signal.libsignal.protocol.ecc.Curve.decodePoint(Curve.java:24)
        at org.asamk.signal.manager.api.DeviceLinkUrl.parseDeviceLinkUri(DeviceLinkUrl.java:40)
        ... 7 more

```

I tried to have other QRcode without % in the URI, but it seems all uuid end with == nowadays.
It also seems to be a protocol issue: teh bad key length (the pub_key) seems to be the problem. But is it not a response from the signal server ?

My OS is Ubunutu24.4, I have the 0.13.10 version of signal-cli and the shell is bash

Can you point to some directions ?

Other than that, I can use signal-cli with the CLI client scli without problem.  Great software, man! Thanks!

**Comment by mdubit** [comment]
I noticed the decoding of the QRcode made online didn't return the right result. For som reason, the '&capabilities=' part was missing. Problem fixed.
