### ISSUE TITLE
UnsatisfiedLinkError on aarm64

### ISSUE THREAD

**Issue by stephkno** [AsamK/signal-cli#1656]
I'm trying to install on a Raspberry Pi 4/Raspbian. I'm following the instructions on the wiki: downloading the aarm64 build of libsignal and zipping it in `libsignal-client-0.13.10.jar`, and overriding `java.library.path`. I'm getting an `UnsatisfiedLinkError` when I try to send messages. How can I get `org.signal.libsignal.internal.Native` working with aarm64?

signal-cli version: 0.13.10
libsignal version: 0.64.1 (from [signal-libs-build](https://github.com/exquo/signal-libs-build/))
OS: Debian GNU/Linux 12 (bookworm)
JDK: openjdk 21.0.5 2024-10-15 LTS / OpenJDK Runtime Environment Zulu21.38+21-CA (build 21.0.5+11-LTS)

~~~
$ signal-cli --verbose -u "+user_number" send -m "test" "+recipient_number"
2024-12-24T05:17:36.166Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.10
2024-12-24T05:17:37.981Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-12-24T05:17:40.448Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-12-24T05:17:41.337Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@2bef51f2
2024-12-24T05:17:41.349Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-12-24T05:17:50.819Z [main] DEBUG o.a.s.manager.internal.JobExecutor - Running RefreshRecipientsJob job
2024-12-24T05:17:50.864Z [pool-2-thread-1] DEBUG o.a.s.manager.helper.RecipientHelper - No new numbers to query.
2024-12-24T05:17:50.869Z [pool-2-thread-1] DEBUG o.a.s.m.s.recipients.RecipientStore - Marking 0 numbers as unregistered
2024-12-24T05:17:50.872Z [pool-2-thread-1] DEBUG o.a.s.m.s.recipients.RecipientStore - Marking 0 numbers as discoverable
2024-12-24T05:17:50.953Z [main] WARN  LibSignal - [PhoneNumberFormatter]: Got local CC: US
2024-12-24T05:17:51.005Z [main] WARN  o.a.s.manager.internal.ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name with the updateProfile command. This may become mandatory in the future.
2024-12-24T05:17:51.239Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-12-24T05:17:51.252Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
java.lang.UnsatisfiedLinkError: 'void org.signal.libsignal.internal.Native.LookupRequest_setReturnAcisWithoutUaks(long, boolean)'
	at org.signal.libsignal.internal.Native.LookupRequest_setReturnAcisWithoutUaks(Native Method)
	at org.signal.libsignal.net.CdsiLookupRequest$NativeRequest.<init>(CdsiLookupRequest.java:85)
	at org.signal.libsignal.net.CdsiLookupRequest.makeNative(CdsiLookupRequest.java:48)
	at org.signal.libsignal.net.CdsiLookup.start(CdsiLookup.java:19)
	at org.signal.libsignal.net.Network.cdsiLookup(Network.java:109)
	at org.whispersystems.signalservice.api.services.CdsiV2Service.lambda$new$1(CdsiV2Service.java:59)
	at org.whispersystems.signalservice.api.services.CdsiV2Service.getRegisteredUsers(CdsiV2Service.java:76)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsersWithCdsi(SignalServiceAccountManager.java:249)
	at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsersV2(RecipientHelper.java:238)
	at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsers(RecipientHelper.java:187)
	at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUserByNumber(RecipientHelper.java:204)
	at org.asamk.signal.manager.helper.RecipientHelper.lambda$resolveRecipient$0(RecipientHelper.java:87)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientByNumber(RecipientStore.java:221)
	at org.asamk.signal.manager.helper.RecipientHelper.resolveRecipient(RecipientHelper.java:85)
	at org.asamk.signal.manager.internal.ManagerImpl.sendMessage(ManagerImpl.java:636)
	at org.asamk.signal.manager.internal.ManagerImpl.sendMessage(ManagerImpl.java:612)
	at org.asamk.signal.manager.internal.ManagerImpl.sendMessage(ManagerImpl.java:747)
	at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:247)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:37)
	at org.asamk.signal.App.handleLocalCommand(App.java:278)
	at org.asamk.signal.App.handleCommand(App.java:179)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:56)
~~~

**Comment by m-ueberall** [comment]
The above is somewhat related to [this comment](https://github.com/AsamK/signal-cli/issues/1642#issuecomment-2559239307); you need to make sure to pair the right versions of `libsignal` and `signal-cli` – for `signal-cli` version **0.13.10**, that would be version **0.62.0** of `libsignal`.

**Comment by stephkno** [comment]
Fixed, thanks!
