### ISSUE TITLE
java.lang.NoClassDefFoundError: org/freedesktop/dbus/exceptions/DBusException

### ISSUE THREAD

**Issue by axapta** [AsamK/signal-cli#167]
I want to use getGroupIds() via dbus. Since there was not a new version since the merge of #102 I followed https://github.com/AsamK/signal-cli#building to compile a private version myself. The build succeeds but when I run it I get the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/freedesktop/dbus/exceptions/DBusException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
        at java.lang.Class.getMethod0(Class.java:2866)
        at java.lang.Class.getMethod(Class.java:1676)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.freedesktop.dbus.exceptions.DBusException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        ... 6 more
``` 

The last official build works however.

**Comment by AsamK** [comment]
Does it work if you run it like this?
```sh
gradle installDist
build/install/signal-cli/bin/signal-cli -u +XXX receive
```

**Comment by axapta** [comment]
On the machine where I compiled `signal-cli` everything seems to work fine. However I am trying to run it at another machine. I wasn't successful compiling `signal-cli` at the target machine due to dependency problems. However the official builds work at this target machine. Unfortunately my unofficial versions of `v0.6.0` or `bdffcff` result in the error above.

**Comment by AsamK** [comment]
I guess some files weren't copied over.
You can create a tar archive that you can easily copy to the other machine:
`./gradlew distTar`
This creates the following tar file, which contains all required binary files:
`build/distributions/signal-cli-0.6.0.tar`

**Comment by axapta** [comment]
That is how I already tried it out. I copied the `signal-cli-0.6.0.tar` file to the target machine and installed it as it is described in https://github.com/AsamK/signal-cli#install-system-wide-on-linux

**Comment by axapta** [comment]
I did a `pkgdiff` between the last official version and my compiled version at `86f5c99`. It said that `signal-cli-0.6.0.jar` differs a little bit. However when I did a `pkgdiff` between the two different `signal-cli-0.6.0.jar` files it said there were the same.

Could you tell me how I could further investigate the issue?

**Comment by axapta** [comment]
What java version do you use to compile the releases @AsamK? I believe that I tried out `java-10-openjdk`, `java-11-openjdk`, `java-7-openjdk` and `java-8-openjdk`. (`java-11-openjdk` failed)

**Comment by AsamK** [comment]
I think I used java-8-openjdk for building the last release.
I also tested the latest master with java-11-openjdk and it compiles and runs just fine.

I honestly don't know, what could be causing the issue.

**Comment by axapta** [comment]
hm. Could you do a new release preferably with `java-8-openjdk` so I could at least use the new `getGroupIds()` feature?

**Comment by axapta** [comment]
Thank you. The new release #170 works. :-)

**Comment by axapta** [comment]
For the actual issue it might be interesting to investigate the following non fatal error that appears in the beginning of starting up `signal-cli` before the first messages arrive:

```
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.asamk.signal.manager.Utils.loadEnvelope(Utils.java:138)
        at org.asamk.signal.manager.Manager.retryFailedReceivedMessages(Manager.java:948)
        at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:979)
        at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:61)
        at org.asamk.signal.Main.handleCommands(Main.java:115)
        at org.asamk.signal.Main.main(Main.java:50)
```

happens in `0.6.1` as well as `0.6.0` and probably in older versions too

**Comment by AsamK** [comment]
Looks like a corrupted message got cached and signal-cli tries to decrypt it at every startup ... but this is an unrelated issue.
