### ISSUE TITLE
NullPointerException during "signal-cli -u +NUMBER receive"

### ISSUE THREAD

**Issue by ventz** [AsamK/signal-cli#191]
Getting:

```
Received a sync message
Received sync message with block list
Blocked numbers:

java.lang.NullPointerException
	at org.asamk.signal.manager.Manager.handleMessage(Manager.java:1152)
	at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1020)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:100)
	at org.asamk.signal.Main.handleCommands(Main.java:115)
	at org.asamk.signal.Main.main(Main.java:50)
```

While trying to sync contacts.

It ends up syncing down just a few contacts (of many), and a few groups.

**Comment by AsamK** [comment]
Thanks for the report, should be fixed on master branch now.

**Comment by ventz** [comment]
@AsamK Awesome - thank you!!

**Comment by Daywalker01** [comment]
I am experiencing the same issue with the current version

```
# signal-cli -u +1234567890 receive --ignore-attachments
Exception in thread "main" java.lang.NullPointerException
        at org.whispersystems.signalservice.api.push.SignalServiceAddress.matches(SignalServiceAddress.java:87)
        at org.asamk.signal.storage.contacts.JsonContactsStore.getContact(JsonContactsStore.java:29)
        at org.asamk.signal.manager.Manager.handleSignalServiceDataMessage(Manager.java:1283)
        at org.asamk.signal.manager.Manager.handleMessage(Manager.java:1554)
        at org.asamk.signal.manager.Manager.retryFailedReceivedMessage(Manager.java:1380)
        at org.asamk.signal.manager.Manager.retryFailedReceivedMessages(Manager.java:1347)
        at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1399)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:160)
        at org.asamk.signal.Main.handleCommands(Main.java:184)
        at org.asamk.signal.Main.handleCommands(Main.java:135)
        at org.asamk.signal.Main.main(Main.java:65)
```
Ubuntu 20.04.1 LTS
openjdk-14-jre-headless:amd64        14.0.2+12-1~20.04
signal-cli v0.6.12

writing messages works perfectly
But not all groups show up
new v2 groups (I only have one) don't seem to show up?

**Comment by AsamK** [comment]
It's an unrelated issue, next time please create a new issue if the stack trace is different ... NullPointerExceptions are not very specific. I've pushed a fix for this to the master branch.
v2 groups will be supported in the next version.
