### ISSUE TITLE
`java.security.InvalidKeyException: Illegal key size` on device being linked during provisioning

### ISSUE THREAD

**Issue by funkybunch** [AsamK/signal-cli#250]
Upon making an attempt to [provision a new device](https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)) I receive this Java error:
```java
Failed to send/receive message (Assertion): java.security.InvalidKeyException: Illegal key size
java.lang.AssertionError: java.security.InvalidKeyException: Illegal key size
	at org.whispersystems.signalservice.internal.crypto.ProvisioningCipher.decrypt(ProvisioningCipher.java:118)
	at org.whispersystems.signalservice.internal.crypto.ProvisioningCipher.decrypt(ProvisioningCipher.java:102)
	at org.whispersystems.signalservice.internal.push.ProvisioningSocket.getProvisioningMessage(ProvisioningSocket.java:51)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.finishNewDeviceRegistration(SignalServiceAccountManager.java:431)
	at org.asamk.signal.manager.Manager.finishDeviceLink(Manager.java:298)
	at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:31)
	at org.asamk.signal.Main.handleCommands(Main.java:126)
	at org.asamk.signal.Main.main(Main.java:61)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.whispersystems.signalservice.internal.crypto.ProvisioningCipher.decrypt(ProvisioningCipher.java:115)
	... 7 more
If you use an Oracle JRE please check if you have unlimited strength crypto enabled, see README
```

Linking failed on the master device but no error was produced.  It is worth noting that the device being linked is running Mac OS rather than a Linux OS.  Master device is Debian-based.

**Comment by funkybunch** [comment]
Local version of Java needed to have the unlimited strength policy file installed.  Existing file turned out to be the limited strength file.

### For others trying to resolve:
**Unlimited Security Policies Download**
https://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Installation of new policies**
https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters
Installation location: `${$JAVA_HOME}/jre/lib/security/`

Make sure you save a backup copy of the existing policies that you'll be replacing just in case things go south.
