### ISSUE TITLE
java.lang.UnsupportedClassVersionError error on macOS

### ISSUE THREAD

**Issue by adekbadek** [AsamK/signal-cli#26]
Hi, I'm getting the following error when executing `./signal-cli`:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/asamk/signal/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

I'm on macOS El Capitan 10.11.5, Java version: Java 8 update 101

**Comment by AsamK** [comment]
This seems to be a problem with your java setup. Class version 51.0 is created by java 7, which should be executed by java 8 without issues. This issue should only appear if you try to run signal-cli with java 6 or earlier. Run `java -version` to see which java version you're running.
See also:
https://stackoverflow.com/questions/12757558/installed-java-7-on-mac-os-x-but-terminal-is-still-using-version-6

**Comment by adekbadek** [comment]
I was wrong - my Java as seen in the Java Control Panel was v.8, but the one used in the terminal was v.6. I downloaded the latest from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html and now it works. Didn't know such version mismatch was possible.
