### ISSUE TITLE
Cannot link to device

### ISSUE THREAD

**Issue by anders-dc** [AsamK/signal-cli#28]
I tried to link `signal-cli` to my iOS client using the pre-built version 0.5.0 release as well as the latest commit on Github which I built using the `gradle` instructions. `signal-cli` generates a *tsdevice:/...* link, but when I scan the qr-encoded barcode on the iOS device, `signal-cli` crashes with the following output (uuid removed):

```
$ signal-cli link -n "laptop"
tsdevice:/?uuid=[REDACTED]
Exception in thread "main" java.lang.AssertionError: java.security.InvalidKeyException: Illegal key size
        at org.whispersystems.signalservice.internal.crypto.ProvisioningCipher.decrypt(ProvisioningCipher.java:118)
        at org.whispersystems.signalservice.internal.crypto.ProvisioningCipher.decrypt(ProvisioningCipher.java:102)
        at org.whispersystems.signalservice.internal.push.ProvisioningSocket.getProvisioningMessage(ProvisioningSocket.java:45)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.finishNewDeviceRegistration(SignalServiceAccountManager.java:376)
        at org.asamk.signal.Manager.finishDeviceLink(Manager.java:373)
        at org.asamk.signal.Main.handleCommands(Main.java:172)
        at org.asamk.signal.Main.main(Main.java:67)
Caused by: java.security.InvalidKeyException: Illegal key size
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
        at javax.crypto.Cipher.implInit(Cipher.java:805)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
        at javax.crypto.Cipher.init(Cipher.java:1396)
        at javax.crypto.Cipher.init(Cipher.java:1327)
        at org.whispersystems.signalservice.internal.crypto.ProvisioningCipher.decrypt(ProvisioningCipher.java:115)
        ... 6 more
```

Please let me know if you need any additional information.

**Comment by AsamK** [comment]
Probably a duplicate of #2 
If you're using the oracle jdk, you need to install "export jurisdiction policy file". Howto:

https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters

**Comment by anders-dc** [comment]
Thanks for the input! I now receive a different error in the linking process. I am running Oracle Java 8.

```
$ signal-cli link -n "laptop"
tsdevice:/?uuid=[REDACTED]
org.whispersystems.libsignal.InvalidKeyException: Bad key type: 230
        at org.whispersystems.libsignal.ecc.Curve.decodePoint(Curve.java:52)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.finishNewDeviceRegistration(SignalServiceAccountManager.java:379)
        at org.asamk.signal.Manager.finishDeviceLink(Manager.java:373)
        at org.asamk.signal.Main.handleCommands(Main.java:172)
        at org.asamk.signal.Main.main(Main.java:67)
```

**Comment by AsamK** [comment]
I debugged this, and it seems the iOS app sends the public key without the type information, that the Android app expects.
I added a workaround for this (https://github.com/AsamK/libsignal-service-java/commit/24680ee328f54caf269094a5258ce7e1865b9471) but I don't have an iOS device to test if it works.

**Comment by anders-dc** [comment]
Awesome, works like a charm! Thanks!
