### ISSUE TITLE
Failed to send/receive message (Assertion): com.google.protobuf.InvalidProtocolBufferException: Failed to parse the message

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#282]
Everytime I do a receive I get this after a few messages:
```
Failed to send/receive message (Assertion): com.google.protobuf.InvalidProtocolBufferException: Failed to parse the message.
java.lang.AssertionError: com.google.protobuf.InvalidProtocolBufferException: Failed to parse the message.
        at org.asamk.signal.storage.protocol.JsonSessionStore.loadSession(JsonSessionStore.java:44)
        at org.asamk.signal.storage.protocol.JsonSignalProtocolStore.loadSession(JsonSignalProtocolStore.java:118)
        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:242)
        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:211)
        at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:189)
        at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:131)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:190)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:138)
        at org.asamk.signal.manager.Manager.decryptMessage(Manager.java:1233)
        at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1461)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:93)
        at org.asamk.signal.Main.handleCommands(Main.java:130)
        at org.asamk.signal.Main.main(Main.java:59)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Failed to parse the message.
        at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1565)
        at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1654)
        at org.whispersystems.libsignal.state.StorageProtos$RecordStructure.parseFrom(StorageProtos.java:4602)
        at org.whispersystems.libsignal.state.SessionRecord.<init>(SessionRecord.java:39)
        at org.asamk.signal.storage.protocol.JsonSessionStore.loadSession(JsonSessionStore.java:39)
        ... 12 more
If you use an Oracle JRE please check if you have unlimited strength crypto enabled, see README
```

**Comment by AsamK** [comment]
does it still happen with the latest release?

**Comment by Trolldemorted** [comment]
Looks good, thanks a lot!
