### ISSUE TITLE
signal-cli always crashes (java.lang.IllegalArgumentException: Empty key)

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#294]
```
PS C:\Users\Benni\repositories\signal-cli> signal-receive                                                                                                                                                                                               Exception in thread "main" java.lang.IllegalArgumentException: Empty key
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
        at org.whispersystems.libsignal.ratchet.ChainKey.getBaseMaterial(ChainKey.java:57)
        at org.whispersystems.libsignal.ratchet.ChainKey.getMessageKeys(ChainKey.java:47)
        at org.whispersystems.libsignal.SessionCipher.encrypt(SessionCipher.java:97)
        at org.signal.libsignal.metadata.SealedSessionCipher.encrypt(SealedSessionCipher.java:70)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:86)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1456)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1406)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1276)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:206)
        at org.asamk.signal.manager.Manager.sendReceipt(Manager.java:686)
        at org.asamk.signal.manager.Manager.handleMessage(Manager.java:1562)
        at org.asamk.signal.manager.Manager.retryFailedReceivedMessage(Manager.java:1447)
        at org.asamk.signal.manager.Manager.retryFailedReceivedMessages(Manager.java:1414)
        at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1459)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:160)
        at org.asamk.signal.Main.handleCommands(Main.java:137)
        at org.asamk.signal.Main.main(Main.java:60)
```

**Comment by Trolldemorted** [comment]
Anything I can do to work around this issue? I haven't been able to receive a single message for 2 weeks :|

**Comment by AsamK** [comment]
I don't know what exactlydata path is going wrong here, but according to the stack trace, it's failing when retrying failed messages, so you could try to remove the message cache with failed messages.
That's the `data/+XXX.d/msg-cache` folder in the signal-cli data path.

**Comment by Trolldemorted** [comment]
Did that, it was able to receive a handful of messages, but it started hanging after this exception:
```
Envelope from: ?me? +49176xxxxx462 (device: 13)
Timestamp: 1587475515687 (2020-04-21T13:25:15.687Z)
Sender: ?Benedikt Radtke? +49176xxxxx462 (device: 13)
Received a sync message
Received sync read messages list
From: ?null? +4917yyyyy348 Message timestamp: 1587474958386 (2020-04-21T13:15:58.386Z)

Exception in thread "main" java.lang.IllegalArgumentException: Empty key
        at java.base/javax.crypto.spec.SecretKeySpec.<init>(Unknown Source)
        at org.whispersystems.libsignal.ratchet.ChainKey.getBaseMaterial(ChainKey.java:57)
        at org.whispersystems.libsignal.ratchet.ChainKey.getMessageKeys(ChainKey.java:47)
        at org.whispersystems.libsignal.SessionCipher.encrypt(SessionCipher.java:97)
        at org.signal.libsignal.metadata.SealedSessionCipher.encrypt(SealedSessionCipher.java:70)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:86)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1456)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1406)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1276)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:206)
        at org.asamk.signal.manager.Manager.sendReceipt(Manager.java:686)
        at org.asamk.signal.manager.Manager.handleMessage(Manager.java:1562)
        at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1496)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:160)
        at org.asamk.signal.Main.handleCommands(Main.java:137)
        at org.asamk.signal.Main.main(Main.java:60)
```

**Comment by AsamK** [comment]
Looks like somehow the session state became corrupted. Unfortunately the sender is not printed, because of the exception.
I just pushed two commits that should help resolve the issue.
The first one should keep continuing with handling received messages after the exception. It will still print the exception, but the first printed message after the stack trace will be the one with the broken session state.
The second commit should allow you to reset that session, by sending a message with `--endsession` to that sender.

**Comment by Trolldemorted** [comment]
Thanks!

It received a handful of messages, and then hang after this stack trace:
```
Exception in thread "main" java.lang.IllegalStateException: No session for (+49176XXXXX462:1)!
        at org.whispersystems.libsignal.SessionCipher.getSessionVersion(SessionCipher.java:334)
        at org.signal.libsignal.metadata.SealedSessionCipher.getSessionVersion(SealedSessionCipher.java:152)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:85)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1456)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1406)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1276)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1250)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:306)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1194)
        at org.asamk.signal.manager.Manager.sendMessageLegacy(Manager.java:1148)
        at org.asamk.signal.manager.Manager.sendUpdateGroupMessage(Manager.java:643)
        at org.asamk.signal.manager.Manager.handleSignalServiceDataMessage(Manager.java:1333)
        at org.asamk.signal.manager.Manager.handleMessage(Manager.java:1576)
        at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1504)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:160)
        at org.asamk.signal.Main.handleCommands(Main.java:137)
        at org.asamk.signal.Main.main(Main.java:60)
```

`+49176XXXXX462:1` should be signal-cli itself, that's my phone number and signal-cli is the master device 🤔

**Comment by Trolldemorted** [comment]
the `endsession` command also prints this stacktrace:
```
PS C:\Users\Benni\repositories\signal-cli> signal send +49176XXXXX242 --endsession
Exception in thread "main" java.lang.IllegalArgumentException: Empty key
        at java.base/javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
        at org.whispersystems.libsignal.ratchet.ChainKey.getBaseMaterial(ChainKey.java:57)
        at org.whispersystems.libsignal.ratchet.ChainKey.getMessageKeys(ChainKey.java:47)
        at org.whispersystems.libsignal.SessionCipher.encrypt(SessionCipher.java:97)
        at org.signal.libsignal.metadata.SealedSessionCipher.encrypt(SealedSessionCipher.java:70)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:86)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1456)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1406)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1276)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:268)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1238)
        at org.asamk.signal.manager.Manager.sendMessageLegacy(Manager.java:1148)
        at org.asamk.signal.manager.Manager.sendEndSessionMessage(Manager.java:737)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:66)
        at org.asamk.signal.Main.handleCommands(Main.java:139)
        at org.asamk.signal.Main.main(Main.java:60)
```

**Comment by AsamK** [comment]
I missed a save call here (87f65de0c56735397fd6f68e77d6fe5cc915675d), please retry `endsession` with the current master.
The first `endsession` command should still print the same stack trace, but afterwards sending messages to that number should work again.

**Comment by Trolldemorted** [comment]
Thanks!
