### ISSUE TITLE
Fails to launch with KeyError: 'active'

### ISSUE THREAD

**Issue by jthvai** [AsamK/signal-cli#295]
As the title says, `scli` fails to launch with the following output:
```
Traceback (most recent call last):
  File "/usr/bin/scli", line 1656, in <module>
    main()
  File "/usr/bin/scli", line 1640, in main
    window = MainWindow(state)
  File "/usr/bin/scli", line 1157, in __init__
    self._wleft = LeftWindow(self.state)
  File "/usr/bin/scli", line 907, in __init__
    self._wcontacts = ContactsWindow(self.state)
  File "/usr/bin/scli", line 793, in __init__
    self.set_contacts(self.state.signal.get_all_contacts())
  File "/usr/bin/scli", line 771, in get_all_contacts
    xs.extend(self.groups())
  File "/usr/bin/scli", line 754, in groups
    return list(filter(lambda a: bool(a['active']),
  File "/usr/bin/scli", line 754, in <lambda>
    return list(filter(lambda a: bool(a['active']),
KeyError: 'active'
```
OS: Arch Linux (Updated), running [this version of scli from the AUR](https://aur.archlinux.org/packages/scli-git/).

**Comment by jthvai** [comment]
Just realised I posted on the wrong repository.
