### ISSUE TITLE
Cannot add Signal Desktop as device

### ISSUE THREAD

**Issue by RalfJung** [AsamK/signal-cli#303]
I would like to use signal-cli + Signal-Desktop to be able to use a number I have on a "dump phone" with Signal. To this end, I started with the steps described [in the README](https://github.com/AsamK/signal-cli#usage), and that is working fine -- I can send messages to other people with signal-cli. That's pretty awesome. :)

Now I want to link that account to Signal-Desktop.  So I scanned the QR code shown by Signal-Desktop and decoded the URI and ran:
```
signal-cli -u +49XXXX addDevice --uri 'tsdevice:/?uuid=YYYY&pub_key=ZZZZ'
```
However, this ends in an exception:
```
org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1109)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1062)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendProvisioningMessage(PushServiceSocket.java:311)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.addDevice(SignalServiceAccountManager.java:693)
        at org.asamk.signal.manager.Manager.addDevice(Manager.java:392)
        at org.asamk.signal.manager.Manager.addDeviceLink(Manager.java:385)
        at org.asamk.signal.commands.AddDeviceCommand.handleCommand(AddDeviceCommand.java:31)
        at org.asamk.signal.Main.handleCommands(Main.java:137)
        at org.asamk.signal.Main.main(Main.java:60)
```
Am I using `addDevice` wrong, or is this feature broken, or is there some other issue here?

**Comment by AsamK** [comment]
The tsdevice URI is only valid for a short amount of time, maybe the link has expired before your called the `addDevice` command.

**Comment by RalfJung** [comment]
Indeed I just tried again and this time it worked. Sorry for that, and thanks a lot again for this tool. :)
