### ISSUE TITLE
signal-cli trust throws exception and waits for a long time period

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#304]
```
PS C:\Users\Benni> signal-cli -u +49176XXXXXX462 trust -a +491573YYYYY55
Exception in thread "main" java.lang.IllegalArgumentException: Empty key
        at java.base/javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
        at org.whispersystems.libsignal.ratchet.ChainKey.getBaseMaterial(ChainKey.java:57)
        at org.whispersystems.libsignal.ratchet.ChainKey.getMessageKeys(ChainKey.java:47)
        at org.whispersystems.libsignal.SessionCipher.encrypt(SessionCipher.java:97)
        at org.signal.libsignal.metadata.SealedSessionCipher.encrypt(SealedSessionCipher.java:70)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:86)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1456)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1406)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1276)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:512)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:353)
        at org.asamk.signal.manager.Manager.sendSyncMessage(Manager.java:1134)
        at org.asamk.signal.manager.Manager.sendVerifiedMessage(Manager.java:1935)
        at org.asamk.signal.manager.Manager.trustIdentityAllKeys(Manager.java:2031)
        at org.asamk.signal.commands.TrustCommand.handleCommand(TrustCommand.java:38)
        at org.asamk.signal.Main.handleCommands(Main.java:137)
        at org.asamk.signal.Main.main(Main.java:60)
```

It did terminate eventually, but it took a while. The exception was printed immediately, tough.

**Comment by AsamK** [comment]
Seems to be the same broken session as in #294
The delay probably comes from the message pipe not being closed, so java waits for the websocket thread to end.

**Comment by Trolldemorted** [comment]
Nice, thanks!
