### ISSUE TITLE
removeContact command

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#335]
Is it possible to delete / remove a contact with signal-cli?

I don't know whether the signal servers themselves support this. Maybe one is supposed to 'archive' conversations instead?

However, there might still be a use-case for this functionality in signal-cli: since the `updateContact` command can create contacts locally, it would be good to be able to delete them locally before they are synced to the signal servers. 
If, for example, one mistypes a contact's phone number when attempting to create a new contact using `updateContact`, there seems to be no way to 'undo' the creation of a wrong-numbered contact.

Related question: is it safe to manually delete a contact's entry from signal-cli's data file? (`~/.local/share/signal-cli/data/+XXXXXXXXXXX`) And to manually edit that file in general?

**Comment by AsamK** [comment]
Removing a contact is currently not implemented.

In general editing the data file is safe, if signal-cli is not running and you know what you are doing. Removing contacts from the contactStore should not be a problem.

**Comment by exquo** [comment]
Thank you for the info!

Then I'm leaving this open as a feature request (unless, of course, you think it shouldn't be).

**Comment by JtheSaw** [comment]
Hey @AsamK 

Is this FR still on your roadmap? 

My project has the requirement to be able to remove a contacts data. I tried this a couple of times while the daemon (v.0.9.2) was stopped. After each time I restarted the daemon and wrote a message from the deleted contacts number to the daemons number.

Deleting the users object inside `recipients-store` JSON results in:
```
Exception in thread "Thread-2" java.lang.NullPointerException
2021-11-24T07:39:10.908683104Z 	at org.asamk.signal.manager.storage.recipients.Recipient.newBuilder(Recipient.java:51)
2021-11-24T07:39:10.909148267Z 	at org.asamk.signal.manager.storage.recipients.RecipientStore.storeProfile(RecipientStore.java:247)
2021-11-24T07:39:10.913157959Z 	at org.asamk.signal.manager.helper.ProfileHelper.getRecipientProfile(ProfileHelper.java:199)
2021-11-24T07:39:10.913186693Z 	at org.asamk.signal.manager.helper.ProfileHelper.getRecipientProfile(ProfileHelper.java:67)
2021-11-24T07:39:10.913725691Z 	at org.asamk.signal.manager.ManagerImpl.getRecipientProfile(ManagerImpl.java:476)
2021-11-24T07:39:10.914255535Z 	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:146)
2021-11-24T07:39:10.914624063Z 	at org.asamk.signal.manager.ManagerImpl.receiveMessagesInternal(ManagerImpl.java:1062)
2021-11-24T07:39:10.918331015Z 	at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$8(ManagerImpl.java:898)
2021-11-24T07:39:10.919109017Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

Sometimes restarting the service a second time helps to be able to contact the daemon again. But sometimes I first get this message after the second restart:
```
WARN ManagerImpl - Message action failed.
2021-11-24T07:47:41.335059493Z org.whispersystems.signalservice.api.push.exceptions.RateLimitException: [413] Rate limit exceeded: 413
2021-11-24T07:47:41.335942025Z 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1692)
2021-11-24T07:47:41.335965348Z 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1682)
2021-11-24T07:47:41.336449859Z 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1666)
2021-11-24T07:47:41.336893613Z 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1655)
2021-11-24T07:47:41.337269880Z 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1592)
2021-11-24T07:47:41.337637554Z 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1586)
2021-11-24T07:47:41.338052129Z 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:611)
2021-11-24T07:47:41.338655265Z 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2108)
2021-11-24T07:47:41.339445841Z 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2083)
2021-11-24T07:47:41.339490903Z 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1721)
2021-11-24T07:47:41.339868586Z 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendNullMessage(SignalServiceMessageSender.java:766)
2021-11-24T07:47:41.340417150Z 	at org.asamk.signal.manager.helper.SendHelper.sendNullMessage(SendHelper.java:185)
2021-11-24T07:47:41.340438574Z 	at org.asamk.signal.manager.actions.RenewSessionAction.execute(RenewSessionAction.java:18)
2021-11-24T07:47:41.340442999Z 	at org.asamk.signal.manager.ManagerImpl.handleQueuedActions(ManagerImpl.java:1107)
2021-11-24T07:47:41.341060541Z 	at org.asamk.signal.manager.ManagerImpl.receiveMessagesInternal(ManagerImpl.java:1022)
2021-11-24T07:47:41.341578195Z 	at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$8(ManagerImpl.java:898)
```


and then after sending a message from the deleted number:
```
Envelope from: unknown source
2021-11-24T07:49:41.399189008Z Timestamp: 1637740180756 (2021-11-24T07:49:40.756Z)
2021-11-24T07:49:41.399834256Z Sent by unidentified/sealed sender
2021-11-24T07:49:41.400511634Z Exception: org.whispersystems.libsignal.InvalidMessageException: invalid message Message decryption failed (ProtocolInvalidMessageException)
2021-11-24T07:49:41.402384137Z No message content
```

It would be awesome if there was a possibility to reliably delete a contacts data and maybe even while the cli is running.

**Comment by JtheSaw** [comment]
Cool, looking forward for this feature 👍🏼 

The --forget flag is exactly what I am looking for.

**Comment by JtheSaw** [comment]
I played around with deleting a contacts files. These are my results:

- `avatars/contact-<phone>` => ✅   Can be deleted
- `avatars/profile-<phone>` => ✅  Can be deleted
- `identities/<id>` => ✅  Can be deleted
- `sessions/<id>` =>  ❌  Throws `java.lang.NullPointerException` after restarting and receiving a message from deleted number
- `recipients-store` => ❗️ Everything from the accounts object can be deleted except `id` and `uuid`

You can find out about the contacts `id` inside `recipients-store` file.

If you restart the daemon and a message from the deleted number is received all the files you deleted are recreated without an error.

I suppose that deleted data stays in memory as long as the daemon is not restarted though.
