### ISSUE TITLE
java.lang.UnsatisfiedLinkError in v0.6.9

### ISSUE THREAD

**Issue by harmtemolder** [AsamK/signal-cli#344]
`signal-cli link` works as expected in v0.6.8 but results in this error in v0.6.9:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no zkgroup in java.library.path: [/Users/harmtemolder/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1907)
	at org.signal.zkgroup.internal.Native.<clinit>(Native.java:37)
	at org.signal.zkgroup.ServerPublicParams.<init>(ServerPublicParams.java:22)
	at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:26)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.<init>(SignalServiceAccountManager.java:136)
	at org.asamk.signal.manager.ProvisioningManager.<init>(ProvisioningManager.java:54)
	at org.asamk.signal.Main.handleCommands(Main.java:109)
	at org.asamk.signal.Main.main(Main.java:65)
```

(Running on macOS 10.15.6)

Please let me know what information I can provide to further investigate.

**Comment by AsamK** [comment]
zkgroup is a dependency of libsignal-service-java, and it looks like the zkgroup jar just contains a linux version of the required native library (libzkgroup.so).
Looks like you'll have to build the native lib yourself ...
https://github.com/signalapp/zkgroup

**Comment by harmtemolder** [comment]
OK, I'll do that for v0.6.9. What could be the reason that it does work for v0.6.8?

**Comment by AsamK** [comment]
v0.6.8 used an older version of libsignal-service-java which didn't use zkgroup yet, or at least not in the SignalServiceAccountManager. 
zkgroup is required for the new group v2 feature (aka zero knowledge groups), which aren't supported by signal-cli yet ... but I'm also not very eager to patch them out of libsignal either.

**Comment by yaodongpo** [comment]
> https://github.com/signalapp/zkgroup

damm
