### ISSUE TITLE
Bug in Version 0.6.9?

### ISSUE THREAD

**Issue by git00x** [AsamK/signal-cli#350]
When I open Signal Messanger on my Smartphone. 
Sending with 'signal-cli -u + xx send -m "test" + xx' does not work.
I have the problem with version 0.6.9, version 0.6.8 is OK.

**Comment by no2spc** [comment]
I second this problem:
when running 
```
./signal-cli -u + xx send -m "test" + xx':
Error loading state file: C:\cygwin64\tmp\resource11891628710604216768.so: %1 ist keine zulässige Win32-Anwendung
```
and linking a new client:
```
$ ./signal-cli link -n "LinkMember"
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\cygwin64\tmp\resou
rce6887313092394858748.so: %1 ist keine zulässige Win32-Anwendung
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2
452)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader
.java:2508)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
        at java.base/java.lang.Runtime.load0(Runtime.java:745)
        at java.base/java.lang.System.load(System.java:1871)
        at org.signal.zkgroup.internal.Native.copyToTempFileAndLoad(Native.java:
56)
        at org.signal.zkgroup.internal.Native.<clinit>(Native.java:35)
        at org.signal.zkgroup.ServerPublicParams.<init>(ServerPublicParams.java:
22)
        at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.crea
te(ClientZkOperations.java:26)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.<ini
t>(SignalServiceAccountManager.java:136)
        at org.asamk.signal.manager.ProvisioningManager.<init>(ProvisioningManag
er.java:54)
        at org.asamk.signal.Main.handleCommands(Main.java:109)
        at org.asamk.signal.Main.main(Main.java:65)

```

javac 14.0.2, Windows 10, executed on a Cygwin bash: 
CYGWIN_NT-10.0 COMPUTERNAME 3.1.6(0.340/5/3) 2020-07-09 08:20 x86_64 Cygwin

The signal-cli (version 0.6.8.) works on the same system.

**Comment by AsamK** [comment]
Related to #344
libzkgroup now requires a native library, but only provides it for linux x86_64 ...
