### ISSUE TITLE
Uncaught exception in main

### ISSUE THREAD

**Issue by troublescooter** [AsamK/signal-cli#359]
Since upgrading to the latest signal-cli release yesterday, I've been experiencing the following exception. It's the third time so far, sometimes it's fine.
```
Exception in thread "main" java.lang.IllegalStateException: value is absent
        at org.whispersystems.libsignal.util.guava.Absent.get(Absent.java:39)
        at org.asamk.signal.ReceiveMessageHandler.handleSignalServiceDataMessage(ReceiveMessageHandler.java:335)
        at org.asamk.signal.ReceiveMessageHandler.handleMessage(ReceiveMessageHandler.java:83)
        at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1508)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:160)
        at org.asamk.signal.Main.handleCommands(Main.java:184)
        at org.asamk.signal.Main.handleCommands(Main.java:135)
        at org.asamk.signal.Main.main(Main.java:65)
```

**Comment by Riamse** [comment]
I'm having the same issue. It reliably happens when someone emoji-reacts to a message.

**Comment by troublescooter** [comment]
Can't confirm that's the case on my end. At least some emoji-reactions seem to be fine.

**Comment by troublescooter** [comment]
Non a transient issue, occurred again.

**Comment by centromere** [comment]
This is happening for me also, same stack trace.

**Comment by AsamK** [comment]
Looks, like there are now senders with only UUIDs, and without phone number, those weren't handled correctly by signal-cli.
Can you verify if it works correctly again with the latest master?

**Comment by troublescooter** [comment]
No issues so far.

**Comment by Riamse** [comment]
Is it possible to push a new release out for this bug?

**Comment by AsamK** [comment]
I just published a new release with the fix:
https://github.com/AsamK/signal-cli/releases/tag/v0.6.11
