### ISSUE TITLE
DBus errors on FreeBSD

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#363]
Originally reported here: isamert/scli#86

Non-dbus commands (`signal-cli -u +Username send ...`) work on FreeBSD, but starting the daemon fails:

```
bsd:~/bin % signal-cli -u +Username daemon
```

```
org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus: No such file or directory
	at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:166)
	at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:334)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:149)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:169)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:228)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:184)
	at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:51)
	at org.asamk.signal.Main.handleCommands(Main.java:181)
	at org.asamk.signal.Main.handleCommands(Main.java:132)
	at org.asamk.signal.Main.main(Main.java:64)
Caused by: java.io.IOException: No such file or directory
	at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:130)
	at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:139)
	at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:68)
	at org.freedesktop.dbus.connections.transports.UnixSocketTransport.connect(UnixSocketTransport.java:59)
	at org.freedesktop.dbus.connections.transports.TransportFactory.createTransport(TransportFactory.java:44)
	at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:161)
	... 9 more
```

Steps to solve the issue by setting up a `DBUS_SESSION_BUS_ADDRESS` variable are described in a blog post [here](https://antranigv.am/weblog_en/posts/freebsd-signal-cli-scli/).

This might be a more general issue with dbus on FreeBSD, rather then an issue specifically with signal-cli, but I've thought I'd report it here since `v0.6.9` [release notes](https://github.com/AsamK/signal-cli/releases/tag/v0.6.9) say "dbus functionality now works on FreeBSD". Maybe there should be a (workaround?) solution in signal-cli, or perhaps this should be reported as a bug to FreeBSD.

**Comment by stevelord** [comment]
I'm having the exact same errors on OpenBSD 6.8 and a git clone build from source via gradle. I'm not quite sure how to debug this as there's a lot of moving parts and bits of java flying around.

**Comment by exquo** [comment]
Try setting the `$DBUS_SESSION_BUS_ADDRESS` environment variable (see [DBus troubleshooting](https://github.com/AsamK/signal-cli/wiki/DBus-service#user-content-troubleshooting) on the wiki).

**Comment by stevelord** [comment]
Sorry, I should've made it clear that this was set already. I've reverted to 0.6.7 and found an interesting error:

> Missing native library dependency for dbus service: no unix-java in java.library.path: [/usr/lib, /usr/local/lib]

I've followed this rabbit hole a little and found that unix-java appears to be a reference to [libmatthew-java](http://www.matthew.ath.cx/projects/java/), a collection of utilities long-since abandoned. One of these is libunix-java. It's 4 disparate helpers in a single bundle and I'm struggling to build it.

It seems to me that given that libmatthew-java is unmaintained, would it make sense to integrate the relevant functionality into signal-cli? This way the depedency would be gone and it should always work.

**Comment by distefam** [comment]
I am having a similar issue. I've followed the instructions in the wiki and exported `DBUS_SESSION_BUS_ADDRESS` but when I run `signal-cli daemon` I get the following error:

```
org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus: Unsupported transport type: 'unix
```

This is interesting as it seems that the issue is that it's unable to connect via the unix transport. Sounds like a relevant library might be lacking?

**Comment by AsamK** [comment]
I've updated signal-cli to use the hypfview dbus-java 4.0 beta, which uses native java unix sockets, that should resolve at least some dbus issues.
If you still have issues with dbus, please open an issue on the [dbus-java project](https://github.com/hypfvieh/dbus-java)
If there are some known workarounds or additional steps, feel free to add it to the wiki: https://github.com/AsamK/signal-cli/wiki/DBus-service
