### ISSUE TITLE
Error while trying to add device (linking Signal Desktop to signal-cli)

### ISSUE THREAD

**Issue by chrabaszcz** [AsamK/signal-cli#369]
I'm trying to use Signal without a smartphone (intending to link Signal Desktop v1.37.3 to signal-cli 0.6.11). I'm running signal-cli on Ubuntu 18.04.

I have successfully registered my number and scanned the QR produced by Signal Desktop to generated the device number. However, when I run the following command:

`signal-cli -u MYNUMBER addDevice --uri "tsdevice:/?uuid=REDACTED`

I get the following error message:

`org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1449)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1434)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1419)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1357)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1333)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendProvisioningMessage(PushServiceSocket.java:354)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.addDevice(SignalServiceAccountManager.java:700)
	at org.asamk.signal.manager.Manager.addDevice(Manager.java:350)
	at org.asamk.signal.manager.Manager.addDeviceLink(Manager.java:343)
	at org.asamk.signal.commands.AddDeviceCommand.handleCommand(AddDeviceCommand.java:31)
	at org.asamk.signal.Main.handleCommands(Main.java:184)
	at org.asamk.signal.Main.handleCommands(Main.java:135)
	at org.asamk.signal.Main.main(Main.java:65)
`

I'm completely at a loss here...

**Comment by AsamK** [comment]
the QR code generated by Signal Desktop is only valid for a short amount of time, looks like it expired before you executed the addDevice command.
