### ISSUE TITLE
Exception when receiving new messages

### ISSUE THREAD

**Issue by centromere** [AsamK/signal-cli#375]
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.signal.zkgroup.internal.Native
	at org.signal.zkgroup.groups.GroupSecretParams.deriveFromMasterKey(GroupSecretParams.java:48)
	at org.asamk.signal.manager.Manager.handleSignalServiceDataMessage(Manager.java:1315)
	at org.asamk.signal.manager.Manager.handleMessage(Manager.java:1637)
	at org.asamk.signal.manager.Manager.retryFailedReceivedMessage(Manager.java:1463)
	at org.asamk.signal.manager.Manager.retryFailedReceivedMessages(Manager.java:1430)
	at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1482)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:160)
	at org.asamk.signal.Main.handleCommands(Main.java:184)
	at org.asamk.signal.Main.handleCommands(Main.java:135)
	at org.asamk.signal.Main.main(Main.java:65)
```

```
commit 6a1b7dc5975161f59fbb1012dd340c7b6e0198f7 (HEAD -> master, origin/master, origin/HEAD)
Author: AsamK <asamk@gmx.de>
Date:   Sun Nov 22 19:47:10 2020 +0100

    Implement support for sending/receiving Group V2 messages
    
    Requires libzkgroup to work, which is currently only included for x86_64 Linux
    
    Related #354
```

FreeBSD 12.1-RELEASE

**Comment by AsamK** [comment]
For the v2 groups the native libzkgroup is now required, see also: https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal

**Comment by centromere** [comment]
Thank you!
