### ISSUE TITLE
updateProfile: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Atomic-Bean** [AsamK/signal-cli#378]
When I run updateProfile (With both name and avatar fields due to #377) I get the following error
```java
signal-cli -u +XXXXXXXXX updateProfile --name cli2 --avatar file.jpg
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.signal.zkgroup.internal.Native
	at org.signal.zkgroup.profiles.ProfileKey.getProfileKeyVersion(ProfileKey.java:47)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.setVersionedProfile(SignalServiceAccountManager.java:730)
	at org.asamk.signal.manager.Manager.setProfile(Manager.java:324)
	at org.asamk.signal.commands.UpdateProfileCommand.handleCommand(UpdateProfileCommand.java:44)
	at org.asamk.signal.Main.handleCommands(Main.java:184)
	at org.asamk.signal.Main.handleCommands(Main.java:135)
	at org.asamk.signal.Main.main(Main.java:65)
```

I am running the latest master. Seems to be similar to #375 since it also complains about "zkgroup" not found.

I think something needs to be added to the readme/wiki stating zkgroup must be installed first for it to work right and a short guide on how to set it up (Since issue #344 says to go [here](https://github.com/signalapp/zkgroup), but running `gradlew build` throws an error over some Android variables)

**Comment by AsamK** [comment]
yeah, updating the profile now also requires libzkgroup

**Comment by Atomic-Bean** [comment]
Ok, I'll close this issue since its pretty much a duplicate of other ones.
