### ISSUE TITLE
Malformed input when receiving messages

### ISSUE THREAD

**Issue by Atomic-Bean** [AsamK/signal-cli#384]
I've changed between multiple versions of signal-cli, and in the process my account has become a bit bugged. Every time I run a receive command I see this error
```
java.io.UTFDataFormatException: malformed input around byte 549
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:639)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569)
	at org.asamk.signal.manager.Utils.loadEnvelope(Utils.java:171)
	at org.asamk.signal.manager.Manager.retryFailedReceivedMessage(Manager.java:1690)
	at org.asamk.signal.manager.Manager.retryFailedReceivedMessages(Manager.java:1670)
	at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1738)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:167)
	at org.asamk.signal.Main.handleCommands(Main.java:185)
	at org.asamk.signal.Main.handleCommands(Main.java:136)
	at org.asamk.signal.Main.main(Main.java:65)
```
Fortunately it is still followed by my new messages.

I assume this error occurs because I was sent a message at some point, but because I was changing versions it can't be read anymore and hence we can't tell the servers that I've read it.

I've run `updateAccount`, but I still get this output. I then tried to remove my device (The computer I use signal-cli on is the master device) with `removeDevice`, but I get this error
```
org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1447)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1435)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1420)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1362)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1338)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.removeDevice(PushServiceSocket.java:356)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.removeDevice(SignalServiceAccountManager.java:704)
	at org.asamk.signal.manager.Manager.removeLinkedDevices(Manager.java:394)
	at org.asamk.signal.commands.RemoveDeviceCommand.handleCommand(RemoveDeviceCommand.java:28)
	at org.asamk.signal.Main.handleCommands(Main.java:185)
	at org.asamk.signal.Main.handleCommands(Main.java:136)
	at org.asamk.signal.Main.main(Main.java:65)
```

I've also tried re-cloning and re-building signal-cli, but I can't get it to revert to a clean slate.

**Comment by AsamK** [comment]
Yeah this could happen if you switch between versions, to fix it, you can remove the cached messages, which were received, but couldn't be decrypted:

> ~/.local/share/signal-cli/data/+xxxx.d/msg-cache

**Comment by Atomic-Bean** [comment]
> Yeah this could happen if you switch between versions, to fix it, you can remove the cached messages, which were received, but couldn't be decrypted:
> 
> > ~/.local/share/signal-cli/data/+xxxx.d/msg-cache

That fixed it. Thanks :)

**Comment by Atomic-Bean** [comment]
I am wondering though, do you know why the authorization failed when trying to remove a device? Its odd because this is the master device, but I can't remove it or the slave device.

**Comment by AsamK** [comment]
no, that's strange, removing slave devices still works for me.

**Comment by Atomic-Bean** [comment]
I realised late yesterday that my cli wasn't actually master, it was slave to my android phone. I'm not sure why I thought it was master, but that explains it.
