### ISSUE TITLE
IncompatibleClassChangeError ECPublicKey

### ISSUE THREAD

**Issue by mhkhung** [AsamK/signal-cli#395]
I am getting an error when trying to verify..
I traced it down to two different versions of org.whispersystems.libsignal.ecc.ECPublicKey:

ECPublicKey is an interface - it's used by signal-cli 
https://github.com/signalapp/libsignal-protocol-java/blob/master/java/src/main/java/org/whispersystems/libsignal/ecc/ECPublicKey.java

ECPublicKey is a class - It's used by libsignal-service-java
```
    api 'org.whispersystems:signal-client-java:0.1.4'
```
https://github.com/signalapp/libsignal-client/blob/master/java/java/src/main/java/org/whispersystems/libsignal/ecc/ECPublicKey.java

Any idea how to fix it?

```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.whispersystems.libsignal.ecc.ECPublicKey, but class was expected
	at org.whispersystems.signalservice.internal.push.PreKeyEntity$ECPublicKeySerializer.serialize(PreKeyEntity.java:54)
	at org.whispersystems.signalservice.internal.push.PreKeyEntity$ECPublicKeySerializer.serialize(PreKeyEntity.java:51)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3220)
	at org.whispersystems.signalservice.internal.util.JsonUtil.toJson(JsonUtil.java:41)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.registerPreKeys(PushServiceSocket.java:473)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.setPreKeys(SignalServiceAccountManager.java:326)
	at org.asamk.signal.manager.Manager.refreshPreKeys(Manager.java:512)
	at org.asamk.signal.manager.Manager.verifyAccount(Manager.java:492)
	at org.asamk.signal.commands.VerifyCommand.handleCommand(VerifyCommand.java:28)
	at org.asamk.signal.Main.handleCommands(Main.java:201)
	at org.asamk.signal.Main.handleCommands(Main.java:152)
	at org.asamk.signal.Main.main(Main.java:67)
```

**Comment by mhkhung** [comment]
It works when I branched off from https://github.com/Turasa/libsignal-service-java/commit/dd63afb6178c88169cf5bd3820e84f082491274d and build that library (and replace the jar in signal-cli)
