### ISSUE TITLE
I can't get the native libzkgroup to be found

### ISSUE THREAD

**Issue by CactiChameleon9** [AsamK/signal-cli#406]
I have followed the instructions [here](https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal) with removing the file using the zip command. I then downloaded the aarch64 libzkgroup.so from the android.zip [here](https://github.com/signalapp/zkgroup/releases/tag/v0.7.1), and I put it in /usr/lib (which was in my java path) and I tried changing the path as suggested and neither work.

Every time I try to start it I still get `[main] WARN org.asamk.signal.Main - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup`

Am I doing something wrong?
I am on a raspberry pi 4 running dietpi OS (based of raspberry OS) 
With the following java version:
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode)
```
And my signal-cli is running as root (just for testing) and I am linked as a slave

Also when I try to recieve I get this error:
```
[main] WARN org.asamk.signal.Main - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.signal.zkgroup.internal.Native
        at org.signal.zkgroup.groups.GroupSecretParams.deriveFromMasterKey(GroupSecretParams.java:48)
        at org.asamk.signal.manager.groups.GroupUtils.getGroupIdV2(GroupUtils.java:54)
        at org.asamk.signal.manager.storage.groups.JsonGroupStore.getGroup(JsonGroupStore.java:83)
        at org.asamk.signal.manager.storage.groups.JsonGroupStore.getOrCreateGroupV1(JsonGroupStore.java:129)
        at org.asamk.signal.manager.Manager.handleMessage(Manager.java:2136)
        at org.asamk.signal.manager.Manager.retryFailedReceivedMessage(Manager.java:1913)
        at org.asamk.signal.manager.Manager.retryFailedReceivedMessages(Manager.java:1878)
        at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1938)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:167)
        at org.asamk.signal.Main.handleCommands(Main.java:196)
        at org.asamk.signal.Main.init(Main.java:127)
        at org.asamk.signal.Main.main(Main.java:67)
```

**Comment by AsamK** [comment]
I don't think the android library will work on the raspberry pi, because android is not using gnu libc.
You'll have to build it yourself.

**Comment by CactiChameleon9** [comment]
OK, that makes sense
Thanks!

**Comment by Atomic-Bean** [comment]
Thanks for posting about this. I have updated the instructions to make it clearer Pis need to compile the lib files manually and added instructions to help people do so.
