### ISSUE TITLE
Cannot addDevice

### ISSUE THREAD

**Issue by Yumekui** [AsamK/signal-cli#43]
got this error when i tried to add my `Signal-Desktop` client to `signal-cli`:

```
signal-cli -u "[REDACTED]" addDevice --uri "tsdevice:/?uuid=[REDACTED]&pub_key=[REDACTED]"
org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:512)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendProvisioningMessage(PushServiceSocket.java:167)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.addDevice(SignalServiceAccountManager.java:411)
	at org.asamk.signal.Manager.addDevice(Manager.java:438)
	at org.asamk.signal.Manager.addDeviceLink(Manager.java:431)
	at org.asamk.signal.Main.handleCommands(Main.java:202)
	at org.asamk.signal.Main.main(Main.java:68)
```

**Comment by Yumekui** [comment]
apparently the issue was that i was on the staging server, sorry.

**Comment by thirs** [comment]
Could someone please explain how to avoid this?
