### ISSUE TITLE
On Thursday I started receiving Failed to send message: Unable to parse entity on updateGroup with a new member

### ISSUE THREAD

**Issue by pafarago** [AsamK/signal-cli#437]
Ubuntu 18.04 LTS signal-cli-0.6.5 executable download

signal-cli --config .sigbot --username +19999999999 updateGroup -g Km+wQdd0o1ecfXsajt2sSQ== -m +18888888888
20

signal-cli --config .sigbot --username +19999999999 updateGroup -n "New group" -m +18888888888
20
Bothe return Failed to send message: Unable to parse entity

All other commands appear to work 

End of strace -k on the -g version about

clone(child_stack=0x7fce8c6a2fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fce8c6a39d0, tls=0x7fce8c6a3700, child_tidptr=0x7fce8c6a39d0) = 16706
 > /lib/x86_64-linux-gnu/libc-2.27.so(clone+0x31) [0x121a31]
 > /usr/lib/jvm/java-11-openjdk-amd64/lib/jli/libjli.so(JLI_GetStdArgc+0xc37) [0xa0a7]
 > /usr/lib/jvm/java-11-openjdk-amd64/lib/jli/libjli.so(JLI_AddArgsFromEnvVar+0x2d22) [0x6682]
 > /usr/lib/jvm/java-11-openjdk-amd64/lib/jli/libjli.so(JLI_Launch+0x157d) [0x7e0d]
 > /usr/lib/jvm/java-11-openjdk-amd64/bin/java(_init+0x203) [0xb73]
 > /lib/x86_64-linux-gnu/libc-2.27.so(__libc_start_main+0xe7) [0x21b97]
 > /usr/lib/jvm/java-11-openjdk-amd64/bin/java(_init+0x2aa) [0xc1a]
futex(0x7fce8c6a39d0, FUTEX_WAIT, 16706, NULLFailed to send message: Unable to parse entity
) = ?

**Comment by AsamK** [comment]
I just released a new version 0.7.3, that has a `--verbose` flag. Can you retry with that maybe it gives more information on the issue.

**Comment by pafarago** [comment]
Thank you for your response, Here is the verbose output. The 429 error looks promising. 

root@cvsnserver:/var/www/html# /opt/signal-cli-0.7.3/bin/signal-cli --verbose --config .sigbot --username +1804xxxxxxx updateGroup -n "Test 7.3" -m +1804yyyyyyy
2021-01-17T10:20:08.820-0500 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: US
2021-01-17T10:20:13.000-0500 [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-01-17T10:20:13.011-0500 [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-01-17T10:20:13.035-0500 [main] WARN LibSignal - [CascadingFuture]: java.io.IOException: No connection!
        at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:195)
        at org.whispersystems.signalservice.api.SignalServiceMessagePipe.getProfile(SignalServiceMessagePipe.java:258)
        at org.asamk.signal.manager.helper.ProfileHelper.getPipeRetrievalFuture(ProfileHelper.java:99)
        at org.asamk.signal.manager.helper.ProfileHelper.lambda$retrieveProfile$5(ProfileHelper.java:79)
        at org.whispersystems.signalservice.internal.util.concurrent.CascadingFuture.doNext(CascadingFuture.java:69)
        at org.whispersystems.signalservice.internal.util.concurrent.CascadingFuture.<init>(CascadingFuture.java:33)
        at org.asamk.signal.manager.helper.ProfileHelper.retrieveProfile(ProfileHelper.java:79)
        at org.asamk.signal.manager.helper.ProfileHelper.retrieveProfileSync(ProfileHelper.java:49)
        at org.asamk.signal.manager.Manager.getRecipientProfile(Manager.java:510)
        at org.asamk.signal.manager.helper.UnidentifiedAccessHelper.getTargetUnidentifiedAccessKey(UnidentifiedAccessHelper.java:49)
        at org.asamk.signal.manager.helper.UnidentifiedAccessHelper.getAccessFor(UnidentifiedAccessHelper.java:83)
        at org.asamk.signal.manager.helper.ProfileHelper.getUnidentifiedAccess(ProfileHelper.java:134)
        at org.asamk.signal.manager.helper.ProfileHelper.retrieveProfile(ProfileHelper.java:66)
        at org.asamk.signal.manager.helper.ProfileHelper.retrieveProfileSync(ProfileHelper.java:49)
        at org.asamk.signal.manager.Manager.getRecipientProfileKeyCredential(Manager.java:536)
        at org.asamk.signal.manager.helper.GroupHelper.buildNewGroupV2(GroupHelper.java:147)
        at org.asamk.signal.manager.helper.GroupHelper.createGroupV2(GroupHelper.java:106)
        at org.asamk.signal.manager.Manager.sendUpdateGroupMessage(Manager.java:684)
        at org.asamk.signal.manager.Manager.updateGroup(Manager.java:671)
        at org.asamk.signal.dbus.DbusSignalImpl.updateGroup(DbusSignalImpl.java:231)
        at org.asamk.signal.commands.UpdateGroupCommand.handleCommand(UpdateGroupCommand.java:59)
        at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:14)
        at org.asamk.signal.App.handleLocalCommand(App.java:209)
        at org.asamk.signal.App.init(App.java:165)
        at org.asamk.signal.Main.main(Main.java:43)

2021-01-17T10:20:13.151-0500 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
2021-01-17T10:20:13.158-0500 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
2021-01-17T10:20:13.303-0500 [main] WARN org.asamk.signal.manager.helper.GroupHelper - Cannot create a V2 group as self does not have a versioned profile
2021-01-17T10:20:13.319-0500 [main] WARN LibSignal - [PushServiceSocket]: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 429
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1477)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1435)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1420)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1362)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1338)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.retrieveDirectory(PushServiceSocket.java:770)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getContacts(SignalServiceAccountManager.java:384)
        at org.asamk.signal.manager.Manager.updateGroupV1(Manager.java:776)
        at org.asamk.signal.manager.Manager.sendUpdateGroupMessage(Manager.java:690)
        at org.asamk.signal.manager.Manager.updateGroup(Manager.java:671)
        at org.asamk.signal.dbus.DbusSignalImpl.updateGroup(DbusSignalImpl.java:231)
        at org.asamk.signal.commands.UpdateGroupCommand.handleCommand(UpdateGroupCommand.java:59)
        at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:14)
        at org.asamk.signal.App.handleLocalCommand(App.java:209)
        at org.asamk.signal.App.init(App.java:165)
        at org.asamk.signal.Main.main(Main.java:43)

Failed to send message: Unable to parse entity
2021-01-17T10:20:13.320-0500 [main] INFO LibSignal - [WebSocketConnection]: disconnect()
2021-01-17T10:20:13.322-0500 [main] INFO LibSignal - [WebSocketConnection]: disconnect()
2021-01-17T10:20:13.332-0500 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onClosing()
2021-01-17T10:20:13.332-0500 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onClose()
2021-01-17T10:20:13.336-0500 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onClosing()
2021-01-17T10:20:13.336-0500 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onClose()

**Comment by AsamK** [comment]
Ah, it's trying to create a v1 group, because your account doesn't have a profile. You can set one with `updateProfile` then it should create a v2 group.

Now the issue with creating the v1 group indeed seems to be the 429 error. Looks like the same error as #415 caused by the old contact discovery `SignalServiceAccountManager.getContacts` ...
