### ISSUE TITLE
Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by pepo-ec** [AsamK/signal-cli#461]
I am using OpenJDK-16 and when try to use signal-cli receive this message:

**/opt/signal-cli/0.7.4/bin/signal-cli**

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

**Comment by AsamK** [comment]
it would seem you're running java 8 ...
```
Java 13 = 57 (0x39 hex)
Java 12 = 56 (0x38 hex)
Java 11 = 55 (0x37 hex)
Java 10 = 54 (0x36 hex)
Java 9 = 53 (0x35 hex)
Java 8 = 52 (0x34 hex)
```

**Comment by Geremia** [comment]
@AsamK I tried with Java 16, and I still get the same issue.

**Comment by parthadc9** [comment]
LinkageError occurred while loading main class org.asamk.signal.Main
	java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode)

**Comment by AsamK** [comment]
the latest signal-cli version requires java 17

**Comment by avsaase** [comment]
Hi, I get the same error but when run `java --version` it shows I'm running version 17:
```
java 17.0.3.1 2022-04-22 LTS
Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)
```
Any idea what I could do to fix this?

**Comment by avsaase** [comment]
My bad, I didn't have the `JAVA_HOME` environment variable set correctly.

**Comment by yjeanrenaud** [comment]
same here.
```
java -version
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Debian-1deb12u1, mixed mode, sharing)
```

**Comment by yjeanrenaud** [comment]
well, I am running in a VM, so no SSSE3 which conflicts with the native one. But thank you for pointing out the jre version. I missed that.

**Comment by m-ueberall** [comment]
For the record, there are also a number of [third-party binary builds](https://github.com/AsamK/signal-cli/wiki/Binary-distributions) that target older systems. For example,
```
% elfx86exts ./signal-cli0131_ubuntu2004_amd64 
File format and CPU architecture: Elf, X86_64
MODE64 (call)
SSE1 (prefetchnta)
CMOV (cmove)
SSE2 (cvtsi2sd)
MMX (pmaxsw)
NOT64BITMODE (xchg)
Instruction set extensions used: CMOV, MMX, MODE64, NOT64BITMODE, SSE1, SSE2
CPU Generation: Unknown
```
