### ISSUE TITLE
Can join particular group, but it still throws an error

### ISSUE THREAD

**Issue by Atomic-Bean** [AsamK/signal-cli#488]
There is a group with group invites turned on, but also only admins can add new members (To be clear, the invite link has no approval enabled, it should just automatically go through). I ran the command to join this group using the group invite link and signal-cli gave the following output.

```
org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeStorageRequestResponse(PushServiceSocket.java:1712)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeStorageRequest(PushServiceSocket.java:1657)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.patchGroupsV2Group(PushServiceSocket.java:2107)
	at org.whispersystems.signalservice.api.groupsv2.GroupsV2Api.patchGroup(GroupsV2Api.java:167)
	at org.asamk.signal.manager.helper.GroupHelper.commitChange(GroupHelper.java:365)
	at org.asamk.signal.manager.helper.GroupHelper.joinGroup(GroupHelper.java:285)
	at org.asamk.signal.manager.Manager.sendJoinGroupMessage(Manager.java:865)
	at org.asamk.signal.manager.Manager.joinGroup(Manager.java:857)
	at org.asamk.signal.commands.JoinGroupCommand.handleCommand(JoinGroupCommand.java:49)
	at org.asamk.signal.App.handleLocalCommand(App.java:206)
	at org.asamk.signal.App.init(App.java:164)
	at org.asamk.signal.Main.main(Main.java:43)
Failed to send message: Authorization failed!
```

Strangely, it did actually let me join the group (I can see it in `listGroups` and `receive`). Also future calls to join the group give the same response (Instead of `"Failed to join group, maybe already a member"`).

I am using the latest build and have both zkgroup and libsignal_jni setup.

**Comment by AsamK** [comment]
strange, I just tested it with a group and it worked ...

**Comment by Atomic-Bean** [comment]
> strange, I just tested it with a group and it worked ...

Must be the particular group I am in...the only other thing of note is that I've never seen most of its members before and the group has a profile picture. Its also a V2 group.

**Comment by AsamK** [comment]
Did this happen again, or can the issue be closed?

**Comment by Atomic-Bean** [comment]
I haven't tried again, but I'm willing to bet its just a me issue so I think its fine to close the issue.
