### ISSUE TITLE
Reply to group

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#490]
So I know I have to supply a groupid to the dbus sendGroupMessage command like this 12,34,56 etc.

But how can I dynamically convert the groupid received from onMessageReceived to that format in Python3?

I tried this:
```
def msgRcv (timestamp, source, groupID, message, attachments):
    signal.sendGroupMessage("Test", [], [','.join(map(str, groupID))])
    return

bus = SystemBus()
loop = GLib.MainLoop()

signal = bus.get('org.asamk.Signal')

signal.onMessageReceived = msgRcv
loop.run()
```

But then I get:

> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.7/site-packages/pydbus/subscription.py", line 52, in <lambda>
>     callback = (lambda con, sender, object, iface, signal, params: signal_fired(sender, object, iface, signal, params.unpack())) if signal_fired is not None else lambda *args: None
>   File "/home/pi/.local/lib/python3.7/site-packages/pydbus/proxy_signal.py", line 15, in signal_fired
>     callback(*params)
>   File "PythonScripts/SignalBot.py", line 35, in msgRcv
>     signal.sendGroupMessage("Test", [], [','.join(map(str, groupID))])
>   File "/home/pi/.local/lib/python3.7/site-packages/pydbus/proxy_method.py", line 74, in __call__
>     self._iface_name, self.__name__, GLib.Variant(self._sinargs, args), GLib.VariantType.new(self._soutargs),
>   File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 172, in __new__
>     v = creator._create(format_string, value)
>   File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 150, in _create
>     builder.add_value(self._create(dup, i))
>   File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 145, in _create
>     builder.add_value(self._create(element_type, i))
>   File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 118, in _create
>     return self._LEAF_CONSTRUCTORS[format](value)
> TypeError: Must be number, not str

**Comment by Tsjippy** [comment]
Found it myself:

```
array= []
for i in base64.b64decode(str.encode(groupid)):
    array.append(i)
    
signal.sendGroupMessage("test", [], array)
```
