### ISSUE TITLE
"Authorization failed" errors

### ISSUE THREAD

**Issue by Larx** [AsamK/signal-cli#518]
I have several numbers registered with signal-cli. I use the dockerized version bbernhard/signal-cli-rest-api, but as the problem also exists when I use the command line within this container, the problem seems not to be container-related.

The accounts worked fine for several months. One account is for Homeassistant, other accounts are linked to signal-desktop instances for "smartphone-less users". All accounts can still send and receive messages. However, I now tried to update the accounts in order to be able to use the new groups. The first time I directly interacted with signal-cli since I set up the accounts. But I always get the error:

ERROR App - Error while checking account +xxxx: Authorization failed!
 
Am I missing something, or why can't I modify the accounts any longer with signal-cli?

**Comment by sttehh** [comment]
I guess i have a similar error, When setting up a new account i first run into the captcha needed error. When at least , getting the code with the captcha process, i am not able to verify.

Verify error: Authorization failed!

**Comment by Larx** [comment]
I have one account I only use for Homeassistant which I somehow was able to access again after several attempts.
Two other accounts which are used "real persons" with a coupled desktop instance of Signal are no longer accessible to me. I only realized that when I tried to fiddle around with this accounts in order to get them back into v2 groups from which they were kicked because their client does not support the new group format,
All accounts are still able to send and receive messages with the coupled desktop applications.
As I use bbernard's Docker image, I'm still at version 0.7.4, if that matters.

**Comment by sttehh** [comment]
with latest version of signal-cli, the issue i had disappears

**Comment by Larx** [comment]
My issue is still there :-( .

**Comment by psunix** [comment]
same for me with the verify command after registering textnow.com number ...

`signal-cli -u +1xxxxxxx verify 123456`

`Verify error: Authorization failed!`

**Comment by Tarmik0s** [comment]
Running with the same error, does anyone fixed the problem?

**Comment by AsamK** [comment]
When you see the problem again, please post a verbose log (with `--verbose`)

**Comment by parthadc9** [comment]
2022-01-24T11:29:10.487Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-01-24T11:29:10.796Z [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:161: Initializing libsignal-client version:0.11.0
Verify error: [403] Authorization failed!
org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [403] Authorization failed!
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1714)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1695)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1677)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1666)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1602)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1578)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.verifyAccountCode(PushServiceSocket.java:360)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.verifyAccount(SignalServiceAccountManager.java:301)
	at org.asamk.signal.manager.RegistrationManagerImpl.verifyAccountWithCode(RegistrationManagerImpl.java:224)
	at org.asamk.signal.manager.RegistrationManagerImpl.verifyAccount(RegistrationManagerImpl.java:159)
	at org.asamk.signal.commands.VerifyCommand.verify(VerifyCommand.java:67)
	at org.asamk.signal.commands.VerifyCommand.handleCommand(VerifyCommand.java:43)
	at org.asamk.signal.App.handleRegistrationCommand(App.java:259)
	at org.asamk.signal.App.init(App.java:200)
	at org.asamk.signal.Main.main(Main.java:53)

**Comment by TimVdStockt** [comment]
Same error here, got the text message, but when I try to verify it I get Authorization failed.
Is there a solution for this?


2023-01-13T15:29:17.923Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.21.1
2023-01-13T15:29:17.927Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-01-13T15:29:18.222Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-01-13T15:29:18.358Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@2374d36a
2023-01-13T15:29:18.360Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-01-13T15:29:19.257Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-01-13T15:29:19.263Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Verify error: [403] Authorization failed!
org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [403] Authorization failed!
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1759)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1742)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1680)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1674)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.verifyAccountCode(PushServiceSocket.java:387)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.verifyAccount(SignalServiceAccountManager.java:300)
        at org.asamk.signal.manager.RegistrationManagerImpl.verifyAccountWithCode(RegistrationManagerImpl.java:222)
        at org.asamk.signal.manager.util.NumberVerificationUtils.verifyAccountWithCode(NumberVerificationUtils.java:85)
        at org.asamk.signal.manager.util.NumberVerificationUtils.verifyNumber(NumberVerificationUtils.java:56)
        at org.asamk.signal.manager.RegistrationManagerImpl.verifyAccount(RegistrationManagerImpl.java:127)
        at org.asamk.signal.commands.VerifyCommand.verify(VerifyCommand.java:67)
        at org.asamk.signal.commands.VerifyCommand.handleCommand(VerifyCommand.java:43)
        at org.asamk.signal.App.handleRegistrationCommand(App.java:261)
        at org.asamk.signal.App.init(App.java:221)
        at org.asamk.signal.Main.main(Main.java:60)

**Comment by VladZheleznyak** [comment]
Same here with 
```
2023-05-18 16:45:31,350 - root - INFO - 'signal-cli --verbose --config /usr/config/signal-cli -a <...> -o json receive' failed with 3 error code and the following message. STDOUT:

STDERR:
2023-05-18T16:45:29.808Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-05-18T16:45:30.074Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.23.1
2023-05-18T16:45:30.193Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-05-18T16:45:30.276Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@5c530d1e
2023-05-18T16:45:30.277Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-05-18T16:45:31.022Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-05-18T16:45:31.024Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Error while checking account +14184749147: [401] Authorization failed!
org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [401] Authorization failed!
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1775)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1758)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1696)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1690)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.setAccountAttributes(PushServiceSocket.java:448)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.setAccountAttributes(SignalServiceAccountManager.java:351)
        at org.asamk.signal.manager.helper.AccountHelper.updateAccountAttributes(AccountHelper.java:267)
        at org.asamk.signal.manager.helper.AccountHelper.checkAccountState(AccountHelper.java:77)
        at org.asamk.signal.manager.ManagerImpl.checkAccountState(ManagerImpl.java:203)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:116)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)
        at org.asamk.signal.App.loadManager(App.java:355)
        at org.asamk.signal.App.handleLocalCommand(App.java:288)
        at org.asamk.signal.App.init(App.java:229)
        at org.asamk.signal.Main.main(Main.java:60)
```
