### ISSUE TITLE
Migrate from old signal-cli version

### ISSUE THREAD

**Issue by contrebande-labs** [AsamK/signal-cli#547]
Hello,

I used an old signal-cli version from a maybe 15-18 months ago. I have all the data files in the old repo (I'm on macOS) : ~.config/signal

When I try a `simple ~/signal-cli-0.8.0/bin/signal-cli -u USER_NAME listDevices`

i get : 

`ERROR App - Error loading state file for user USER_NAME: 'long[] org.signal.client.internal.Native.IdentityKeyPair_Deserialize(byte[])'`

Is there a way I can migrate old config/data/state files to the new version ?

Thanks !

**Comment by AsamK** [comment]
Normally the old data files should be supported by the new version. Try running it with --verbose flag which might provide more information.
You could also try to first upgrade to 0.7.4, which still used an older method to deseralize the identity key.

**Comment by contrebande-labs** [comment]
Here's what I get with verbose :

```
~/signal-cli-0.8.0/bin/signal-cli --verbose -u +USER_NAME listDevices
2021-02-27T10:09:15.599-0500 [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:172: Initializing libsignal-client version:0.1.6
2021-02-27T10:09:16.130-0500 [main] ERROR org.asamk.signal.App - Error loading state file for user + USER_NAME: 'long[] org.signal.client.internal.Native.IdentityKeyPair_Deserialize(byte[])'
```

I will try with 0.7.4 now. But if you know what is going on with 0.8.0, please let me know.

Thanks.

**Comment by contrebande-labs** [comment]
`listDevices` and `addDevice` work with 0.7.4. But I would really like to be able to use 0.8.0 if I can find a way to fix the data. Thanks!

**Comment by AsamK** [comment]
The error message is coming from the libsignal-client library, which is new in 0.8.0 and requires a native library to work.
Normally I'd expect another error message in case it's not working ... did you provide the native library as described in the wiki?
https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal

**Comment by contrebande-labs** [comment]
Yes I did, I'm on a mac and only the linux libs were originally bundled and I got an error message for two missing native libs, so I followed the instructions for mac somewhere and I compiled one from the rust source and for the other I downloaded the mac version from Github. I put both in their respective jars and I didn't get the missing library error messages anymore, just that ` Error loading state file for user` error.

**Comment by AsamK** [comment]
hm, might be a version incompatibility, signal-cli 0.8.0 needs libsignal-client 0.2.3
https://github.com/signalapp/libsignal-client/releases/tag/java-0.2.3

**Comment by contrebande-labs** [comment]
Thanks for pointing that out. I will try it with that version and let you know ASAP.

**Comment by contrebande-labs** [comment]
`listDevices` now works with 0.8.0 with libsignal-client 0.2.3 compiled from the rust source. However, receive gives me this:

```
Exception in thread "main" java.lang.NullPointerException
	at org.whispersystems.signalservice.internal.push.SignalServiceProtos$Envelope.setType(SignalServiceProtos.java:327)
	at org.whispersystems.signalservice.internal.push.SignalServiceProtos$Envelope.access$100(SignalServiceProtos.java:168)
	at org.whispersystems.signalservice.internal.push.SignalServiceProtos$Envelope$Builder.setType(SignalServiceProtos.java:902)
	at org.whispersystems.signalservice.api.messages.SignalServiceEnvelope.<init>(SignalServiceEnvelope.java:80)
	at org.asamk.signal.manager.util.MessageCacheUtils.loadEnvelope(MessageCacheUtils.java:65)
	at org.asamk.signal.manager.storage.messageCache.CachedMessage.loadEnvelope(CachedMessage.java:24)
	at org.asamk.signal.manager.Manager.retryFailedReceivedMessage(Manager.java:1668)
	at org.asamk.signal.manager.Manager.retryFailedReceivedMessages(Manager.java:1661)
	at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1704)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:168)
	at org.asamk.signal.App.handleLocalCommand(App.java:211)
	at org.asamk.signal.App.init(App.java:169)
	at org.asamk.signal.Main.main(Main.java:43)
```

**Comment by AsamK** [comment]
looks like there's an old message in the message cache, that the new libsignal-service doesn't support anymore ...
I've pushed a workaround to master. Alternatively you could just delete the cached messages from `~/.config/signal/data/+$NUMBER.d/msg-cache/`

**Comment by contrebande-labs** [comment]
Actually it was a macOS [.DS_Store](https://en.wikipedia.org/wiki/.DS_Store) that was in there. I deleted it and it worked. Thanks !

**Comment by AsamK** [comment]
Interesting it could open it that far ...
