### ISSUE TITLE
java.lang.AssertionError: Unknown version: 0

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#552]
```
$ signal-cli send +XXXXXXXXXXX -m "Message"

Failed to send/receive message (Assertion): Unknown version: 0
java.lang.AssertionError: Unknown version: 0
    at org.whispersystems.signalservice.internal.push.PushTransportDetails.getPaddedMessageBody(PushTransportDetails.java:45)
    at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:94)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1729)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1689)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1534)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:320)
    at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1417)
    at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1345)
    at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1008)
    at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:90)
    at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:134)
    at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:14)
    at org.asamk.signal.App.handleLocalCommand(App.java:211)
    at org.asamk.signal.App.init(App.java:169)
    at org.asamk.signal.Main.main(Main.java:43)
If you use an Oracle JRE please check if you have unlimited strength crypto enabled, see README

$ echo $?
1
```

```
$ java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

$ signal-cli --version
signal-cli 0.8.0
```

The message actually _is_ sent and is received on the recipient's device. It is _not_ however shown on the 'linked' devices (the `syncMessage` to them not sent?).

Running with `--verbose` does not seem to provide other clues. 

I have tried to use the previous version (`0.7.4`) for comparison, but it produced a different error (I guess the fields in the config file have been changed since):

```
$ ./signal-cli-0.7.4/bin/signal-cli  send +XXXXXXXXXXX -m "Message"
ERROR App - Error loading state file for user +YYYYYYYYYYY: Unrecognized field "about" (class org.asamk.signal.manager.storage.profiles.SignalProfile), not marked as ignorable (5 known properties: "unidentifiedAccess", "identityKey", "name", "unrestrictedUnidentifiedAccess", "capabilities"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.asamk.signal.manager.storage.profiles.ProfileStore["profiles"]->org.asamk.signal.manager.storage.profiles.SignalProfile["about"])
```

I'm at a loss what would start causing this. Everything had been working fine; I don't think I've changed any relevant components, and this does not look like an error coming from signal servers.

**Comment by exquo** [comment]
For completeness, the `--verbose` output:

```
$ signal-cli --verbose send +XXXXXXXXXXX -m "Message"
2021-03-01T18:43:40.466Z [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: US
2021-03-01T18:43:40.472Z [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-03-01T18:43:40.484Z [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-03-01T18:43:40.729Z [main] WARN LibSignal - [SignalServiceMessageSender]: No attachments present...
2021-03-01T18:43:40.785Z [main] WARN LibSignal - [SignalServiceMessageSender]: java.io.IOException: No connection!
    at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:206)
    at org.whispersystems.signalservice.api.SignalServiceMessagePipe.send(SignalServiceMessagePipe.java:194)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1553)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:316)
    at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1417)
    at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1345)
    at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1008)
    at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:90)
    at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:134)
    at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:14)
    at org.asamk.signal.App.handleLocalCommand(App.java:211)
    at org.asamk.signal.App.init(App.java:169)
    at org.asamk.signal.Main.main(Main.java:43)

2021-03-01T18:43:40.785Z [main] WARN LibSignal - [SignalServiceMessageSender]: [sendMessage] Unidentified pipe failed, falling back...
2021-03-01T18:43:41.440Z [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
2021-03-01T18:43:41.440Z [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
Failed to send/receive message (Assertion): Unknown version: 0
java.lang.AssertionError: Unknown version: 0
    at org.whispersystems.signalservice.internal.push.PushTransportDetails.getPaddedMessageBody(PushTransportDetails.java:45)
    at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:94)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1729)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1689)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1534)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:320)
    at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1417)
    at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1345)
    at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1008)
    at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:90)
    at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:134)
    at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:14)
    at org.asamk.signal.App.handleLocalCommand(App.java:211)
    at org.asamk.signal.App.init(App.java:169)
    at org.asamk.signal.Main.main(Main.java:43)
If you use an Oracle JRE please check if you have unlimited strength crypto enabled, see README
2021-03-01T18:43:41.739Z [main] INFO LibSignal - [WebSocketConnection]: disconnect()
2021-03-01T18:43:41.740Z [main] INFO LibSignal - [WebSocketConnection]: disconnect()
```

**Comment by AsamK** [comment]
Can you check if it works with the latest master.
I fixed an issue with broken session records there, which manifests itself with the same stack trace.
https://github.com/AsamK/signal-cli/commit/8249f852f9244cc83698c9330a304604f385daaa

**Comment by gmanic** [comment]
Altough I'm not the original reported, but I had the same issue. I build signal-cli based on master and can confirm that messages are being send again without error.

Will report back if problem reappears.
(Last time it did not appear immediately).

**Comment by exquo** [comment]
Running the latest master, the issue is gone. Thanks!

Weird how it started happening without any actions on my side (that I'm aware of). The underlying problem must then be the same as in #530, although I haven't touched the master signal app on the phone.
