### ISSUE TITLE
GraalVM: No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer

### ISSUE THREAD

**Issue by filipre** [AsamK/signal-cli#572]
Hi,

I am coming from https://github.com/bbernhard/signal-cli-rest-api/issues/103. When I try to receive messages and there are actually new ones available (i.e. non-empty array), the data in org.asamk.signal.json.JsonSyncMessage cannot be serialized and I get the following error back
```
Failed to send/receive message (Assertion): com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["syncMessage"])
java.lang.AssertionError: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["syncMessage"])
	at org.asamk.signal.JsonWriter.write(JsonWriter.java:32)
	at org.asamk.signal.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.java:37)
	at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1782)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:168)
	at org.asamk.signal.App.handleLocalCommand(App.java:211)
	at org.asamk.signal.App.init(App.java:169)
	at org.asamk.signal.Main.main(Main.java:43)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["syncMessage"])
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:313)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3202)
	at org.asamk.signal.JsonWriter.write(JsonWriter.java:29)
	... 6 more
If you use an Oracle JRE please check if you have unlimited strength crypto enabled, see README
```

This only happens when I try to use singal-cli with GraalVM in native mode. I suspect the reason for that is that the `reflect-config.json` is not correct and GraalVM cannot determine the correct serializer. I tried adding `org.asamk.signal.json.JsonSyncMessage` like this

```json
{
  "name":"org.asamk.signal.json.JsonSyncMessage",
  "allDeclaredFields":true,
  "allDeclaredMethods":true,
  "allDeclaredConstructors":true,
  "allPublicConstructors" : true,
  "allPublicMethods" : true,
  "allPublicFields" : true
},
```

but I had no luck. Does someone have an idea where the issue could be? I was quite certain that extending `reflect-config.json` would work. It must be related to GraalVM because everything works fine when I am not in native mode. I believe issues like https://github.com/micronaut-projects/micronaut-aws/issues/207#issuecomment-678092993 and https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection are very related but I could not solve it myself and I am really bad at Java. I'm using the Dockerfile from the repo above. I'm on a MacBook Pro 10.15.4 and my architecture is
```
Darwin Renes-MBP.fritz.box 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

Thank you very much!

**Comment by AsamK** [comment]
should be fixed in the latest version
