### ISSUE TITLE
Upgrade from signal-cli 0.8.1 to 0.8.2 - Error loading state file for user

### ISSUE THREAD

**Issue by BOFH90** [AsamK/signal-cli#616]
I did a upgrade from 0.8.1 to 0.8.2 and get the following error:

/home/XXX/signal-cli/bin/signal-cli --verbose --config "/home/openhab/signal-cli-datastore" -u +49XXX listDevices
2021-05-12T07:04:23.862+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy recipient store.
2021-05-12T07:04:23.868+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy pre key store.
2021-05-12T07:04:23.877+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy signed pre key store.
2021-05-12T07:04:23.879+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy session store.
2021-05-12T07:04:23.893+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy identity session store.
2021-05-12T07:04:23.909+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy contact store.
2021-05-12T07:04:23.918+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy profile store.
Error loading state file for user +49XXX: null (NullPointerException)

Any Idea how to migrate ?

**Comment by AsamK** [comment]
I fixed a possible cause for this issue on master (3fc5bec149344754f9056fca20d214b4247b96c0) and also extended the logging in verbose mode.
Can you try again with this build (or build the master yourself): [signal-cli-0.8.2.tar.gz](https://github.com/AsamK/signal-cli/files/6468068/signal-cli-0.8.2.tar.gz)

**Comment by BOFH90** [comment]
Thanks for helping me. 

It sadly doesnt work either:

2021-05-12T20:07:37.342+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy recipient store.
2021-05-12T20:07:37.349+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy pre key store.
2021-05-12T20:07:37.356+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy signed pre key store.
2021-05-12T20:07:37.357+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy session store.
2021-05-12T20:07:37.367+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy identity session store.
2021-05-12T20:07:37.382+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy contact store.
2021-05-12T20:07:37.388+0200 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy profile store.
2021-05-12T20:07:37.409+0200 [main] DEBUG org.asamk.signal.App - Loading state file failed
java.lang.NullPointerException
	at org.asamk.signal.manager.storage.SignalAccount.loadLegacyStores(SignalAccount.java:555)
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:424)
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:113)
	at org.asamk.signal.manager.Manager.init(Manager.java:291)
	at org.asamk.signal.App.loadManager(App.java:240)
	at org.asamk.signal.App.handleLocalCommand(App.java:202)
	at org.asamk.signal.App.init(App.java:163)
	at org.asamk.signal.Main.main(Main.java:51)
Error loading state file for user +4966592209: null (NullPointerException)

**Comment by AsamK** [comment]
Thanks for testing. I've fixed another issue, which is now obvious with the extend logging.
[signal-cli-0.8.2.tar.gz](https://github.com/AsamK/signal-cli/files/6468280/signal-cli-0.8.2.tar.gz)

**Comment by BOFH90** [comment]
Perfect, its working flawless now :+1:  Thanks
