### ISSUE TITLE
signal-cli daemon fails on FreeBSD/powerpc64

### ISSUE THREAD

**Issue by chmeeedalf** [AsamK/signal-cli#632]
When trying to run `signal-cli daemon' it fails with the following exception:

Exception in thread "main" java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider                                              
        at jnr.ffi.provider.InvalidRuntime.newLoadError(InvalidRuntime.java:101)                                                                                   
        at jnr.ffi.provider.InvalidRuntime.findType(InvalidRuntime.java:42)                                                                                        
        at jnr.ffi.Struct$NumberField.<init>(Struct.java:873)                                                                                                      
        at jnr.ffi.Struct$Unsigned8.<init>(Struct.java:1114)                                                                                                       
        at jnr.unixsocket.SockAddrUnix$BSDSockAddrUnix.<init>(SockAddrUnix.java:187)                                                                               
        at jnr.unixsocket.SockAddrUnix.create(SockAddrUnix.java:174)                                                                                               
        at jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:53)                                                                                      
        at org.freedesktop.dbus.connections.transports.UnixSocketTransport.<init>(UnixSocketTransport.java:31)                                                     
        at org.freedesktop.dbus.connections.transports.TransportFactory.createTransport(TransportFactory.java:37)                                                  
        at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:149)                                                                 
        at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:322)                                                                    
        at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:134)                                                             
        at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:195)                                                             
        at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:158)                                                             
        at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:100)                                                                           
        at org.asamk.signal.App.handleMultiLocalCommand(App.java:232)                                                                                              
        at org.asamk.signal.App.init(App.java:146)                                                                                                                 
        at org.asamk.signal.Main.main(Main.java:51)                                                                                                                
Caused by: java.lang.UnsatisfiedLinkError: could not get native definition for type `POINTER`, original error message follows: java.lang.UnsatisfiedLinkError: coul
d not locate stub library in jar file.  Tried [jni/ppc64-FreeBSD/libjffi-1.2.so, /jni/ppc64-FreeBSD/libjffi-1.2.so]                                                

I tried a naive approach of adding a ppc64/freebsd/TypeAliases.java in jnr-ffi, but the tests for that failed with the exact same error.  Is there any documentation anywhere on adding platform support for this?  I would love to be able to run signal-cli and scli (needs daemon mode) on FreeBSD/powerpc64.  'signal-cli' in non-daemon mode appears to work fine.

**Comment by AsamK** [comment]
signal-cli uses https://github.com/hypfvieh/dbus-java for dbus functionality which uses https://github.com/jnr/jnr-unixsocket for unix socket support. You probably need to add platform support to the jnr project.
