### ISSUE TITLE
Native mode on 0.8.2 and 0.8.3 amd64 

### ISSUE THREAD

**Issue by haberda** [AsamK/signal-cli#634]
Hello,

When trying to use native mode on 0.8.2 or 0.8.3 with an amd64 machine I am getting an error message like this one:

```
{"error":"Error loading or creating state file: Cannot construct instance of `org.asamk.signal.manager.storage.groups.GroupStore$Storage$GroupV1$JsonSignalServiceAddress` (no Creators, like default construct, exist): cannot  deserialize from Object value (no delegate- or property-based Creator)\n at [Source: UNKNOWN; line: -1, column:  -1] (through reference chain: org.asamk.signal.manager.storage.groups.GroupStore$Storage[\"groups\"]-\u003eorg.a samk.signal.manager.storage.groups.GroupStore$Storage$GroupV1[\"members\"]) (IllegalArgumentException)\n"}
```

The above error message was captured after I decided to delete my previous statefile and start over, hoping that if I started with native mode everything would work. I get similar messages for attempting any action with native mode. Here is one I recived while attempting to send a message with this command `echo "test" | signal-cli-native --verbose --config /data -u +<fromnum> send +<tonum>:`

```
2021-05-27T12:14:27.492-0700 [main] DEBUG org.asamk.signal.App - Loading state file failed
java.lang.IllegalArgumentException: Cannot construct instance of `org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3751)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3669)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:413)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:113)
        at org.asamk.signal.manager.Manager.init(Manager.java:291)
        at org.asamk.signal.App.loadManager(App.java:248)
        at org.asamk.signal.App.handleLocalCommand(App.java:210)
        at org.asamk.signal.App.init(App.java:171)
        at org.asamk.signal.Main.main(Main.java:51)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3746)
        ... 8 more
Error loading state file for user +<sendnum>: Cannot construct instance of `org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1] (IllegalArgumentException)
```

The standard mode works as expected. I am using this in a dockerized environment and the original thread documenting this issue can be found [here](https://github.com/bbernhard/signal-cli-rest-api/issues/134).

**Comment by haberda** [comment]
Also, for clarity, on 0.8.1 native mode worked fine.

**Comment by haberda** [comment]
Deleted statefile and started over and it works. Closing.
