### ISSUE TITLE
java.lang.NullPointerException on register

### ISSUE THREAD

**Issue by parrotx-proton** [AsamK/signal-cli#644]
Get NPE on new number registration:
```bash
$./signal-cli --verbose -u $USERNAME register
2021-06-15T12:58:13.305+0200 [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.8.1
Exception in thread "main" java.lang.NullPointerException
	at org.asamk.signal.commands.RegisterCommand.handleCommand(RegisterCommand.java:30)
	at org.asamk.signal.App.handleRegistrationCommand(App.java:201)
	at org.asamk.signal.App.init(App.java:166)
	at org.asamk.signal.Main.main(Main.java:51)
```
Versions:
```bash
$./signal-cli -v
signal-cli 0.8.4

$java --version
openjdk 13.0.5.1 2020-11-06
OpenJDK Runtime Environment (build 13.0.5.1+1-Debian-1)
OpenJDK 64-Bit Server VM (build 13.0.5.1+1-Debian-1, mixed mode)
```

**Comment by AsamK** [comment]
There's a missing null check ... as a workaround you can provide a captcha value with the `--captcha` parameter, then registering should work:
https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#register

**Comment by parrotx-proton** [comment]
Thank you @AsamK ! Works perfectly
Leaving this open for addition of null check and probably a better message
