### ISSUE TITLE
linking doesn't work

### ISSUE THREAD

**Issue by mhellwig** [AsamK/signal-cli#66]
I have done a fresh install of signal-cli on a computer, where it has never before been installed (running Fedora).
as a next step, I wanted to link the signal-cli instance to my phone. The result I get is (whenever I try, not just once):
$ signal-cli link
Exception in thread "main" java.lang.NullPointerException
	at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.connect(WebSocketConnection.java:81)
	at org.whispersystems.signalservice.internal.push.ProvisioningSocket.getProvisioningUuid(ProvisioningSocket.java:29)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getNewDeviceUuid(SignalServiceAccountManager.java:348)
	at org.asamk.signal.Manager.getDeviceLinkUri(Manager.java:363)
	at org.asamk.signal.Main.handleCommands(Main.java:175)
	at org.asamk.signal.Main.main(Main.java:68)

as far as I can tell I am using the command according to the manpage. What am I doing wrong?

**Comment by Trolldemorted** [comment]
are you running 0.5.5?

**Comment by mhellwig** [comment]
ah. now that you put it like that ...
