### ISSUE TITLE
Using `daemon` mode fails with native image (GraalVM)

### ISSUE THREAD

**Issue by moppman** [AsamK/signal-cli#673]
Hi,

Using the `daemon` command with **native-image** `signal-cli`  (v. 0.8.4.1) isn't working. I noticed this when trying to use the native image with the python client [scli](https://github.com/isamert/scli).
Invoking `signal-cli  --verbose -u <number>  daemon` yields 
```
2021-07-29T18:26:39.712+0200 [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.8.1
2021-07-29T18:26:42.832+0200 [main] DEBUG org.freedesktop.dbus.connections.transports.TransportFactory - Connecting to UNIX: {path=/run/user/1000/bus}
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface jnr.unixsocket.Native$LibC, interface jnr.ffi.provider.LoadedLibrary] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:88)
	at com.oracle.svm.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:113)
	at java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:66)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006)
	at jnr.ffi.LibraryLoader.createErrorProxy(LibraryLoader.java:419)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:414)
	at jnr.unixsocket.Native.<clinit>(Native.java:80)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at jnr.unixsocket.UnixSocketChannel.<init>(UnixSocketChannel.java:101)
	at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:65)
	at org.freedesktop.dbus.connections.transports.UnixSocketTransport.connect(UnixSocketTransport.java:58)
	at org.freedesktop.dbus.connections.transports.TransportFactory.createTransport(TransportFactory.java:44)
	at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:149)
	at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:322)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:134)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:195)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:158)
	at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:67)
	at org.asamk.signal.App.handleLocalCommand(App.java:214)
	at org.asamk.signal.App.init(App.java:174)
	at org.asamk.signal.Main.main(Main.java:51)

```
I added the missing interfaces [jnr.unixsocket.Native$LibC](https://github.com/jnr/jnr-unixsocket) and [jnr.ffi.provider.LoadedLibrary](https://github.com/jnr/jnr-ffi) from the error message to `proxy-config.json` in the `graalvm-config-dir` and re-build the native image, however, the  error persists.
Also, in both build scenarios, two warnings can be observed:

`WARNING: Could not resolve jnr.enxio.channels.Native$LibC$jnr$ffi$1 for reflection configuration. Reason: java.lang.ClassNotFoundException: jnr.enxio.channels.Native$LibC$jnr$ffi$1.`
and
`WARNING: Could not resolve jnr.unixsocket.Native$LibC$jnr$ffi$0 for reflection configuration. Reason: java.lang.ClassNotFoundException: jnr.unixsocket.Native$LibC$jnr$ffi$0.`

Those warnings are also present in #617.

**Comment by technillogue** [comment]
Hi, can you share what you tried adding to config?

**Comment by moppman** [comment]
> Hi, can you share what you tried adding to config?

Sure: 

>I added the missing interfaces jnr.unixsocket.Native$LibC and jnr.ffi.provider.LoadedLibrary from the error message to proxy-config.json in the graalvm-config-dir

So the `proxy-config.json` looked like this:
```json
[
  ["org.asamk.Signal"],
  ["org.freedesktop.dbus.interfaces.DBus"],
  ["jnr.unixsocket.Native$LibC"],
  ["jnr.ffi.provider.LoadedLibrary"]
]

```

**Comment by technillogue** [comment]
I wonder if it's an issue with `sourceSets.main.get().runtimeClasspath.asPath` in build.gradle.kts. 

It does give me these jars, which are the same jars as in the installDist classpath...

~/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-unixsocket/0.38.5/5b4428d124be6d94c122cc2ad63312be6d85e80a/jnr-unixsocket-0.38.5.jar
.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-enxio/0.32.3/e6007f2a4b9b00af26ab2dff3aecd21f0adb48ae/jnr-enxio-0.32.3.jar:

**Comment by AsamK** [comment]
the jnr unixsocket library doesn't seem to work with graalvm.
The next hypfvieh/dbus-java version will have support for native java unix sockets, that should also work with graalvm: https://github.com/hypfvieh/dbus-java#changes-in-400-not-yet-released

**Comment by moppman** [comment]
I've just compiled a fresh native image from f58f85ef6012be11541597550f6ae3f7c08d8eda, and it looks like it "just works", didn't have to fiddle in the config files or anything like that. Nice work!

**Comment by moppman** [comment]
Having said that, there were some warnings during compilation about missing `nativeHandle()` functions:
```
Warning: Method org.whispersystems.libsignal.groups.state. SenderKeyRecord.nativeHandle() not found.
Warning: Method org.whispersystems.libsignal.protocol.PlaintextContent.nativeHandle() not found.
Warning: Method org.whispersystems.libsignal.protocol. PreKeySignalMessage.nativeHandle() notfound.
Warning: Method org.whispersystems.libsignal.protocol.SignalMessage.nativeHandle() not found.
Warning: Method org.whispersystems. libsignal.state.PreKeyRecord.nativeHandle() not found.
Warning: Method org.whispersystems.libsignal.state.SessionRecord.nativeHandle() not found.
Warning: Method org.whispersystems.libsignal.state. SignedPreKeyRecord.nativeHandle() not found.
```
I don't know if this warrants a separate issue, though?

**Comment by AsamK** [comment]
Nice, thanks for testing.
I've seen those as well, the warnings can be safely ignored, it just means that they could be removed from the config file.

**Comment by moppman** [comment]
Dang it, upon further testing it's still not really working:
Invoking `signal-cli -u +xxxxxx --output=json daemon` results in the following error:
```
{"envelope"Exception in thread "Thread-0" java.lang.AssertionError: com.fasterxml.jackson.databind.JsonMappingException: Failed to access RecordComponents of type `org.asamk.signal.json.JsonCallMessage$Offer` (through reference chain: java.util.HashMap["envelope"])
	at org.asamk.signal.output.JsonWriterImpl.write(JsonWriterImpl.java:27)
	at org.asamk.signal.json.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.java:35)
	at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$9(ManagerImpl.java:975)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$10(ManagerImpl.java:973)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:200)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:169)
	at org.asamk.signal.manager.ManagerImpl.receiveMessagesInternal(ManagerImpl.java:1142)
	at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$11(ManagerImpl.java:971)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to access RecordComponents of type `org.asamk.signal.json.JsonCallMessage$Offer` (through reference chain: java.util.HashMap["envelope"])
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1330)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1468)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:376)
	at com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:174)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1473)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:376)
	at com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:197)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1453)
	at com.fasterxml.jackson.databind.SerializerProvider.findContentValueSerializer(SerializerProvider.java:777)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:90)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer._findAndAddDynamic(MapSerializer.java:1139)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer._findSerializer(MapSerializer.java:1248)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:806)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4569)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3805)
	at org.asamk.signal.output.JsonWriterImpl.write(JsonWriterImpl.java:24)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Failed to access RecordComponents of type `org.asamk.signal.json.JsonCallMessage$Offer`
	at com.fasterxml.jackson.databind.jdk14.JDK14Util$RecordAccessor.recordComponents(JDK14Util.java:124)
	at com.fasterxml.jackson.databind.jdk14.JDK14Util$RecordAccessor.getRecordFieldNames(JDK14Util.java:78)
	at com.fasterxml.jackson.databind.jdk14.JDK14Util.getRecordFieldNames(JDK14Util.java:27)
	at com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy$RecordNaming.<init>(DefaultAccessorNamingStrategy.java:531)
	at com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy$Provider.forRecord(DefaultAccessorNamingStrategy.java:448)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:185)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:86)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:11)
	at com.fasterxml.jackson.databind.SerializationConfig.introspect(SerializationConfig.java:862)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:143)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1463)
	... 34 more
```

**Comment by AsamK** [comment]
yeah, now that's missing reflect config. I've added it for this case (incoming call message), but that's a general issue with the native-image, it's hard to find all instances ...
If you find another case, you could run the normal signal-cli with an attached native-image agent to automatically update the reflect config:
https://www.graalvm.org/reference-manual/native-image/Agent/

**Comment by moppman** [comment]
Hehe, dug a bit more into the native-image agent stuff and wow, this is really cool stuff, but on the other hand quite cumbersome to work with because of the "non-determistic" trace reports. Feels like herding chickens :sweat_smile:

**Comment by morph027** [comment]
Hm...i see https://github.com/AsamK/signal-cli/blob/master/graalvm-config-dir/reflect-config.json#L496, but the resulting image still fails w/ the same error.

```
$ signal-cli --output=json daemon

INFO DaemonCommand - Starting daemon in multi-account mode
INFO DaemonCommand - DBus daemon running on SESSION bus: org.asamk.Signal

{"envelope"Exception in thread "Thread-0" java.lang.AssertionError: com.fasterxml.jackson.databind.JsonMappingException: Failed to access RecordComponents of type `org.asamk.signal.json.JsonCallMessage$Answer` (through reference chain: java.util.HashMap["envelope"])
	at org.asamk.signal.output.JsonWriterImpl.write(JsonWriterImpl.java:27)
	at org.asamk.signal.json.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.java:35)
	at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$9(ManagerImpl.java:1011)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$10(ManagerImpl.java:1009)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:200)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:169)
	at org.asamk.signal.manager.ManagerImpl.receiveMessagesInternal(ManagerImpl.java:1184)
	at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$11(ManagerImpl.java:1007)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to access RecordComponents of type `org.asamk.signal.json.JsonCallMessage$Answer` (through reference chain: java.util.HashMap["envelope"])
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1330)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1468)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:376)
	at com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:174)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1473)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:376)
	at com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:197)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1453)
	at com.fasterxml.jackson.databind.SerializerProvider.findContentValueSerializer(SerializerProvider.java:777)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:90)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer._findAndAddDynamic(MapSerializer.java:1139)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer._findSerializer(MapSerializer.java:1248)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:806)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4569)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3805)
	at org.asamk.signal.output.JsonWriterImpl.write(JsonWriterImpl.java:24)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Failed to access RecordComponents of type `org.asamk.signal.json.JsonCallMessage$Answer`
	at com.fasterxml.jackson.databind.jdk14.JDK14Util$RecordAccessor.recordComponents(JDK14Util.java:124)
	at com.fasterxml.jackson.databind.jdk14.JDK14Util$RecordAccessor.getRecordFieldNames(JDK14Util.java:78)
	at com.fasterxml.jackson.databind.jdk14.JDK14Util.getRecordFieldNames(JDK14Util.java:27)
	at com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy$RecordNaming.<init>(DefaultAccessorNamingStrategy.java:531)
	at com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy$Provider.forRecord(DefaultAccessorNamingStrategy.java:448)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:185)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:86)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:11)
	at com.fasterxml.jackson.databind.SerializationConfig.introspect(SerializationConfig.java:862)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:143)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1463)
	... 34 more

```

Ref: https://gitlab.com/packaging/signal-cli/-/issues/3

**Comment by morph027** [comment]
Running JRE version with `JAVA_TOOL_OPTIONS="-agentpath:/tmp/graalvm-ce-java17-21.3.0/lib/libnative-image-agent.so=config-merge-dir=/tmp/signal-cli/graalvm-config-dir/"` does not change anything.
