### ISSUE TITLE
Failed to send message: StatusCode: 428

### ISSUE THREAD

**Issue by jk20004** [AsamK/signal-cli#708]
when we send messages from the signal-cli we have some mobile numbers where we are not able to send messages instead we get the status code 428 

```
**signal-cli --verbose --config nnnn -u +nnnnn send -m "Test" +nnnnnn**
2021-09-08T08:18:28.822+0200 [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.8.1
2021-09-08T08:18:36.499+0200 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: DE
2021-09-08T08:18:36.503+0200 [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-09-08T08:18:36.508+0200 [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-09-08T08:18:36.681+0200 [main] WARN LibSignal - [SignalServiceMessageSender]: No attachments present...
2021-09-08T08:18:36.962+0200 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
2021-09-08T08:18:36.963+0200 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
2021-09-08T08:18:37.169+0200 [main] INFO LibSignal - [WebSocketConnection]: disconnect()
2021-09-08T08:18:37.171+0200 [main] INFO LibSignal - [WebSocketConnection]: disconnect()
Failed to send message: StatusCode: 428

```
signal-cli-0.8.5
Red Hat Enterprise Linux release 8.4 
x86_64

does anyone have an idea what we can do

**Comment by AsamK** [comment]
428 is a ratelimiting status code from the signal server.
Can you retry with the latest master branch version? It has more detailed logging and should show which call is rate limited.
You can get a prebuild artifact from the last build: https://github.com/AsamK/signal-cli/actions/runs/1214562481

**Comment by jk20004** [comment]
this version requires GNU libc 2.29 but with RedHat 8.4 i only have 2.28
i have just updated from RedHat 7 to 8 to get 0.8.5 running do i require 2.29 for the next version?

**Comment by jk20004** [comment]
after replacing the libsignal_jni.so i get

```
2021-09-09T09:02:14.900+0200 [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.8.1
2021-09-09T09:02:30.452+0200 [main] DEBUG org.asamk.signal.manager.storage.senderKeys.SenderKeySharedStore - Creating new shared sender key store.
2021-09-09T09:02:36.735+0200 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: DE
2021-09-09T09:02:36.941+0200 [main] DEBUG LibSignal - [SignalServiceMessageSender]: [1631170956817] Sending a data message.
Failed to send message: StatusCode: 428 (ProofRequiredException)
org.whispersystems.signalservice.api.push.exceptions.ProofRequiredException: StatusCode: 428
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1592)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1549)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1534)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1476)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1470)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:576)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2115)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2090)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1732)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendDataMessage(SignalServiceMessageSender.java:346)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:272)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:80)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:568)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:624)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:108)
        at org.asamk.signal.App.handleLocalCommand(App.java:247)
        at org.asamk.signal.App.init(App.java:197)
        at org.asamk.signal.Main.main(Main.java:52)
```

**Comment by AsamK** [comment]
Thanks!
I've added another commit to handle the ProofRequiredException and print the server response.
If the server allows it you can then lift the rate limit by solving a captcha and using the new `submitRateLimitChallenge` command.
Unfortunately I can't test this as I haven't experience the 428 status code myself yet.

**Comment by jk20004** [comment]
where can i find the new version?

**Comment by AsamK** [comment]
https://github.com/AsamK/signal-cli/actions/runs/1218277691

**Comment by jk20004** [comment]
i have a problem to find the "--challenge" for the command, any help appreciated :-)

**Comment by AsamK** [comment]
The challenge token should be printed in the new error message when you try to send a message again.
Unless the server doesn't allow it in this case, then the error message would show an empty list...

**Comment by jk20004** [comment]
ok so i wait for the 428 error (appears excitingly only in the afternoon)
i think there is a second place where you should extract the challenge token

```
2021-09-10T07:51:30.728+0200 [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.8.1
2021-09-10T07:51:34.361+0200 [main] DEBUG org.asamk.signal.manager.storage.senderKeys.SenderKeySharedStore - Creating new shared sender key store.
2021-09-10T07:51:35.316+0200 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: DE
2021-09-10T07:51:35.516+0200 [main] DEBUG LibSignal - [SignalServiceMessageSender]: [1631253095395] Sending a data message.
Failed to send message: [413] Rate limit exceeded: 413 (RateLimitException)
org.whispersystems.signalservice.api.push.exceptions.RateLimitException: [413] Rate limit exceeded: 413
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1559)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1549)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1534)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1476)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1470)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:576)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2115)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2090)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1732)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendDataMessage(SignalServiceMessageSender.java:346)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:273)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:81)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:572)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:628)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:108)
        at org.asamk.signal.App.handleLocalCommand(App.java:247)
        at org.asamk.signal.App.init(App.java:197)
        at org.asamk.signal.Main.main(Main.java:52)

```

**Comment by AsamK** [comment]
That's unfortunately a 413 status code, which doesn't provide a challenge code, only 428 has one ...

**Comment by jk20004** [comment]
now i get a "Failed to send (some) messages" error with the new version when i try to send a message to a number where i receive a 428 with the "normal" version

```
2021-09-10T10:05:53.984+0200 [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.8.1
2021-09-10T10:05:56.600+0200 [main] DEBUG org.asamk.signal.manager.storage.senderKeys.SenderKeySharedStore - Creating new shared sender key store.
2021-09-10T10:05:57.559+0200 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: DE
2021-09-10T10:05:57.767+0200 [main] DEBUG LibSignal - [SignalServiceMessageSender]: [1631261157648] Sending a data message.
1631261157648
Failed to send (some) messages:
Network failure for "+xxxxxxxxxxxxxx"
```
after two more tests i get the 413

```
2021-09-10T10:08:29.697+0200 [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.8.1
2021-09-10T10:08:34.820+0200 [main] DEBUG org.asamk.signal.manager.storage.senderKeys.SenderKeySharedStore - Creating new shared sender key store.
2021-09-10T10:08:35.780+0200 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: DE
2021-09-10T10:08:35.985+0200 [main] DEBUG LibSignal - [SignalServiceMessageSender]: [1631261315861] Sending a data message.
Failed to send message: [413] Rate limit exceeded: 413 (RateLimitException)
org.whispersystems.signalservice.api.push.exceptions.RateLimitException: [413] Rate limit exceeded: 413
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1559)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1549)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1534)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1476)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1470)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:576)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2115)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2090)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1732)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendDataMessage(SignalServiceMessageSender.java:346)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:273)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:81)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:572)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:628)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:108)
        at org.asamk.signal.App.handleLocalCommand(App.java:247)
        at org.asamk.signal.App.init(App.java:197)
        at org.asamk.signal.Main.main(Main.java:52)

```

**Comment by AsamK** [comment]
ah, libsignal-service classifies the proof required error as network failure as well...
Next attempt: https://github.com/AsamK/signal-cli/actions/runs/1220470222

**Comment by jk20004** [comment]
great job :-) if seen the token now the first time and i was able to enable it with the captcha hope that will help for longer.
thank you!

**Comment by jk20004** [comment]
.... but now i get at [FAILED toString()] when i call a getUserStatus

```
2021-09-10T10:55:29.613+0200 [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.8.1
2021-09-10T10:55:31.994+0200 [main] DEBUG org.asamk.signal.manager.storage.senderKeys.SenderKeySharedStore - Creating new shared sender key store.
2021-09-10T10:55:32.957+0200 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: DE
SLF4J: Failed toString() invocation on an object of type [org.whispersystems.libsignal.util.Pair]
Reported exception:
java.lang.NullPointerException
        at org.whispersystems.libsignal.util.Pair.hashCode(Pair.java:32)
        at java.base/java.lang.Object.toString(Object.java:246)
        at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
        at org.asamk.signal.PlainTextWriterImpl.println(PlainTextWriterImpl.java:23)
        at org.asamk.signal.commands.GetUserStatusCommand.handleCommand(GetUserStatusCommand.java:64)
        at org.asamk.signal.App.handleLocalCommand(App.java:247)
        at org.asamk.signal.App.init(App.java:197)
        at org.asamk.signal.Main.main(Main.java:52)
+xxxx: [FAILED toString()]
```
this is my wait to find out if the other end has the Signal App installed

**Comment by AsamK** [comment]
Nice, thanks for testing.
Looks like a bug in signal-cli, please create a new issue for it :)

**Comment by jk20004** [comment]
are you sure? it works in the "normal" signal-cli-0.8.5

**Comment by AsamK** [comment]
Yeah, it's a bug that was introduced in a refactoring in the master branch since then.
