### ISSUE TITLE
sendContacts failed

### ISSUE THREAD

**Issue by neomsg-git** [AsamK/signal-cli#710]
### Platform
M1 MacBook

### Steps to reproduce
I followed these [instructions](https://gist.github.com/szepeviktor/2c6a19cb91c4bb561369707f22bcf413) to setup signal-cli with the Signal desktop application. Although I was not able to compile zkgroup library due to the architecture of my system  everything went smoothly so far. Next I added my contacts:
`./signal-cli updateContact -n "SOME_PERSON" "SOME_NUMBER"`
Lastly I wanted to send those contacts to the Signal desktop application: 
`./signal-cli sendContacts`

### Error message
```
WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
INFO Manager - The Signal protocol expects that incoming messages are regularly received.
Exception in thread "main" java.lang.NullPointerException
	at org.asamk.signal.manager.SignalDependencies.lambda$getMessageSender$13(SignalDependencies.java:142)
	at org.asamk.signal.manager.SignalDependencies.getOrCreate(SignalDependencies.java:183)
	at org.asamk.signal.manager.SignalDependencies.getMessageSender(SignalDependencies.java:134)
	at org.asamk.signal.manager.helper.SendHelper.sendSyncMessage(SendHelper.java:187)
	at org.asamk.signal.manager.helper.SyncHelper.sendContacts(SyncHelper.java:180)
	at org.asamk.signal.manager.Manager.sendContacts(Manager.java:999)
	at org.asamk.signal.commands.SendContactsCommand.handleCommand(SendContactsCommand.java:30)
	at org.asamk.signal.App.handleLocalCommand(App.java:246)
	at org.asamk.signal.App.init(App.java:196)
	at org.asamk.signal.Main.main(Main.java:51)
```

**Comment by AsamK** [comment]
Thanks for reporting should be fixed in master now.
