### ISSUE TITLE
Native mode not working in master branch

### ISSUE THREAD

**Issue by bbernhard** [AsamK/signal-cli#713]
Hi,

not sure if this is already known, but I think the native mode doesn't work in the master branch right now. I am always getting this message here: `WARN ServiceConfig - Failed to call libsignal-client: Can't load library: /tmp/resource4844848801909423323.so\nMissing required native library dependency: libsignal-client`

I think my dependencies (`libsignal-client` & `libzkgroup`) should be fine, as the normal mode and JSON-RPC mode works fine for me.

In case this is already known, please just close the ticket.

Best Regards,
Bernhard

**Comment by AsamK** [comment]
It works on my machine, with the upstream libs.
I'd guess the native-image build doesn't use the jars where you replaced the dependencies.
Maybe you need to replace the libs in the gradle cache (if that's possible ...): `~/.gradle/caches/modules-2/files-2.1/org.whispersystems/signal-client-java/0.9.0/c0f6019f50feaa4d3aa6556aa1ba891dfce03fae/signal-client-java-0.9.0.jar`

**Comment by bbernhard** [comment]
Thanks a lot for the quick reply!

I _think_ I've found the issue - it seems the issue was related to glibc. I was building `libsignal-client` inside docker with Debian Buster as build platform - which has a rather old glibc vesion. This was working fine until `signal-cli 0.8.5`, but the newest `libsignal-client` seems to require a newer glibc. After updating to Debian Bullseye the above error is gone. (I am glad that I saw the info regarding the glibc version in your `README.md` - without that it would probably have taken me way longer to troubleshoot)

The `receive` command is now working fine again with the native mode. However, the `send` and the `listGroups` commands are throwing some errors for me:

`signal-cli-native --config /home/.local/share/signal-cli --output json -u <number> listGroups -d`

outputs:

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: The offset of private java.lang.String org.signal.storageservice.protos.groups.local.DecryptedGroup.title_ is accessed without the field being first registered as unsafe accessed. Please register the field as unsafe accessed. You can do so with a reflection configuration that contains an entry for the field with the attribute "allowUnsafeAccess": true. Such a configuration file can be generated for you. Read BuildConfiguration.md and Reflection.md for details.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
	at jdk.internal.misc.Unsafe.objectFieldOffset(Unsafe.java:50)
	at sun.misc.Unsafe.objectFieldOffset(Unsafe.java:640)
	at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:522)
	at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:221)
	at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:85)
	at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
	at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1530)
	at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1670)
	at org.signal.storageservice.protos.groups.local.DecryptedGroup.parseFrom(DecryptedGroup.java:809)
	at org.asamk.signal.manager.storage.groups.GroupStore.loadDecryptedGroupLocked(GroupStore.java:238)
	at org.asamk.signal.manager.storage.groups.GroupStore.getGroups(GroupStore.java:174)
	at org.asamk.signal.manager.Manager.getGroups(Manager.java:479)
	at org.asamk.signal.commands.ListGroupsCommand.handleCommand(ListGroupsCommand.java:84)
	at org.asamk.signal.App.handleLocalCommand(App.java:247)
	at org.asamk.signal.App.init(App.java:197)
	at org.asamk.signal.Main.main(Main.java:52)

```

and 

`echo 'hello' | signal-cli-native --config /home/.local/share/signal-cli -u <number> send <recipient>`

outputs

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: The offset of private java.lang.String org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.body_ is accessed without the field being first registered as unsafe accessed. Please register the field as unsafe accessed. You can do so with a reflection configuration that contains an entry for the field with the attribute "allowUnsafeAccess": true. Such a configuration file can be generated for you. Read BuildConfiguration.md and Reflection.md for details.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
	at jdk.internal.misc.Unsafe.objectFieldOffset(Unsafe.java:50)
	at sun.misc.Unsafe.objectFieldOffset(Unsafe.java:640)
	at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:522)
	at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:221)
	at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
	at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
	at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:170)
	at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:386)
	at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:394)
	at org.whispersystems.signalservice.internal.push.SignalServiceProtos$Content.setDataMessage(SignalServiceProtos.java:1587)
	at org.whispersystems.signalservice.internal.push.SignalServiceProtos$Content.access$2800(SignalServiceProtos.java:1546)
	at org.whispersystems.signalservice.internal.push.SignalServiceProtos$Content$Builder.setDataMessage(SignalServiceProtos.java:2101)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createMessageContent(SignalServiceMessageSender.java:998)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendDataMessage(SignalServiceMessageSender.java:340)
	at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:294)
	at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:83)
	at org.asamk.signal.manager.Manager.sendMessage(Manager.java:546)
	at org.asamk.signal.manager.Manager.sendMessage(Manager.java:602)
	at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:108)
	at org.asamk.signal.App.handleLocalCommand(App.java:247)
	at org.asamk.signal.App.init(App.java:197)
	at org.asamk.signal.Main.main(Main.java:52)

```

**Comment by AsamK** [comment]
Normally that's a sign that some entries are missing in `reflect-config.json`, but those commands also work with the native build on my machine (graalvm 21.2.0) ...

**Comment by bbernhard** [comment]
Many thanks! I've updated `graalvm` to version `21.2.0` and now it works also for me.
