### ISSUE TITLE
Cannot link device to master

### ISSUE THREAD

**Issue by bonfus** [AsamK/signal-cli#795]
I tried a few times adding devices with

`signal-cli -u +xxxxxxxxxxxx addDevice --uri 'sgnl://linkdevice?uuid=MANYCHARACTERS&pub_key=EVENMORECHARACTERS'`

But I always get

```
java.lang.IncompatibleClassChangeError: Expecting non-static method 'byte[] org.whispersystems.libsignal.kdf.HKDF.deriveSecrets(byte[], byte[], int)'
	at org.whispersystems.signalservice.internal.crypto.ProvisioningCipher.encrypt(ProvisioningCipher.java:49)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.addDevice(SignalServiceAccountManager.java:829)
	at org.asamk.signal.manager.ManagerImpl.addDevice(ManagerImpl.java:437)
	at org.asamk.signal.manager.ManagerImpl.addDeviceLink(ManagerImpl.java:429)
	at org.asamk.signal.commands.AddDeviceCommand.handleCommand(AddDeviceCommand.java:42)
	at org.asamk.signal.App.handleLocalCommand(App.java:248)
	at org.asamk.signal.App.init(App.java:198)
	at org.asamk.signal.Main.main(Main.java:52)
```

Using last available version: signal-cli 0.9.2

**Comment by bonfus** [comment]
Short updated: the problem only appears with the signal-cli package from archlinux's AUR repository. Running the precompiled release from github works fine.

**Comment by AsamK** [comment]
Ah, looks like there was an incompatible change in libsignal-client 0.9.8 patch version ... Can you try downgrading that to 0.9.7?

**Comment by AsamK** [comment]
Yeah this commit has a breaking change: https://github.com/signalapp/libsignal-client/commit/64ad39c54d1fef54e90586d50af0574fb2eb16fb#diff-e01273c0c9ee503ff6d52ed9656cfb246d6e331e7f528d6ce0042e0097a9d389R12

**Comment by bonfus** [comment]
You already figured it out, but yes, downgrading to 0.9.7 works, thanks!

**Comment by bemug** [comment]
Got the same error. I confirm downgrading to 0.9.7 fixes the issue.
