### ISSUE TITLE
FFI_RETURN_INPUT_ERROR when trying to verify number

### ISSUE THREAD

**Issue by vic-951** [AsamK/signal-cli#817]
Hello there, I´ve installed signal-client with java 17 on my Raspberry Pi 4. But at the last steps I get an error, I can´t solve.
The step with verification and the captcha works, I get the code from Signal
`signal-cli -u "+number" register --captcha signalcaptcha`

then I want to 
`signal-cli -u "+number" verify 998129`

and I get these errors

java.lang.IllegalArgumentException: org.signal.zkgroup.InvalidInputException: FFI_RETURN_INPUT_ERROR
        at org.signal.zkgroup.ServerPublicParams.<init>(ServerPublicParams.java:25)
        at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:29)
        at org.asamk.signal.manager.SignalDependencies.lambda$getGroupsV2Operations$5(SignalDependencies.java:86)
        at org.asamk.signal.manager.SignalDependencies.getOrCreate(SignalDependencies.java:189)
        at org.asamk.signal.manager.SignalDependencies.getGroupsV2Operations(SignalDependencies.java:85)
        at org.asamk.signal.manager.SignalDependencies.lambda$getAccountManager$1(SignalDependencies.java:76)
        at org.asamk.signal.manager.SignalDependencies.getOrCreate(SignalDependencies.java:189)
        at org.asamk.signal.manager.SignalDependencies.getAccountManager(SignalDependencies.java:72)
        at org.asamk.signal.manager.SignalDependencies.lambda$getKeyBackupService$15(SignalDependencies.java:156)
        at org.asamk.signal.manager.SignalDependencies.getOrCreate(SignalDependencies.java:189)
        at org.asamk.signal.manager.SignalDependencies.getKeyBackupService(SignalDependencies.java:155)
        at org.asamk.signal.manager.ManagerImpl.<init>(ManagerImpl.java:177)
        at org.asamk.signal.manager.RegistrationManager.verifyAccount(RegistrationManager.java:182)
        at org.asamk.signal.commands.VerifyCommand.handleCommand(VerifyCommand.java:37)
        at org.asamk.signal.App.handleRegistrationCommand(App.java:233)
        at org.asamk.signal.App.init(App.java:190)
        at org.asamk.signal.Main.main(Main.java:52)
Caused by: org.signal.zkgroup.InvalidInputException: FFI_RETURN_INPUT_ERROR
        ... 17 more

how can I solve the problem or what did I wrong?

**Comment by AsamK** [comment]
You probably built the wrong version of libsignal-client or libzkgroup. Make sure to use the same version as that `.jar` file in the lib folder.

**Comment by vic-951** [comment]
thank you very much for your answer, can you tell me how I check the versions?

**Comment by AsamK** [comment]
The latest signal-cli release requires libsignal-client 0.9.7 and libzkgroup 0.8.2
