### ISSUE TITLE
group sync requests are confirmed without ensuring the response

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#83]
This could be the cause of #82:

- have signal-cli master
- have poor network
- link slave
- slave sends sync requests
- signal-cli reads request out of the queue, fails to respond
- request is gone but will never be answered

```
C:\Users\Benni\repositories\signal-cli\build\install\signal-cli\bin>signal-cli.bat -u +49XXXXXXXXXXX addDevice --uri "tsdevice:/?uuid=XXXXXXXXXXX&pub_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
C:\Users\Benni\repositories\signal-cli\build\install\signal-cli\bin>signal-cli.bat -u +49XXXXXXXXXXX receive

java.io.IOException: Error writing request body to server
        at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3479)
        at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3462)
        at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3457)
        at org.whispersystems.signalservice.api.crypto.AttachmentCipherOutputStream.write(AttachmentCipherOutputStream.java:70)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:516)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:379)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.createAttachmentPointer(SignalServiceMessageSender.java:486)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.createMultiDeviceGroupsContent(SignalServiceMessageSender.java:316)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:216)
        at org.asamk.signal.Manager.sendSyncMessage(Manager.java:877)
        at org.asamk.signal.Manager.sendGroups(Manager.java:1474)
        at org.asamk.signal.Manager.handleMessage(Manager.java:1204)
        at org.asamk.signal.Manager.receiveMessages(Manager.java:1159)
        at org.asamk.signal.Main.handleCommands(Main.java:423)
        at org.asamk.signal.Main.main(Main.java:73)
Envelope from: ?MYSELF? +49XXXXXXXXXXX (device: 9)
Timestamp: 1496079550740 (2017-05-29T17:39:10.740Z)
Received a sync message
Received sync request
 - groups request
```

**Comment by AsamK** [comment]
I won't improve this anytime soon, it's a corner case, that would need a larger solution to fix reliably.
Due the the signal protocol encryption, messages should only be sent after all messages from the queue have been received and decrypted. It probably needs a persistent cache for outgoing messages and retry logic ...
