### ISSUE TITLE
GraalVM: Failed to access RecordComponents of type `org.asamk.signal.json.JsonCallMessage$Answer`

### ISSUE THREAD

**Issue by technillogue** [AsamK/signal-cli#841]
I'm not sure how to fix this because Answer is already in reflect-config.json: https://github.com/AsamK/signal-cli/blob/master/graalvm-config-dir/reflect-config.json#L446

```
java.lang.IllegalArgumentException: Failed to access RecordComponents of type `org.asamk.signal.json.JsonCallMessage$Answer` (through reference chain: java.util.HashMap["envelope"])
       at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3395)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.lambda$subscribeReceive$0(SignalJsonRpcDispatcherHandler.java:95)
       at org.asamk.signal.json.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.java:35)
       at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$9(ManagerImpl.java:1014)
       at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
       at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
       at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
       at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$10(ManagerImpl.java:1012)
       at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:203)
       at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:172)
       at org.asamk.signal.manager.ManagerImpl.receiveMessagesInternal(ManagerImpl.java:1191)
       at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$11(ManagerImpl.java:1010)
       at java.lang.Thread.run(Thread.java:833)
       at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
       at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

```

**Comment by AsamK** [comment]
The accessor methods were missing for that record.

**Comment by technillogue** [comment]
Thank you!
