### ISSUE TITLE
Fix or more informative error for unauthorized device headers

### ISSUE THREAD

**Issue by technillogue** [AsamK/signal-cli#843]
On Android, the same group has 
```GroupSendUtil: Can use sender key for 231/233 recipients.
GroupSendUtil: Successfully sent using sender key to 231/231 sender key targets.
GroupSendUtil: Need to do 2 legacy sends.
GroupSendUtil: Successfully sent using 1:1 to 2/2 legacy targets
```

With signal-cli:

```
2021-12-22T20:34:42.637Z [main] WARN LibSignal - [SignalServiceMessageSender]: [sendGroupMessage][1640205281816] Pipe failed, falling back... (AuthorizationFailedException: [401] Authorization failed!)
2021-12-22T20:34:42.850Z [main] WARN org.asamk.signal.manager.helper.SendHelper - Someone had a bad UD header. Falling back to legacy sends.
org.whispersystems.signalservice.internal.push.exceptions.InvalidUnidentifiedAccessHeaderException: StatusCode: 401
       at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendGroupMessage(PushServiceSocket.java:499)
       at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupMessage(SignalServiceMessageSender.java:1909)
       at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendGroupDataMessage(SignalServiceMessageSender.java:429)
       at org.asamk.signal.manager.helper.SendHelper.lambda$sendGroupMessage$3(SendHelper.java:156)
       at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternalWithSenderKey(SendHelper.java:444)
       at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternal(SendHelper.java:318)
       at org.asamk.signal.manager.helper.SendHelper.sendGroupMessage(SendHelper.java:147)
       at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:134)
       at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:111)
       at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:628)
       at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:716)
       at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:138)
       at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:25)
       at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:15)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler$CommandRunnerImpl.handleCommand(SignalJsonRpcDispatcherHandler.java:211)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.parseParamsAndRunCommand(SignalJsonRpcDispatcherHandler.java:322)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.runCommand(SignalJsonRpcDispatcherHandler.java:270)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleRequest(SignalJsonRpcDispatcherHandler.java:153)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.lambda$handleConnection$1(SignalJsonRpcDispatcherHandler.java:119)
       at org.asamk.signal.jsonrpc.JsonRpcReader.handleRequest(JsonRpcReader.java:68)
       at org.asamk.signal.jsonrpc.JsonRpcReader.readMessages(JsonRpcReader.java:43)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:119)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:85)
       at org.asamk.signal.commands.JsonRpcDispatcherCommand.handleCommand(JsonRpcDispatcherCommand.java:54)
       at org.asamk.signal.App.handleLocalCommand(App.java:252)
       at org.asamk.signal.App.init(App.java:202)
       at org.asamk.signal.Main.main(Main.java:53)
2021-12-22T20:34:42.853Z [main] DEBUG org.asamk.signal.manager.helper.SendHelper - Need to do 237 legacy sends.
```

It would be nice to get numbers for the group members with bad UD headers.

By the way, great work on implementing senderkeys.

**Comment by AsamK** [comment]
I've also seen that error for larger groups, I'm guessing that it's related to incorrect profile keys, because the access keys are derived from the profile keys.
However it's not easy to see which members have the wrong access key. For sender key sending all access keys are XORed and then sent as a single header to the server ... I haven't found out yet what the Android app does differently.
https://github.com/signalapp/Signal-Server/blob/9a5ffea0addd476880eda05c607a1f2fe8481099/service/src/main/java/org/whispersystems/textsecuregcm/controllers/MessageController.java#L402

**Comment by AsamK** [comment]
The issue was with recipients that have unrestricted sealed sender enabled, signal-cli handled those differently than Signal-Android.
