### ISSUE TITLE
Failed to create sender keys path 

### ISSUE THREAD

**Issue by technillogue** [AsamK/signal-cli#844]
This is using 9a7273. Most messages are sent successfully now, but doesn't seem to be using senderkeys

```
INFO core:448: input to signal: {"jsonrpc": "2.0", "id": "send-1640213899186-faec", "method": "send", "params": {"message": "bob\u2019s burgers in the style of akira\nTook 1m53s to generate, 0.6208 loss, \n\ufffc", "quote-timestamp": 1640213492764, "quote-author": "+16175191472", "quote-message": "bob\u2019s burgers in the style of akira", "mention": "74:1:+16175191472", "attachments": ["/app/progress.png"], "group-id": "72Z8qDeqm2BB9dYRXPGNRT7YFQTcgYyhKBvX9zU7AgY="}}
2021-12-22T22:58:19.187Z [main] DEBUG org.asamk.signal.jsonrpc.JsonRpcReader - Received json rpc request, method: send
2021-12-22T22:58:19.188Z [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: US
2021-12-22T22:58:19.188Z [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: US
2021-12-22T22:58:19.188Z [main] DEBUG LibSignal - [SignalServiceMessageSender]: Using pipe to retrieve attachment upload attributes...
2021-12-22T22:58:19.933Z [main] DEBUG org.asamk.signal.manager.helper.UnidentifiedAccessHelper - Using phone number privacy sender certificate for message to RecipientId[id=3]
...
2021-12-22T22:58:19.956Z [main] DEBUG org.asamk.signal.manager.helper.UnidentifiedAccessHelper - Using phone number privacy sender certificate for message to RecipientId[id=297]
2021-12-22T22:58:19.956Z [main] DEBUG org.asamk.signal.manager.helper.SendHelper - Can use sender key for 238/240 recipients.
der certificate for message to RecipientId[id=298]
2021-12-22T22:58:19.956Z [main] DEBUG org.asamk.signal.manager.helper.SendHelper - Can use sender key for 238/240 recipients.
java.lang.AssertionError: Failed to create sender keys path
c.SignalJsonRpcDispatcherHandler - Command execution failed
java.lang.AssertionError: Failed to create sender keys path
       at org.asamk.signal.manager.storage.senderKeys.SenderKeyRecordStore.getSenderKeyFile(SenderKeyRecordStore.java:184)
       at org.asamk.signal.manager.storage.senderKeys.SenderKeyRecordStore.getCreateTimeForKey(SenderKeyRecordStore.java:64)
       at org.asamk.signal.manager.storage.senderKeys.SenderKeyStore.getCreateTimeForOurKey(SenderKeyStore.java:81)
       at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternalWithSenderKey(SendHelper.java:421)
       at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternal(SendHelper.java:318)
       at org.asamk.signal.manager.helper.SendHelper.sendGroupMessage(SendHelper.java:147)
       at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:134)
       at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:111)
       at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:628)
       at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:716)
       at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:138)
       at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:25)
INFO core:230: signal-cli: {"jsonrpc":"2.0","error":{"code":-32603,"message":"Failed to create sender keys path","data":null},"id":"send-1640213899186-faec"}

INFO core:448: input to signal-cli: {"jsonrpc": "2.0", "id": "send-1640213918209-f58a", "method": "send", "params": {"message": "South Park in the style of Totoro\nTook 1m52s to generate, 0.6241 loss, \n\ufffc", "quote-timestamp": 1640213526391, "quote-author": "+18186184348", "quote-message": "South Park in the style of Totoro", "mention": "72:1:+18186184348", "attachments": ["/app/progress.png"], "group-id": "72Z8qDeqm2BB9dYRXPGNRT7YFQTcgYyhKBvX9zU7AgY="}}
2021-12-22T22:58:38.210Z [main] DEBUG org.asamk.signal.jsonrpc.JsonRpcReader - Received json rpc request, method: send
2021-12-22T22:58:38.210Z [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: US
2021-12-22T22:58:38.210Z [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: US
2021-12-22T22:58:38.210Z [main] DEBUG LibSignal - [SignalServiceMessageSender]: Using pipe to retrieve attachment upload attributes...
2021-12-22T22:58:38.886Z [main] DEBUG org.asamk.signal.manager.helper.UnidentifiedAccessHelper - Using phone number privacy sender certificate for message to RecipientId[id=3]

2021-12-22T22:58:38.909Z [main] DEBUG org.asamk.signal.manager.helper.UnidentifiedAccessHelper - Using phone number privacy sender certificate for message to RecipientId[id=298]
2021-12-22T22:58:38.909Z [main] DEBUG org.asamk.signal.manager.helper.SendHelper - Can use sender key for 238/240 recipients.
java.lang.AssertionError: Failed to create sender keys path
c.SignalJsonRpcDispatcherHandler - Command execution failed
java.lang.AssertionError: Failed to create sender keys path
       at org.asamk.signal.manager.storage.senderKeys.SenderKeyRecordStore.getSenderKeyFile(SenderKeyRecordStore.java:184)
       at org.asamk.signal.manager.storage.senderKeys.SenderKeyRecordStore.getCreateTimeForKey(SenderKeyRecordStore.java:64)
       at org.asamk.signal.manager.storage.senderKeys.SenderKeyStore.getCreateTimeForOurKey(SenderKeyStore.java:81)
       at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternalWithSenderKey(SendHelper.java:421)
       at org.asamk.signal.manager.helper.SendHelper.sendGroupMessageInternal(SendHelper.java:318)
       at org.asamk.signal.manager.helper.SendHelper.sendGroupMessage(SendHelper.java:147)
       at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:134)
       at org.asamk.signal.manager.helper.SendHelper.sendAsGroupMessage(SendHelper.java:111)
       at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:628)
       at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:716)
       at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:138)
       at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:25)
       at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:15)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler$CommandRunnerImpl.handleCommand(SignalJsonRpcDispatcherHandler.java:211)
       at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.parseParamsAndRunCommand(SignalJsonRpcDispatcherHandler.java:322)
       at org.asamk.signal.manager.util.IOUtils.createPrivateDirectories(IOUtils.java:43)
2021-12-22T22:58:59.914Z [Thread-1] INFO LibSignal - [WebSocketConnection]: [normal:2011973147] Sending keep alive...
2021-12-22T22:58:59.914Z [Thread-1] INFO LibSignal - [WebSocketConnection]: [unidentified:454886271] Sending keep alive...
2021-12-22T22:59:54.916Z [Thread-1] INFO LibSignal - [WebSocketConnection]: [normal:2011973147] Sending keep alive...
2021-12-22T22:59:54.916Z [Thread-1] INFO LibSignal - [WebSocketConnection]: [unidentified:454886271] Sending keep alive...
```

**Comment by AsamK** [comment]
Looks like it fails to create the sender-keys directory, also the stacktrace appears to be incomplete ...
Can you check if your user has write access to the config directory?
`ls -ld ~/.local/share/signal-cli/data/+*.d{,/sender-keys}`

I've also added some additional logging to hopefully print the actual error message.

**Comment by technillogue** [comment]
This one might be on me, it's running on FUSE to upload data on signal-cli fsyncs. This hasn't happened before though. Signal-cli is running as root in a container. 
```
+12692069506.d:
total 38
drwx------ 2 root root      0 Dec 23 22:26 group-cache
drwx------ 2 1000 1000      0 Dec 23 22:26 identities
drwx------ 2 1000 1000      0 Dec 23 22:26 pre-keys
-rw-rw-r-- 1 1000 1000 250266 Dec 22 07:38 recipients-store
drwx------ 2 root root      0 Dec 23 22:26 sender-keys
drwx------ 2 1000 1000      0 Dec 23 22:26 sessions
-rw-r--r-- 1 root root  65533 Dec 22 07:47 shared-sender-keys-store
drwx------ 2 1000 1000      0 Dec 23 22:26 signed-pre-keys

+12692069506.d/sender-keys:
total 0
-rw-r--r-- 1 root root  404 Dec 22 20:02 101_1_668b736d-f3aa-46f7-b51f-7d45adfb3a4a
-rw-r--r-- 1 root root   85 Dec 22 18:59 101_2_0c0b7f87-6527-48f1-996c-7fc7164ad5cb
-rw-r--r-- 1 root root  746 Dec 22 18:59 103_1_0ab63015-30fa-41fd-9fd6-77292256d8f9
-rw-r--r-- 1 root root  121 Dec 23 04:16 105_1_c0988728-4d8e-4fbb-b8ba-8be8b1e94473
-rw-r--r-- 1 root root   85 Dec 22 18:59 107_2_b923a44a-a833-4861-a783-6b97bb3e0b78
-rw-r--r-- 1 root root   83 Dec 23 03:05 112_1_3167b295-4d83-47cc-9c69-6430881a6ffe
-rw-r--r-- 1 root root   84 Dec 22 08:57 115_1_9992c3b4-a296-4ac5-a762-bd5f81eb1af8
-rw-r--r-- 1 root root  338 Dec 22 08:18 11_1_ff2a58d0-232d-45e6-b466-7f4004b6d660
-rw-r--r-- 1 root root  255 Dec 22 19:13 121_1_bd064369-9280-485b-a7f8-1ac8ddd69f05
-rw-r--r-- 1 root root  976 Dec 22 18:59 122_1_61b2ed87-6104-4d0d-81d7-2cc286a1da3f
-rw-r--r-- 1 root root  244 Dec 22 18:59 127_1_ba2febdd-cec8-4a72-a9e0-cc63a47e9c61
-rw-r--r-- 1 root root  285 Dec 22 08:21 129_1_23c8e7a0-1a15-4cf1-b6ac-faa774798c63
-rw-r--r-- 1 root root   85 Dec 22 19:00 131_1_9194c819-b2e7-45b6-b5cc-0e95d199e492
-rw-r--r-- 1 root root   84 Dec 22 19:16 13_3_2282880c-00da-4ada-8cf8-e12087d19692
-rw-r--r-- 1 root root   85 Dec 22 08:47 140_1_f5afc91f-9231-4c0d-9b9a-53c7e638e4ae
-rw-r--r-- 1 root root   82 Dec 22 18:59 148_1_e23a53c2-37ed-43a2-a88b-e15865caa000
-rw-r--r-- 1 root root   83 Dec 22 18:59 155_1_9748fc5d-2103-4090-b4c0-68f7a4a0460d
-rw-r--r-- 1 root root 1583 Dec 22 18:59 156_1_985b9fca-4404-4e6a-8ed7-5cab06e6a0c8
-rw-r--r-- 1 root root  768 Dec 22 18:57 156_2_25af5de9-7f7c-4777-ae76-147b38406117
-rw-r--r-- 1 root root  170 Dec 22 08:13 158_1_7cef0326-96c4-4e82-b946-b1d40ca40713
-rw-r--r-- 1 root root   85 Dec 22 18:59 16_7_be754bc1-8e22-4e92-993a-8a38495829b3
-rw-r--r-- 1 root root   85 Dec 23 03:06 175_1_d047c9fc-8069-4b24-a957-ea6e0cddf866
-rw-r--r-- 1 root root   85 Dec 22 18:59 180_2_505e32f2-6984-4e5a-9e56-830af1ba1a85
-rw-r--r-- 1 root root   84 Dec 23 01:52 18_2_2908d163-48a5-4dad-9d38-069be49dabbb
-rw-r--r-- 1 root root   83 Dec 22 19:00 192_1_c1555e84-c20b-4865-8a17-e465f340de05
-rw-r--r-- 1 root root 1272 Dec 22 07:55 193_1_f1dfe478-4d4c-49af-a896-719df0c4ef20
-rw-r--r-- 1 root root  119 Dec 22 08:42 1_3_28efaa36-bde7-4d14-a97e-2eb55f6e2d5f
-rw-r--r-- 1 root root  119 Dec 22 07:51 1_3_2e0b7288-7e65-40f8-ae98-cae30348fda5
-rw-r--r-- 1 root root  120 Dec 22 07:47 1_3_a2b42471-1213-49c2-8a9a-42a3e5de00ca
-rw-r--r-- 1 root root   85 Dec 22 18:59 202_2_90dc6ab5-57f4-412f-9cee-12f68bd3397d
-rw-r--r-- 1 root root   85 Dec 23 22:33 205_1_abeeb7c1-471e-48ac-bb53-596c274ca9ec
-rw-r--r-- 1 root root  170 Dec 23 01:51 21_3_d5f75507-c383-4ebe-b5dc-6562b124a731
-rw-r--r-- 1 root root   85 Dec 22 18:59 21_4_1cff8a66-6c8b-49bf-ab5d-9b0c511643f3
-rw-r--r-- 1 root root  170 Dec 22 18:59 227_2_382ed787-dadf-4f37-a592-9e3c505ed802
-rw-r--r-- 1 root root  835 Dec 22 18:59 234_1_09b5ca19-619e-4f8a-9692-24bc35c973c3
-rw-r--r-- 1 root root   84 Dec 22 19:00 234_4_4543bb3f-aafa-45ea-b941-23d181f9ae42
-rw-r--r-- 1 root root   85 Dec 22 18:59 239_2_360fd921-5743-4da9-877f-8ab07c510bc8
-rw-r--r-- 1 root root   85 Dec 22 19:06 241_1_ca786185-007d-483e-8d9c-aba24f7c31be
-rw-r--r-- 1 root root   85 Dec 22 19:26 264_1_52a84be5-9cdb-4c7d-91bb-edad56311ce1
-rw-r--r-- 1 root root   85 Dec 22 20:49 266_1_6a690b5d-fe2f-49af-85a2-79f54384228b
-rw-r--r-- 1 root root   86 Dec 23 22:58 313_1_036bb85c-c85c-42ac-aca3-5d9b3ce97486
-rw-r--r-- 1 root root   85 Dec 23 22:37 3_1_a852ef93-1116-4575-bdc4-22fb889e8991
-rw-r--r-- 1 root root   85 Dec 23 22:38 3_4_abb850fa-6fd2-4868-aadc-eb5ed2ee28f9
-rw-r--r-- 1 root root   85 Dec 23 03:14 40_1_34f550d3-8c7c-4056-9c5f-590e7a046938
-rw-r--r-- 1 root root  338 Dec 22 18:59 4_1_cc660a16-423b-4b62-aa70-c856942eb36a
-rw-r--r-- 1 root root 2436 Dec 22 07:47 4_3_06625a7f-dcc4-4925-b1fd-f2462d431125
-rw-r--r-- 1 root root 1647 Dec 22 07:51 4_3_e9f72732-0494-4411-abbf-a63a1f54b852
-rw-r--r-- 1 root root   85 Dec 22 19:38 55_3_e587c4a1-1b74-4a2e-9970-018e1c019cfb
-rw-r--r-- 1 root root   85 Dec 22 19:27 59_1_1368f4f2-d741-4bcb-81e7-e0335e414c30
-rw-r--r-- 1 root root   85 Dec 22 19:11 5_1_cb0c0e22-6cba-4dc3-8faf-64ed77f5f558
-rw-r--r-- 1 root root  170 Dec 22 19:00 5_2_81d5493d-fa0f-467d-b26d-aea5a7f4e502
-rw-r--r-- 1 root root  170 Dec 22 20:16 61_1_868050ad-90d1-4f27-b983-5c5a33f6da1a
-rw-r--r-- 1 root root   85 Dec 23 23:02 61_2_ed186cb1-2cb5-4a52-9b8f-c4ab667457ab
-rw-r--r-- 1 root root   85 Dec 22 07:52 68_1_d5b2012b-f0b6-4f99-8d5f-089be16dd9b6
-rw-r--r-- 1 root root   85 Dec 22 07:53 68_2_b4454c2a-267e-4795-82e9-50ab6078e568
-rw-r--r-- 1 root root  160 Dec 23 03:56 6_1_4f978fbb-b8c1-46e7-a145-7991e57fe8a5
-rw-r--r-- 1 root root  352 Dec 23 03:56 6_1_a6b01134-4b07-4da0-aa77-872c8c2d4ccf
-rw-r--r-- 1 root root  208 Dec 22 20:15 6_2_b40d9107-4d33-4ff3-9929-bfc5fd61a23a
-rw-r--r-- 1 root root   85 Dec 22 08:22 72_1_7b410b8e-4816-4466-b683-ba76393636df
-rw-r--r-- 1 root root  170 Dec 23 04:16 77_1_5983b1fa-3fe2-4b69-a41d-348e7030292f
-rw-r--r-- 1 root root  170 Dec 22 19:35 81_1_b3c1ef9b-de66-42d0-97ae-85c782d158ed
-rw-r--r-- 1 root root   85 Dec 23 01:54 82_2_01e7f650-0c87-4b08-b121-f9a8a086dae6
-rw-r--r-- 1 root root  285 Dec 22 19:00 8_4_49715cd8-2251-4acb-885e-01f49bc701d6
-rw-r--r-- 1 root root   85 Dec 22 19:32 92_3_1951d6fa-ca86-45fe-982e-43f3691f519d
-rw-r--r-- 1 root root   85 Dec 23 03:13 95_1_84aa8ede-6c2d-452f-bf98-92baf3da8e26
-rw-r--r-- 1 root root  160 Dec 22 19:22 99_1_b3e89309-283b-487e-a055-248dca628e00
```

**Comment by AsamK** [comment]
ok, yeah probably related to the FUSE filesystem. But strange, if the directory exists it shouldn't even attempt to create it ...
Could you post another verbose log with the latest signal-cli master? That might contain a hint to what's going on.

**Comment by technillogue** [comment]
I switched to use a new account with latest master and could not reproduce this issue :woman_shrugging:

**Comment by technillogue** [comment]
Yeah, the issue was from the FUSE process running out of memory. Is there any chance there would be a separate write / fsync per group member per message sent?
