### ISSUE TITLE
Abstract sockets not supported

### ISSUE THREAD

**Issue by kjk11** [AsamK/signal-cli#854]
Since updating the package I receive the following error message when trying to run signal-cli in daemon mode:

java.lang.UnsupportedOperationException: Abstract sockets are not supported by transport org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport
        at org.freedesktop.dbus.connections.transports.AbstractTransport.<init>(AbstractTransport.java:47)
        at org.freedesktop.dbus.connections.transports.AbstractUnixTransport.<init>(AbstractUnixTransport.java:11)
        at org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport.<init>(NativeUnixSocketTransport.java:38)
        at org.freedesktop.dbus.transport.jre.NativeTransportProvider.createTransport(NativeTransportProvider.java:22)
        at org.freedesktop.dbus.connections.transports.TransportBuilder.build(TransportBuilder.java:334)
        at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:154)
        at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:351)
        at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:136)
        at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:214)
        at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:160)
        at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:340)
        at org.asamk.signal.commands.DaemonCommand.runDbusSingleAccount(DaemonCommand.java:277)
        at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:131)
        at org.asamk.signal.App.handleLocalCommand(App.java:252)
        at org.asamk.signal.App.init(App.java:202)
        at org.asamk.signal.Main.main(Main.java:53)

I run jdk-openjdk 17.0.1.u12-1 on arch and have installed through the latest AUR package build. 

Thank you in advance for any help

**Comment by AsamK** [comment]
That's a limitation of the unix socket support in Java. You need to run your DBus daemon with file based sockets, see also: #837
