### ISSUE TITLE
local raspi4

### ISSUE THREAD

**Issue by cacko** [AsamK/signal-cli#866]
here's the thing, I am not saying it is a bug, just trying to figure it out.

so I run daemon --tcp (or socket doesn't matter as longa s it is jsonrpc) then I connect via python steam, asyncio.open_connection for example.

same code works fine on macos, but throws  java.net.SocketTimeoutException on the raspi4, both using java17, same network..etc... but it just doesn't work on the raspi4.

also if I use jsonRpc and put the json directly, it seems to be dependant somehow on the size, let's say if I put just "test" as message all is good, althouhg if I go with big one, it just timesout...

anybody has any idea what needs to be set/alter in the aarch64 java handling ?

**Comment by AsamK** [comment]
Not much information to go on, the stack trace for the exception would be interesting. If it's not shown, run signal-cli with `--verbose` flag.

**Comment by cacko** [comment]
```
2022-01-23T07:40:57.016Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-01-23T07:40:57.398Z [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:161: Initializing libsignal-client version:0.11.0
2022-01-23T07:41:04.580Z [main] INFO LibSignal - [WebSocketConnection]: [provisioning:...] connect()
2022-01-23T07:41:05.512Z [OkHttp https://chat.signal.org/...] INFO LibSignal - [WebSocketConnection]: [provisioning:...] onOpen() connected
sgnl://linkdevice?uuid=tYKMH..w&pub_key=B,..QsSl9hv8q
█████████████████████████████████████████████
█████████████████████████████████████████████
████ ▄▄▄▄▄ █▀█ █▄▀  ▄██▄▄██▄█ ▄▀▄█ ▄▄▄▄▄ ████
████ █   █ █▀▀▀█ ▀▄ ▀██ █▄  ██▀▄▀█ █   █ ████
████ █▄▄▄█ █▀ █▀▀▀  ▄███▄ ▀█▀█   █ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄▀ ▀▄█▄▀ █▄█ ▀ ▀ █ █ █▄▄▄▄▄▄▄████
████▄  ▄ █▄▄▄▄▀▄▀   ▀▄▀▀▀█ ▀▄▄ ▄▀ █ █▄▀▄█████
████▄▄▄▄█▄▄ ▄▀██▀▄█▄ ▄▀█  ▀██▄▀ █    ▀▄█▄████
█████▄▄ ▄▄▄█▀ ▀█▄█  ▀▄▄▄▀█▀▀█▄ ▀▀ ▄▄▄▄ ▀█████
████ ▄▀▄▀ ▄▀▄▄  ▄█▀▄▄█▄██  █ █  █   ██▄█ ████
████   ▀▄█▄▀ ▀▄▄▀▄ ▄▄█▀▀▄ ▄▀█▄ █ ▄▄▀▄▄ ▄█████
█████▀ ▀█ ▄ ▄▄▄█▀▄▀  ██▀▄▀█▀▄█  █▀▀▄▄▄█▄▄████
████ ▄ ▀ ▄▄ ▄ ▀█▄█ ▄▄▄█▀▄  ▀  ▄▀▀▄▄▀▄  ▄█████
████ ▀ ██▀▄▄ ▀▀ ▄▄▀ ▀██▀ ▀█▀█▄▄  ▄ ▄▀██ ▄████
████ ██▄█▄▄ █▄ ▄  ▄ ▀ ▀█ ▀▀▀██ ▀▀▀▄▀▄▄ ▄▄████
████ ██ ▄ ▄ ▀▀▄█▀█▄ ▀▄█▀  ▀█▀▄▀▄▄ ▀▀▄▄▄ ▄████
████▄█▄█▄█▄█  █▀█ ▀▄ ▄██▀▀  ▄▀▄▀ ▄▄▄   ▀▄████
████ ▄▄▄▄▄ █▄█ █ █▀▄▄█▄▀▄▀ ▀▄▄█▄ █▄█ █▄▄▄████
████ █   █ █  ▄ ▀ ▄▀▀▄▄▀ █▄ ▄█▄▄▄    ▄▄█▄████
████ █▄▄▄█ █ █▄▀▄██  █▄█▄ ██▀█▀▄▄ ▀ █▄█▄ ████
████▄▄▄▄▄▄▄█▄▄███▄▄▄▄▄▄▄▄▄▄███▄███▄▄█▄▄▄▄████
█████████████████████████████████████████████
█████████████████████████████████████████████
2022-01-23T07:41:43.865Z [main] INFO LibSignal - [WebSocketConnection]: [provisioning:..] disconnect()
2022-01-23T07:41:43.883Z [main] INFO org.asamk.signal.manager.ProvisioningManagerImpl - Received link information from +..., linking in progress ...
2022-01-23T07:41:43.921Z [main] DEBUG org.asamk.signal.manager.ProvisioningManagerImpl - Finishing new device registration
2022-01-23T07:41:43.956Z [OkHttp https://chat.signal.org/...] INFO LibSignal - [WebSocketConnection]: [provisioning:...] onClosing()
2022-01-23T07:41:43.957Z [OkHttp https://chat.signal.org/...] INFO LibSignal - [WebSocketConnection]: [provisioning:...] onClose()
2022-01-23T07:41:45.126Z [main] DEBUG org.asamk.signal.manager.storage.recipients.RecipientStore - Got new recipient, both uuid and number are unknown
2022-01-23T07:41:45.203Z [main] DEBUG org.asamk.signal.manager.storage.recipients.RecipientStore - Adding new recipient RecipientId[id=1] with address RecipientAddress[uuid=Optional[...], number=Optional[+...]]
2022-01-23T07:41:45.332Z [main] DEBUG org.asamk.signal.manager.ProvisioningManagerImpl - Refreshing pre keys
2022-01-23T07:42:15.832Z [main] ERROR org.asamk.signal.manager.ProvisioningManagerImpl - Failed to refresh pre keys.
2022-01-23T07:42:15.833Z [main] DEBUG org.asamk.signal.manager.ProvisioningManagerImpl - Requesting sync data
2022-01-23T07:42:16.703Z [main] WARN org.asamk.signal.manager.helper.ProfileHelper - Failed to retrieve profile, ignoring: [401] Authorization failed!
2022-01-23T07:42:16.717Z [main] WARN org.asamk.signal.manager.helper.ProfileHelper - Failed to retrieve profile, ignoring: java.lang.RuntimeException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [401] Authorization failed!
2022-01-23T07:42:46.110Z [main] WARN org.asamk.signal.manager.helper.UnidentifiedAccessHelper - Failed to get sender certificate, ignoring: [401] Authorization failed!
2022-01-23T07:42:46.210Z [main] DEBUG LibSignal - [PushServiceSocket]: Fetching prekeys for .....*, i.e. GET /v2/keys/..../*
2022-01-23T07:42:46.614Z [main] WARN LibSignal - [SignalServiceMessageSender]: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [401] Authorization failed!
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1714)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1695)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1677)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1666)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1602)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1596)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:609)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2132)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2107)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1734)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendSyncMessage(SignalServiceMessageSender.java:542)
	at org.asamk.signal.manager.helper.SendHelper.sendSyncMessage(SendHelper.java:204)
	at org.asamk.signal.manager.helper.SyncHelper.requestSyncGroups(SyncHelper.java:277)
	at org.asamk.signal.manager.helper.SyncHelper.requestAllSyncData(SyncHelper.java:51)
	at org.asamk.signal.manager.ManagerImpl.requestAllSyncData(ManagerImpl.java:716)
	at org.asamk.signal.manager.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:141)
	at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
	at org.asamk.signal.App.handleProvisioningCommand(App.java:223)
	at org.asamk.signal.App.init(App.java:170)
	at org.asamk.signal.Main.main(Main.java:53)

```

odd thing is, it works with no issues on another pi4 on the same network just the working one is on wifi, hence there is most likely a bit more latency there, not that it matters.

**Comment by cacko** [comment]
f**k it, it runs perfect on the other pi4.
