### ISSUE TITLE
[Question] DBus: send messages w/ user mentions

### ISSUE THREAD

**Issue by morph027** [AsamK/signal-cli#873]
I was digging through the issues already and found #658, #726 and some more which are refering to f39983f.

Looking at the code and also by introspecting DBus, i'm somehow unable to find any method or parameter to create mentions for messages being sent through DBus.

In #584, i see 53b84bad0280694a19e47d6f76620f8a140fdd15 has added mentions for sending and there's a change to DbusSignalImpl.java too, but not sure how to pass a message with mentions.

Can you give me a hint into the right direction? ;)

**Comment by morph027** [comment]
Looks like the parameter just needs to be added to the methods in https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/dbus/DbusSignalImpl.java#L196 and https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/dbus/DbusSignalImpl.java#L201.

Will try if i'm able to get it working.

**Comment by morph027** [comment]
Does this look sane (sorry, not real into Java programming ;) ) ?

```
diff --git a/src/main/java/org/asamk/signal/dbus/DbusSignalImpl.java b/src/main/java/org/asamk/signal/dbus/DbusSignalImpl.java
index ae9edfe..0854bd1 100644
--- a/src/main/java/org/asamk/signal/dbus/DbusSignalImpl.java
+++ b/src/main/java/org/asamk/signal/dbus/DbusSignalImpl.java
@@ -410,6 +410,27 @@ public class DbusSignalImpl implements Signal {
         }
     }
 
+    @Override
+    public long sendGroupMessage(final String message, final List<String> attachments, final byte[] groupId, final List<Message.Mention> mentions) {
+        try {
+            var results = m.sendMessage(new Message(message,
+                    attachments,
+                    mentions,
+                    Optional.empty(),
+                    Optional.empty()), Set.of(getGroupRecipientIdentifier(groupId)));
+            checkSendMessageResults(results);
+            return results.timestamp();
+        } catch (IOException | InvalidStickerException e) {
+            throw new Error.Failure(e.getMessage());
+        } catch (GroupNotFoundException | NotAGroupMemberException | GroupSendingNotAllowedException e) {
+            throw new Error.GroupNotFound(e.getMessage());
+        } catch (AttachmentInvalidException e) {
+            throw new Error.AttachmentInvalid(e.getMessage());
+        } catch (UnregisteredRecipientException e) {
+            throw new Error.UntrustedIdentity(e.getSender().getIdentifier() + " is not registered.");
+        }
+    }
+
     @Override
     public void sendGroupTyping(
             final byte[] groupId, final boolean stop
```

Compiler fails:

```
> Task :compileJava FAILED
/tmp/signal-cli/src/main/java/org/asamk/signal/dbus/DbusSignalImpl.java:413: error: method does not override or implement a method from a supertype
    @Override
    ^
```

Any hints?

**Comment by morph027** [comment]
Compiles, but throws runtime error:

```
org.freedesktop.dbus.exceptions.DBusException: Exporting non-exportable type: class org.asamk.signal.manager.api.Message$Mention
        at org.freedesktop.dbus.Marshalling.recursiveGetDBusType(Marshalling.java:293)
        at org.freedesktop.dbus.Marshalling.recursiveGetDBusType(Marshalling.java:219)
        at org.freedesktop.dbus.Marshalling.getDBusType(Marshalling.java:135)
        at org.freedesktop.dbus.Marshalling.getDBusType(Marshalling.java:120)
        at org.freedesktop.dbus.messages.ExportedObject.generateMethodsXml(ExportedObject.java:180)
        at org.freedesktop.dbus.messages.ExportedObject.generateIntrospectionXml(ExportedObject.java:309)
        at org.freedesktop.dbus.messages.ExportedObject.<init>(ExportedObject.java:55)
        at org.freedesktop.dbus.connections.AbstractConnection.exportObject(AbstractConnection.java:309)
        at org.freedesktop.dbus.connections.AbstractConnection.exportObject(AbstractConnection.java:329)
        at org.asamk.signal.commands.DaemonCommand.exportDbusObject(DaemonCommand.java:368)
        at org.asamk.signal.commands.DaemonCommand.exportMultiAccountManager(DaemonCommand.java:357)
        at org.asamk.signal.commands.DaemonCommand.lambda$runDbusMultiAccount$10(DaemonCommand.java:317)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at org.asamk.signal.commands.DaemonCommand.lambda$runDbusMultiAccount$11(DaemonCommand.java:319)
        at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:341)
        at org.asamk.signal.commands.DaemonCommand.runDbusMultiAccount(DaemonCommand.java:288)
        at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:190)
        at org.asamk.signal.App.handleMultiLocalCommand(App.java:332)
        at org.asamk.signal.App.init(App.java:178)
        at org.asamk.signal.Main.main(Main.java:53)
```

**Comment by morph027** [comment]
Jip, got that already while digging deeper through the code. I'm stil trying to figure out how to add it to the methods, as the basics are in there already, the default method is just passing an empty list of mentions.

Will have another look later but would appreciate some help ;)

**Comment by morph027** [comment]
Not getting further with my knowlegde, for me and my project (https://gitlab.com/morph027/signal-cli-dbus-rest-api), it's easier to switch to JSON RPC. Closing this and asking questions in https://github.com/AsamK/signal-cli/discussions/799.
