### ISSUE TITLE
Upgrading from v0.10.0 to v0.10.3 causes "The database disk image is malformed "

### ISSUE THREAD

**Issue by technillogue** [AsamK/signal-cli#885]
This account was previously running on fba7a6a75c838686b645d7934de7d4c75d419d47. I attempted to upgrade to 8e773d92c19533cf4a00bb2e21c30bd4a85e2feb and got this error:

```
2022-02-09T01:45:38.146Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2022-02-09T01:45:38.176Z [main] INFO  LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:161: Initializing libsignal-client version:0.11.0
2022-02-09T01:45:38.186Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-02-09T01:45:38.270Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@77980b5e
2022-02-09T01:45:38.270Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-02-09T01:45:38.272Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-02-09T01:45:38.273Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Error loading state file for user +12406171657: org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed) (RuntimeException)
java.lang.RuntimeException: org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$17(SignalAccount.java:890)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1117)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:886)
        at org.asamk.signal.manager.storage.SignalAccount.initDatabase(SignalAccount.java:236)
        at org.asamk.signal.manager.Manager.init(Manager.java:74)
        at org.asamk.signal.App.loadManager(App.java:347)
        at org.asamk.signal.App.handleLocalCommand(App.java:288)
        at org.asamk.signal.App.init(App.java:208)
        at org.asamk.signal.Main.main(Main.java:58)
Caused by: org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
        at org.sqlite.core.DB.newSQLException(DB.java:1030)
        at org.sqlite.core.DB.newSQLException(DB.java:1042)
        at org.sqlite.core.DB.execute(DB.java:884)
        at org.sqlite.core.CoreStatement.exec(CoreStatement.java:80)
        at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:68)
        at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:110)
        at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
        at org.asamk.signal.manager.storage.Database.getUserVersion(Database.java:73)
        at org.asamk.signal.manager.storage.Database.initDb(Database.java:56)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:35)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:23)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$17(SignalAccount.java:888)
        ... 8 more
```

**Comment by technillogue** [comment]
Deleting account.db works at first, but then fails the next time signal-cli is run

2022-02-09T01:57:39.763Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-02-09T01:57:40.008Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@62f4595b
2022-02-09T01:57:40.009Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-02-09T01:57:40.253Z [main] DEBUG o.asamk.signal.jsonrpc.JsonRpcReader - Received json rpc request, method: send
2022-02-09T01:57:40.253Z [main] WARN  LibSignal - [PhoneNumberFormatter]: Got local CC: US
2022-02-09T01:57:40.261Z [receive-0] DEBUG org.asamk.signal.manager.ManagerImpl - Starting receiving messages
2022-02-09T01:57:40.261Z [receive-0] INFO  LibSignal - [WebSocketConnection]: [normal:358962655] connect()
2022-02-09T01:57:40.267Z [receive-0] INFO  LibSignal - [WebSocketConnection]: [unidentified:1694716505] connect()
2022-02-09T01:57:40.274Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2022-02-09T01:57:40.279Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
2022-02-09T01:57:40.282Z [main] DEBUG LibSignal - [SignalServiceMessageSender]: [1644371860265] Sending a data message.
2022-02-09T01:57:40.352Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [normal:358962655] onOpen() connected
2022-02-09T01:57:40.352Z [RxComputationThreadPool-1] DEBUG o.a.s.m.SignalWebSocketHealthMonitor - WebSocket is now connected
2022-02-09T01:57:40.362Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [unidentified:1694716505] onOpen() connected
2022-02-09T01:57:40.363Z [RxComputationThreadPool-1] DEBUG o.a.s.m.SignalWebSocketHealthMonitor - WebSocket is now connected
2022-02-09T01:57:40.363Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Received indicator that server queue is empty
2022-02-09T01:57:40.363Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2022-02-09T01:57:40.363Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
2022-02-09T01:57:40.993Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - New message received from server
2022-02-09T01:57:40.993Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/sealed_sender.rs:441: deserialized UnidentifiedSenderMessageContent from 412e180d-c500-4c60-b370-14f6693d8ea7.3 with type Whisper
2022-02-09T01:57:40.994Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/session_cipher.rs:551: 412e180d-c500-4c60-b370-14f6693d8ea7.3 creating new chains.
2022-02-09T01:57:40.994Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/state/session.rs:222: Trimming excessive receiver_chain for session with base key 88bc5140897e46918dc512c12c99db9b3ffbd5dd9c571b622eda7302a252b22e, chain count: 6
2022-02-09T01:57:40.995Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/session_cipher.rs:409: decrypted message from 412e180d-c500-4c60-b370-14f6693d8ea7.3 with current session state (base key e920150ac777e3480d4dcb1a47d4451628056c2dd887ea91aa4ffcc30b829255)
2022-02-09T01:57:41.012Z [receive-0] WARN  o.a.s.m.s.s.MessageSendLogStore - Failed delete from message send log
org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
        at org.sqlite.core.DB.newSQLException(DB.java:1030)
        at org.sqlite.core.DB.newSQLException(DB.java:1042)
        at org.sqlite.core.DB.throwex(DB.java:1007)
        at org.sqlite.core.DB.exec(DB.java:178)
        at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:422)
        at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:377)
        at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.deleteEntriesForRecipient(MessageSendLogStore.java:240)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleMessage(IncomingMessageHandler.java:214)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:188)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:154)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:173)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:88)
        at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$11(ManagerImpl.java:767)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        Suppressed: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot rollback - no transaction is active)
                at org.sqlite.core.DB.newSQLException(DB.java:1030)
                at org.sqlite.core.DB.newSQLException(DB.java:1042)
                at org.sqlite.core.DB.throwex(DB.java:1007)
                at org.sqlite.core.DB.exec(DB.java:178)
                at org.sqlite.SQLiteConnection.rollback(SQLiteConnection.java:433)
                at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:249)
                at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.deleteEntriesForRecipient(MessageSendLogStore.java:225)
                ... 9 common frames omitted
2022-02-09T01:57:41.015Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2022-02-09T01:57:41.017Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
2022-02-09T01:57:52.793Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - New message received from server
2022-02-09T01:57:52.793Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/sealed_sender.rs:441: deserialized UnidentifiedSenderMessageContent from 412e180d-c500-4c60-b370-14f6693d8ea7.3 with type Whisper
2022-02-09T01:57:52.794Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/session_cipher.rs:409: decrypted message from 412e180d-c500-4c60-b370-14f6693d8ea7.3 with current session state (base key e920150ac777e3480d4dcb1a47d4451628056c2dd887ea91aa4ffcc30b829255)
2022-02-09T01:57:52.796Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2022-02-09T01:57:52.797Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
2022-02-09T01:58:20.158Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - New message received from server
2022-02-09T01:58:20.158Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/sealed_sender.rs:441: deserialized UnidentifiedSenderMessageContent from b6a54569-b072-4d2e-9bd3-1d9f8b4f4e21.2 with type Whisper
2022-02-09T01:58:20.160Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/session_cipher.rs:551: b6a54569-b072-4d2e-9bd3-1d9f8b4f4e21.2 creating new chains.
2022-02-09T01:58:20.160Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/state/session.rs:222: Trimming excessive receiver_chain for session with base key 086ecc316048ebc4c1df5829b09dcf9214fe93f7db1c2f7804395bcaed7fc579, chain count: 6
2022-02-09T01:58:20.160Z [receive-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/session_cipher.rs:409: decrypted message from b6a54569-b072-4d2e-9bd3-1d9f8b4f4e21.2 with current session state (base key e386d841a5b9019ab91280ee533eff55a57c1ba53c19742023841235f58d862a)
2022-02-09T01:58:20.163Z [receive-0] WARN  o.a.s.m.s.s.MessageSendLogStore - Failed delete from message send log
org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
        at org.sqlite.core.DB.newSQLException(DB.java:1030)
        at org.sqlite.core.DB.newSQLException(DB.java:1042)
        at org.sqlite.core.DB.execute(DB.java:884)
        at org.sqlite.core.DB.executeUpdate(DB.java:922)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.deleteEntriesForRecipient(MessageSendLogStore.java:235)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleMessage(IncomingMessageHandler.java:214)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:188)
        at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:154)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:173)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:88)
        at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$11(ManagerImpl.java:767)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        Suppressed: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot rollback - no transaction is active)
                at org.sqlite.core.DB.newSQLException(DB.java:1030)
                at org.sqlite.core.DB.newSQLException(DB.java:1042)
                at org.sqlite.core.DB.throwex(DB.java:1007)
                at org.sqlite.core.DB.exec(DB.java:178)
                at org.sqlite.SQLiteConnection.rollback(SQLiteConnection.java:433)
                at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:249)
                at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.deleteEntriesForRecipient(MessageSendLogStore.java:225)
                ... 9 common frames omitted

**Comment by AsamK** [comment]
hm, nothing interesting in there ... can you delete the file again and run signal-cli with extended logging again?
You could also run an integrity check on the database file, maybe it gives a hint of what is corrupted:
`sqlite3 .../data/+XXX.d/account.db  "PRAGMA integrity_check;"`

**Comment by cacko** [comment]
I had sqlite errors too after last update

`Mar 06 19:58:51 pi4 task[164000]: WARN  MessageSendLogStore - Failed delete from message send log
Mar 06 19:58:51 pi4 task[164000]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
Mar 06 19:58:51 pi4 task[164000]:         at org.sqlite.core.DB.newSQLException(DB.java:1030)
Mar 06 19:58:51 pi4 task[164000]:         at org.sqlite.core.DB.newSQLException(DB.java:1042)
Mar 06 19:58:51 pi4 task[164000]:         at org.sqlite.core.DB.execute(DB.java:881)
Mar 06 19:58:51 pi4 task[164000]:         at org.sqlite.core.DB.executeUpdate(DB.java:922)
Mar 06 19:58:51 pi4 task[164000]:         at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
Mar 06 19:58:51 pi4 task[164000]:         at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
Mar 06 19:58:51 pi4 task[164000]:         at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
Mar 06 19:58:51 pi4 task[164000]:         at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.deleteEntriesForRecipient(MessageSendLogStore.java:235)
Mar 06 19:58:51 pi4 task[164000]:         at org.asamk.signal.manager.helper.IncomingMessageHandler.handleMessage(IncomingMessageHandler.java:216)
Mar 06 19:58:51 pi4 task[164000]:         at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:190)
Mar 06 19:58:51 pi4 task[164000]:         at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:156)
Mar 06 19:58:51 pi4 task[164000]:         at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:195)
Mar 06 19:58:51 pi4 task[164000]:         at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:106)
Mar 06 19:58:51 pi4 task[164000]:         at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesContinuously(ReceiveHelper.java:79)
Mar 06 19:58:51 pi4 task[164000]:         at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$12(ManagerImpl.java:768)
Mar 06 19:58:51 pi4 task[164000]:         at java.base/java.lang.Thread.run(Thread.java:833)
Mar 06 19:58:51 pi4 task[164000]:         Suppressed: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot rollback - no transaction is active)
Mar 06 19:58:51 pi4 task[164000]:                 at org.sqlite.core.DB.newSQLException(DB.java:1030)
Mar 06 19:58:51 pi4 task[164000]:                 at org.sqlite.core.DB.newSQLException(DB.java:1042)
Mar 06 19:58:51 pi4 task[164000]:                 at org.sqlite.core.DB.throwex(DB.java:1007)
Mar 06 19:58:51 pi4 task[164000]:                 at org.sqlite.core.DB.exec(DB.java:178)
Mar 06 19:58:51 pi4 task[164000]:                 at org.sqlite.SQLiteConnection.rollback(SQLiteConnection.java:433)
Mar 06 19:58:51 pi4 task[164000]:                 at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:249)
Mar 06 19:58:51 pi4 task[164000]:                 at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.deleteEntriesForRecipient(MessageSendLogStore.java:225)
Mar 06 19:58:51 pi4 task[164000]:                 ... 8 common frames omitted`

I know this probably does not help, I had another error before I deleted account.db

`Mar 06 18:55:20 pi4 task[157590]: WARN  MessageSendLogStore - Failed to insert into message send log
Mar 06 18:55:20 pi4 task[157590]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
Mar 06 18:55:20 pi4 task[157590]:         at org.sqlite.core.DB.newSQLException(DB.java:1030)
Mar 06 18:55:20 pi4 task[157590]:         at org.sqlite.core.DB.newSQLException(DB.java:1042)
Mar 06 18:55:20 pi4 task[157590]:         at org.sqlite.core.DB.throwex(DB.java:1007)
Mar 06 18:55:20 pi4 task[157590]:         at org.sqlite.core.DB.exec(DB.java:178)
Mar 06 18:55:20 pi4 task[157590]:         at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:421)
Mar 06 18:55:20 pi4 task[157590]:         at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:377)
Mar 06 18:55:20 pi4 task[157590]:         at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
Mar 06 18:55:20 pi4 task[157590]:         at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.insert(MessageSendLogStore.java:296)
Mar 06 18:55:20 pi4 task[157590]:         at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.insertIfPossible(MessageSendLogStore.java:138)
Mar 06 18:55:20 pi4 task[157590]:         at org.asamk.signal.manager.helper.SendHelper.lambda$sendGroupMessage$6(SendHelper.java:313)
Mar 06 18:55:20 pi4 task[157590]:         at org.whispersystems.signalservice.api.SignalServiceMessageSender.lambda$sendMessage$2(SignalServiceMessageSender.java:1685)
Mar 06 18:55:20 pi4 task[157590]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Mar 06 18:55:20 pi4 task[157590]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Mar 06 18:55:20 pi4 task[157590]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Mar 06 18:55:20 pi4 task[157590]:         at java.base/java.lang.Thread.run(Thread.java:833)
Mar 06 18:55:20 pi4 task[157590]:         Suppressed: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot rollback - no transaction is active)
Mar 06 18:55:20 pi4 task[157590]:                 at org.sqlite.core.DB.newSQLException(DB.java:1030)
Mar 06 18:55:20 pi4 task[157590]:                 at org.sqlite.core.DB.newSQLException(DB.java:1042)
Mar 06 18:55:20 pi4 task[157590]:                 at org.sqlite.core.DB.throwex(DB.java:1007)
Mar 06 18:55:20 pi4 task[157590]:                 at org.sqlite.core.DB.exec(DB.java:178)
Mar 06 18:55:20 pi4 task[157590]:                 at org.sqlite.SQLiteConnection.rollback(SQLiteConnection.java:433)
Mar 06 18:55:20 pi4 task[157590]:                 at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:249)
Mar 06 18:55:20 pi4 task[157590]:                 at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.insert(MessageSendLogStore.java:272)
Mar 06 18:55:20 pi4 task[157590]:                 ... 7 common frames omitted`

dunno, I guess I'll just revert to older version and see of that deadlock is happening there.

**Comment by technillogue** [comment]
Issue also occurs with 0.10.4.1

# sqlite3 account.db  "PRAGMA integrity_check;"
Error: database disk image is malformed

**Comment by technillogue** [comment]
This keeps happening, immediately after deleting the file. I tried manually creating the db following https://github.com/AsamK/signal-cli/blob/master/lib/src/main/java/org/asamk/signal/manager/storage/sendLog/MessageSendLogStore.java#L73, and am able to reproduce the error

```bash
root@120b9134:/app# rm data/+12406171657.d/account.db
root@120b9134:/app# sqlite3 data/+12406171657.d/account.db
SQLite version 3.35.5 2021-04-19 18:32:05
Enter ".help" for usage hints.
sqlite>                     CREATE TABLE message_send_log (
                      _id INTEGER PRIMARY KEY,
                      content_id INTEGER NOT NULL REFERENCES message_send_log_content (_id) ON DELETE CASCADE,
                      recipient_id INTEGER NOT NULL,
                      device_id INTEGER NOT NULL
                    );
sqlite>                     CREATE TABLE message_send_log_content (
                      _id INTEGER PRIMARY KEY,
                      group_id BLOB,
                      timestamp INTEGER NOT NULL,
                      content BLOB NOT NULL,
                      content_hint INTEGER NOT NULL
                    );
sqlite>                     CREATE INDEX mslc_timestamp_index ON message_send_log_content (timestamp);
Error: database disk image is malformed

```

**Comment by technillogue** [comment]
issue appears to be caused by running in FUSE, for unclear reasons
