### ISSUE TITLE
NullPointerException in receiveMessages GroupInfoV1.isBlocked

### ISSUE THREAD

**Issue by brad2014** [AsamK/signal-cli#888]
Signal version: 0.10.3

```
WARN  ReceiveHelper - Message action failed.
java.lang.NullPointerException: Cannot invoke "org.asamk.signal.manager.storage.groups.GroupInfoV1.isBlocked()" because "groupV1" is null
	at org.asamk.signal.manager.helper.StorageHelper.readGroupV1Record(StorageHelper.java:141)
	at org.asamk.signal.manager.helper.StorageHelper.readDataFromStorage(StorageHelper.java:73)
	at org.asamk.signal.manager.actions.RetrieveStorageDataAction.execute(RetrieveStorageDataAction.java:19)
	at org.asamk.signal.manager.helper.ReceiveHelper.handleQueuedActions(ReceiveHelper.java:262)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:135)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:88)
	at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:848)
	at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:831)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:62)
	at org.asamk.signal.App.handleLocalCommand(App.java:292)
	at org.asamk.signal.App.init(App.java:211)
	at org.asamk.signal.Main.main(Main.java:58)
```

Note: I was unable to reproduce this, but if it's ok, I'll put here in case others see it also.

**Comment by AsamK** [comment]
Thanks for reporting!
I assume this happened because the main device migrated a v1 group to v2 and signal-cli didn't handle the temporary inconsistent state correctly.
