### ISSUE TITLE
java.lang.ClassCastException when running listDevices

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#889]
Getting this error when running `listDevices` with a system service. The account was registered with signal-cli.

	$ signal-cli --dbus-system  -u +1234567890  --verbose listDevices

	2022-02-11T18:18:54.587Z [main] DEBUG o.f.d.c.transports.TransportBuilder - Found provider 'NativeTransportProvider' named 'dbus-java-transport-native-unixsocket' providing bustype 'UNIX'
	2022-02-11T18:18:54.706Z [main] DEBUG o.f.d.t.j.NativeUnixSocketTransport - No alternative ISocketProvider found, using built-in implementation
	2022-02-11T18:18:54.782Z [main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 1
	2022-02-11T18:18:54.783Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	2022-02-11T18:18:54.784Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [1, [[1, [o, /org/freedesktop/DBus]], [6, [s, org.freedesktop.DBus]], [2, [s, org.freedesktop.DBus]], [3, [s, Hello]]]]
	2022-02-11T18:18:54.784Z [main] DEBUG o.f.dbus.messages.MethodCall - Appended body, type: null start: 128 end: 128 size: 0
	2022-02-11T18:18:54.784Z [main] DEBUG o.f.dbus.messages.MethodCall - marshalled size ([0, 0, 0, 0]): 000000	00 00 00 00                                            ....              
	2022-02-11T18:18:54.803Z [DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,1) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>Hello, Destination=>org.freedesktop.DBus } { }
	2022-02-11T18:18:54.811Z [DBusConnection] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodReturn(1,1) { Reply Serial=>1, Destination=>:1.88, Sender=>org.freedesktop.DBus, Signature=>s } { :1.88 }
	2022-02-11T18:18:54.812Z [DBusConnection] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method return: MethodReturn(1,1) { Reply Serial=>1, Destination=>:1.88, Sender=>org.freedesktop.DBus, Signature=>s } { :1.88 }
	2022-02-11T18:18:54.829Z [DBusConnection] DEBUG o.f.d.s.m.InputStreamMessageReader - => DBusSignal(1,2) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>NameAcquired, Destination=>:1.88, Sender=>org.freedesktop.DBus, Signature=>s } { :1.88 }
	2022-02-11T18:18:54.829Z [DBusConnection] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming signal: DBusSignal(1,2) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>NameAcquired, Destination=>:1.88, Sender=>org.freedesktop.DBus, Signature=>s } { :1.88 }
	2022-02-11T18:18:54.867Z [main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 2
	2022-02-11T18:18:54.867Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	2022-02-11T18:18:54.867Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [2, [[1, [o, /org/asamk/Signal/_1234567890]], [6, [s, org.asamk.Signal]], [2, [s, org.asamk.Signal]], [3, [s, getThisDevice]]]]
	2022-02-11T18:18:54.868Z [main] DEBUG o.f.dbus.messages.MethodCall - Appended body, type: null start: 144 end: 144 size: 0
	2022-02-11T18:18:54.868Z [main] DEBUG o.f.dbus.messages.MethodCall - marshalled size ([0, 0, 0, 0]): 000000	00 00 00 00                                            ....              
	2022-02-11T18:18:54.868Z [DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,2) { Path=>/org/asamk/Signal/_1234567890, Interface=>org.asamk.Signal, Member=>getThisDevice, Destination=>org.asamk.Signal } { }
	2022-02-11T18:18:54.876Z [DBus Worker Thread-1] DEBUG o.f.dbus.messages.DBusSignal - Converting signal to type: class org.freedesktop.dbus.interfaces.DBus$NameAcquired
	2022-02-11T18:18:54.893Z [DBus Worker Thread-1] DEBUG o.f.d.interfaces.DBus$NameAcquired - Creating message with serial 3
	2022-02-11T18:18:54.893Z [DBus Worker Thread-1] DEBUG o.f.d.interfaces.DBus$NameAcquired - Appending sig: yyyy data: [108, 4, 0, 1]
	2022-02-11T18:18:54.894Z [DBus Worker Thread-1] DEBUG o.f.d.interfaces.DBus$NameAcquired - Appending sig: ua(yv) data: [4, [[1, [o, /org/freedesktop/DBus]], [2, [s, org.freedesktop.DBus]], [3, [s, NameAcquired]], [8, [g, s]]]]
	2022-02-11T18:18:55.736Z [DBusConnection] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodReturn(0,31) { Reply Serial=>2, Destination=>:1.88, Sender=>:1.53, Signature=>o } { /org/asamk/Signal/_1234567890/Devices/1 }
	2022-02-11T18:18:55.737Z [DBusConnection] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method return: MethodReturn(0,31) { Reply Serial=>2, Destination=>:1.88, Sender=>:1.53, Signature=>o } { /org/asamk/Signal/_1234567890/Devices/1 }
	2022-02-11T18:18:55.739Z [main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 4
	2022-02-11T18:18:55.739Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	2022-02-11T18:18:55.739Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [4, [[1, [o, /org/asamk/Signal/_1234567890]], [6, [s, org.asamk.Signal]], [2, [s, org.asamk.Signal]], [3, [s, listDevices]]]]
	2022-02-11T18:18:55.740Z [main] DEBUG o.f.dbus.messages.MethodCall - Appended body, type: null start: 144 end: 144 size: 0
	2022-02-11T18:18:55.740Z [main] DEBUG o.f.dbus.messages.MethodCall - marshalled size ([0, 0, 0, 0]): 000000	00 00 00 00                                            ....              
	2022-02-11T18:18:55.740Z [DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,4) { Path=>/org/asamk/Signal/_1234567890, Interface=>org.asamk.Signal, Member=>listDevices, Destination=>org.asamk.Signal } { }
	2022-02-11T18:18:55.915Z [DBusConnection] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodReturn(0,32) { Reply Serial=>4, Destination=>:1.88, Sender=>:1.53, Signature=>a(oxs) } { [[Ljava.lang.Object;@188915a0] }
	2022-02-11T18:18:55.916Z [DBusConnection] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method return: MethodReturn(0,32) { Reply Serial=>4, Destination=>:1.88, Sender=>:1.53, Signature=>a(oxs) } { [[Ljava.lang.Object;@188915a0] }
	2022-02-11T18:18:55.960Z [main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 5
	2022-02-11T18:18:55.961Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	2022-02-11T18:18:55.961Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending arguments with signature: s
	2022-02-11T18:18:55.961Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [5, [[1, [o, /org/asamk/Signal/_1234567890/Devices/1]], [6, [s, org.asamk.Signal]], [2, [s, org.asamk.Signal.Device]], [3, [s, GetAll]], [8, [g, s]]]]
	2022-02-11T18:18:55.962Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: s data: [org.asamk.Signal.Device]
	2022-02-11T18:18:55.962Z [main] DEBUG o.f.dbus.messages.MethodCall - Appended body, type: s start: 160 end: 188 size: 28
	2022-02-11T18:18:55.962Z [main] DEBUG o.f.dbus.messages.MethodCall - marshalled size ([28, 0, 0, 0]): 000000	1c 00 00 00                                            ...              
	2022-02-11T18:18:55.962Z [DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,5) { Path=>/org/asamk/Signal/_1234567890/Devices/1, Interface=>org.asamk.Signal.Device, Member=>GetAll, Destination=>org.asamk.Signal, Signature=>s } { org.asamk.Signal.Device }
	2022-02-11T18:18:55.967Z [DBusConnection] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodReturn(0,33) { Reply Serial=>5, Destination=>:1.88, Sender=>:1.53, Signature=>a{sv} } { { Id => [1],LastSeen => [1644537600000],Name => [],Created => [1644588373605] } }
	2022-02-11T18:18:55.982Z [DBusConnection] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method return: MethodReturn(0,33) { Reply Serial=>5, Destination=>:1.88, Sender=>:1.53, Signature=>a{sv} } { { Id => [1],LastSeen => [1644537600000],Name => [],Created => [1644588373605] } }
	2022-02-11T18:18:55.986Z [main] DEBUG o.f.d.c.impl.DBusConnection - Disconnecting last remaining DBusConnection
	2022-02-11T18:18:55.987Z [main] DEBUG org.freedesktop.dbus.errors.Error - Creating message with serial 6
	2022-02-11T18:18:55.987Z [main] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: yyyy data: [108, 3, 0, 1]
	2022-02-11T18:18:55.987Z [main] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: ua(yv) data: [6, [[4, [s, org.freedesktop.DBus.Local.Disconnected]], [5, [u, 0]], [6, [s, org.freedesktop.DBus.Local]], [8, [g, s]]]]
	2022-02-11T18:18:55.987Z [main] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: s data: [Disconnected]
	2022-02-11T18:18:55.987Z [main] DEBUG o.f.d.c.impl.DBusConnection - Sending disconnected signal
	2022-02-11T18:18:55.988Z [main] DEBUG o.f.d.interfaces.Local$Disconnected - Creating message with serial 7
	2022-02-11T18:18:55.988Z [main] DEBUG o.f.d.interfaces.Local$Disconnected - Appending sig: yyyy data: [108, 4, 0, 1]
	2022-02-11T18:18:55.988Z [main] DEBUG o.f.d.interfaces.Local$Disconnected - Appending sig: ua(yv) data: [8, [[1, [o, /]], [2, [s, org.freedesktop.DBus.Local]], [3, [s, Disconnected]]]]
	2022-02-11T18:18:55.988Z [main] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming signal: Disconnected(0,8) { Path=>/, Interface=>org.freedesktop.DBus.Local, Member=>Disconnected } { }
	2022-02-11T18:18:55.989Z [main] DEBUG o.f.d.c.impl.DBusConnection - Handling Disconnected signal from bus
	2022-02-11T18:18:55.989Z [main] DEBUG org.freedesktop.dbus.errors.Error - Creating message with serial 8
	2022-02-11T18:18:55.989Z [main] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: yyyy data: [108, 3, 0, 1]
	2022-02-11T18:18:55.989Z [main] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: ua(yv) data: [8, [[4, [s, org.freedesktop.DBus.Local.Disconnected]], [5, [u, 0]], [6, [s, org.freedesktop.DBus.Local]], [8, [g, s]]]]
	2022-02-11T18:18:55.989Z [main] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: s data: [Disconnected]
	2022-02-11T18:18:55.990Z [main] DEBUG o.f.d.c.impl.DBusConnection - Handling Disconnected signal from bus
	2022-02-11T18:18:55.990Z [main] DEBUG org.freedesktop.dbus.errors.Error - Creating message with serial 9
	2022-02-11T18:18:55.990Z [main] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: yyyy data: [108, 3, 0, 1]
	2022-02-11T18:18:55.990Z [main] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: ua(yv) data: [9, [[4, [s, org.freedesktop.DBus.Local.Disconnected]], [5, [u, 0]], [6, [s, org.freedesktop.DBus.Local]], [8, [g, s]]]]
	2022-02-11T18:18:55.990Z [main] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: s data: [Disconnected]
	2022-02-11T18:18:55.991Z [main] DEBUG o.f.d.c.impl.DBusConnection - Disconnecting Abstract Connection
	2022-02-11T18:18:55.991Z [main] DEBUG o.f.d.t.j.NativeUnixSocketTransport - Disconnecting Transport
	2022-02-11T18:18:55.992Z [main] DEBUG o.f.d.s.m.OutputStreamMessageWriter - Closing Message Writer
	java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
		at org.asamk.signal.dbus.DbusManagerImpl.lambda$getLinkedDevices$4(DbusManagerImpl.java:176)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
		at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
		at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
		at org.asamk.signal.dbus.DbusManagerImpl.getLinkedDevices(DbusManagerImpl.java:181)
		at org.asamk.signal.commands.ListDevicesCommand.handleCommand(ListDevicesCommand.java:40)
		at org.asamk.signal.App.handleLocalCommand(App.java:306)
		at org.asamk.signal.App.initDbusClient(App.java:425)
		at org.asamk.signal.App.init(App.java:142)
		at org.asamk.signal.Main.main(Main.java:58)

	$ signal-cli --version

	signal-cli 0.10.3

**Comment by AsamK** [comment]
Thanks for reporting!
