### ISSUE TITLE
DBusException: Failed to register bus name on starting a second daemon

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#890]
To reproduce: start one daemon with

	$ signal-cli -u +1111111111 daemon

	INFO  DaemonCommand - Starting daemon in single-account mode for +1111111111
	INFO  DaemonCommand - DBus daemon running on SESSION bus: org.asamk.Signal

In another terminal, start a daemon with a different account

	$ signal-cli  -u +2222222222  daemon

	INFO  DaemonCommand - Starting daemon in single-account mode for +2222222222
	ERROR DaemonCommand - Dbus command failed
	org.freedesktop.dbus.exceptions.DBusException: Failed to register bus name
		at org.freedesktop.dbus.connections.impl.DBusConnection.requestBusName(DBusConnection.java:506)
		at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:348)
		at org.asamk.signal.commands.DaemonCommand.runDbusSingleAccount(DaemonCommand.java:284)
		at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:132)
		at org.asamk.signal.App.handleLocalCommand(App.java:292)
		at org.asamk.signal.App.init(App.java:211)
		at org.asamk.signal.Main.main(Main.java:58)
	Dbus command failed

Both are linked accounts, if it matters. Signal-cli v0.10.3 linux.

With `--verbose`:

	$ signal-cli  -u +2222222222  --verbose daemon

	2022-02-11T18:41:52.939Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
	2022-02-11T18:41:53.262Z [main] INFO  LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:161: Initializing libsignal-client version:0.11.0
	2022-02-11T18:41:56.882Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
	2022-02-11T18:41:57.021Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@ec2cc4
	2022-02-11T18:41:57.023Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
	2022-02-11T18:41:58.965Z [main] INFO  o.a.signal.commands.DaemonCommand - Starting daemon in single-account mode for +2222222222
	2022-02-11T18:41:58.981Z [receive-0] DEBUG org.asamk.signal.manager.ManagerImpl - Starting receiving messages
	2022-02-11T18:41:59.013Z [main] DEBUG o.f.d.c.transports.TransportBuilder - Found provider 'NativeTransportProvider' named 'dbus-java-transport-native-unixsocket' providing bustype 'UNIX'
	2022-02-11T18:41:59.072Z [receive-0] INFO  LibSignal - [WebSocketConnection]: [normal:1976462225] connect()
	2022-02-11T18:41:59.105Z [receive-0] INFO  LibSignal - [WebSocketConnection]: [unidentified:197968849] connect()
	2022-02-11T18:41:59.122Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
	2022-02-11T18:41:59.132Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
	2022-02-11T18:41:59.146Z [main] DEBUG o.f.d.t.j.NativeUnixSocketTransport - No alternative ISocketProvider found, using built-in implementation
	2022-02-11T18:41:59.182Z [main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 1
	2022-02-11T18:41:59.188Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	2022-02-11T18:41:59.189Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [1, [[1, [o, /org/freedesktop/DBus]], [6, [s, org.freedesktop.DBus]], [2, [s, org.freedesktop.DBus]], [3, [s, Hello]]]]
	2022-02-11T18:41:59.189Z [main] DEBUG o.f.dbus.messages.MethodCall - Appended body, type: null start: 128 end: 128 size: 0
	2022-02-11T18:41:59.189Z [main] DEBUG o.f.dbus.messages.MethodCall - marshalled size ([0, 0, 0, 0]): 000000	00 00 00 00                                            ....              
	2022-02-11T18:41:59.206Z [DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,1) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>Hello, Destination=>org.freedesktop.DBus } { }
	2022-02-11T18:41:59.213Z [DBusConnection] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodReturn(1,1) { Reply Serial=>1, Destination=>:1.45, Sender=>org.freedesktop.DBus, Signature=>s } { :1.45 }
	2022-02-11T18:41:59.214Z [DBusConnection] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method return: MethodReturn(1,1) { Reply Serial=>1, Destination=>:1.45, Sender=>org.freedesktop.DBus, Signature=>s } { :1.45 }
	2022-02-11T18:41:59.222Z [DBusConnection] DEBUG o.f.d.s.m.InputStreamMessageReader - => DBusSignal(1,2) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>NameAcquired, Destination=>:1.45, Sender=>org.freedesktop.DBus, Signature=>s } { :1.45 }
	2022-02-11T18:41:59.222Z [DBusConnection] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming signal: DBusSignal(1,2) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>NameAcquired, Destination=>:1.45, Sender=>org.freedesktop.DBus, Signature=>s } { :1.45 }
	2022-02-11T18:41:59.233Z [DBus Worker Thread-1] DEBUG o.f.dbus.messages.DBusSignal - Converting signal to type: class org.freedesktop.dbus.interfaces.DBus$NameAcquired
	2022-02-11T18:41:59.238Z [DBus Worker Thread-1] DEBUG o.f.d.interfaces.DBus$NameAcquired - Creating message with serial 2
	2022-02-11T18:41:59.242Z [DBus Worker Thread-1] DEBUG o.f.d.interfaces.DBus$NameAcquired - Appending sig: yyyy data: [108, 4, 0, 1]
	2022-02-11T18:41:59.245Z [DBus Worker Thread-1] DEBUG o.f.d.interfaces.DBus$NameAcquired - Appending sig: ua(yv) data: [3, [[1, [o, /org/freedesktop/DBus]], [2, [s, org.freedesktop.DBus]], [3, [s, NameAcquired]], [8, [g, s]]]]
	2022-02-11T18:41:59.268Z [main] DEBUG o.f.dbus.messages.ObjectTree - Adding /org/asamk/Signal to object tree
	2022-02-11T18:41:59.271Z [main] DEBUG o.a.signal.commands.DaemonCommand - Exported dbus object: /org/asamk/Signal
	2022-02-11T18:41:59.569Z [dbus-init] DEBUG o.f.dbus.messages.ObjectTree - Adding /org/asamk/Signal/Devices/1 to object tree
	2022-02-11T18:41:59.569Z [dbus-init] DEBUG org.asamk.signal.dbus.DbusSignalImpl - Exported dbus object: /org/asamk/Signal/Devices/1
	2022-02-11T18:41:59.572Z [dbus-init] DEBUG o.f.dbus.messages.ObjectTree - Adding /org/asamk/Signal/Devices/2 to object tree
	2022-02-11T18:41:59.573Z [dbus-init] DEBUG org.asamk.signal.dbus.DbusSignalImpl - Exported dbus object: /org/asamk/Signal/Devices/2
	2022-02-11T18:41:59.585Z [dbus-init] DEBUG o.f.dbus.messages.ObjectTree - Removing /org/asamk/Signal/Configuration from object tree
	2022-02-11T18:41:59.591Z [dbus-init] DEBUG o.f.dbus.messages.ObjectTree - Adding /org/asamk/Signal/Configuration to object tree
	2022-02-11T18:41:59.592Z [dbus-init] DEBUG org.asamk.signal.dbus.DbusSignalImpl - Exported dbus object: /org/asamk/Signal/Configuration
	2022-02-11T18:41:59.592Z [main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 3
	2022-02-11T18:41:59.593Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	2022-02-11T18:41:59.593Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending arguments with signature: su
	2022-02-11T18:41:59.593Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [3, [[1, [o, /org/freedesktop/DBus]], [6, [s, org.freedesktop.DBus]], [2, [s, org.freedesktop.DBus]], [3, [s, RequestName]], [8, [g, su]]]]
	2022-02-11T18:41:59.594Z [main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: su data: [org.asamk.Signal, 6]
	2022-02-11T18:41:59.594Z [main] DEBUG o.f.dbus.messages.MethodCall - Appended body, type: su start: 144 end: 172 size: 28
	2022-02-11T18:41:59.600Z [main] DEBUG o.f.dbus.messages.MethodCall - marshalled size ([28, 0, 0, 0]): 000000	1c 00 00 00                                            ...              
	2022-02-11T18:41:59.601Z [DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,3) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>RequestName, Destination=>org.freedesktop.DBus, Signature=>su } { org.asamk.Signal, 6 }
	2022-02-11T18:41:59.603Z [DBusConnection] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodReturn(1,3) { Reply Serial=>3, Destination=>:1.45, Sender=>org.freedesktop.DBus, Signature=>u } { 3 }
	2022-02-11T18:41:59.603Z [DBusConnection] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method return: MethodReturn(1,3) { Reply Serial=>3, Destination=>:1.45, Sender=>org.freedesktop.DBus, Signature=>u } { 3 }
	2022-02-11T18:41:59.605Z [main] ERROR o.a.signal.commands.DaemonCommand - Dbus command failed
	org.freedesktop.dbus.exceptions.DBusException: Failed to register bus name
		at org.freedesktop.dbus.connections.impl.DBusConnection.requestBusName(DBusConnection.java:506)
		at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:348)
		at org.asamk.signal.commands.DaemonCommand.runDbusSingleAccount(DaemonCommand.java:284)
		at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:132)
		at org.asamk.signal.App.handleLocalCommand(App.java:292)
		at org.asamk.signal.App.init(App.java:211)
		at org.asamk.signal.Main.main(Main.java:58)
	2022-02-11T18:41:59.607Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
	2022-02-11T18:41:59.607Z [receive-0] INFO  LibSignal - [WebSocketConnection]: [normal:1976462225] disconnect()
	2022-02-11T18:41:59.608Z [receive-0] INFO  LibSignal - [WebSocketConnection]: [unidentified:197968849] disconnect()
	2022-02-11T18:41:59.609Z [receive-0] DEBUG org.asamk.signal.manager.ManagerImpl - Finished receiving messages
	2022-02-11T18:41:59.611Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
	2022-02-11T18:41:59.614Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
	Dbus command failed
	org.freedesktop.dbus.exceptions.DBusException: Failed to register bus name
		at org.freedesktop.dbus.connections.impl.DBusConnection.requestBusName(DBusConnection.java:506)
		at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:348)
		at org.asamk.signal.commands.DaemonCommand.runDbusSingleAccount(DaemonCommand.java:284)
		at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:132)
		at org.asamk.signal.App.handleLocalCommand(App.java:292)
		at org.asamk.signal.App.init(App.java:211)
		at org.asamk.signal.Main.main(Main.java:58)

**Comment by AsamK** [comment]
That happens because a dbus service name can only be registered by one program at a time.
To run multiple accounts at the same time you can use signal-cli multi-account mode:
`$ signal-cli --verbose daemon`

**Comment by exquo** [comment]
I suspected as much. I vaguely remember it being possible in the past, but can't remember for sure..

Either way, it might be worth considering adding a message from signal-cli to that effect, to replace the long stack trace from java with something clear and concise. Similar to how it's now done when signal-cli is invoked while another instance of daemon is already running ("Config file is in use by another instance ..")
