### ISSUE TITLE
HikariDataSource error when using jsonRpc sendSyncRequest

### ISSUE THREAD

**Issue by brad2014** [AsamK/signal-cli#892]
Version: signal-cli 0.10.3

On my android signal app, I send a "note to self" message, then on my Linux box, with a freshly linked signal-cli instance, I simply want to get the json version of the message (I've been using "signal-cli receive", but accurately parsing out the message body from its text output is problematic).

So I tried the jsonRpc method, but it immediately errors, so with your indulgence I'll share the stack trace:  

```
% echo '{"jsonrpc":"2.0","method":"sendSyncRequest","id":9}' | signal-cli -u +1[REDACTED] jsonRpc > results
WARN  IncomingMessageHandler - Received a group v1 sync message, that can't be handled anymore, ignoring.
WARN  IncomingMessageHandler - Failed to handle received sync contacts, ignoring: java.io.InterruptedIOException
WARN  HikariDataSource - HikariPool-1 - Interrupted during closing
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1660)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1464)
	at com.zaxxer.hikari.pool.HikariPool.shutdown(HikariPool.java:243)
	at com.zaxxer.hikari.HikariDataSource.close(HikariDataSource.java:351)
	at org.asamk.signal.manager.storage.Database.close(Database.java:66)
	at org.asamk.signal.manager.storage.SignalAccount.close(SignalAccount.java:1083)
	at org.asamk.signal.manager.ManagerImpl.close(ManagerImpl.java:1025)
	at org.asamk.signal.App.handleLocalCommand(App.java:293)
	at org.asamk.signal.App.init(App.java:211)
	at org.asamk.signal.Main.main(Main.java:58)
%
```

The group v1 sync message error in 0.10.3 was reported in #888 (addressed in https://github.com/AsamK/signal-cli/commit/fd8ba66509d5f11f7829b0f8ea8458a0008914b7) . The HikariDataSource error is the issue here.

**Comment by brad2014** [comment]
I'm looking for an approach to getting all  receivable messages in json format, something, essentially, like :

```
% signal-cli --json -u +1XXXXXXXXXX receive | jq ...
```

Apologies if that is already supported - I couldn't find it.

**Comment by AsamK** [comment]
Hi, thanks for reporting, this exception should already be fixed on master (https://github.com/AsamK/signal-cli/commit/cf0cc50e328c0fc4fcbbecfa0ed21887613110a1)

For just receiving messages you can use the output parameter:
`signal-cli --output=json -u +1XXXXXXXXXX receive | jq `
