### ISSUE TITLE
signal-cli stuck after a closed connection

### ISSUE THREAD

**Issue by cuu508** [AsamK/signal-cli#893]
I noticed that the signal-cli daemon is not sending any messages (can send a message over JSON-RPC, but nothing comes back) and is not receiving messages (no messages about received messages in logs).

I restarted signal-cli and a message in logs flashed back saying something along the lines of "messages have not been received for 11 days, signal protocol expects you receive messages regularly". So I looked 11 days back in the logs and found this:

```
Feb 06 12:00:14 www3 signal-cli[448]: INFO DaemonCommand - Connection closed:  UnixDomainPrincipal[user=nobody, group=nogroup]
Feb 06 12:00:14 www3 signal-cli[448]: Exception in thread "Thread-0" java.lang.AssertionError: java.io.IOException: Broken pipe
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.output.JsonWriterImpl.write(JsonWriterImpl.java:32)
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.jsonrpc.JsonRpcSender.sendRequest(JsonRpcSender.java:16)
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.lambda$subscribeReceive$0(SignalJs>
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.json.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.ja>
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$9(ManagerImpl.jav>
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$10(ManagerImpl.ja>
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessa>
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandl>
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:1>
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:88)
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$11(ManagerImpl.ja>
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/java.lang.Thread.run(Thread.java:833)
Feb 06 12:00:14 www3 signal-cli[448]: Caused by: java.io.IOException: Broken pipe
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:53)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:231)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
Feb 06 12:00:14 www3 signal-cli[448]:         at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160)
Feb 06 12:00:14 www3 signal-cli[448]:         at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.close(WriterBasedJsonGenerator.ja>
Feb 06 12:00:14 www3 signal-cli[448]:         at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4573)
Feb 06 12:00:14 www3 signal-cli[448]:         at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3804)
Feb 06 12:00:14 www3 signal-cli[448]:         at org.asamk.signal.output.JsonWriterImpl.write(JsonWriterImpl.java:24)
Feb 06 12:00:14 www3 signal-cli[448]:         ... 14 more
```

After this, the only messages in the logs were about JSON-RPC connections:

```
Feb 06 12:22:58 www3 signal-cli[448]: INFO DaemonCommand - Accepted new client:  UnixDomainPrincipal[user=nobody, group=nogroup]
Feb 06 13:50:00 www3 signal-cli[448]: INFO DaemonCommand - Accepted new client:  UnixDomainPrincipal[user=nobody, group=nogroup]
Feb 06 14:02:52 www3 signal-cli[448]: INFO DaemonCommand - Accepted new client:  UnixDomainPrincipal[user=nobody, group=nogroup]
Feb 06 14:20:06 www3 signal-cli[448]: INFO DaemonCommand - Accepted new client:  UnixDomainPrincipal[user=nobody, group=nogroup]
Feb 06 14:25:07 www3 signal-cli[448]: INFO DaemonCommand - Accepted new client:  UnixDomainPrincipal[user=nobody, group=nogroup]
Feb 06 14:27:30 www3 signal-cli[448]: INFO DaemonCommand - Accepted new client:  UnixDomainPrincipal[user=nobody, group=nogroup]
Feb 06 14:34:49 www3 signal-cli[448]: INFO DaemonCommand - Accepted new client:  UnixDomainPrincipal[user=nobody, group=nogroup]
...
```

I'm not sure what went wrong (what connection was closed and why) but it would be great if signal-cli could recover on its own. 

PS. Took me far too long to notice the issue, but that's on me :-/

**Comment by AsamK** [comment]
Looks like signal-cli tried to send a message via a UNIX socket connection after it has been closed.
It should indeed handle that case gracefully.

**Comment by cuu508** [comment]
A Python script to reproduce the issue:

```
import socket

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("/tmp/socket")
s.send(b"{")
```

(save as script.py and run with `python3 script.py`)

Results in:

```
INFO DaemonCommand - Accepted new client:  UnixDomainPrincipal[user=cepe, group=cepe]
Exception in thread "Thread-4" java.lang.AssertionError: java.io.IOException: Broken pipe
	at org.asamk.signal.output.JsonWriterImpl.write(JsonWriterImpl.java:32)
	at org.asamk.signal.jsonrpc.JsonRpcSender.sendResponse(JsonRpcSender.java:24)
	at org.asamk.signal.jsonrpc.JsonRpcReader.parseJsonRpcMessage(JsonRpcReader.java:111)
	at org.asamk.signal.jsonrpc.JsonRpcReader.readMessage(JsonRpcReader.java:97)
	at org.asamk.signal.jsonrpc.JsonRpcReader.readMessages(JsonRpcReader.java:39)
	at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:119)
	at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:85)
	at org.asamk.signal.commands.DaemonCommand.lambda$runSocketSingleAccount$3(DaemonCommand.java:224)
	at org.asamk.signal.commands.DaemonCommand.lambda$runSocket$5(DaemonCommand.java:255)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:53)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:231)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.close(WriterBasedJsonGenerator.java:1007)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4573)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3804)
	at org.asamk.signal.output.JsonWriterImpl.write(JsonWriterImpl.java:24)
	... 9 more
```

**Comment by cuu508** [comment]
Awesome, thank you for the fix, and for putting out a new release quickly! Appreciate it!
