### ISSUE TITLE
"No key type identifier" when linking to iOS device

### ISSUE THREAD

**Issue by jjosi** [AsamK/signal-cli#897]
Hi,

first of all, thanks a lot for developing signal-cli!

I'm trying to link signal-cli to my main device (iOS), and I run into the following error after scanning the barcode on the iPhone.

```
$ signal-cli --verbose link | tee >(xargs -L 1 qrencode -t utf8)
2022-02-23T23:14:31.354+0100 [main] INFO  LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal-client version:0.12.3
2022-02-23T23:14:31.356+0100 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-02-23T23:14:31.671+0100 [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:2002790740] connect()
2022-02-23T23:14:32.470+0100 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:2002790740] onOpen() connected
sgnl://linkdevice?uuid=[omitted]&pub_key=[omitted]
[barcode omitted]
2022-02-23T23:14:37.789+0100 [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:2002790740] disconnect()
Link request error: Failed to decrypt public key
java.io.IOException: Failed to decrypt public key
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getIdentityKeyPair(SignalServiceAccountManager.java:796)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getNewDeviceRegistration(SignalServiceAccountManager.java:764)
	at org.asamk.signal.manager.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:97)
	at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
	at org.asamk.signal.App.handleProvisioningCommand(App.java:222)
	at org.asamk.signal.App.init(App.java:181)
	at org.asamk.signal.Main.main(Main.java:58)
Caused by: org.whispersystems.libsignal.InvalidKeyException: No key type identifier
	at org.whispersystems.libsignal.ecc.Curve.decodePoint(Curve.java:22)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getIdentityKeyPair(SignalServiceAccountManager.java:794)
	... 6 more
```

Versions used:
* signal-cli 0.10.4-1 installed via https://aur.archlinux.org/packages/signal-cli on Arch Linux
* Main device: Signal 5.29.0 on iOS 15.3.

Is there any more information I can provide to help debugging this issue?

(This seems somewhat similar to issue #28 from 2016.)

**Comment by AsamK** [comment]
Thanks for reporting, signal-cli 0.10.4 expected the new PNI identity to be present, which iOS doesn't send yet.

**Comment by jarrah31** [comment]
I have the same problem, thanks for working on a fix @AsamK. 

If you don't mind me asking, when will the next version be released please?

**Comment by jarrah31** [comment]
v0.10.4.1 now works for me, thanks @AsamK!
