### ISSUE TITLE
sendReceipt not working 

### ISSUE THREAD

**Issue by nbelavic** [AsamK/signal-cli#901]
I have successfully installed and registered new account with my landline number. I am able to receive and send messages.
But i cannot send Receipt:
`nicols@snorlax:~$ signal-cli -u +385XXXXXXXXX sendReceipt "+385XXXXXXXXX"`

`java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "org.whispersystems.signalservice.api.messages.SignalServiceReceiptMessage.getTimestamps()" is null
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.createReceiptContent(SignalServiceMessageSender.java:807)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:206)
        at org.asamk.signal.manager.helper.SendHelper.lambda$sendReceiptMessage$0(SendHelper.java:123)
        at org.asamk.signal.manager.helper.SendHelper.handleSendMessage(SendHelper.java:586)
        at org.asamk.signal.manager.helper.SendHelper.sendReceiptMessage(SendHelper.java:122)
        at org.asamk.signal.manager.ManagerImpl.sendReceiptMessage(ManagerImpl.java:502)
        at org.asamk.signal.manager.ManagerImpl.sendReadReceipt(ManagerImpl.java:480)
        at org.asamk.signal.commands.SendReceiptCommand.handleCommand(SendReceiptCommand.java:50)
        at org.asamk.signal.App.handleLocalCommand(App.java:273)
        at org.asamk.signal.App.init(App.java:213)
        at org.asamk.signal.Main.main(Main.java:58)`
        
 I have tried different options, with or without quotes, adding timestap, --type, nothing seems to work

**Comment by AsamK** [comment]
With `--target-timestamp` it should work. I've also improved the error message in case it's missing.
`signal-cli -u +385XXXXXXXXX sendReceipt "+385XXXXXXXXX" --target-timestamp 123`
