### ISSUE TITLE
Crash in java.util.Optional.get

### ISSUE THREAD

**Issue by brad2014** [AsamK/signal-cli#910]
Version: signal-cli 0.10.4

I am seeing this crash upon moving to 0.10.4. in `signal-cli receive`.  It is occurring sporadically, I'm not sure how to get you more information or a reproducible case, but am open to suggestions.

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.asamk.signal.json.JsonMessageEnvelope.from(JsonMessageEnvelope.java:52)
	at org.asamk.signal.json.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.java:32)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.checkAndHandleMessage(IncomingMessageHandler.java:194)
	at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:156)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:195)
	at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:106)
	at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:851)
	at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:834)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:62)
	at org.asamk.signal.App.handleLocalCommand(App.java:273)
	at org.asamk.signal.App.init(App.java:213)
	at org.asamk.signal.Main.main(Main.java:58)

**Comment by AsamK** [comment]
Thanks for reporting!
The stack trace was helpful here, the error appears when receiving a message from an untrusted identity.

**Comment by brad2014** [comment]
Wow.  Thank you!

**Comment by lindes** [comment]
Thanks for fixing this!  I'd been hitting it, too, and was going to attempt a fix, but took a while to get the build environment going, got sidetracked a while, and then came back and here we are: yay, it works now!  :)

Thanks @AsamK !
