### ISSUE TITLE
ProofRequiredException when sending a message to a new recipient

### ISSUE THREAD

**Issue by cuu508** [AsamK/signal-cli#923]
I've come across an issue with a particular recipient where messages from the official Signal client get delivered, but signal-cli fails.

JSON-RPC response when sending message:

```
{'jsonrpc': '2.0', 'error': {'code': -1, 'message': 'Failed to send message', 'data': {'response': {'timestamp': 1649148157954, 'results': [{'recipientAddress': {'uuid': '6c65f1bd-ed62-4b46-b45a-e3249f7a5a5e', 'number': '+redacted 'type': 'NETWORK_FAILURE', 'token': '2fc05128-a86a-4b99-9b33-ce615fee9258', 'retryAfterSeconds': 86400}]}}}, 'id': '4ddf6672-abc4-41d8-8a80-af1b787a09fc'}
```

I started signal-cli with `--verbose` and saw this:

```
2022-04-05T11:10:36.842+0200 [daemon-connection-0] DEBUG LibSignal - [SignalServiceMessageSender]: [1649149836825] Sending a data message.
2022-04-05T11:10:36.917+0200 [daemon-connection-0] INFO  LibSignal - [libsignal-client]: rust/protocol/src/session_cipher.rs:55: Building PreKeyWhisperMessage for: 6c65f1bd-ed62-4b46-b45a-e3249f7a5a5e.1 with preKeyId: 13850981
2022-04-05T11:10:37.094+0200 [daemon-connection-0] WARN  LibSignal - [SignalServiceMessageSender]: org.whispersystems.signalservice.api.push.exceptions.ProofRequiredException: StatusCode: 428
     at org.whispersystems.signalservice.internal.websocket.DefaultErrorMapper.parseError(DefaultErrorMapper.java:136)
     at org.whispersystems.signalservice.internal.websocket.DefaultResponseMapper.map(DefaultResponseMapper.java:47)
     at org.whispersystems.signalservice.internal.websocket.ResponseMapper.map(ResponseMapper.java:21)
     at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:58)
     at io.reactivex.rxjava3.internal.operators.single.SingleTimeout$TimeoutMainObserver.onSuccess(SingleTimeout.java:141)
     at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
     at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
     at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
     at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
     at java.base/java.lang.Thread.run(Thread.java:833)
2022-04-05T11:10:37.097+0200 [daemon-connection-0] WARN  LibSignal - [SignalServiceMessageSender]: [sendMessage][1649149836825] Pipe failed, falling back... (ProofRequiredException: StatusCode: 428)
```

What is going wrong here, and what can I do to fix it? Thanks!

PS. Tested with signal-cli 10.4.2.

**Comment by cuu508** [comment]
One thing that would help here would be a more specific error message in the JSON-RPC response. I could then add extra logic on the client side to detect this, and alert me about it.

A couple related questions, in case anyone knows:

* Does signal apply rate-limiting per recipient, or account-wide? Consequently, do I need to do `submitRateLimitChallenge` for every failing recipient, or only once?
* I solved a recaptcha puzzle (click on cars, traffic lights, fire hydrants, ...), what is the PUSH_CHALLENGE option? Is there any way to make challenge solving less onerous?

**Comment by AsamK** [comment]
I've adapted the code to output "type": "RATE_LIMIT_FAILURE" for all rate limiting errors.
If it's rate limiting, that can be lifted by solving a captcha, there is a "token" field in the response that can be used with the submitRateLimitChallenge command.

- I don't know how rate limit is implemented in the Signnal server
- The PUSH challenge uses APN or firebase push message on iOS/Android. It's not implemented in signal-cli.

**Comment by cuu508** [comment]
Thanks @AsamK!

Does the JSON-RPC response include the challenge token (or would it be possible to include it)?

I've run into the rate limit issue a couple times now, and what I did was:

1. notice a JSON-RPC send call has failed
1. stop the JSON-RPC daemon
1. run `signal-cli send` call from command line to get the challenge token
1. solve the captcha and run `signal-cli submitRateLimitChallenge`
1. start the JSON-RPC daemon

If JSON-RPC returned the challenge token, I could probably eliminate steps 2, 3 and 5

**Comment by AsamK** [comment]
yeah, the response you posted above already contains it : `'token': '2fc05128-a86a-4b99-9b33-ce615fee9258',`

**Comment by cuu508** [comment]
Oops – missed it! Thanks!
