### ISSUE TITLE
Error while checking account +123456789: java.net.SocketTimeoutException: Connect timed out

### ISSUE THREAD

**Issue by jk20004** [AsamK/signal-cli#931]
with the latest Version V0.10.4.2.now we get some time:

```
2022-04-11T06:40:04.701+0200 [main] INFO  LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal-client version:0.12.3
2022-04-11T06:40:05.013+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-04-11T06:40:05.095+0200 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@3ecd267f
2022-04-11T06:40:05.097+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-04-11T06:40:35.409+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-04-11T06:40:35.411+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Error while checking account +123456789: java.net.SocketTimeoutException: Connect timed out
org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.SocketTimeoutException: Connect timed out
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:1800)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1701)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1689)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1678)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1614)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1590)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getAvailablePreKeys(PushServiceSocket.java:597)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getPreKeysCount(SignalServiceAccountManager.java:443)
        at org.asamk.signal.manager.helper.PreKeyHelper.refreshPreKeysIfNecessary(PreKeyHelper.java:37)
        at org.asamk.signal.manager.helper.PreKeyHelper.refreshPreKeysIfNecessary(PreKeyHelper.java:32)
        at org.asamk.signal.manager.helper.AccountHelper.checkAccountState(AccountHelper.java:58)
        at org.asamk.signal.manager.ManagerImpl.checkAccountState(ManagerImpl.java:178)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:97)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:64)
        at org.asamk.signal.App.loadManager(App.java:337)
        at org.asamk.signal.App.handleLocalCommand(App.java:272)
        at org.asamk.signal.App.init(App.java:213)
        at org.asamk.signal.Main.main(Main.java:58)
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:261)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.asamk.signal.manager.config.ServiceConfig.lambda$getServiceEnvironmentConfig$0(ServiceConfig.java:68)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:1793)
        ... 17 more

```

**Comment by AsamK** [comment]
Looks like a server or network issue.
