### ISSUE TITLE
java.lang.IllegalArgumentException in ReceiveMessages

### ISSUE THREAD

**Issue by brad2014** [AsamK/signal-cli#941]
When using the signal-cli receive function, I periodically get a crash with the following stack trace. 
This appears to be a regression from signal-cli 0.10.4 + libsignal_jni 0.12.0.

My versions:
signal-cli 0.10.5
libsignal_jni 0.15.0 (bespoke compiled for centos 7)

% signal-cli receive

stack trace in log file:
```
2022-04-24T18:00:14.629Z [main] WARN  o.a.s.manager.helper.ReceiveHelper - Message action failed.
java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
  at org.whispersystems.signalservice.internal.storage.protos.ManifestRecord$Identifier$Type.getNumber(ManifestRecord.java:102)
  at org.whispersystems.signalservice.api.storage.SignalStorageModels.remoteToLocalStorageManifest(SignalStorageModels.java:27)
  at org.whispersystems.signalservice.api.SignalServiceAccountManager.getStorageManifestIfDifferentVersion(SignalServiceAccountManager.java:619)
  at org.asamk.signal.manager.helper.StorageHelper.readDataFromStorage(StorageHelper.java:48)
  at org.asamk.signal.manager.actions.RetrieveStorageDataAction.execute(RetrieveStorageDataAction.java:19)
  at org.asamk.signal.manager.helper.ReceiveHelper.handleQueuedActions(ReceiveHelper.java:283)
  at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:158)
  at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:106)
  at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:857)
  at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:840)
  at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:62)
  at org.asamk.signal.App.handleLocalCommand(App.java:273)
  at org.asamk.signal.App.init(App.java:213)
  at org.asamk.signal.Main.main(Main.java:58)
```

**Comment by AsamK** [comment]
Thanks for reporting, this is already fixed in the latest master, in a0c304d3cab59073ea37949b9d580cd9fb20c3e1
