### ISSUE TITLE
[Error] Failed to send base64 attatcement when running on jsonrpc + tcp daemon

### ISSUE THREAD

**Issue by iwas108** [AsamK/signal-cli#950]
When running signal-cli in JSONRPC + TCP Daemon (version 0.10.5):
```
signal-cli -u +00000000000 daemon --tcp
```
An error occurred:
```
INFO  DaemonCommand - Accepted new client connection 3: /127.0.0.1:45970 null
ERROR SignalJsonRpcDispatcherHandler - Command execution failed
org.asamk.signal.commands.exceptions.UnexpectedErrorException: Failed to send message: /tmp/8782d51d-d034-416b-a425-5985b1c47596_0_jhpsh726..jpg: /tmp/8782d51d-d034-416b-a425-5985b1c47596_0_jhpsh726..jpg (Permission denied) (AttachmentInvalidException)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:158)
        at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:25)
        at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:15)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler$CommandRunnerImpl.handleCommand(SignalJsonRpcDispatcherHandler.java:245)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.parseParamsAndRunCommand(SignalJsonRpcDispatcherHandler.java:356)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.runCommand(SignalJsonRpcDispatcherHandler.java:304)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleRequest(SignalJsonRpcDispatcherHandler.java:182)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.lambda$handleConnection$3(SignalJsonRpcDispatcherHandler.java:136)
        at org.asamk.signal.jsonrpc.JsonRpcReader.handleRequest(JsonRpcReader.java:69)
        at org.asamk.signal.jsonrpc.JsonRpcReader.readMessages(JsonRpcReader.java:44)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:136)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:89)
        at org.asamk.signal.commands.DaemonCommand.lambda$runSocketSingleAccount$3(DaemonCommand.java:225)
        at org.asamk.signal.commands.DaemonCommand.lambda$runSocket$5(DaemonCommand.java:259)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.asamk.signal.manager.api.AttachmentInvalidException: /tmp/8782d51d-d034-416b-a425-5985b1c47596_0_jhpsh726..jpg: /tmp/8782d51d-d034-416b-a425-5985b1c47596_0_jhpsh726..jpg (Permission denied)
        at org.asamk.signal.manager.util.AttachmentUtils.getSignalServiceAttachments(AttachmentUtils.java:25)
        at org.asamk.signal.manager.helper.AttachmentHelper.uploadAttachments(AttachmentHelper.java:42)
        at org.asamk.signal.manager.ManagerImpl.applyMessage(ManagerImpl.java:531)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:521)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:150)
        ... 14 common frames omitted
INFO  DaemonCommand - Connection 3 closed: /127.0.0.1:45970 null

```

any help on this?

**Comment by AsamK** [comment]
Looks like the signal-cli daemon doesn't have access to your temp file: `/tmp/8782d51d-d034-416b-a425-5985b1c47596_0_jhpsh726..jpg (Permission denied)`
