### ISSUE TITLE
Error loading state file for user - Unrecognized field "gv2"

### ISSUE THREAD

**Issue by Henner** [AsamK/signal-cli#981]
signal-cli 0.10.8

2022-07-15T18:07:58.971+0200 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.17.0
2022-07-15T18:07:58.980+0200 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-07-15T18:07:59.378+0200 [main] DEBUG o.a.s.manager.storage.SignalAccount - Migrating legacy recipient store.
2022-07-15T18:07:59.416+0200 [main] DEBUG o.a.s.manager.storage.SignalAccount - Migrating legacy pre key store.
2022-07-15T18:07:59.440+0200 [main] DEBUG o.a.s.manager.storage.SignalAccount - Migrating legacy signed pre key store.
2022-07-15T18:07:59.442+0200 [main] DEBUG o.a.s.manager.storage.SignalAccount - Migrating legacy session store.
2022-07-15T18:07:59.479+0200 [main] DEBUG o.a.s.manager.storage.SignalAccount - Migrating legacy identity session store.
2022-07-15T18:07:59.530+0200 [main] DEBUG o.a.s.manager.storage.SignalAccount - Migrating legacy contact store.
2022-07-15T18:07:59.541+0200 [main] DEBUG o.a.s.manager.storage.SignalAccount - Migrating legacy profile store.
Error loading state file for user +494516195602: Unrecognized field "gv2" (class org.asamk.signal.manager.storage.profiles.SignalProfile$Capabilities), not marked as ignorable (2 known properties: "storage", "gv1Migration"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.asamk.signal.manager.storage.profiles.LegacyProfileStore["profiles"]->org.asamk.signal.manager.storage.profiles.SignalProfile["capabilities"]->org.asamk.signal.manager.storage.profiles.SignalProfile$Capabilities["gv2"]) (IllegalArgumentException)
java.lang.IllegalArgumentException: Unrecognized field "gv2" (class org.asamk.signal.manager.storage.profiles.SignalProfile$Capabilities), not marked as ignorable (2 known properties: "storage", "gv1Migration"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.asamk.signal.manager.storage.profiles.LegacyProfileStore["profiles"]->org.asamk.signal.manager.storage.profiles.SignalProfile["capabilities"]->org.asamk.signal.manager.storage.profiles.SignalProfile$Capabilities["gv2"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4324)
        at org.asamk.signal.manager.storage.SignalAccount.loadLegacyStores(SignalAccount.java:755)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:620)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:169)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:89)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:76)
        at org.asamk.signal.App.loadManager(App.java:345)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.init(App.java:219)
        at org.asamk.signal.Main.main(Main.java:58)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "gv2" (class org.asamk.signal.manager.storage.profiles.SignalProfile$Capabilities), not marked as ignorable (2 known properties: "storage", "gv1Migration"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.asamk.signal.manager.storage.profiles.LegacyProfileStore["profiles"]->org.asamk.signal.manager.storage.profiles.SignalProfile["capabilities"]->org.asamk.signal.manager.storage.profiles.SignalProfile$Capabilities["gv2"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3295)
        at org.asamk.signal.manager.storage.profiles.LegacyProfileStore$ProfileStoreDeserializer.deserialize(LegacyProfileStore.java:63)
        at org.asamk.signal.manager.storage.profiles.LegacyProfileStore$ProfileStoreDeserializer.deserialize(LegacyProfileStore.java:34)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4388)
        ... 10 more

**Comment by AsamK** [comment]
Thanks for reporting, there was an issue with loading older account files.
Please try it again with the latest master version. You can get a prebuilt version from the build artifact: https://github.com/AsamK/signal-cli/actions/runs/2678571724

**Comment by Henner** [comment]
works for me, thank you
