### ISSUE TITLE
Verify error: [422] Bad response: 422 

### ISSUE THREAD

**Issue by tarun14110** [AsamK/signal-cli#984]
```
./signal-cli --verbose -a +16666666666 verify 875724
2022-07-20T13:34:32.901-0600 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.17.0
2022-07-20T13:34:32.903-0600 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
Verify error: [422] Bad response: 422 
org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: [422] Bad response: 422 
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1806)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1743)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1725)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1714)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1650)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1626)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.verifyAccountCode(PushServiceSocket.java:368)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.verifyAccount(SignalServiceAccountManager.java:294)
	at org.asamk.signal.manager.RegistrationManagerImpl.verifyAccountWithCode(RegistrationManagerImpl.java:213)
	at org.asamk.signal.manager.util.NumberVerificationUtils.verifyAccountWithCode(NumberVerificationUtils.java:85)
	at org.asamk.signal.manager.util.NumberVerificationUtils.verifyNumber(NumberVerificationUtils.java:56)
	at org.asamk.signal.manager.RegistrationManagerImpl.verifyAccount(RegistrationManagerImpl.java:119)
	at org.asamk.signal.commands.VerifyCommand.verify(VerifyCommand.java:67)
	at org.asamk.signal.commands.VerifyCommand.handleCommand(VerifyCommand.java:43)
	at org.asamk.signal.App.handleRegistrationCommand(App.java:251)
	at org.asamk.signal.App.init(App.java:211)
	at org.asamk.signal.Main.main(Main.java:58)

```

**Comment by AsamK** [comment]
I can't reproduce this and I also can't find where a 422 response is returned by the verify endpoint in the Signal-Server.
Does this happen everytime and/or only with a specific number?
