### ISSUE TITLE
signal-cli 0.10.9 libsignal version:0.18.1 Deserialization failure in zkgroup

### ISSUE THREAD

**Issue by LFrank2021** [AsamK/signal-cli#988]
Compiled signal-cli v0.10.9 and libsignal v0.18.1
And got hit with this stacktrace.
Any idea where the cause lies?
```
# /opt/signal-cli-0.10.9/bin/signal-cli --verbose --config /var/lib/signal-cli -u <PHONE> listIdentities
2022-07-28T12:16:13.153+0200 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.18.1
2022-07-28T12:16:13.418+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-07-28T12:16:13.504+0200 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@4c4748bf
2022-07-28T12:16:13.506+0200 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
Error loading state file for user <PHONE>: org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup (AssertionError)
java.lang.AssertionError: org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup
        at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:33)
        at org.asamk.signal.manager.SignalDependencies.lambda$getGroupsV2Operations$5(SignalDependencies.java:108)
        at org.asamk.signal.manager.SignalDependencies.getOrCreate(SignalDependencies.java:213)
        at org.asamk.signal.manager.SignalDependencies.getGroupsV2Operations(SignalDependencies.java:106)
        at org.asamk.signal.manager.SignalDependencies.lambda$getAccountManager$1(SignalDependencies.java:85)
        at org.asamk.signal.manager.SignalDependencies.getOrCreate(SignalDependencies.java:213)
        at org.asamk.signal.manager.SignalDependencies.getAccountManager(SignalDependencies.java:81)
        at org.asamk.signal.manager.helper.PreKeyHelper.refreshPreKeysIfNecessary(PreKeyHelper.java:37)
        at org.asamk.signal.manager.helper.PreKeyHelper.refreshPreKeysIfNecessary(PreKeyHelper.java:32)
        at org.asamk.signal.manager.helper.AccountHelper.checkAccountState(AccountHelper.java:58)
        at org.asamk.signal.manager.ManagerImpl.checkAccountState(ManagerImpl.java:191)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:113)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:76)
        at org.asamk.signal.App.loadManager(App.java:345)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.init(App.java:219)
        at org.asamk.signal.Main.main(Main.java:58)
Caused by: org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup
        at org.signal.libsignal.internal.Native.ServerPublicParams_CheckValidContents(Native Method)
        at org.signal.libsignal.zkgroup.ServerPublicParams.<init>(ServerPublicParams.java:14)
        at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:31)
        ... 16 more
```

Host CentOS7
signal-cli compiled with gcc 4.8.5 (4.8.5 20150623 (Red Hat 4.8.5-44))
libsignal compiled with gcc 9.3.1 (9.3.1 20200408 (Red Hat 9.3.1-2), ```scl enable devtoolset-9 bash```)

Because libsignal has requirements for newer versions, I had to self compile a clang version and find a way to a newer gcc version.

Kind regards
Frank

**Comment by AsamK** [comment]
I gave you the wrong version, signal-cli 0.10.9 uses libsignal-client 0.17
The latest master version of signal-cli uses 0.18.1 ...

**Comment by LFrank2021** [comment]
:) master is stable (enough)?

**Comment by LFrank2021** [comment]
That worked.
Thank you.
Quick side question:
What does this debug message mean?
```
2022-07-28T17:50:09.383+0200 [main] INFO  LibSignal - [SignalServiceMessageSender]: [sendMessage][1659023409053] Unidentified pipe unavailable, falling back... (WebSocketUnavailableException: WebSocket not currently available.)
```

**Comment by AsamK** [comment]
At least i try to keep the master stable ;)

The debug message means that there is currently no websocket connection that can be used for the request, instead a new http connection will be used.
The message comes from the libsignal-service library and is to be expected for most commands, except `daemon` and `receive` which open a long-running websocket connection.
