### ISSUE TITLE
Using Windows binary from Java causes CreateProcess error=193

### ISSUE THREAD

**Issue by KoljaHartmann** [AsamK/signal-cli#994]
I tried to automate sending and receiving Signal messages from a Windows machine using a Java Program. I use the signal-cli-0.10.10 on Windows 10 and Oracle OpenJDK version 18.0.2. I set up the signal cli manually and were successfully able to send and receive messages in the normal Windows cmd command line.
I then tried to automate the process in a Java Program, using:

`java.lang.Runtime.getRuntime().exec(new String[]{signalCliPath, command});`

This causes an IOException:

`java.io.IOException: Cannot run program "C:\Signal\signal-cli-0.10.10\bin\signal-cli": CreateProcess error=193, %1 is not a valid win32 application
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at java.base/java.lang.Runtime.exec(Runtime.java:615)
at java.base/java.lang.Runtime.exec(Runtime.java:474)
at Controler.SignalController.receiveMessages(SignalController.java:103)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)`

`Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid win32 application
at java.base/java.lang.ProcessImpl.create(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
... 10 more`

If I log out the exact command causing the error and then manually paste that command to the command line, I can execute that command without problems. Additionally, if I migrate the whole Project to a Linux machine (using the Linux binary there) the whole Program runs without issue. So this seems to be an issue with the combination signal-cli + Windows + Java.

**Comment by AsamK** [comment]
bin/signal-cli is a unix shell script, on windows you need to run bin/signal-cli.bat. (on the commandline windows adds the extension automatically...)
Also maybe from java you need to run the bat file with the windows cmd command, but I'm not sure if executing a bat file directly works.

**Comment by KoljaHartmann** [comment]
Thank you! Just adding .bat to the signal-cli path fixes the issue.
