### ISSUE TITLE
Unable to join group using Invite Link

### ISSUE THREAD

**Issue by nimjitzu** [AsamK/signal-cli#998]
signal-cli v0.10.11

I am trying to join a group that was created via the Signal app using the group link.  I receive the following error.

$ signal-cli --verbose -u +<phoneNumber> joinGroup --uri "https://signal.group/<group_id>"
2022-08-22T15:17:46.599-0400 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.19.3
2022-08-22T15:17:46.600-0400 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-08-22T15:17:46.836-0400 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-08-22T15:17:46.895-0400 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@63b1d4fa
2022-08-22T15:17:46.895-0400 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-08-22T15:17:46.950-0400 [main] INFO  o.a.s.manager.helper.AccountHelper - The Signal protocol expects that incoming messages are regularly received.
2022-08-22T15:17:48.318-0400 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-08-22T15:17:48.324-0400 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Failed to send message: StatusCode: 400 (GroupPatchNotAcceptedException)
org.whispersystems.signalservice.internal.push.exceptions.GroupPatchNotAcceptedException: StatusCode: 400
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.lambda$static$9(PushServiceSocket.java:2418)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket$ResponseCodeHandler.handle(PushServiceSocket.java:2383)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeStorageRequestResponse(PushServiceSocket.java:2056)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeStorageRequest(PushServiceSocket.java:2006)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.patchGroupsV2Group(PushServiceSocket.java:2479)
        at org.whispersystems.signalservice.api.groupsv2.GroupsV2Api.patchGroup(GroupsV2Api.java:168)
        at org.asamk.signal.manager.helper.GroupV2Helper.commitChange(GroupV2Helper.java:557)
        at org.asamk.signal.manager.helper.GroupV2Helper.joinGroup(GroupV2Helper.java:436)
        at org.asamk.signal.manager.helper.GroupHelper.joinGroup(GroupHelper.java:300)
        at org.asamk.signal.manager.ManagerImpl.joinGroup(ManagerImpl.java:433)
        at org.asamk.signal.commands.JoinGroupCommand.handleCommand(JoinGroupCommand.java:54)
        at org.asamk.signal.App.handleLocalCommand(App.java:279)
        at org.asamk.signal.App.init(App.java:219)
        at org.asamk.signal.Main.main(Main.java:58)
$

 Please assist.

Thank you

**Comment by AsamK** [comment]
`joinGroup` works fine for me. Does it work with another user or another group?
