### ISSUE TITLE
UnregisteredUserException

### ISSUE THREAD

**Issue by ionwerz** [AsamK/signal-cli#999]
Hi, I'm using version signal-cli 0.10.0, everything was ok untill today I'm getting next error:
```
ERROR DynamicManagerSender - Client #1661200407745. Error handling: org.whispersystems.signalservice.api.push.exceptions.UnregisteredUserException
org.whispersystems.signalservice.api.push.exceptions.UnregisteredUserException
at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:171)
at org.asamk.signal.manager.ManagerImpl.resolveRecipient(ManagerImpl.java:1467)
at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:612)
at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:713)
at org.asamk.signal.asterisk.DynamicManagerSender.run(DynamicManagerSender.java:63)
INFO DynamicManagerSender - Client #1661200407745. Connection closed
```
This error I get only for a new contacts that I have never message before

**Comment by AsamK** [comment]
Please check if this also occurs with the latest signal-cli version 0.10.11

**Comment by ionwerz** [comment]
After update to 0.10.11 I'm able to send message to the new contact, when I get that new message on Android client I get it from "Unknown" contact, 
- when I try to view contact details instead of phone number I see "No linked devices",
-  then when I try to "Add to your device contacts" option the phone number is empty either,
- when I try to "View safety number" I get pop-up message "You must first exchange messages in order to view Unkown's safety number" but Outgoing and Incoming messages are working fine
I used to try to `updateProfile` with `--name` option, after that on android client I'm able to see that name instead of "Unknown", but I'm still not able to see contact phone number or add to contact or view safety number

**Comment by AsamK** [comment]
That's related to a recent Signal-Server change.
See also #1002

**Comment by pidevcom** [comment]
If I message first from the iOS or Android client to signal-cli I get next log:
```
2022-08-27T19:04:52.410Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.19.3
2022-08-27T19:04:52.412Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-08-27T19:04:52.758Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-08-27T19:04:52.863Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@5d2a4eed
2022-08-27T19:04:52.865Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-08-27T19:04:54.113Z [main] INFO  LibSignal - [WebSocketConnection]: [normal:757779849] connect()
2022-08-27T19:04:54.136Z [main] INFO  LibSignal - [WebSocketConnection]: [unidentified:66774422] connect()
2022-08-27T19:04:54.145Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2022-08-27T19:04:54.152Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
2022-08-27T19:04:54.632Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [normal:757779849] onOpen() connected
2022-08-27T19:04:54.633Z [RxComputationThreadPool-1] DEBUG o.a.s.m.SignalWebSocketHealthMonitor - WebSocket is now connected
2022-08-27T19:04:54.633Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [unidentified:66774422] onOpen() connected
2022-08-27T19:04:54.634Z [RxComputationThreadPool-1] DEBUG o.a.s.m.SignalWebSocketHealthMonitor - WebSocket is now connected
2022-08-27T19:04:54.664Z [main] DEBUG o.a.s.m.s.recipients.RecipientStore - Got new recipient, both uuid and number are unknown
2022-08-27T19:04:54.664Z [main] DEBUG o.a.s.m.s.recipients.RecipientStore - Adding new recipient RecipientId[id=6] with address RecipientAddress[uuid=Optional[448d67d6-87a8-4f77-a552-5129aa80b109], number=Optional.empty]
2022-08-27T19:04:54.722Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - New message received from server
2022-08-27T19:04:54.755Z [main] DEBUG o.a.s.m.s.i.IdentityKeyStore - Initial identity found for RecipientId[id=6], saving.
2022-08-27T19:04:54.755Z [main] DEBUG o.a.s.m.s.i.IdentityKeyStore - Storing new identity for recipient RecipientId[id=6] with trust TRUSTED_UNVERIFIED
2022-08-27T19:04:54.777Z [main] INFO  LibSignal - [libsignal]: rust/protocol/src/session.rs:91: processing PreKey message from 448d67d6-87a8-4f77-a552-5129aa80b109.1
2022-08-27T19:04:54.796Z [main] INFO  LibSignal - [libsignal]: rust/protocol/src/state/session.rs:587: Skipping archive, current session state is fresh
2022-08-27T19:04:54.796Z [main] INFO  LibSignal - [libsignal]: rust/protocol/src/state/session.rs:587: Skipping archive, current session state is fresh
2022-08-27T19:04:54.797Z [main] INFO  LibSignal - [libsignal]: rust/protocol/src/session_cipher.rs:639: 448d67d6-87a8-4f77-a552-5129aa80b109.1 creating new chains.
2022-08-27T19:04:54.797Z [main] INFO  LibSignal - [libsignal]: rust/protocol/src/session_cipher.rs:438: decrypted PreKey message from 448d67d6-87a8-4f77-a552-5129aa80b109.1 with current session state (base key 7fd97428bc934ae89cff59544040a98746b7a6b6a48ab162d2fb3d9ef35bba4c)
2022-08-27T19:04:54.925Z [main] DEBUG org.asamk.signal.manager.util.Utils - Invalid locale 'en', using fallback: en_US
Envelope from: “gt” 448d67d6-87a8-4f77-a552-5129aa80b109 (device: 1)
Timestamp: 1661627084982 (2022-08-27T19:04:44.982Z)
Server timestamps: received: 1661627084131 (2022-08-27T19:04:44.131Z) delivered: 1661627097436 (2022-08-27T19:04:57.436Z)
Message timestamp: 1661627084982 (2022-08-27T19:04:44.982Z)
Body: Test
With profile key

2022-08-27T19:04:55.127Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
2022-08-27T19:04:55.128Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Received indicator that server queue is empty
2022-08-27T19:04:55.128Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2022-08-27T19:04:55.128Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
2022-08-27T19:04:58.128Z [main] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2022-08-27T19:04:58.129Z [main] INFO  LibSignal - [WebSocketConnection]: [normal:757779849] disconnect()
2022-08-27T19:04:58.129Z [main] INFO  LibSignal - [WebSocketConnection]: [unidentified:66774422] disconnect()
2022-08-27T19:04:58.130Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-08-27T19:04:58.133Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
```
As you can see there is no  phone number
